ALTER TABLE sessions DROP CONSTRAINT IF EXISTS sessions_status_check;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS login_at timestamp;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS ip_address varchar(100);
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS terminated_by bigint;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS terminated_at timestamp;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS termination_reason varchar(500);
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'sessions_status_check') THEN
        ALTER TABLE sessions ADD CONSTRAINT sessions_status_check CHECK (status IN ('ACTIVE','EXPIRED','LOGGED_OUT','TERMINATED'));
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_sessions_terminated_by') THEN
        ALTER TABLE sessions ADD CONSTRAINT fk_sessions_terminated_by FOREIGN KEY (terminated_by) REFERENCES users(user_id);
    END IF;
END $$;
COMMENT ON COLUMN sessions.status IS 'ACTIVE:활성|EXPIRED:만료|LOGGED_OUT:로그아웃|TERMINATED:강제종료';
COMMENT ON COLUMN sessions.login_at IS '로그인 인증 성공 시 애플리케이션 또는 migration seed에서 갱신';
COMMENT ON COLUMN sessions.ip_address IS '로그인 인증 성공 시 요청 IP로 애플리케이션에서 갱신';
COMMENT ON COLUMN sessions.terminated_by IS 'users.user_id 참조 의도 (강제종료 처리자)';
COMMENT ON COLUMN sessions.terminated_at IS 'ActiveSessionService.terminateActiveSession 시 애플리케이션에서 갱신';
COMMENT ON COLUMN sessions.termination_reason IS 'ActiveSessionService.terminateActiveSession 시 애플리케이션에서 갱신';

CREATE TABLE IF NOT EXISTS session_termination_history (
    history_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id varchar(128) NOT NULL,
    termination_type varchar(30) NOT NULL CHECK (termination_type IN ('LOGOUT','IDLE_TIMEOUT','ABSOLUTE_TIMEOUT','ADMIN_TERMINATED')),
    termination_reason varchar(500),
    terminated_at timestamp NOT NULL,
    CONSTRAINT fk_session_termination_history_session FOREIGN KEY (session_id) REFERENCES sessions(session_id)
);
COMMENT ON TABLE session_termination_history IS '로그아웃·유휴만료·절대만료·관리자 강제종료 원인을 장기 보존하는 조회 전용 이력 테이블.';
COMMENT ON COLUMN session_termination_history.termination_type IS 'LOGOUT:로그아웃|IDLE_TIMEOUT:유휴만료|ABSOLUTE_TIMEOUT:절대만료|ADMIN_TERMINATED:관리자강제종료';

CREATE TABLE IF NOT EXISTS business_process_audit_logs (
    audit_log_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_type varchar(50) NOT NULL CHECK (action_type IN ('CREATE','UPDATE','DELETE','CONFIRM','AUTH','APPROVE','CANCEL','BATCH','SESSION_TERMINATE')),
    target_key varchar(200) NOT NULL,
    before_state jsonb,
    after_state jsonb,
    actor_user_id bigint NOT NULL,
    result_status varchar(20) NOT NULL CHECK (result_status IN ('SUCCESS','FAILURE')),
    request_id varchar(100) NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_business_process_audit_logs_actor FOREIGN KEY (actor_user_id) REFERENCES users(user_id)
);
COMMENT ON TABLE business_process_audit_logs IS '등록·수정·삭제·확인·인증·승인·취소·일괄처리와 세션 강제종료 처리 결과를 보존하는 불변 감사로그.';
COMMENT ON COLUMN business_process_audit_logs.action_type IS 'CREATE:등록|UPDATE:수정|DELETE:삭제|CONFIRM:확인|AUTH:인증|APPROVE:승인|CANCEL:취소|BATCH:일괄처리|SESSION_TERMINATE:세션강제종료';
COMMENT ON COLUMN business_process_audit_logs.result_status IS 'SUCCESS:성공|FAILURE:실패';
COMMENT ON COLUMN business_process_audit_logs.before_state IS '보호대상 원문값은 마스킹 후 업무 서비스에서 저장';
COMMENT ON COLUMN business_process_audit_logs.after_state IS '보호대상 원문값은 마스킹 후 업무 서비스에서 저장';

CREATE INDEX IF NOT EXISTS idx_sessions_active_status ON sessions(status, expires_at, last_accessed_at);
CREATE INDEX IF NOT EXISTS idx_sessions_last_accessed_at ON sessions(last_accessed_at);
CREATE INDEX IF NOT EXISTS idx_session_termination_history_filter ON session_termination_history(terminated_at, termination_type);
CREATE INDEX IF NOT EXISTS idx_business_process_audit_logs_request_id ON business_process_audit_logs(request_id);
CREATE INDEX IF NOT EXISTS idx_business_process_audit_logs_filter ON business_process_audit_logs(created_at, action_type, result_status);

INSERT INTO sessions (session_id, user_id, login_at, expires_at, status, last_accessed_at, ip_address)
SELECT 'SEED-SESSION-ACTIVE-001', u.user_id, CURRENT_TIMESTAMP - INTERVAL '10 minutes', CURRENT_TIMESTAMP + INTERVAL '30 minutes', 'ACTIVE', CURRENT_TIMESTAMP - INTERVAL '1 minutes', '127.0.0.1'
FROM users u
WHERE u.login_id = 'professor1'
ON CONFLICT (session_id) DO NOTHING;

INSERT INTO menus (menu_id, parent_menu_id, menu_type, menu_name, display_order, screen_id, url, icon, business_category, description, system_use_yn, status, updated_by) VALUES
(220,NULL,'MAIN','보안·감사 관리',3,NULL,NULL,'shield-alert','SYSTEM','접속기록과 감사 로그 관리 대메뉴','Y','ACTIVE',1),
(221,220,'MIDDLE','접속기록 관리',1,NULL,NULL,'monitor','SYSTEM','활성 세션과 종료 이력 관리','Y','ACTIVE',1),
(222,221,'SCREEN','접속현황 조회',1,'SCR-ACTIVE-SESSION-STATUS','/admin/security/active-sessions','monitor-check','SYSTEM','활성 세션 조회 및 관리자 강제종료','Y','ACTIVE',1)
ON CONFLICT (menu_id) DO UPDATE SET menu_name = EXCLUDED.menu_name, parent_menu_id = EXCLUDED.parent_menu_id, url = EXCLUDED.url, screen_id = EXCLUDED.screen_id, updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_execution_info (menu_id, screen_id, url, icon, business_category, description, updated_by)
SELECT menu_id, screen_id, url, icon, business_category, description, 1 FROM menus WHERE screen_id = 'SCR-ACTIVE-SESSION-STATUS'
ON CONFLICT (menu_id) DO UPDATE SET screen_id = EXCLUDED.screen_id, url = EXCLUDED.url, updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_permissions (target_type, target_id, menu_id, access_allowed, status, created_by, updated_by, change_reason)
SELECT 'ROLE', 'R09', menu_id, 'ALLOW', 'ACTIVE', 1, 1, 'BASIC-29 접속현황 조회 권한'
FROM menus WHERE screen_id = 'SCR-ACTIVE-SESSION-STATUS'
ON CONFLICT (target_type, target_id, menu_id) DO UPDATE SET access_allowed = EXCLUDED.access_allowed, status = EXCLUDED.status, updated_at = CURRENT_TIMESTAMP;
