CREATE TABLE IF NOT EXISTS sensitive_information_access_logs (
    access_log_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    information_type varchar(50) NOT NULL CHECK (information_type IN ('PERSONAL_EVALUATION_RESULT','SCORE_CALCULATION','PERSONAL_INFORMATION','ACCOUNT_INFORMATION')),
    viewer_user_id bigint NOT NULL,
    target_scope varchar(1000) NOT NULL,
    access_purpose varchar(500) NOT NULL,
    purpose_source varchar(50) NOT NULL DEFAULT 'SYSTEM_CONTEXT' CHECK (purpose_source IN ('USER_INPUT','SYSTEM_CONTEXT','POLICY_RULE')),
    access_result varchar(20) NOT NULL CHECK (access_result IN ('SUCCESS','FAILURE')),
    request_id varchar(100) NOT NULL,
    accessed_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sensitive_information_access_logs_viewer FOREIGN KEY (viewer_user_id) REFERENCES users(user_id)
);
COMMENT ON TABLE sensitive_information_access_logs IS '개인정보·평가결과·계좌정보 등 중요정보 조회 시 대상범위와 조회목적을 보호 원문값 없이 보존하는 불변 조회로그. SEED-SENSITIVE-ACCESS-001 seed marker를 보존한다.';
COMMENT ON COLUMN sensitive_information_access_logs.information_type IS 'PERSONAL_EVALUATION_RESULT:개인평가결과|SCORE_CALCULATION:점수산정|PERSONAL_INFORMATION:개인정보|ACCOUNT_INFORMATION:계좌정보';
COMMENT ON COLUMN sensitive_information_access_logs.viewer_user_id IS 'users.user_id 참조 의도 (중요정보 조회자)';
COMMENT ON COLUMN sensitive_information_access_logs.target_scope IS '보호대상 원문값 없이 조회 대상 범위만 업무 서비스에서 저장';
COMMENT ON COLUMN sensitive_information_access_logs.access_purpose IS '사용자 입력 또는 시스템 맥락에서 결정된 조회목적을 업무 서비스에서 저장';
COMMENT ON COLUMN sensitive_information_access_logs.purpose_source IS 'USER_INPUT:사용자입력|SYSTEM_CONTEXT:시스템맥락|POLICY_RULE:정책규칙';
COMMENT ON COLUMN sensitive_information_access_logs.access_result IS 'SUCCESS:성공|FAILURE:실패';
COMMENT ON COLUMN sensitive_information_access_logs.request_id IS '요청 식별자 전 구간 추적을 위해 애플리케이션에서 기록';

CREATE INDEX IF NOT EXISTS idx_sensitive_information_access_logs_viewer ON sensitive_information_access_logs(viewer_user_id, accessed_at);
CREATE INDEX IF NOT EXISTS idx_sensitive_information_access_logs_filter ON sensitive_information_access_logs(accessed_at, information_type, access_result);
CREATE INDEX IF NOT EXISTS idx_sensitive_information_access_logs_request_id ON sensitive_information_access_logs(request_id);

INSERT INTO sensitive_information_access_logs (information_type, viewer_user_id, target_scope, access_purpose, purpose_source, access_result, request_id, accessed_at)
SELECT 'PERSONAL_INFORMATION', u.user_id, '교직원 3명 개인정보 조회 범위', '감사 요청 검토', 'USER_INPUT', 'SUCCESS', 'REQ-SENSITIVE-SEED', CURRENT_TIMESTAMP - INTERVAL '10 minutes'
FROM users u
WHERE u.login_id = 'admin'
  AND NOT EXISTS (SELECT 1 FROM sensitive_information_access_logs WHERE request_id = 'REQ-SENSITIVE-SEED');

INSERT INTO sensitive_information_access_logs (information_type, viewer_user_id, target_scope, access_purpose, purpose_source, access_result, request_id, accessed_at)
SELECT 'ACCOUNT_INFORMATION', u.user_id, '계좌정보 권한 검증 범위', '권한 없는 조회 차단 감사', 'SYSTEM_CONTEXT', 'FAILURE', 'REQ-SENSITIVE-FAILURE', CURRENT_TIMESTAMP - INTERVAL '8 minutes'
FROM users u
WHERE u.login_id = 'admin'
  AND NOT EXISTS (SELECT 1 FROM sensitive_information_access_logs WHERE request_id = 'REQ-SENSITIVE-FAILURE');

INSERT INTO menus (menu_id, parent_menu_id, menu_type, menu_name, display_order, screen_id, url, icon, business_category, description, system_use_yn, status, updated_by) VALUES
(226,224,'SCREEN','중요정보 조회 로그',2,'SCR-SENSITIVE-INFO-ACCESS-LOG','/admin/audit/sensitive-information-access-logs','shield-search','SYSTEM','중요정보 유형별 조회 대상범위와 조회목적 조회','Y','ACTIVE',1)
ON CONFLICT (menu_id) DO UPDATE SET menu_name = EXCLUDED.menu_name, parent_menu_id = EXCLUDED.parent_menu_id, url = EXCLUDED.url, screen_id = EXCLUDED.screen_id, updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_execution_info (menu_id, screen_id, url, icon, business_category, description, updated_by)
SELECT menu_id, screen_id, url, icon, business_category, description, 1 FROM menus WHERE screen_id = 'SCR-SENSITIVE-INFO-ACCESS-LOG'
ON CONFLICT (menu_id) DO UPDATE SET screen_id = EXCLUDED.screen_id, url = EXCLUDED.url, updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_permissions (target_type, target_id, menu_id, access_allowed, status, created_by, updated_by, change_reason)
SELECT 'ROLE', 'R09', menu_id, 'ALLOW', 'ACTIVE', 1, 1, 'BASIC-29 중요정보 조회 로그 조회 권한'
FROM menus WHERE screen_id = 'SCR-SENSITIVE-INFO-ACCESS-LOG'
ON CONFLICT (target_type, target_id, menu_id) DO UPDATE SET access_allowed = EXCLUDED.access_allowed, status = EXCLUDED.status, updated_at = CURRENT_TIMESTAMP;
