CREATE TABLE IF NOT EXISTS business_status_codes (
    status_code_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    definition_version varchar(30) NOT NULL,
    business_type varchar(50) NOT NULL,
    status_code varchar(50) NOT NULL,
    display_name varchar(100) NOT NULL,
    system_use_yn varchar(1) NOT NULL DEFAULT 'Y',
    change_reason varchar(500) NOT NULL DEFAULT '초기 상태코드 seed',
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    CONSTRAINT uq_business_status_codes_key UNIQUE (business_type, definition_version, status_code),
    CONSTRAINT ck_business_status_codes_definition_version CHECK (definition_version IN ('DRAFT','CONFIRMED','DISCARDED')),
    CONSTRAINT ck_business_status_codes_business_type CHECK (business_type IN ('FACULTY_ACHIEVEMENT','ACADEMIC_GRANT','OBJECTION')),
    CONSTRAINT ck_business_status_codes_use CHECK (system_use_yn IN ('Y','N')),
    CONSTRAINT fk_business_status_codes_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_business_status_codes_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE business_status_codes IS '교수업적평가·학술지원금·이의신청 업무유형별 상태정의 버전, 기술 상태코드, 사용자 표시명을 관리하는 업무 상태코드.';
COMMENT ON COLUMN business_status_codes.definition_version IS 'DRAFT:작성중|CONFIRMED:확정|DISCARDED:폐기';
COMMENT ON COLUMN business_status_codes.business_type IS 'FACULTY_ACHIEVEMENT:교수업적평가|ACADEMIC_GRANT:학술지원금|OBJECTION:이의신청';
COMMENT ON COLUMN business_status_codes.system_use_yn IS 'Y:사용|N:미사용';

CREATE TABLE IF NOT EXISTS data_change_histories (
    history_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_business varchar(100) NOT NULL,
    target_key varchar(200) NOT NULL,
    change_type varchar(20) NOT NULL,
    field_name varchar(100) NOT NULL,
    before_value text,
    after_value text,
    changed_by bigint NOT NULL,
    changed_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    change_reason varchar(500) NOT NULL,
    CONSTRAINT ck_data_change_histories_change_type CHECK (change_type IN ('CREATE','UPDATE','DELETE')),
    CONSTRAINT fk_data_change_histories_changed_by FOREIGN KEY (changed_by) REFERENCES users(user_id)
);
COMMENT ON TABLE data_change_histories IS 'BASIC-32 업무 운영 데이터의 등록·수정·삭제 전후값을 필드 단위로 보존하는 조회 전용 변경 이력.';
COMMENT ON COLUMN data_change_histories.change_type IS 'CREATE:등록|UPDATE:수정|DELETE:삭제';
COMMENT ON COLUMN data_change_histories.before_value IS 'BusinessStatusCodeService 등 업무 서비스 저장 직전 값으로 애플리케이션에서 기록';
COMMENT ON COLUMN data_change_histories.after_value IS 'BusinessStatusCodeService 등 업무 서비스 저장 직후 값으로 애플리케이션에서 기록';

CREATE INDEX IF NOT EXISTS idx_business_status_codes_filter ON business_status_codes(business_type, definition_version, status_code);
CREATE INDEX IF NOT EXISTS idx_business_status_codes_use ON business_status_codes(system_use_yn, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_data_change_histories_filter ON data_change_histories(target_business, target_key, changed_at DESC);
CREATE INDEX IF NOT EXISTS idx_data_change_histories_changed_by ON data_change_histories(changed_by, changed_at DESC);

INSERT INTO business_status_codes (definition_version, business_type, status_code, display_name, system_use_yn, change_reason, created_by, updated_by)
SELECT version_seed.definition_version, business_seed.business_type, status_seed.status_code, status_seed.display_name, 'Y', 'BASIC-32 상태코드 기본 seed', 1, 1
FROM (VALUES ('DRAFT'), ('CONFIRMED')) AS version_seed(definition_version)
CROSS JOIN (VALUES ('FACULTY_ACHIEVEMENT'), ('ACADEMIC_GRANT'), ('OBJECTION')) AS business_seed(business_type)
CROSS JOIN (VALUES
    ('DRAFTING', '작성중'),
    ('SUBMITTED', '제출'),
    ('DEPARTMENT_CONFIRMED', '학과장확인'),
    ('DEPARTMENT_REJECTED', '학과장미승인'),
    ('CERTIFIED', '인증'),
    ('CERTIFICATION_RETURNED', '인증반려'),
    ('EVALUATION_CONFIRMED', '평가확정'),
    ('DELETED', '삭제')
) AS status_seed(status_code, display_name)
ON CONFLICT (business_type, definition_version, status_code) DO NOTHING;

INSERT INTO menus (menu_id, parent_menu_id, menu_type, menu_name, display_order, screen_id, url, icon, business_category, description, system_use_yn, status, updated_by)
VALUES (311, 300, 'MIDDLE', '업무상태 관리', 2, NULL, NULL, 'workflow', 'BUSINESS', '업무유형별 상태코드와 상태 전이 관리', 'Y', 'ACTIVE', 1)
ON CONFLICT (menu_id) DO UPDATE SET menu_name = EXCLUDED.menu_name,
                                      parent_menu_id = EXCLUDED.parent_menu_id,
                                      display_order = EXCLUDED.display_order,
                                      icon = EXCLUDED.icon,
                                      business_category = EXCLUDED.business_category,
                                      description = EXCLUDED.description,
                                      system_use_yn = EXCLUDED.system_use_yn,
                                      status = EXCLUDED.status,
                                      updated_at = CURRENT_TIMESTAMP,
                                      updated_by = EXCLUDED.updated_by;

INSERT INTO menus (menu_id, parent_menu_id, menu_type, menu_name, display_order, screen_id, url, icon, business_category, description, system_use_yn, status, updated_by)
VALUES (322, 311, 'SCREEN', '상태코드 관리', 1, 'SCR-BUSINESS-STATUS-CODE', '/admin/business-status-codes', 'list-checks', 'BUSINESS', '업무유형별 상태정의 버전과 상태코드 표시명을 관리', 'Y', 'ACTIVE', 1)
ON CONFLICT (menu_id) DO UPDATE SET menu_name = EXCLUDED.menu_name,
                                      parent_menu_id = EXCLUDED.parent_menu_id,
                                      display_order = EXCLUDED.display_order,
                                      screen_id = EXCLUDED.screen_id,
                                      url = EXCLUDED.url,
                                      icon = EXCLUDED.icon,
                                      business_category = EXCLUDED.business_category,
                                      description = EXCLUDED.description,
                                      system_use_yn = EXCLUDED.system_use_yn,
                                      status = EXCLUDED.status,
                                      updated_at = CURRENT_TIMESTAMP,
                                      updated_by = EXCLUDED.updated_by;

INSERT INTO menu_execution_info (menu_id, screen_id, url, icon, business_category, description, updated_by)
VALUES (322, 'SCR-BUSINESS-STATUS-CODE', '/admin/business-status-codes', 'list-checks', 'BUSINESS', '업무유형별 상태정의 버전과 상태코드 표시명을 관리', 1)
ON CONFLICT (menu_id) DO UPDATE SET screen_id = EXCLUDED.screen_id,
                                      url = EXCLUDED.url,
                                      icon = EXCLUDED.icon,
                                      business_category = EXCLUDED.business_category,
                                      description = EXCLUDED.description,
                                      updated_at = CURRENT_TIMESTAMP,
                                      updated_by = EXCLUDED.updated_by;

INSERT INTO menu_permissions (target_type, target_id, menu_id, access_allowed, status, created_by, updated_by, change_reason)
VALUES ('ROLE', 'R09', 322, 'ALLOW', 'ACTIVE', 1, 1, '시스템관리자 상태코드 관리 메뉴 접근')
ON CONFLICT (target_type, target_id, menu_id) DO UPDATE SET access_allowed = EXCLUDED.access_allowed,
                                                            status = EXCLUDED.status,
                                                            updated_at = CURRENT_TIMESTAMP,
                                                            updated_by = EXCLUDED.updated_by,
                                                            change_reason = EXCLUDED.change_reason;

INSERT INTO function_permissions (screen_id, role_code, function_type, permission_allowed, change_reason, created_by, updated_by)
SELECT 'SCR-BUSINESS-STATUS-CODE', 'R09', function_type, 'ALLOW', '시스템관리자 상태코드 관리 기능 기본 허용', 1, 1
FROM (VALUES ('READ'), ('CREATE'), ('UPDATE')) AS seed(function_type)
ON CONFLICT (screen_id, role_code, function_type) DO NOTHING;
