CREATE TABLE IF NOT EXISTS business_status_transitions (
    transition_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    definition_version varchar(30) NOT NULL,
    business_type varchar(50) NOT NULL,
    from_status_code varchar(50) NOT NULL,
    to_status_code varchar(50) NOT NULL,
    executor_role_code varchar(20) NOT NULL,
    opinion_required_yn varchar(1) NOT NULL DEFAULT 'N',
    attachment_required_yn varchar(1) NOT NULL DEFAULT 'N',
    cancellable_yn varchar(1) NOT NULL DEFAULT 'N',
    change_reason varchar(500) NOT NULL DEFAULT '초기 상태 전이규칙 seed',
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    CONSTRAINT uq_business_status_transitions_key UNIQUE (business_type, definition_version, from_status_code, to_status_code, executor_role_code),
    CONSTRAINT ck_business_status_transitions_definition_version CHECK (definition_version IN ('DRAFT','CONFIRMED','DISCARDED')),
    CONSTRAINT ck_business_status_transitions_business_type CHECK (business_type IN ('FACULTY_ACHIEVEMENT','ACADEMIC_GRANT','OBJECTION')),
    CONSTRAINT ck_business_status_transitions_opinion CHECK (opinion_required_yn IN ('Y','N')),
    CONSTRAINT ck_business_status_transitions_attachment CHECK (attachment_required_yn IN ('Y','N')),
    CONSTRAINT ck_business_status_transitions_cancellable CHECK (cancellable_yn IN ('Y','N')),
    CONSTRAINT ck_business_status_transitions_not_self CHECK (from_status_code <> to_status_code),
    CONSTRAINT fk_business_status_transitions_from_code FOREIGN KEY (business_type, definition_version, from_status_code) REFERENCES business_status_codes(business_type, definition_version, status_code),
    CONSTRAINT fk_business_status_transitions_to_code FOREIGN KEY (business_type, definition_version, to_status_code) REFERENCES business_status_codes(business_type, definition_version, status_code),
    CONSTRAINT fk_business_status_transitions_executor_role FOREIGN KEY (executor_role_code) REFERENCES roles(role_code),
    CONSTRAINT fk_business_status_transitions_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_business_status_transitions_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE business_status_transitions IS '업무유형별 상태정의 버전 안에서 현재 상태별 다음 상태, 실행 역할, 필수조건과 취소 가능 여부를 관리하는 업무 상태 전이규칙.';
COMMENT ON COLUMN business_status_transitions.definition_version IS 'DRAFT:작성중|CONFIRMED:확정|DISCARDED:폐기';
COMMENT ON COLUMN business_status_transitions.business_type IS 'FACULTY_ACHIEVEMENT:교수업적평가|ACADEMIC_GRANT:학술지원금|OBJECTION:이의신청';
COMMENT ON COLUMN business_status_transitions.executor_role_code IS 'roles.role_code 참조 의도 (R01~R09 기존 역할 seed 재사용)';
COMMENT ON COLUMN business_status_transitions.opinion_required_yn IS 'Y:필수|N:선택';
COMMENT ON COLUMN business_status_transitions.attachment_required_yn IS 'Y:필수|N:선택';
COMMENT ON COLUMN business_status_transitions.cancellable_yn IS 'Y:취소가능|N:취소불가';

CREATE INDEX IF NOT EXISTS idx_business_status_transitions_filter ON business_status_transitions(business_type, from_status_code, executor_role_code);
CREATE INDEX IF NOT EXISTS idx_business_status_transitions_to_status ON business_status_transitions(business_type, to_status_code);
CREATE INDEX IF NOT EXISTS idx_business_status_transitions_updated ON business_status_transitions(updated_at DESC);

INSERT INTO business_status_transitions (definition_version, business_type, from_status_code, to_status_code, executor_role_code, opinion_required_yn, attachment_required_yn, cancellable_yn, change_reason, created_by, updated_by)
SELECT version_seed.definition_version, business_seed.business_type, transition_seed.from_status_code, transition_seed.to_status_code, transition_seed.executor_role_code, transition_seed.opinion_required_yn, transition_seed.attachment_required_yn, transition_seed.cancellable_yn, 'BASIC-32 상태 전이규칙 기본 seed', 1, 1
FROM (VALUES ('DRAFT'), ('CONFIRMED')) AS version_seed(definition_version)
CROSS JOIN (VALUES ('FACULTY_ACHIEVEMENT'), ('ACADEMIC_GRANT'), ('OBJECTION')) AS business_seed(business_type)
CROSS JOIN (VALUES
    ('DRAFTING', 'SUBMITTED', 'R01', 'N', 'N', 'Y'),
    ('SUBMITTED', 'DEPARTMENT_CONFIRMED', 'R02', 'N', 'N', 'Y'),
    ('SUBMITTED', 'DEPARTMENT_REJECTED', 'R02', 'Y', 'N', 'N'),
    ('DEPARTMENT_REJECTED', 'SUBMITTED', 'R01', 'N', 'N', 'Y'),
    ('DEPARTMENT_CONFIRMED', 'CERTIFIED', 'R03', 'N', 'N', 'Y'),
    ('DEPARTMENT_CONFIRMED', 'CERTIFICATION_RETURNED', 'R03', 'Y', 'N', 'N'),
    ('CERTIFICATION_RETURNED', 'SUBMITTED', 'R01', 'N', 'N', 'Y'),
    ('CERTIFIED', 'EVALUATION_CONFIRMED', 'R09', 'N', 'N', 'N'),
    ('EVALUATION_CONFIRMED', 'CERTIFIED', 'R09', 'N', 'N', 'Y')
) AS transition_seed(from_status_code, to_status_code, executor_role_code, opinion_required_yn, attachment_required_yn, cancellable_yn)
ON CONFLICT (business_type, definition_version, from_status_code, to_status_code, executor_role_code) DO NOTHING;

INSERT INTO menus (menu_id, parent_menu_id, menu_type, menu_name, display_order, screen_id, url, icon, business_category, description, system_use_yn, status, updated_by)
VALUES (323, 311, 'SCREEN', '상태 전이 관리', 2, 'SCR-BUSINESS-STATUS-TRANSITION', '/admin/business-status-transitions', 'git-branch', 'BUSINESS', '업무유형별 현재 상태에서 이동 가능한 다음 상태와 실행 역할·필수조건을 관리', 'Y', 'ACTIVE', 1)
ON CONFLICT (menu_id) DO UPDATE SET menu_name = EXCLUDED.menu_name,
                                      parent_menu_id = EXCLUDED.parent_menu_id,
                                      display_order = EXCLUDED.display_order,
                                      screen_id = EXCLUDED.screen_id,
                                      url = EXCLUDED.url,
                                      icon = EXCLUDED.icon,
                                      business_category = EXCLUDED.business_category,
                                      description = EXCLUDED.description,
                                      system_use_yn = EXCLUDED.system_use_yn,
                                      status = EXCLUDED.status,
                                      updated_at = CURRENT_TIMESTAMP,
                                      updated_by = EXCLUDED.updated_by;

INSERT INTO menu_execution_info (menu_id, screen_id, url, icon, business_category, description, updated_by)
VALUES (323, 'SCR-BUSINESS-STATUS-TRANSITION', '/admin/business-status-transitions', 'git-branch', 'BUSINESS', '업무유형별 현재 상태에서 이동 가능한 다음 상태와 실행 역할·필수조건을 관리', 1)
ON CONFLICT (menu_id) DO UPDATE SET screen_id = EXCLUDED.screen_id,
                                      url = EXCLUDED.url,
                                      icon = EXCLUDED.icon,
                                      business_category = EXCLUDED.business_category,
                                      description = EXCLUDED.description,
                                      updated_at = CURRENT_TIMESTAMP,
                                      updated_by = EXCLUDED.updated_by;

INSERT INTO menu_permissions (target_type, target_id, menu_id, access_allowed, status, created_by, updated_by, change_reason)
VALUES ('ROLE', 'R09', 323, 'ALLOW', 'ACTIVE', 1, 1, '시스템관리자 상태 전이 관리 메뉴 접근')
ON CONFLICT (target_type, target_id, menu_id) DO UPDATE SET access_allowed = EXCLUDED.access_allowed,
                                                            status = EXCLUDED.status,
                                                            updated_at = CURRENT_TIMESTAMP,
                                                            updated_by = EXCLUDED.updated_by,
                                                            change_reason = EXCLUDED.change_reason;

INSERT INTO function_permissions (screen_id, role_code, function_type, permission_allowed, change_reason, created_by, updated_by)
SELECT 'SCR-BUSINESS-STATUS-TRANSITION', 'R09', function_type, 'ALLOW', '시스템관리자 상태 전이 관리 기능 기본 허용', 1, 1
FROM (VALUES ('READ'), ('CREATE'), ('UPDATE')) AS seed(function_type)
ON CONFLICT (screen_id, role_code, function_type) DO NOTHING;
