CREATE TABLE IF NOT EXISTS researcher_profiles (
    employee_no varchar(50) PRIMARY KEY,
    contact varchar(100),
    researcher_registration_no varchar(100),
    external_provision_yn char(1) NOT NULL DEFAULT 'N' CHECK (external_provision_yn IN ('Y','N')),
    information_public_yn char(1) NOT NULL DEFAULT 'N' CHECK (information_public_yn IN ('Y','N')),
    final_degree_type varchar(20) CHECK (final_degree_type IN ('BACHELOR','MASTER','DOCTOR')),
    degree_prerequisite_missing_yn char(1) NOT NULL DEFAULT 'N' CHECK (degree_prerequisite_missing_yn IN ('Y','N')),
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    CONSTRAINT fk_researcher_profiles_employee FOREIGN KEY (employee_no) REFERENCES korus_personnel_snapshots(employee_no),
    CONSTRAINT fk_researcher_profiles_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_researcher_profiles_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE researcher_profiles IS 'KORUS 교원 snapshot과 직접관리 연구자 기준정보를 연결하는 연구자 프로필. KORUS 원천 필드는 직접 수정하지 않고 로컬 공개·연구자 등록 정보를 보존한다.';
COMMENT ON COLUMN researcher_profiles.external_provision_yn IS 'Y:제공|N:미제공';
COMMENT ON COLUMN researcher_profiles.information_public_yn IS 'Y:공개|N:비공개';
COMMENT ON COLUMN researcher_profiles.final_degree_type IS 'BACHELOR:학사|MASTER:석사|DOCTOR:박사';
COMMENT ON COLUMN researcher_profiles.degree_prerequisite_missing_yn IS 'Y:미충족|N:충족';
COMMENT ON COLUMN researcher_profiles.updated_at IS 'ResearcherProfileService 저장 시 직접관리 정보 변경일시로 애플리케이션에서 갱신';

CREATE TABLE IF NOT EXISTS researcher_research_fields (
    research_field_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_no varchar(50) NOT NULL,
    major_name varchar(200) NOT NULL,
    detail_major_name varchar(200),
    major_series varchar(100),
    changed_by bigint NOT NULL,
    changed_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_researcher_research_fields_profile FOREIGN KEY (employee_no) REFERENCES researcher_profiles(employee_no),
    CONSTRAINT fk_researcher_research_fields_changed_by FOREIGN KEY (changed_by) REFERENCES users(user_id)
);
COMMENT ON TABLE researcher_research_fields IS '교원 연구자 프로필의 연구분야 탭 데이터. 전공명·세부전공명·전공계열과 변경 메타정보를 보존한다.';
COMMENT ON COLUMN researcher_research_fields.employee_no IS 'researcher_profiles.employee_no 참조 의도';
COMMENT ON COLUMN researcher_research_fields.changed_at IS 'ResearcherProfileService.saveResearchFields 처리 시 애플리케이션에서 갱신';

CREATE TABLE IF NOT EXISTS researcher_careers (
    career_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_no varchar(50) NOT NULL,
    work_start_ym varchar(6) NOT NULL,
    work_end_ym varchar(6),
    workplace varchar(200) NOT NULL,
    position_name varchar(100),
    duty varchar(500),
    changed_by bigint NOT NULL,
    changed_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_researcher_careers_profile FOREIGN KEY (employee_no) REFERENCES researcher_profiles(employee_no),
    CONSTRAINT fk_researcher_careers_changed_by FOREIGN KEY (changed_by) REFERENCES users(user_id),
    CONSTRAINT ck_researcher_careers_period CHECK (work_end_ym IS NULL OR work_end_ym >= work_start_ym)
);
COMMENT ON TABLE researcher_careers IS '교원 연구자 프로필의 경력 탭 데이터. 근무기간·근무처·직위·담당업무와 변경 메타정보를 보존한다.';
COMMENT ON COLUMN researcher_careers.employee_no IS 'researcher_profiles.employee_no 참조 의도';
COMMENT ON COLUMN researcher_careers.changed_at IS 'ResearcherProfileService.saveCareers 처리 시 애플리케이션에서 갱신';

CREATE TABLE IF NOT EXISTS researcher_degrees (
    degree_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_no varchar(50) NOT NULL,
    degree_type varchar(20) NOT NULL CHECK (degree_type IN ('BACHELOR','MASTER','DOCTOR')),
    university_name varchar(200) NOT NULL,
    start_ym varchar(6),
    acquired_ym varchar(6),
    country_name varchar(100),
    college_name varchar(200),
    advisor_name varchar(100),
    changed_by bigint NOT NULL,
    changed_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_researcher_degrees_profile FOREIGN KEY (employee_no) REFERENCES researcher_profiles(employee_no),
    CONSTRAINT fk_researcher_degrees_changed_by FOREIGN KEY (changed_by) REFERENCES users(user_id)
);
COMMENT ON TABLE researcher_degrees IS '교원 연구자 프로필의 학위 탭 데이터. 취득학위구분·수여대학·취득년월과 박사 선행학위 검증 근거를 보존한다.';
COMMENT ON COLUMN researcher_degrees.employee_no IS 'researcher_profiles.employee_no 참조 의도';
COMMENT ON COLUMN researcher_degrees.degree_type IS 'BACHELOR:학사|MASTER:석사|DOCTOR:박사';
COMMENT ON COLUMN researcher_degrees.changed_at IS 'ResearcherProfileService.saveDegrees 처리 시 애플리케이션에서 갱신';

CREATE TABLE IF NOT EXISTS researcher_certifications (
    certification_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_no varchar(50) NOT NULL,
    acquired_ym varchar(6),
    certification_name varchar(200) NOT NULL,
    issuing_organization_name varchar(200),
    changed_by bigint NOT NULL,
    changed_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_researcher_certifications_profile FOREIGN KEY (employee_no) REFERENCES researcher_profiles(employee_no),
    CONSTRAINT fk_researcher_certifications_changed_by FOREIGN KEY (changed_by) REFERENCES users(user_id)
);
COMMENT ON TABLE researcher_certifications IS '교원 연구자 프로필의 자격 탭 데이터. 자격취득년월·자격증명·부여기관명과 변경 메타정보를 보존한다.';
COMMENT ON COLUMN researcher_certifications.employee_no IS 'researcher_profiles.employee_no 참조 의도';
COMMENT ON COLUMN researcher_certifications.changed_at IS 'ResearcherProfileService.saveCertifications 처리 시 애플리케이션에서 갱신';

CREATE INDEX IF NOT EXISTS idx_researcher_profiles_degree_missing ON researcher_profiles(degree_prerequisite_missing_yn, employee_no);
CREATE INDEX IF NOT EXISTS idx_researcher_research_fields_employee ON researcher_research_fields(employee_no);
CREATE INDEX IF NOT EXISTS idx_researcher_careers_employee ON researcher_careers(employee_no);
CREATE INDEX IF NOT EXISTS idx_researcher_degrees_employee ON researcher_degrees(employee_no);
CREATE INDEX IF NOT EXISTS idx_researcher_degrees_type ON researcher_degrees(employee_no, degree_type);
CREATE INDEX IF NOT EXISTS idx_researcher_certifications_employee ON researcher_certifications(employee_no);

INSERT INTO researcher_profiles (employee_no, contact, researcher_registration_no, external_provision_yn, information_public_yn, final_degree_type, degree_prerequisite_missing_yn, created_by, updated_by)
SELECT employee_no, '', employee_no || '-RID', 'N', 'N', 'DOCTOR', 'Y', 1, 1
FROM korus_personnel_snapshots
WHERE employee_no = 'E1001'
ON CONFLICT (employee_no) DO UPDATE SET degree_prerequisite_missing_yn = EXCLUDED.degree_prerequisite_missing_yn, updated_at = CURRENT_TIMESTAMP;

INSERT INTO researcher_degrees (employee_no, degree_type, university_name, start_ym, acquired_ym, country_name, college_name, advisor_name, changed_by)
SELECT 'E1001', 'DOCTOR', '한국교원대학교', '202001', '202402', '대한민국', '교육대학원', '김교수', 1
WHERE EXISTS (SELECT 1 FROM researcher_profiles WHERE employee_no = 'E1001')
  AND NOT EXISTS (SELECT 1 FROM researcher_degrees WHERE employee_no = 'E1001' AND degree_type = 'DOCTOR');

INSERT INTO menus (menu_id, parent_menu_id, menu_type, menu_name, display_order, screen_id, url, icon, business_category, description, system_use_yn, status, updated_by)
VALUES
(3630, 3600, 'MIDDLE', '연구자 프로필 관리', 3, NULL, NULL, 'id-card', 'BASIC36', '교원 연구자 프로필 관리', 'Y', 'ACTIVE', 1),
(3631, 3630, 'SCREEN', '교원 검색·목록', 1, 'SCR-RESEARCHER-PROFILE-LIST', '/researcher-profiles', 'search', 'BASIC36', '교원 검색 후 연구자 프로필 조회', 'Y', 'ACTIVE', 1),
(3632, 3630, 'SCREEN', '연구자 프로필 상세', 2, 'SCR-RESEARCHER-PROFILE-DETAIL', '/researcher-profiles/{employeeNo}', 'user', 'BASIC36', 'KORUS 조회 전용 필드와 직접관리 탭 저장', 'Y', 'ACTIVE', 1),
(3633, 3630, 'SCREEN', '선행학위 미충족 대상', 3, 'SCR-DEGREE-PREREQ-MISSING', '/admin/researcher-profiles/degree-prerequisite-missing', 'alert-triangle', 'BASIC36', '박사 선행학위 미충족 연구자 목록 조회', 'Y', 'ACTIVE', 1)
ON CONFLICT (menu_id) DO UPDATE SET parent_menu_id = EXCLUDED.parent_menu_id, menu_name = EXCLUDED.menu_name, screen_id = EXCLUDED.screen_id, url = EXCLUDED.url, description = EXCLUDED.description, updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_execution_info (menu_id, screen_id, url, icon, business_category, description, updated_by)
SELECT menu_id, screen_id, url, icon, business_category, description, 1
FROM menus
WHERE screen_id IN ('SCR-RESEARCHER-PROFILE-LIST','SCR-RESEARCHER-PROFILE-DETAIL','SCR-DEGREE-PREREQ-MISSING')
ON CONFLICT (menu_id) DO UPDATE SET screen_id = EXCLUDED.screen_id, url = EXCLUDED.url, icon = EXCLUDED.icon, business_category = EXCLUDED.business_category, description = EXCLUDED.description, updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_permissions (target_type, target_id, menu_id, access_allowed, status, created_by, updated_by, change_reason)
SELECT 'ROLE', role_code, menu_id, 'ALLOW', 'ACTIVE', 1, 1, 'BASIC-36 연구자 프로필 관리 접근'
FROM roles
CROSS JOIN (VALUES (3631), (3632)) AS menu_ids(menu_id)
WHERE role_code IN ('R01','R04','R09')
ON CONFLICT (target_type, target_id, menu_id) DO UPDATE SET access_allowed = EXCLUDED.access_allowed, status = EXCLUDED.status, updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_permissions (target_type, target_id, menu_id, access_allowed, status, created_by, updated_by, change_reason)
SELECT 'ROLE', role_code, 3633, 'ALLOW', 'ACTIVE', 1, 1, 'BASIC-36 선행학위 미충족 대상 접근'
FROM roles
WHERE role_code IN ('R04','R09')
ON CONFLICT (target_type, target_id, menu_id) DO UPDATE SET access_allowed = EXCLUDED.access_allowed, status = EXCLUDED.status, updated_at = CURRENT_TIMESTAMP;
