ALTER TABLE menus ADD COLUMN IF NOT EXISTS exposure_start_at timestamp;
ALTER TABLE menus ADD COLUMN IF NOT EXISTS exposure_end_at timestamp;
COMMENT ON COLUMN menus.exposure_start_at IS '메뉴 노출 시작일시. null이면 시작 제한 없음';
COMMENT ON COLUMN menus.exposure_end_at IS '메뉴 노출 종료일시. null이면 종료 제한 없음';

ALTER TABLE detail_codes ADD COLUMN IF NOT EXISTS usage_change_reason varchar(500);
COMMENT ON COLUMN detail_codes.usage_change_reason IS '상세코드 사용기간/사용여부 변경 사유';

CREATE TABLE IF NOT EXISTS common_settings (
    setting_key varchar(100) PRIMARY KEY,
    setting_value varchar(200) NOT NULL,
    setting_unit varchar(50) NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    change_reason varchar(500),
    CONSTRAINT ck_common_settings_key CHECK (setting_key IN ('SESSION_IDLE_MINUTES','PAGE_SIZE_DEFAULT','DEFAULT_SEARCH_PERIOD_DAYS','LARGE_QUERY_THRESHOLD','LONG_RUNNING_TASK_THRESHOLD')),
    CONSTRAINT ck_common_settings_value CHECK (length(trim(setting_value)) > 0),
    CONSTRAINT fk_common_settings_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE common_settings IS '세션 유휴시간, 페이지당 조회건수, 기본 검색기간, 대량조회 기준, 장시간작업 기준 등 시스템 공통 환경설정.';
COMMENT ON COLUMN common_settings.setting_key IS 'SESSION_IDLE_MINUTES:세션유휴분|PAGE_SIZE_DEFAULT:페이지당조회건수|DEFAULT_SEARCH_PERIOD_DAYS:기본검색기간일|LARGE_QUERY_THRESHOLD:대량조회기준건수|LONG_RUNNING_TASK_THRESHOLD:장시간작업안내초';
COMMENT ON COLUMN common_settings.setting_value IS '설정 키별 단위에 맞는 필수 값';
COMMENT ON COLUMN common_settings.setting_unit IS 'MINUTES:분|ROWS:행|DAYS:일|COUNT:건|SECONDS:초';

CREATE TABLE IF NOT EXISTS base_year_settings (
    base_year integer PRIMARY KEY,
    current_evaluation_year integer NOT NULL,
    default_search_year integer NOT NULL,
    copy_requested_yn varchar(1) NOT NULL DEFAULT 'N' CHECK (copy_requested_yn IN ('Y','N')),
    initialize_requested_yn varchar(1) NOT NULL DEFAULT 'N' CHECK (initialize_requested_yn IN ('Y','N')),
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    change_reason varchar(500),
    CONSTRAINT ck_base_year_range CHECK (base_year BETWEEN 2000 AND 2100 AND current_evaluation_year BETWEEN 2000 AND 2100 AND default_search_year BETWEEN 2000 AND 2100),
    CONSTRAINT fk_base_year_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE base_year_settings IS '현재 평가연도와 사용자 화면 기본 조회연도를 저장하는 기준연도 설정.';
COMMENT ON COLUMN base_year_settings.copy_requested_yn IS 'Y:복사요청|N:복사안함';
COMMENT ON COLUMN base_year_settings.initialize_requested_yn IS 'Y:초기화요청|N:초기화안함';

CREATE TABLE IF NOT EXISTS standard_year_preparation_history (
    preparation_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_year integer NOT NULL,
    copy_requested_yn varchar(1) NOT NULL CHECK (copy_requested_yn IN ('Y','N')),
    initialize_requested_yn varchar(1) NOT NULL CHECK (initialize_requested_yn IN ('Y','N')),
    prepared_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    prepared_by bigint,
    change_reason varchar(500),
    CONSTRAINT fk_standard_year_base FOREIGN KEY (base_year) REFERENCES base_year_settings(base_year),
    CONSTRAINT fk_standard_year_prepared_by FOREIGN KEY (prepared_by) REFERENCES users(user_id)
);
COMMENT ON TABLE standard_year_preparation_history IS '연도별 기준정보 복사 또는 초기화 준비 요청 이력. 기존 연도 평가자료는 삭제·변경하지 않는다.';
COMMENT ON COLUMN standard_year_preparation_history.copy_requested_yn IS 'Y:복사요청|N:복사안함';
COMMENT ON COLUMN standard_year_preparation_history.initialize_requested_yn IS 'Y:초기화요청|N:초기화안함';

CREATE INDEX IF NOT EXISTS idx_menus_exposure ON menus(system_use_yn, exposure_start_at, exposure_end_at);
CREATE INDEX IF NOT EXISTS idx_detail_codes_usage ON detail_codes(group_id, system_use_yn, valid_start_date, valid_end_date);
CREATE INDEX IF NOT EXISTS idx_standard_year_preparation_base ON standard_year_preparation_history(base_year, prepared_at);

INSERT INTO common_settings (setting_key, setting_value, setting_unit, updated_by, change_reason)
VALUES ('SESSION_IDLE_MINUTES','30','MINUTES',1,'BASIC-7 기본 공통 환경설정'),
       ('PAGE_SIZE_DEFAULT','20','ROWS',1,'BASIC-7 기본 공통 환경설정'),
       ('DEFAULT_SEARCH_PERIOD_DAYS','30','DAYS',1,'BASIC-7 기본 공통 환경설정'),
       ('LARGE_QUERY_THRESHOLD','1000','COUNT',1,'BASIC-7 기본 공통 환경설정'),
       ('LONG_RUNNING_TASK_THRESHOLD','10','SECONDS',1,'BASIC-7 기본 공통 환경설정')
ON CONFLICT (setting_key) DO NOTHING;

INSERT INTO base_year_settings (base_year, current_evaluation_year, default_search_year, copy_requested_yn, initialize_requested_yn, updated_by, change_reason)
VALUES (2026, 2026, 2026, 'N', 'N', 1, 'BASIC-7 기본 기준연도')
ON CONFLICT (base_year) DO NOTHING;

INSERT INTO menus (menu_id, parent_menu_id, menu_type, menu_name, display_order, screen_id, url, icon, business_category, description, system_use_yn, status, updated_by) VALUES
(143,140,'SCREEN','코드 사용 관리',3,'SCR-CODE-USAGE-MGMT','/admin/detail-code-usage','calendar-check','SYSTEM','상세코드 사용기간과 사용여부 관리','Y','ACTIVE',1),
(150,100,'MIDDLE','공통 운영 관리',5,NULL,NULL,'sliders','SYSTEM','공통 운영 설정과 기준연도 관리','Y','ACTIVE',1),
(151,130,'SCREEN','메뉴 사용 관리',3,'SCR-MENU-USAGE-MGMT','/admin/menu-usage','eye','SYSTEM','메뉴 사용여부와 노출기간 관리','Y','ACTIVE',1),
(152,150,'SCREEN','공통 환경설정',1,'SCR-COMMON-SETTINGS','/admin/common-settings','settings-2','SYSTEM','세션·조회·검색·작업 공통 설정 관리','Y','ACTIVE',1),
(153,150,'SCREEN','기준연도 관리',2,'SCR-BASE-YEAR-MGMT','/admin/base-years','calendar-days','SYSTEM','현재 평가연도와 기본 조회연도 관리','Y','ACTIVE',1)
ON CONFLICT (menu_id) DO UPDATE SET menu_name = EXCLUDED.menu_name, parent_menu_id = EXCLUDED.parent_menu_id, url = EXCLUDED.url, screen_id = EXCLUDED.screen_id, updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_execution_info (menu_id, screen_id, url, icon, business_category, description, updated_by)
SELECT menu_id, screen_id, url, icon, business_category, description, 1 FROM menus WHERE menu_id IN (143,151,152,153)
ON CONFLICT (menu_id) DO UPDATE SET screen_id = EXCLUDED.screen_id, url = EXCLUDED.url, updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_permissions (target_type, target_id, menu_id, access_allowed, status, created_by, updated_by, change_reason)
SELECT 'ROLE', 'R09', menu_id, 'ALLOW', 'ACTIVE', 1, 1, 'BASIC-7 신규 공통 운영 화면 접근'
FROM menus WHERE menu_id IN (143,151,152,153)
ON CONFLICT (target_type, target_id, menu_id) DO UPDATE SET access_allowed = EXCLUDED.access_allowed, status = EXCLUDED.status, updated_at = CURRENT_TIMESTAMP;
