CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE IF NOT EXISTS appeal_period_settings (
    setting_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluation_year varchar(4) NOT NULL,
    college_organization_code varchar(50) NOT NULL,
    department_organization_code varchar(50),
    appeal_start_at timestamp NOT NULL,
    appeal_end_at timestamp NOT NULL,
    handler_user_id bigint NOT NULL,
    active_yn varchar(1) NOT NULL DEFAULT 'Y',
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    change_reason varchar(500) NOT NULL,
    CONSTRAINT ck_appeal_period_settings_year CHECK (evaluation_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_appeal_period_settings_period CHECK (appeal_end_at >= appeal_start_at),
    CONSTRAINT ck_appeal_period_settings_active CHECK (active_yn IN ('Y','N')),
    CONSTRAINT fk_appeal_period_settings_college FOREIGN KEY (college_organization_code) REFERENCES organizations(organization_code),
    CONSTRAINT fk_appeal_period_settings_department FOREIGN KEY (department_organization_code) REFERENCES organizations(organization_code),
    CONSTRAINT fk_appeal_period_settings_handler FOREIGN KEY (handler_user_id) REFERENCES users(user_id),
    CONSTRAINT fk_appeal_period_settings_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_appeal_period_settings_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id),
    CONSTRAINT ex_appeal_period_settings_active_period EXCLUDE USING gist (
        evaluation_year WITH =,
        college_organization_code WITH =,
        COALESCE(department_organization_code, '') WITH =,
        tsrange(appeal_start_at, appeal_end_at, '[]') WITH &&
    ) WHERE (active_yn = 'Y')
);
COMMENT ON TABLE appeal_period_settings IS '이의신청기간 관리 설정. 평가연도와 소속대학·학과별 이의신청 접수 시작·종료일시 및 처리 담당자를 저장한다.';
COMMENT ON COLUMN appeal_period_settings.active_yn IS 'Y:사용|N:미사용';
COMMENT ON COLUMN appeal_period_settings.created_by IS 'users.user_id 참조 의도 (이의신청기간 관리 생성자)';
COMMENT ON COLUMN appeal_period_settings.updated_by IS 'users.user_id 참조 의도 (이의신청기간 관리 수정자)';

CREATE INDEX IF NOT EXISTS idx_appeal_period_settings_search
    ON appeal_period_settings(evaluation_year, college_organization_code, department_organization_code, active_yn, appeal_start_at, appeal_end_at);
CREATE INDEX IF NOT EXISTS idx_appeal_period_settings_handler
    ON appeal_period_settings(handler_user_id, active_yn, appeal_start_at, appeal_end_at);

INSERT INTO appeal_period_settings (setting_id, evaluation_year, college_organization_code, department_organization_code,
                                    appeal_start_at, appeal_end_at, handler_user_id, active_yn, created_by, updated_by, change_reason)
VALUES (1, '2026', 'KNUE-COL-EDU', 'KNUE-DEPT-COMP', TIMESTAMP '2026-06-01 09:00:00',
        TIMESTAMP '2026-06-10 18:00:00', 1, 'Y', 1, 1, 'B40-SEED-001 이의신청기간 관리 seed')
ON CONFLICT (setting_id) DO UPDATE SET evaluation_year = EXCLUDED.evaluation_year,
                                      college_organization_code = EXCLUDED.college_organization_code,
                                      department_organization_code = EXCLUDED.department_organization_code,
                                      appeal_start_at = EXCLUDED.appeal_start_at,
                                      appeal_end_at = EXCLUDED.appeal_end_at,
                                      handler_user_id = EXCLUDED.handler_user_id,
                                      active_yn = EXCLUDED.active_yn,
                                      updated_at = CURRENT_TIMESTAMP,
                                      updated_by = EXCLUDED.updated_by,
                                      change_reason = EXCLUDED.change_reason;

SELECT setval(pg_get_serial_sequence('appeal_period_settings', 'setting_id'), COALESCE((SELECT MAX(setting_id) FROM appeal_period_settings), 1), true);

INSERT INTO menus (menu_id, parent_menu_id, menu_type, menu_name, display_order, screen_id, url, icon, business_category, description, system_use_yn, status, updated_by)
VALUES (356, 350, 'SCREEN', '이의신청기간 관리', 6, 'SCR-APPEAL-PERIOD-MGMT', '/admin/appeal-periods', 'calendar-alert', 'BUSINESS', '소속별 이의신청 접수기간과 처리 담당자 관리 화면', 'Y', 'ACTIVE', 1)
ON CONFLICT (menu_id) DO UPDATE SET menu_name = EXCLUDED.menu_name,
                                      parent_menu_id = EXCLUDED.parent_menu_id,
                                      display_order = EXCLUDED.display_order,
                                      screen_id = EXCLUDED.screen_id,
                                      url = EXCLUDED.url,
                                      icon = EXCLUDED.icon,
                                      business_category = EXCLUDED.business_category,
                                      description = EXCLUDED.description,
                                      system_use_yn = EXCLUDED.system_use_yn,
                                      status = EXCLUDED.status,
                                      updated_at = CURRENT_TIMESTAMP,
                                      updated_by = EXCLUDED.updated_by;

INSERT INTO menu_execution_info (menu_id, screen_id, url, icon, business_category, description, updated_by)
VALUES (356, 'SCR-APPEAL-PERIOD-MGMT', '/admin/appeal-periods', 'calendar-alert', 'BUSINESS', '이의신청기간 관리 화면', 1)
ON CONFLICT (menu_id) DO UPDATE SET screen_id = EXCLUDED.screen_id,
                                      url = EXCLUDED.url,
                                      icon = EXCLUDED.icon,
                                      business_category = EXCLUDED.business_category,
                                      description = EXCLUDED.description,
                                      updated_at = CURRENT_TIMESTAMP,
                                      updated_by = EXCLUDED.updated_by;

INSERT INTO menu_permissions (target_type, target_id, menu_id, access_allowed, status, created_by, updated_by, change_reason)
SELECT 'ROLE', role_seed.role_code, 356, 'ALLOW', 'ACTIVE', 1, 1, 'BASIC-40 이의신청기간 관리 메뉴 접근'
FROM (VALUES ('R04'), ('R09')) AS role_seed(role_code)
ON CONFLICT (target_type, target_id, menu_id) DO UPDATE SET access_allowed = EXCLUDED.access_allowed,
                                                            status = EXCLUDED.status,
                                                            updated_at = CURRENT_TIMESTAMP,
                                                            updated_by = EXCLUDED.updated_by,
                                                            change_reason = EXCLUDED.change_reason;

INSERT INTO function_permissions (screen_id, role_code, function_type, permission_allowed, change_reason, created_by, updated_by)
SELECT 'SCR-APPEAL-PERIOD-MGMT', role_seed.role_code, function_seed.function_type, 'ALLOW', 'BASIC-40 이의신청기간 관리 기능 허용', 1, 1
FROM (VALUES ('R04'), ('R09')) AS role_seed(role_code)
CROSS JOIN (VALUES ('READ'), ('CREATE'), ('UPDATE')) AS function_seed(function_type)
ON CONFLICT (screen_id, role_code, function_type) DO UPDATE SET permission_allowed = EXCLUDED.permission_allowed,
                                                               change_reason = EXCLUDED.change_reason,
                                                               updated_at = CURRENT_TIMESTAMP,
                                                               updated_by = EXCLUDED.updated_by;
