CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE IF NOT EXISTS exception_period_settings (
    setting_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluation_year varchar(4) NOT NULL,
    teacher_user_id bigint NOT NULL,
    area_code varchar(50) NOT NULL,
    target_function_code varchar(50) NOT NULL,
    exception_start_at timestamp NOT NULL,
    exception_end_at timestamp NOT NULL,
    approval_reason varchar(1000) NOT NULL,
    active_yn varchar(1) NOT NULL DEFAULT 'Y',
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    change_reason varchar(500) NOT NULL,
    CONSTRAINT ck_exception_period_settings_year CHECK (evaluation_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_exception_period_settings_period CHECK (exception_end_at >= exception_start_at),
    CONSTRAINT ck_exception_period_settings_active CHECK (active_yn IN ('Y','N')),
    CONSTRAINT fk_exception_period_settings_teacher FOREIGN KEY (teacher_user_id) REFERENCES users(user_id),
    CONSTRAINT fk_exception_period_settings_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_exception_period_settings_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id),
    CONSTRAINT ex_exception_period_settings_active_period EXCLUDE USING gist (
        evaluation_year WITH =,
        teacher_user_id WITH =,
        area_code WITH =,
        target_function_code WITH =,
        tsrange(exception_start_at, exception_end_at, '[]') WITH &&
    ) WHERE (active_yn = 'Y')
);
COMMENT ON TABLE exception_period_settings IS '예외기간 관리 설정. 특정 교원·평가영역·대상 기능별 예외 시작·종료일시와 승인사유를 저장하며 일반 수정기간 판정에 우선 적용한다.';
COMMENT ON COLUMN exception_period_settings.target_function_code IS 'MODIFY_ACHIEVEMENT:업적수정|DELETE_ACHIEVEMENT:업적삭제';
COMMENT ON COLUMN exception_period_settings.active_yn IS 'Y:사용|N:미사용';
COMMENT ON COLUMN exception_period_settings.teacher_user_id IS 'users.user_id 참조 의도 (예외기간 대상 교원)';
COMMENT ON COLUMN exception_period_settings.area_code IS 'evaluation_areas.area_code 참조 의도 (예외기간 평가영역)';
COMMENT ON COLUMN exception_period_settings.created_by IS 'users.user_id 참조 의도 (예외기간 관리 생성자)';
COMMENT ON COLUMN exception_period_settings.updated_by IS 'users.user_id 참조 의도 (예외기간 관리 수정자)';

CREATE INDEX IF NOT EXISTS idx_exception_period_settings_search
    ON exception_period_settings(evaluation_year, teacher_user_id, area_code, target_function_code, active_yn, exception_start_at, exception_end_at);
CREATE INDEX IF NOT EXISTS idx_exception_period_settings_target
    ON exception_period_settings(teacher_user_id, area_code, target_function_code, active_yn, exception_start_at, exception_end_at);

INSERT INTO exception_period_settings (setting_id, evaluation_year, teacher_user_id, area_code, target_function_code,
                                       exception_start_at, exception_end_at, approval_reason, active_yn,
                                       created_by, updated_by, change_reason)
VALUES (1, '2026', 2, 'EDUCATION', 'MODIFY_ACHIEVEMENT', TIMESTAMP '2026-08-01 09:00:00',
        TIMESTAMP '2026-08-05 18:00:00', 'B40-SEED-003 예외기간 승인사유', 'Y', 1, 1, 'B40-SEED-003 예외기간 관리 seed')
ON CONFLICT (setting_id) DO UPDATE SET evaluation_year = EXCLUDED.evaluation_year,
                                      teacher_user_id = EXCLUDED.teacher_user_id,
                                      area_code = EXCLUDED.area_code,
                                      target_function_code = EXCLUDED.target_function_code,
                                      exception_start_at = EXCLUDED.exception_start_at,
                                      exception_end_at = EXCLUDED.exception_end_at,
                                      approval_reason = EXCLUDED.approval_reason,
                                      active_yn = EXCLUDED.active_yn,
                                      updated_at = CURRENT_TIMESTAMP,
                                      updated_by = EXCLUDED.updated_by,
                                      change_reason = EXCLUDED.change_reason;

SELECT setval(pg_get_serial_sequence('exception_period_settings', 'setting_id'), COALESCE((SELECT MAX(setting_id) FROM exception_period_settings), 1), true);

INSERT INTO menus (menu_id, parent_menu_id, menu_type, menu_name, display_order, screen_id, url, icon, business_category, description, system_use_yn, status, updated_by)
VALUES (358, 350, 'SCREEN', '예외기간 관리', 8, 'SCR-EXCEPTION-PERIOD-MGMT', '/admin/exception-periods', 'calendar-clock', 'BUSINESS', '특정 교원·영역·기능별 예외기간과 승인사유 관리 화면', 'Y', 'ACTIVE', 1)
ON CONFLICT (menu_id) DO UPDATE SET menu_name = EXCLUDED.menu_name,
                                      parent_menu_id = EXCLUDED.parent_menu_id,
                                      display_order = EXCLUDED.display_order,
                                      screen_id = EXCLUDED.screen_id,
                                      url = EXCLUDED.url,
                                      icon = EXCLUDED.icon,
                                      business_category = EXCLUDED.business_category,
                                      description = EXCLUDED.description,
                                      system_use_yn = EXCLUDED.system_use_yn,
                                      status = EXCLUDED.status,
                                      updated_at = CURRENT_TIMESTAMP,
                                      updated_by = EXCLUDED.updated_by;

INSERT INTO menu_execution_info (menu_id, screen_id, url, icon, business_category, description, updated_by)
VALUES (358, 'SCR-EXCEPTION-PERIOD-MGMT', '/admin/exception-periods', 'calendar-clock', 'BUSINESS', '예외기간 관리 화면', 1)
ON CONFLICT (menu_id) DO UPDATE SET screen_id = EXCLUDED.screen_id,
                                      url = EXCLUDED.url,
                                      icon = EXCLUDED.icon,
                                      business_category = EXCLUDED.business_category,
                                      description = EXCLUDED.description,
                                      updated_at = CURRENT_TIMESTAMP,
                                      updated_by = EXCLUDED.updated_by;

INSERT INTO menu_permissions (target_type, target_id, menu_id, access_allowed, status, created_by, updated_by, change_reason)
SELECT 'ROLE', role_seed.role_code, 358, 'ALLOW', 'ACTIVE', 1, 1, 'BASIC-40 예외기간 관리 메뉴 접근'
FROM (VALUES ('R04'), ('R09')) AS role_seed(role_code)
ON CONFLICT (target_type, target_id, menu_id) DO UPDATE SET access_allowed = EXCLUDED.access_allowed,
                                                            status = EXCLUDED.status,
                                                            updated_at = CURRENT_TIMESTAMP,
                                                            updated_by = EXCLUDED.updated_by,
                                                            change_reason = EXCLUDED.change_reason;

INSERT INTO function_permissions (screen_id, role_code, function_type, permission_allowed, change_reason, created_by, updated_by)
SELECT 'SCR-EXCEPTION-PERIOD-MGMT', role_seed.role_code, function_seed.function_type, 'ALLOW', 'BASIC-40 예외기간 관리 기능 허용', 1, 1
FROM (VALUES ('R04'), ('R09')) AS role_seed(role_code)
CROSS JOIN (VALUES ('READ'), ('CREATE'), ('UPDATE')) AS function_seed(function_type)
ON CONFLICT (screen_id, role_code, function_type) DO UPDATE SET permission_allowed = EXCLUDED.permission_allowed,
                                                               change_reason = EXCLUDED.change_reason,
                                                               updated_at = CURRENT_TIMESTAMP,
                                                               updated_by = EXCLUDED.updated_by;
