ALTER TABLE users ADD COLUMN IF NOT EXISTS email varchar(254);
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified_yn varchar(1) DEFAULT 'N';
ALTER TABLE users ADD COLUMN IF NOT EXISTS account_status varchar(20) DEFAULT 'ACTIVE';

UPDATE users
SET email_verified_yn = COALESCE(email_verified_yn, 'Y'),
    account_status = COALESCE(account_status, CASE WHEN status = 'INACTIVE' THEN 'SUSPENDED' ELSE 'ACTIVE' END)
WHERE email_verified_yn IS NULL OR account_status IS NULL;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_users_email_verified_yn') THEN
        ALTER TABLE users ADD CONSTRAINT ck_users_email_verified_yn CHECK (email_verified_yn IN ('Y','N'));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_users_account_status') THEN
        ALTER TABLE users ADD CONSTRAINT ck_users_account_status CHECK (account_status IN ('PENDING_EMAIL','ACTIVE','SUSPENDED'));
    END IF;
END $$;

COMMENT ON COLUMN users.email IS '회원가입 이메일 주소. 신규 가입 계정은 lowercase 저장하며 기존 관리자 계정은 nullable 허용';
COMMENT ON COLUMN users.email_verified_yn IS 'Y:인증완료|N:미인증';
COMMENT ON COLUMN users.account_status IS 'PENDING_EMAIL:이메일인증대기|ACTIVE:활성|SUSPENDED:정지';

CREATE UNIQUE INDEX IF NOT EXISTS uq_users_email_lower ON users (lower(email)) WHERE email IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_users_account_status ON users(account_status, email_verified_yn);

CREATE TABLE IF NOT EXISTS email_verification_tokens (
    token_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    token_hash varchar(64) NOT NULL,
    expire_dt timestamp NOT NULL,
    used_yn varchar(1) NOT NULL DEFAULT 'N' CHECK (used_yn IN ('Y','N')),
    used_dt timestamp,
    reg_dt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_email_verification_tokens_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);
COMMENT ON TABLE email_verification_tokens IS '이메일 인증 링크 검증을 위한 SHA-256 token hash와 만료/사용 상태. 원본 token은 저장하지 않는다.';
COMMENT ON COLUMN email_verification_tokens.used_yn IS 'Y:사용됨|N:미사용';
COMMENT ON COLUMN email_verification_tokens.used_dt IS '이메일 인증 완료 또는 재발송 무효화 시 애플리케이션에서 갱신';
COMMENT ON COLUMN email_verification_tokens.reg_dt IS 'token 생성 시각 및 24시간 만료 산정 기준';

CREATE UNIQUE INDEX IF NOT EXISTS uq_email_verification_tokens_token_hash ON email_verification_tokens(token_hash);
CREATE INDEX IF NOT EXISTS idx_email_verification_tokens_user_current ON email_verification_tokens(user_id, used_yn, expire_dt DESC);

CREATE TABLE IF NOT EXISTS mail_send_attempts (
    attempt_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint,
    email varchar(254) NOT NULL,
    mail_type varchar(40) NOT NULL CHECK (mail_type IN ('EMAIL_VERIFICATION')),
    send_status varchar(20) NOT NULL CHECK (send_status IN ('REQUESTED','SENT','FAILED','RATE_LIMITED','SKIPPED_ACTIVE','SKIPPED_UNKNOWN')),
    failure_reason varchar(500),
    request_id varchar(100) NOT NULL,
    reg_dt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_dt timestamp,
    CONSTRAINT fk_mail_send_attempts_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);
COMMENT ON TABLE mail_send_attempts IS '인증 메일 발송 요청·성공·실패·스킵 이력. SMTP 장애와 재발송 rate limit 추적에 사용한다.';
COMMENT ON COLUMN mail_send_attempts.mail_type IS 'EMAIL_VERIFICATION:이메일인증';
COMMENT ON COLUMN mail_send_attempts.send_status IS 'REQUESTED:요청됨|SENT:발송됨|FAILED:실패|RATE_LIMITED:재요청제한|SKIPPED_ACTIVE:인증완료스킵|SKIPPED_UNKNOWN:미존재스킵';
COMMENT ON COLUMN mail_send_attempts.failure_reason IS 'JavaMailSender 발송 실패 시 애플리케이션에서 갱신';
COMMENT ON COLUMN mail_send_attempts.sent_dt IS 'JavaMailSender 발송 성공 시 애플리케이션에서 갱신';

CREATE INDEX IF NOT EXISTS idx_mail_send_attempts_email_reg_dt ON mail_send_attempts(lower(email), reg_dt DESC);
CREATE INDEX IF NOT EXISTS idx_mail_send_attempts_request_id ON mail_send_attempts(request_id);

WITH active_user AS (
    INSERT INTO users (login_id, password_hash, email, email_verified_yn, account_status, system_use_yn, status, change_reason)
    VALUES ('test_active', 'sha256:0c3a6f4a25c59e547aa22c7ad502c44af0b8682ff2d90335dc55b9f8348c6603', 'test_active@example.edu', 'Y', 'ACTIVE', 'Y', 'ACTIVE', 'BASIC57_USER_ACTIVE seed')
    ON CONFLICT (login_id) DO UPDATE SET email = EXCLUDED.email, email_verified_yn = 'Y', account_status = 'ACTIVE', updated_at = CURRENT_TIMESTAMP
    RETURNING user_id
), pending_user AS (
    INSERT INTO users (login_id, password_hash, email, email_verified_yn, account_status, system_use_yn, status, change_reason)
    VALUES ('test_pending', 'sha256:87bf0f02a11b2a44a2e834efac277c8d44b9d428001c79775c23d54ba45fa987', 'test_pending@example.edu', 'N', 'PENDING_EMAIL', 'Y', 'ACTIVE', 'BASIC57_USER_PENDING seed')
    ON CONFLICT (login_id) DO UPDATE SET email = EXCLUDED.email, email_verified_yn = 'N', account_status = 'PENDING_EMAIL', updated_at = CURRENT_TIMESTAMP
    RETURNING user_id
), suspended_user AS (
    INSERT INTO users (login_id, password_hash, email, email_verified_yn, account_status, system_use_yn, status, change_reason)
    VALUES ('test_suspended', 'sha256:0fb19db57d0d97ac81a019e37778c31c7daae1858c31d9514f498903d332d198', 'test_suspended@example.edu', 'Y', 'SUSPENDED', 'N', 'INACTIVE', 'BASIC57_USER_SUSPENDED seed')
    ON CONFLICT (login_id) DO UPDATE SET email = EXCLUDED.email, email_verified_yn = 'Y', account_status = 'SUSPENDED', system_use_yn = 'N', status = 'INACTIVE', updated_at = CURRENT_TIMESTAMP
    RETURNING user_id
), all_seed_users AS (
    SELECT user_id, 'R08'::varchar AS role_code, 'BASIC57_USER_ACTIVE'::varchar AS seed_id FROM active_user
    UNION ALL SELECT user_id, 'R08', 'BASIC57_USER_PENDING' FROM pending_user
    UNION ALL SELECT user_id, 'R08', 'BASIC57_USER_SUSPENDED' FROM suspended_user
)
INSERT INTO user_roles (user_id, role_code, assignment_type, valid_start_date, status, change_reason)
SELECT user_id, role_code, 'MANUAL', CURRENT_DATE, 'ACTIVE', seed_id
FROM all_seed_users seed
WHERE NOT EXISTS (
    SELECT 1 FROM user_roles ur
    WHERE ur.user_id = seed.user_id AND ur.role_code = seed.role_code AND ur.status = 'ACTIVE'
);

WITH pending_user AS (SELECT user_id FROM users WHERE login_id = 'test_pending'),
active_user AS (SELECT user_id FROM users WHERE login_id = 'test_active')
insert into email_verification_tokens (user_id, token_hash, expire_dt, used_yn, used_dt, reg_dt)
SELECT user_id, '1111111111111111111111111111111111111111111111111111111111111111', CURRENT_TIMESTAMP + INTERVAL '24 hours', 'N', NULL, CURRENT_TIMESTAMP FROM pending_user
ON CONFLICT (token_hash) DO NOTHING;
-- BASIC57_TOKEN_VALID: 미사용 정상 인증 token seed

WITH pending_user AS (SELECT user_id FROM users WHERE login_id = 'test_pending')
insert into email_verification_tokens (user_id, token_hash, expire_dt, used_yn, used_dt, reg_dt)
SELECT user_id, '2222222222222222222222222222222222222222222222222222222222222222', CURRENT_TIMESTAMP + INTERVAL '24 hours', 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP - INTERVAL '2 hours' FROM pending_user
ON CONFLICT (token_hash) DO NOTHING;
-- BASIC57_TOKEN_USED: 이미 사용된 인증 token seed

WITH pending_user AS (SELECT user_id FROM users WHERE login_id = 'test_pending')
insert into email_verification_tokens (user_id, token_hash, expire_dt, used_yn, used_dt, reg_dt)
SELECT user_id, '3333333333333333333333333333333333333333333333333333333333333333', CURRENT_TIMESTAMP - INTERVAL '1 hour', 'N', NULL, CURRENT_TIMESTAMP - INTERVAL '25 hours' FROM pending_user
ON CONFLICT (token_hash) DO NOTHING;
-- BASIC57_TOKEN_EXPIRED: 24시간 만료 경계 token seed

WITH pending_user AS (SELECT user_id FROM users WHERE login_id = 'test_pending')
insert into mail_send_attempts (user_id, email, mail_type, send_status, failure_reason, request_id, reg_dt, sent_dt)
SELECT user_id, 'test_pending@example.edu', 'EMAIL_VERIFICATION', 'REQUESTED', NULL, 'BASIC57_MAIL_REQUESTED', CURRENT_TIMESTAMP, NULL FROM pending_user
WHERE NOT EXISTS (SELECT 1 FROM mail_send_attempts WHERE request_id = 'BASIC57_MAIL_REQUESTED');

WITH pending_user AS (SELECT user_id FROM users WHERE login_id = 'test_pending')
insert into mail_send_attempts (user_id, email, mail_type, send_status, failure_reason, request_id, reg_dt, sent_dt)
SELECT user_id, 'test_pending@example.edu', 'EMAIL_VERIFICATION', 'SENT', NULL, 'BASIC57_MAIL_SENT', CURRENT_TIMESTAMP - INTERVAL '3 minutes', CURRENT_TIMESTAMP - INTERVAL '3 minutes' FROM pending_user
WHERE NOT EXISTS (SELECT 1 FROM mail_send_attempts WHERE request_id = 'BASIC57_MAIL_SENT');

WITH pending_user AS (SELECT user_id FROM users WHERE login_id = 'test_pending')
insert into mail_send_attempts (user_id, email, mail_type, send_status, failure_reason, request_id, reg_dt, sent_dt)
SELECT user_id, 'test_pending@example.edu', 'EMAIL_VERIFICATION', 'FAILED', 'BASIC57_MAIL_FAILED smtp fixture', 'BASIC57_MAIL_FAILED', CURRENT_TIMESTAMP - INTERVAL '2 minutes', NULL FROM pending_user
WHERE NOT EXISTS (SELECT 1 FROM mail_send_attempts WHERE request_id = 'BASIC57_MAIL_FAILED');
