ALTER TABLE users
    ADD COLUMN IF NOT EXISTS email varchar(320),
    ADD COLUMN IF NOT EXISTS email_verified_yn varchar(1) NOT NULL DEFAULT 'N',
    ADD COLUMN IF NOT EXISTS account_status varchar(30),
    ADD COLUMN IF NOT EXISTS email_substitute_yn varchar(1) NOT NULL DEFAULT 'N',
    ADD COLUMN IF NOT EXISTS verification_origin varchar(30);

ALTER TABLE users ALTER COLUMN account_status SET DEFAULT 'ACTIVE';

UPDATE users
SET account_status = status
WHERE account_status IS NULL
  AND status IN ('ACTIVE', 'INACTIVE', 'DELETED');

ALTER TABLE users ALTER COLUMN account_status SET NOT NULL;

COMMENT ON COLUMN users.email IS '정규화된 이메일. 일반 계정은 대소문자 무시 고유성이 적용되고 기존 대체 이메일 예외는 email_substitute_yn으로 식별한다.';
COMMENT ON COLUMN users.email_verified_yn IS 'Y:인증완료|N:미인증';
COMMENT ON COLUMN users.account_status IS 'ACTIVE:활성|INACTIVE:비활성|DELETED:삭제|PENDING_EMAIL:이메일인증대기';
COMMENT ON COLUMN users.email_substitute_yn IS 'Y:대체이메일|N:일반이메일';
COMMENT ON COLUMN users.verification_origin IS 'EXEMPT_EXISTING:기존계정면제|LINK_VERIFIED:링크인증완료';

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_users_email_verified_yn') THEN
        ALTER TABLE users ADD CONSTRAINT ck_users_email_verified_yn CHECK (email_verified_yn IN ('Y','N'));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_users_account_status') THEN
        ALTER TABLE users ADD CONSTRAINT ck_users_account_status CHECK (account_status IN ('ACTIVE','INACTIVE','DELETED','PENDING_EMAIL'));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_users_email_substitute_yn') THEN
        ALTER TABLE users ADD CONSTRAINT ck_users_email_substitute_yn CHECK (email_substitute_yn IN ('Y','N'));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_users_verification_origin') THEN
        ALTER TABLE users ADD CONSTRAINT ck_users_verification_origin CHECK (verification_origin IS NULL OR verification_origin IN ('EXEMPT_EXISTING','LINK_VERIFIED'));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_users_substitute_email_guard') THEN
        ALTER TABLE users ADD CONSTRAINT ck_users_substitute_email_guard CHECK (
            lower(coalesce(email, '')) <> 'admin@kndadmin.com' OR email_substitute_yn = 'Y'
        );
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS email_verification_tokens (
    token_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    target_email varchar(320) NOT NULL,
    token_hash varchar(255) NOT NULL,
    issued_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP + interval '24 hours'),
    used_at timestamp,
    status varchar(30) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','USED','EXPIRED','SUPERSEDED')),
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_email_verification_tokens_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT uq_email_verification_tokens_hash UNIQUE (token_hash),
    CONSTRAINT ck_email_verification_tokens_target_email CHECK (length(trim(target_email)) > 0),
    CONSTRAINT ck_email_verification_tokens_used_state CHECK (
        (status = 'USED' AND used_at IS NOT NULL) OR (status <> 'USED' AND used_at IS NULL)
    ),
    CONSTRAINT ck_email_verification_tokens_expiry CHECK (expires_at > issued_at)
);
COMMENT ON TABLE email_verification_tokens IS '회원가입 이메일 인증 토큰의 해시·대상 이메일·만료·일회성 사용 상태를 보존한다.';
COMMENT ON COLUMN email_verification_tokens.user_id IS 'users.user_id 참조';
COMMENT ON COLUMN email_verification_tokens.target_email IS '토큰 발급 시점의 정규화된 대상 이메일. 인증 시 다른 이메일로 전용할 수 없다.';
COMMENT ON COLUMN email_verification_tokens.token_hash IS '원문 토큰은 저장하지 않고 SHA-256 등 서버 해시만 저장한다.';
COMMENT ON COLUMN email_verification_tokens.expires_at IS '발급 시점 + 24시간으로 애플리케이션에서 설정하거나 기본값으로 보정한다.';
COMMENT ON COLUMN email_verification_tokens.status IS 'ACTIVE:활성|USED:사용됨|EXPIRED:만료|SUPERSEDED:대체됨';

CREATE TABLE IF NOT EXISTS mail_delivery_attempts (
    attempt_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint,
    normalized_email varchar(320) NOT NULL,
    delivery_status varchar(30) NOT NULL DEFAULT 'REQUESTED' CHECK (delivery_status IN ('REQUESTED','SENT','FAILED_AUTH','FAILED_TIMEOUT','FAILED_RATE_LIMIT','FAILED_OTHER')),
    diagnostic_category varchar(40) NOT NULL DEFAULT 'NONE' CHECK (diagnostic_category IN ('NONE','AUTH','TIMEOUT','RATE_LIMIT','CONFIGURATION','NETWORK','UNKNOWN')),
    diagnostic_message varchar(1000),
    retry_eligible_yn varchar(1) NOT NULL DEFAULT 'N' CHECK (retry_eligible_yn IN ('Y','N')),
    requested_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at timestamp,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mail_delivery_attempts_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT ck_mail_delivery_attempts_no_substitute CHECK (lower(normalized_email) <> 'admin@kndadmin.com')
);
COMMENT ON TABLE mail_delivery_attempts IS 'Gmail SMTP 인증 메일 발송 시도와 운영자 진단 상태를 보존한다. SMTP 비밀정보는 기록하지 않는다.';
COMMENT ON COLUMN mail_delivery_attempts.user_id IS 'users.user_id 참조. 미등록 이메일 재발송 요청처럼 계정이 확인되지 않는 경우 null 가능';
COMMENT ON COLUMN mail_delivery_attempts.normalized_email IS '정규화된 대상 이메일. admin@kndadmin.com 대체 주소는 민감 메일 대상으로 허용하지 않는다.';
COMMENT ON COLUMN mail_delivery_attempts.delivery_status IS 'REQUESTED:요청됨|SENT:SMTP접수|FAILED_AUTH:인증실패|FAILED_TIMEOUT:시간초과|FAILED_RATE_LIMIT:전송제한|FAILED_OTHER:기타실패';
COMMENT ON COLUMN mail_delivery_attempts.diagnostic_category IS 'NONE:없음|AUTH:인증|TIMEOUT:시간초과|RATE_LIMIT:전송제한|CONFIGURATION:설정|NETWORK:네트워크|UNKNOWN:알수없음';
COMMENT ON COLUMN mail_delivery_attempts.diagnostic_message IS '메일 어댑터가 비밀정보를 제거한 운영자 진단 메시지를 기록한다.';
COMMENT ON COLUMN mail_delivery_attempts.retry_eligible_yn IS 'Y:재시도가능|N:재시도불가';

CREATE TABLE IF NOT EXISTS email_verification_events (
    event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    event_type varchar(30) NOT NULL CHECK (event_type IN ('EXEMPT_EXISTING','LINK_VERIFIED','RESEND_REQUESTED','TOKEN_REJECTED')),
    occurred_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    token_id bigint,
    normalized_email varchar(320),
    actor_type varchar(30) NOT NULL DEFAULT 'SYSTEM' CHECK (actor_type IN ('SYSTEM','VISITOR','USER')),
    event_reason varchar(500),
    CONSTRAINT fk_email_verification_events_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_email_verification_events_token FOREIGN KEY (token_id) REFERENCES email_verification_tokens(token_id)
);
COMMENT ON TABLE email_verification_events IS '기존 계정 정책 면제와 실제 링크 인증 등 이메일 인증 출처를 append-only로 보존한다.';
COMMENT ON COLUMN email_verification_events.user_id IS 'users.user_id 참조';
COMMENT ON COLUMN email_verification_events.event_type IS 'EXEMPT_EXISTING:기존계정면제|LINK_VERIFIED:링크인증완료|RESEND_REQUESTED:재발송요청|TOKEN_REJECTED:토큰거부';
COMMENT ON COLUMN email_verification_events.token_id IS 'email_verification_tokens.token_id 참조. 기존 계정 면제 이벤트는 null 가능';
COMMENT ON COLUMN email_verification_events.actor_type IS 'SYSTEM:시스템|VISITOR:방문자|USER:사용자';

CREATE UNIQUE INDEX IF NOT EXISTS uq_users_normal_email_ci
    ON users (lower(email))
    WHERE email IS NOT NULL AND coalesce(email_substitute_yn, 'N') = 'N';
CREATE INDEX IF NOT EXISTS idx_users_account_status ON users(account_status);
CREATE INDEX IF NOT EXISTS idx_email_verification_tokens_user_status ON email_verification_tokens(user_id, status, expires_at);
CREATE UNIQUE INDEX IF NOT EXISTS uq_email_verification_tokens_active_user_email
    ON email_verification_tokens (user_id, target_email)
    WHERE status = 'ACTIVE';
CREATE INDEX IF NOT EXISTS idx_mail_delivery_attempts_email_requested ON mail_delivery_attempts(normalized_email, requested_at DESC);
CREATE INDEX IF NOT EXISTS idx_mail_delivery_attempts_user_requested ON mail_delivery_attempts(user_id, requested_at DESC);
CREATE INDEX IF NOT EXISTS idx_email_verification_events_user_time ON email_verification_events(user_id, occurred_at DESC);

CREATE OR REPLACE FUNCTION supersede_email_verification_tokens(p_user_id bigint, p_target_email varchar)
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
    affected integer;
BEGIN
    UPDATE email_verification_tokens
    SET status = 'SUPERSEDED',
        updated_at = CURRENT_TIMESTAMP
    WHERE user_id = p_user_id
      AND target_email = lower(trim(p_target_email))
      AND status = 'ACTIVE';
    GET DIAGNOSTICS affected = ROW_COUNT;
    RETURN affected;
END;
$$;

UPDATE users
SET email_substitute_yn = 'Y'
WHERE email IS NULL
  AND login_id IN ('admin', 'professor1')
  AND coalesce(account_status, status) IN ('ACTIVE', 'INACTIVE', 'DELETED');

UPDATE users
SET email_verified_yn = 'Y',
    verification_origin = 'EXEMPT_EXISTING',
    account_status = coalesce(account_status, status),
    updated_at = CURRENT_TIMESTAMP
WHERE login_id = 'admin'
  AND coalesce(account_status, status) IN ('ACTIVE', 'INACTIVE', 'DELETED');

UPDATE users
SET email_verified_yn = 'Y',
    verification_origin = 'EXEMPT_EXISTING',
    account_status = coalesce(account_status, status),
    updated_at = CURRENT_TIMESTAMP
WHERE login_id = 'professor1'
  AND coalesce(account_status, status) IN ('ACTIVE', 'INACTIVE', 'DELETED');

INSERT INTO email_verification_events (user_id, event_type, normalized_email, actor_type, event_reason)
SELECT u.user_id, 'EXEMPT_EXISTING', u.email, 'SYSTEM', 'BASIC-58 existing-account exemption migration'
FROM users u
WHERE u.login_id IN ('admin', 'professor1')
  AND u.email_verified_yn = 'Y'
  AND u.verification_origin = 'EXEMPT_EXISTING'
  AND NOT EXISTS (
      SELECT 1
      FROM email_verification_events existing
      WHERE existing.user_id = u.user_id
        AND existing.event_type = 'EXEMPT_EXISTING'
  );
