INSERT INTO evaluation_rule_versions (version_code, effective_start_date, effective_end_date, version_status, change_reason, created_by, updated_by)
VALUES
    ('B60-DRAFT-2026', DATE '2026-01-01', DATE '2026-12-31', 'DRAFT', 'BASIC-60 운영설정 작성중 seed', 1, 1),
    ('B60-CONFIRMED-2026', DATE '2026-01-01', DATE '2026-12-31', 'CONFIRMED', 'BASIC-60 운영설정 확정 seed', 1, 1)
ON CONFLICT (version_code) DO UPDATE SET effective_start_date = EXCLUDED.effective_start_date,
                                      effective_end_date = EXCLUDED.effective_end_date,
                                      version_status = EXCLUDED.version_status,
                                      change_reason = EXCLUDED.change_reason,
                                      updated_at = CURRENT_TIMESTAMP,
                                      updated_by = EXCLUDED.updated_by;

CREATE TABLE IF NOT EXISTS evaluation_element_management_item_settings (
    setting_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_version_id bigint NOT NULL,
    target_scope varchar(100) NOT NULL,
    area_code varchar(50) NOT NULL,
    item_code varchar(50) NOT NULL,
    evaluation_year varchar(4) NOT NULL,
    element_code varchar(50) NOT NULL,
    management_item_code varchar(50) NOT NULL,
    management_item_name varchar(100) NOT NULL,
    sort_order integer NOT NULL,
    active_yn char(1) NOT NULL DEFAULT 'Y',
    teacher_editable_yn char(1) NOT NULL DEFAULT 'N',
    effective_start_date date NOT NULL,
    effective_end_date date NOT NULL,
    evaluation_confirmed_yn char(1) NOT NULL DEFAULT 'N',
    change_reason varchar(500) NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    CONSTRAINT uq_eval_elem_mgmt_item_settings_key UNIQUE (rule_version_id, target_scope, area_code, item_code, evaluation_year, element_code, management_item_code),
    CONSTRAINT ck_eval_elem_mgmt_item_settings_year CHECK (evaluation_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_eval_elem_mgmt_item_settings_active CHECK (active_yn IN ('Y','N')),
    CONSTRAINT ck_eval_elem_mgmt_item_settings_teacher CHECK (teacher_editable_yn IN ('Y','N')),
    CONSTRAINT ck_eval_elem_mgmt_item_settings_confirmed CHECK (evaluation_confirmed_yn IN ('Y','N')),
    CONSTRAINT ck_eval_elem_mgmt_item_settings_period CHECK (effective_end_date >= effective_start_date),
    CONSTRAINT fk_eval_elem_mgmt_item_settings_rule FOREIGN KEY (rule_version_id) REFERENCES evaluation_rule_versions(rule_version_id),
    CONSTRAINT fk_eval_elem_mgmt_item_settings_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_eval_elem_mgmt_item_settings_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE evaluation_element_management_item_settings IS 'BASIC-60 평가요소별 관리항목 운영 설정. 분류체계를 변경하지 않고 적용 대상별 표시·입력 가능·사용 여부 값을 관리한다.';
COMMENT ON COLUMN evaluation_element_management_item_settings.target_scope IS '기존 조직·소속·평가대상 참조 의도 (FK 미선언)';
COMMENT ON COLUMN evaluation_element_management_item_settings.active_yn IS 'Y:사용|N:미사용';
COMMENT ON COLUMN evaluation_element_management_item_settings.teacher_editable_yn IS 'Y:교원입력가능|N:교원입력불가';
COMMENT ON COLUMN evaluation_element_management_item_settings.evaluation_confirmed_yn IS 'Y:평가확정 영향범위|N:일반';
COMMENT ON COLUMN evaluation_element_management_item_settings.created_by IS 'users.user_id 참조 의도 (설정 생성자)';
COMMENT ON COLUMN evaluation_element_management_item_settings.updated_by IS 'users.user_id 참조 의도 (설정 수정자)';

CREATE TABLE IF NOT EXISTS participation_allocation_rate_settings (
    setting_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_version_id bigint NOT NULL,
    target_scope varchar(100) NOT NULL,
    area_code varchar(50) NOT NULL,
    item_code varchar(50) NOT NULL,
    evaluation_year varchar(4) NOT NULL,
    element_code varchar(50) NOT NULL,
    management_item_code varchar(50) NOT NULL,
    researcher_count integer NOT NULL,
    participation_type varchar(50) NOT NULL,
    allocation_rate numeric(7,4) NOT NULL,
    active_yn char(1) NOT NULL DEFAULT 'Y',
    effective_start_date date NOT NULL,
    effective_end_date date NOT NULL,
    evaluation_confirmed_yn char(1) NOT NULL DEFAULT 'N',
    change_reason varchar(500) NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    CONSTRAINT uq_participation_alloc_rate_settings_key UNIQUE (rule_version_id, target_scope, management_item_code, researcher_count, participation_type, effective_start_date, effective_end_date),
    CONSTRAINT ck_participation_alloc_rate_settings_year CHECK (evaluation_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_participation_alloc_rate_settings_count CHECK (researcher_count > 0),
    CONSTRAINT ck_participation_alloc_rate_settings_rate CHECK (allocation_rate >= 0 AND allocation_rate <= 1),
    CONSTRAINT ck_participation_alloc_rate_settings_active CHECK (active_yn IN ('Y','N')),
    CONSTRAINT ck_participation_alloc_rate_settings_confirmed CHECK (evaluation_confirmed_yn IN ('Y','N')),
    CONSTRAINT ck_participation_alloc_rate_settings_period CHECK (effective_end_date >= effective_start_date),
    CONSTRAINT fk_participation_alloc_rate_settings_rule FOREIGN KEY (rule_version_id) REFERENCES evaluation_rule_versions(rule_version_id),
    CONSTRAINT fk_participation_alloc_rate_settings_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_participation_alloc_rate_settings_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE participation_allocation_rate_settings IS 'BASIC-60 참여구분별 배분율 운영 설정. 관리항목·연구자수·참여구분별 배분율 값을 적용기간과 상태별로 보존한다.';
COMMENT ON COLUMN participation_allocation_rate_settings.target_scope IS '기존 조직·소속·평가대상 참조 의도 (FK 미선언)';
COMMENT ON COLUMN participation_allocation_rate_settings.participation_type IS '공통코드 참여구분 참조 의도 (FK 미선언)';
COMMENT ON COLUMN participation_allocation_rate_settings.active_yn IS 'Y:사용|N:미사용';
COMMENT ON COLUMN participation_allocation_rate_settings.evaluation_confirmed_yn IS 'Y:평가확정 영향범위|N:일반';
COMMENT ON COLUMN participation_allocation_rate_settings.created_by IS 'users.user_id 참조 의도 (설정 생성자)';
COMMENT ON COLUMN participation_allocation_rate_settings.updated_by IS 'users.user_id 참조 의도 (설정 수정자)';

CREATE TABLE IF NOT EXISTS management_item_evaluation_score_settings (
    setting_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_version_id bigint NOT NULL,
    target_scope varchar(100) NOT NULL,
    area_code varchar(50) NOT NULL,
    item_code varchar(50) NOT NULL,
    evaluation_year varchar(4) NOT NULL,
    element_code varchar(50) NOT NULL,
    management_item_code varchar(50) NOT NULL,
    organization_code varchar(50) NOT NULL,
    organization_name varchar(100),
    evaluation_score numeric(10,2) NOT NULL,
    max_score numeric(10,2),
    sort_order integer NOT NULL,
    active_yn char(1) NOT NULL DEFAULT 'Y',
    effective_start_date date NOT NULL,
    effective_end_date date NOT NULL,
    evaluation_confirmed_yn char(1) NOT NULL DEFAULT 'N',
    change_reason varchar(500) NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    CONSTRAINT uq_mgmt_item_eval_score_settings_key UNIQUE (rule_version_id, target_scope, management_item_code, organization_code, effective_start_date, effective_end_date),
    CONSTRAINT ck_mgmt_item_eval_score_settings_year CHECK (evaluation_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_mgmt_item_eval_score_settings_score CHECK (evaluation_score >= 0 AND NOT (max_score < evaluation_score)),
    CONSTRAINT ck_mgmt_item_eval_score_settings_active CHECK (active_yn IN ('Y','N')),
    CONSTRAINT ck_mgmt_item_eval_score_settings_confirmed CHECK (evaluation_confirmed_yn IN ('Y','N')),
    CONSTRAINT ck_mgmt_item_eval_score_settings_period CHECK (effective_end_date >= effective_start_date),
    CONSTRAINT fk_mgmt_item_eval_score_settings_rule FOREIGN KEY (rule_version_id) REFERENCES evaluation_rule_versions(rule_version_id),
    CONSTRAINT fk_mgmt_item_eval_score_settings_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_mgmt_item_eval_score_settings_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE management_item_evaluation_score_settings IS 'BASIC-60 관리항목별 평가점수 운영 설정. 관리항목·소속대학별 점수와 상한점수를 버전과 적용기간별로 보존한다.';
COMMENT ON COLUMN management_item_evaluation_score_settings.target_scope IS '기존 조직·소속·평가대상 참조 의도 (FK 미선언)';
COMMENT ON COLUMN management_item_evaluation_score_settings.organization_code IS 'organizations.organization_code 참조 의도 (FK 미선언)';
COMMENT ON COLUMN management_item_evaluation_score_settings.active_yn IS 'Y:사용|N:미사용';
COMMENT ON COLUMN management_item_evaluation_score_settings.evaluation_confirmed_yn IS 'Y:평가확정 영향범위|N:일반';
COMMENT ON COLUMN management_item_evaluation_score_settings.created_by IS 'users.user_id 참조 의도 (설정 생성자)';
COMMENT ON COLUMN management_item_evaluation_score_settings.updated_by IS 'users.user_id 참조 의도 (설정 수정자)';

CREATE TABLE IF NOT EXISTS course_area_group_grade_results (
    result_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    faculty_user_id bigint NOT NULL,
    employee_no varchar(50) NOT NULL,
    faculty_name varchar(100) NOT NULL,
    completion_type varchar(50) NOT NULL,
    semester varchar(20) NOT NULL,
    course_area varchar(50) NOT NULL,
    group_grade numeric(5,2) NOT NULL,
    detail_summary varchar(500) NOT NULL,
    published_yn char(1) NOT NULL DEFAULT 'Y',
    evaluated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_course_area_group_grade_published CHECK (published_yn IN ('Y','N')),
    CONSTRAINT ck_course_area_group_grade_score CHECK (group_grade >= 0)
);
COMMENT ON TABLE course_area_group_grade_results IS 'BASIC-60 교과영역 그룹평가 성적 조회 projection. 평가 실행 결과를 조회 전용으로 제공하며 이 기능에서 생성·수정·삭제하지 않는다.';
COMMENT ON COLUMN course_area_group_grade_results.faculty_user_id IS 'users.user_id 참조 의도 (교원 성적 소유자, FK 미선언)';
COMMENT ON COLUMN course_area_group_grade_results.completion_type IS 'MAJOR:전공|LIBERAL:교양|TEACHING:교직|OTHER:기타';
COMMENT ON COLUMN course_area_group_grade_results.course_area IS 'LECTURE:강의|PRACTICE:실습|ONLINE:온라인|OTHER:기타';
COMMENT ON COLUMN course_area_group_grade_results.published_yn IS 'Y:조회가능|N:비공개';

CREATE INDEX IF NOT EXISTS idx_eval_elem_mgmt_item_settings_search ON evaluation_element_management_item_settings(rule_version_id, target_scope, area_code, item_code, evaluation_year, active_yn);
CREATE INDEX IF NOT EXISTS idx_participation_alloc_rate_settings_search ON participation_allocation_rate_settings(rule_version_id, target_scope, management_item_code, participation_type, active_yn);
CREATE INDEX IF NOT EXISTS idx_mgmt_item_eval_score_settings_search ON management_item_evaluation_score_settings(rule_version_id, target_scope, management_item_code, organization_code, active_yn);
CREATE INDEX IF NOT EXISTS idx_course_area_group_grade_results_search ON course_area_group_grade_results(faculty_user_id, completion_type, semester, course_area, published_yn);

INSERT INTO evaluation_element_management_item_settings (rule_version_id, target_scope, area_code, item_code, evaluation_year, element_code, management_item_code, management_item_name, sort_order, active_yn, teacher_editable_yn, effective_start_date, effective_end_date, evaluation_confirmed_yn, change_reason, created_by, updated_by)
SELECT rv.rule_version_id, seed.target_scope, seed.area_code, seed.item_code, seed.evaluation_year, seed.element_code, seed.management_item_code, seed.management_item_name, seed.sort_order, seed.active_yn, seed.teacher_editable_yn, seed.effective_start_date, seed.effective_end_date, seed.evaluation_confirmed_yn, 'BASIC-60 평가요소별 관리항목 seed', 1, 1
FROM evaluation_rule_versions rv
CROSS JOIN (VALUES
    ('COLLEGE_EDU','EDUCATION','LECTURE','2026','COURSE_GROUP','ATTENDANCE','출석관리',1,'Y','Y',DATE '2026-01-01',DATE '2026-12-31','N'),
    ('COLLEGE_EDU','EDUCATION','LECTURE','2026','COURSE_GROUP','SYLLABUS','강의계획서',2,'Y','N',DATE '2026-01-01',DATE '2026-06-30','N'),
    ('COLLEGE_RESEARCH','EDUCATION','LECTURE','2026','COURSE_GROUP','LOCKED_ITEM','평가확정 잠금항목',99,'N','N',DATE '2026-01-01',DATE '2026-12-31','Y')
) AS seed(target_scope, area_code, item_code, evaluation_year, element_code, management_item_code, management_item_name, sort_order, active_yn, teacher_editable_yn, effective_start_date, effective_end_date, evaluation_confirmed_yn)
WHERE rv.version_code = 'B60-DRAFT-2026'
ON CONFLICT (rule_version_id, target_scope, area_code, item_code, evaluation_year, element_code, management_item_code) DO NOTHING;

INSERT INTO participation_allocation_rate_settings (rule_version_id, target_scope, area_code, item_code, evaluation_year, element_code, management_item_code, researcher_count, participation_type, allocation_rate, active_yn, effective_start_date, effective_end_date, evaluation_confirmed_yn, change_reason, created_by, updated_by)
SELECT rv.rule_version_id, seed.target_scope, seed.area_code, seed.item_code, seed.evaluation_year, seed.element_code, seed.management_item_code, seed.researcher_count, seed.participation_type, seed.allocation_rate, seed.active_yn, seed.effective_start_date, seed.effective_end_date, seed.evaluation_confirmed_yn, 'BASIC-60 참여구분별 배분율 seed', 1, 1
FROM evaluation_rule_versions rv
CROSS JOIN (VALUES
    ('COLLEGE_EDU','RESEARCH','PAPER','2026','AUTHORSHIP','PAPER_SCORE',1,'SOLE',1.0000,'Y',DATE '2026-01-01',DATE '2026-12-31','N'),
    ('COLLEGE_EDU','RESEARCH','PAPER','2026','AUTHORSHIP','PAPER_SCORE',3,'LEAD',0.7000,'Y',DATE '2026-01-01',DATE '2026-12-31','N'),
    ('COLLEGE_RESEARCH','RESEARCH','PAPER','2026','AUTHORSHIP','LOCKED_RATE',2,'CO',0.5000,'N',DATE '2026-01-01',DATE '2026-12-31','Y')
) AS seed(target_scope, area_code, item_code, evaluation_year, element_code, management_item_code, researcher_count, participation_type, allocation_rate, active_yn, effective_start_date, effective_end_date, evaluation_confirmed_yn)
WHERE rv.version_code = 'B60-DRAFT-2026'
ON CONFLICT (rule_version_id, target_scope, management_item_code, researcher_count, participation_type, effective_start_date, effective_end_date) DO NOTHING;

INSERT INTO management_item_evaluation_score_settings (rule_version_id, target_scope, area_code, item_code, evaluation_year, element_code, management_item_code, organization_code, organization_name, evaluation_score, max_score, sort_order, active_yn, effective_start_date, effective_end_date, evaluation_confirmed_yn, change_reason, created_by, updated_by)
SELECT rv.rule_version_id, seed.target_scope, seed.area_code, seed.item_code, seed.evaluation_year, seed.element_code, seed.management_item_code, seed.organization_code, seed.organization_name, seed.evaluation_score, seed.max_score, seed.sort_order, seed.active_yn, seed.effective_start_date, seed.effective_end_date, seed.evaluation_confirmed_yn, 'BASIC-60 관리항목별 평가점수 seed', 1, 1
FROM evaluation_rule_versions rv
CROSS JOIN (VALUES
    ('COLLEGE_EDU','EDUCATION','LECTURE','2026','COURSE_GROUP','ATTENDANCE','COL-EDU','사범대학',10.00,20.00,1,'Y',DATE '2026-01-01',DATE '2026-12-31','N'),
    ('COLLEGE_EDU','EDUCATION','LECTURE','2026','COURSE_GROUP','SYLLABUS','COL-EDU','사범대학',5.00,10.00,2,'Y',DATE '2026-01-01',DATE '2026-06-30','N'),
    ('COLLEGE_RESEARCH','EDUCATION','LECTURE','2026','COURSE_GROUP','LOCKED_SCORE','COL-RES','연구대학',3.00,3.00,99,'N',DATE '2026-01-01',DATE '2026-12-31','Y')
) AS seed(target_scope, area_code, item_code, evaluation_year, element_code, management_item_code, organization_code, organization_name, evaluation_score, max_score, sort_order, active_yn, effective_start_date, effective_end_date, evaluation_confirmed_yn)
WHERE rv.version_code = 'B60-DRAFT-2026'
ON CONFLICT (rule_version_id, target_scope, management_item_code, organization_code, effective_start_date, effective_end_date) DO NOTHING;

INSERT INTO course_area_group_grade_results (faculty_user_id, employee_no, faculty_name, completion_type, semester, course_area, group_grade, detail_summary, published_yn, evaluated_at)
VALUES
    (2, 'E0002', '교원사용자', 'MAJOR', '2026-1', 'LECTURE', 95.50, '전공 강의 그룹평가 상위 등급', 'Y', CURRENT_TIMESTAMP),
    (2, 'E0002', '교원사용자', 'LIBERAL', '2026-1', 'ONLINE', 88.00, '교양 온라인 강의 그룹평가', 'Y', CURRENT_TIMESTAMP),
    (4, 'E0004', '업무담당자', 'MAJOR', '2026-2', 'PRACTICE', 76.25, '타 교원 실습 그룹평가 권한 차이 seed', 'Y', CURRENT_TIMESTAMP),
    (2, 'E0002', '교원사용자', 'OTHER', '2025-2', 'OTHER', 60.00, '비공개 경계 seed', 'N', CURRENT_TIMESTAMP)
ON CONFLICT DO NOTHING;

INSERT INTO menus (menu_id, parent_menu_id, menu_type, menu_name, display_order, screen_id, url, icon, business_category, description, system_use_yn, status, updated_by)
VALUES
    (601, 340, 'SCREEN', '평가요소별 관리항목 설정', 6, 'SCR-EVALUATION-ELEMENT-MANAGEMENT-ITEM-SETTINGS', '/admin/evaluation-element-management-item-settings', 'clipboard-list', 'BUSINESS', '평가요소별 관리항목 운영 설정', 'Y', 'ACTIVE', 1),
    (602, 340, 'SCREEN', '관리항목별 평가점수 설정', 7, 'SCR-MANAGEMENT-ITEM-EVALUATION-SCORE-SETTINGS', '/admin/management-item-evaluation-score-settings', 'badge-plus', 'BUSINESS', '관리항목별 평가점수 운영 설정', 'Y', 'ACTIVE', 1),
    (603, 340, 'SCREEN', '참여구분별 배분율 설정', 8, 'SCR-PARTICIPATION-ALLOCATION-RATE-SETTINGS', '/admin/participation-allocation-rate-settings', 'percent', 'BUSINESS', '참여구분별 배분율 운영 설정', 'Y', 'ACTIVE', 1),
    (604, 300, 'SCREEN', '교과영역 그룹평가 성적 조회', 60, 'SCR-COURSE-AREA-GROUP-GRADE-QUERY', '/faculty/course-area-group-grades', 'graduation-cap', 'BUSINESS', '교원 교과영역 그룹평가 성적 조회', 'Y', 'ACTIVE', 1)
ON CONFLICT (menu_id) DO UPDATE SET menu_name = EXCLUDED.menu_name,
                                      parent_menu_id = EXCLUDED.parent_menu_id,
                                      display_order = EXCLUDED.display_order,
                                      screen_id = EXCLUDED.screen_id,
                                      url = EXCLUDED.url,
                                      icon = EXCLUDED.icon,
                                      business_category = EXCLUDED.business_category,
                                      description = EXCLUDED.description,
                                      system_use_yn = EXCLUDED.system_use_yn,
                                      status = EXCLUDED.status,
                                      updated_at = CURRENT_TIMESTAMP,
                                      updated_by = EXCLUDED.updated_by;

INSERT INTO menu_execution_info (menu_id, screen_id, url, icon, business_category, description, updated_by)
VALUES
    (601, 'SCR-EVALUATION-ELEMENT-MANAGEMENT-ITEM-SETTINGS', '/admin/evaluation-element-management-item-settings', 'clipboard-list', 'BUSINESS', '평가요소별 관리항목 운영 설정', 1),
    (602, 'SCR-MANAGEMENT-ITEM-EVALUATION-SCORE-SETTINGS', '/admin/management-item-evaluation-score-settings', 'badge-plus', 'BUSINESS', '관리항목별 평가점수 운영 설정', 1),
    (603, 'SCR-PARTICIPATION-ALLOCATION-RATE-SETTINGS', '/admin/participation-allocation-rate-settings', 'percent', 'BUSINESS', '참여구분별 배분율 운영 설정', 1),
    (604, 'SCR-COURSE-AREA-GROUP-GRADE-QUERY', '/faculty/course-area-group-grades', 'graduation-cap', 'BUSINESS', '교원 교과영역 그룹평가 성적 조회', 1)
ON CONFLICT (menu_id) DO UPDATE SET screen_id = EXCLUDED.screen_id,
                                      url = EXCLUDED.url,
                                      icon = EXCLUDED.icon,
                                      business_category = EXCLUDED.business_category,
                                      description = EXCLUDED.description,
                                      updated_at = CURRENT_TIMESTAMP,
                                      updated_by = EXCLUDED.updated_by;

INSERT INTO menu_permissions (target_type, target_id, menu_id, access_allowed, status, created_by, updated_by, change_reason)
SELECT 'ROLE', role_seed.role_code, menu_seed.menu_id, 'ALLOW', 'ACTIVE', 1, 1, 'BASIC-60 업무 메뉴 접근'
FROM (VALUES ('R04'), ('R09')) AS role_seed(role_code)
CROSS JOIN (VALUES (601), (602), (603)) AS menu_seed(menu_id)
ON CONFLICT (target_type, target_id, menu_id) DO UPDATE SET access_allowed = EXCLUDED.access_allowed,
                                                            status = EXCLUDED.status,
                                                            updated_at = CURRENT_TIMESTAMP,
                                                            updated_by = EXCLUDED.updated_by,
                                                            change_reason = EXCLUDED.change_reason;

INSERT INTO menu_permissions (target_type, target_id, menu_id, access_allowed, status, created_by, updated_by, change_reason)
SELECT 'ROLE', role_seed.role_code, 604, 'ALLOW', 'ACTIVE', 1, 1, 'BASIC-60 성적 조회 메뉴 접근'
FROM (VALUES ('R01'), ('R04'), ('R08'), ('R09')) AS role_seed(role_code)
ON CONFLICT (target_type, target_id, menu_id) DO UPDATE SET access_allowed = EXCLUDED.access_allowed,
                                                            status = EXCLUDED.status,
                                                            updated_at = CURRENT_TIMESTAMP,
                                                            updated_by = EXCLUDED.updated_by,
                                                            change_reason = EXCLUDED.change_reason;

INSERT INTO function_permissions (screen_id, role_code, function_type, permission_allowed, change_reason, created_by, updated_by)
SELECT screen.screen_id, role_seed.role_code, function_seed.function_type, 'ALLOW', 'BASIC-60 설정 기능 허용', 1, 1
FROM (VALUES
    ('SCR-EVALUATION-ELEMENT-MANAGEMENT-ITEM-SETTINGS'),
    ('SCR-MANAGEMENT-ITEM-EVALUATION-SCORE-SETTINGS'),
    ('SCR-PARTICIPATION-ALLOCATION-RATE-SETTINGS')
) AS screen(screen_id)
CROSS JOIN (VALUES ('R04'), ('R09')) AS role_seed(role_code)
CROSS JOIN (VALUES ('READ'), ('CREATE'), ('UPDATE')) AS function_seed(function_type)
ON CONFLICT (screen_id, role_code, function_type) DO UPDATE SET permission_allowed = EXCLUDED.permission_allowed,
                                                               change_reason = EXCLUDED.change_reason,
                                                               updated_at = CURRENT_TIMESTAMP,
                                                               updated_by = EXCLUDED.updated_by;

INSERT INTO function_permissions (screen_id, role_code, function_type, permission_allowed, change_reason, created_by, updated_by)
SELECT 'SCR-COURSE-AREA-GROUP-GRADE-QUERY', role_seed.role_code, 'READ', 'ALLOW', 'BASIC-60 성적 조회 기능 허용', 1, 1
FROM (VALUES ('R01'), ('R04'), ('R08'), ('R09')) AS role_seed(role_code)
ON CONFLICT (screen_id, role_code, function_type) DO UPDATE SET permission_allowed = EXCLUDED.permission_allowed,
                                                               change_reason = EXCLUDED.change_reason,
                                                               updated_at = CURRENT_TIMESTAMP,
                                                               updated_by = EXCLUDED.updated_by;
