CREATE TABLE IF NOT EXISTS teaching_evaluation_achievements (
    achievement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    faculty_user_id bigint NOT NULL,
    evaluation_year varchar(4) NOT NULL,
    academic_year varchar(4) NOT NULL,
    semester varchar(20) NOT NULL,
    course_code varchar(50) NOT NULL,
    course_name varchar(200) NOT NULL,
    evaluation_score numeric(5,2) NOT NULL,
    evaluation_status varchar(30) NOT NULL DEFAULT 'DRAFTING',
    management_item_setting_id bigint,
    attachment_ref varchar(300),
    deleted_yn char(1) NOT NULL DEFAULT 'N',
    deleted_at timestamp,
    deleted_by bigint,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    CONSTRAINT uq_teaching_evaluation_achievements UNIQUE (faculty_user_id, academic_year, semester, course_code, deleted_yn),
    CONSTRAINT ck_teaching_evaluation_achievements_year CHECK (evaluation_year ~ '^[0-9]{4}$' AND academic_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_teaching_evaluation_achievements_score CHECK (evaluation_score >= 0 AND evaluation_score <= 100),
    CONSTRAINT ck_teaching_evaluation_achievements_status CHECK (evaluation_status IN ('DRAFTING','SUBMITTED','DEPARTMENT_CONFIRMED','DEPARTMENT_REJECTED','CERTIFIED','CERTIFICATION_RETURNED','EVALUATION_CONFIRMED','DELETED')),
    CONSTRAINT ck_teaching_evaluation_achievements_deleted CHECK (deleted_yn IN ('Y','N')),
    CONSTRAINT fk_teaching_evaluation_achievements_faculty FOREIGN KEY (faculty_user_id) REFERENCES users(user_id),
    CONSTRAINT fk_teaching_evaluation_achievements_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_teaching_evaluation_achievements_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id),
    CONSTRAINT fk_teaching_evaluation_achievements_deleted_by FOREIGN KEY (deleted_by) REFERENCES users(user_id)
);
COMMENT ON TABLE teaching_evaluation_achievements IS '교육영역 강의평가 실적. 교원의 강좌별 강의평가 결과와 업적 인증 상태를 보존한다.';
COMMENT ON COLUMN teaching_evaluation_achievements.evaluation_status IS 'DRAFTING:작성중|SUBMITTED:제출|DEPARTMENT_CONFIRMED:학과장확인|DEPARTMENT_REJECTED:학과장미승인|CERTIFIED:인증|CERTIFICATION_RETURNED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN teaching_evaluation_achievements.management_item_setting_id IS 'evaluation_element_management_item_settings.setting_id 참조 의도 (동적 관리항목 연결, FK 미선언)';
COMMENT ON COLUMN teaching_evaluation_achievements.attachment_ref IS '기존 FileStoragePort 첨부 참조값 (애플리케이션에서 갱신)';
COMMENT ON COLUMN teaching_evaluation_achievements.deleted_yn IS 'Y:삭제|N:정상';
COMMENT ON COLUMN teaching_evaluation_achievements.deleted_by IS 'users.user_id 참조 의도 (논리 삭제 처리자)';
CREATE INDEX IF NOT EXISTS idx_teaching_evaluation_achievements_search
    ON teaching_evaluation_achievements(faculty_user_id, evaluation_year, semester, evaluation_status, deleted_yn, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_teaching_evaluation_achievements_management_item
    ON teaching_evaluation_achievements(management_item_setting_id);

CREATE TABLE IF NOT EXISTS teaching_achievements (
    achievement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    faculty_user_id bigint NOT NULL,
    evaluation_year varchar(4) NOT NULL,
    academic_year varchar(4) NOT NULL,
    semester varchar(20) NOT NULL,
    course_code varchar(50) NOT NULL,
    course_name varchar(200) NOT NULL,
    course_type varchar(50) NOT NULL,
    credit_hours numeric(4,1) NOT NULL,
    achievement_status varchar(30) NOT NULL DEFAULT 'DRAFTING',
    management_item_setting_id bigint,
    attachment_ref varchar(300),
    deleted_yn char(1) NOT NULL DEFAULT 'N',
    deleted_at timestamp,
    deleted_by bigint,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    CONSTRAINT uq_teaching_achievements UNIQUE (faculty_user_id, academic_year, semester, course_code, deleted_yn),
    CONSTRAINT ck_teaching_achievements_year CHECK (evaluation_year ~ '^[0-9]{4}$' AND academic_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_teaching_achievements_hours CHECK (credit_hours > 0),
    CONSTRAINT ck_teaching_achievements_status CHECK (achievement_status IN ('DRAFTING','SUBMITTED','DEPARTMENT_CONFIRMED','DEPARTMENT_REJECTED','CERTIFIED','CERTIFICATION_RETURNED','EVALUATION_CONFIRMED','DELETED')),
    CONSTRAINT ck_teaching_achievements_deleted CHECK (deleted_yn IN ('Y','N')),
    CONSTRAINT fk_teaching_achievements_faculty FOREIGN KEY (faculty_user_id) REFERENCES users(user_id),
    CONSTRAINT fk_teaching_achievements_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_teaching_achievements_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id),
    CONSTRAINT fk_teaching_achievements_deleted_by FOREIGN KEY (deleted_by) REFERENCES users(user_id)
);
COMMENT ON TABLE teaching_achievements IS '교육영역 강의실적. 교원의 학기별 강좌·학점시수 실적과 인증 상태를 보존한다.';
COMMENT ON COLUMN teaching_achievements.achievement_status IS 'DRAFTING:작성중|SUBMITTED:제출|DEPARTMENT_CONFIRMED:학과장확인|DEPARTMENT_REJECTED:학과장미승인|CERTIFIED:인증|CERTIFICATION_RETURNED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN teaching_achievements.management_item_setting_id IS 'evaluation_element_management_item_settings.setting_id 참조 의도 (동적 관리항목 연결, FK 미선언)';
COMMENT ON COLUMN teaching_achievements.attachment_ref IS '기존 FileStoragePort 첨부 참조값 (애플리케이션에서 갱신)';
COMMENT ON COLUMN teaching_achievements.deleted_yn IS 'Y:삭제|N:정상';
COMMENT ON COLUMN teaching_achievements.deleted_by IS 'users.user_id 참조 의도 (논리 삭제 처리자)';
CREATE INDEX IF NOT EXISTS idx_teaching_achievements_search
    ON teaching_achievements(faculty_user_id, evaluation_year, semester, achievement_status, deleted_yn, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_teaching_achievements_management_item
    ON teaching_achievements(management_item_setting_id);

CREATE TABLE IF NOT EXISTS student_guidance_achievements (
    achievement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    faculty_user_id bigint NOT NULL,
    evaluation_year varchar(4) NOT NULL,
    academic_year varchar(4) NOT NULL,
    semester varchar(20) NOT NULL,
    student_no varchar(50) NOT NULL,
    student_name varchar(100) NOT NULL,
    guidance_type varchar(50) NOT NULL,
    guidance_date date NOT NULL,
    guidance_content varchar(2000) NOT NULL,
    achievement_status varchar(30) NOT NULL DEFAULT 'DRAFTING',
    management_item_setting_id bigint,
    attachment_ref varchar(300),
    deleted_yn char(1) NOT NULL DEFAULT 'N',
    deleted_at timestamp,
    deleted_by bigint,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    CONSTRAINT uq_student_guidance_achievements UNIQUE (faculty_user_id, student_no, guidance_type, guidance_date, deleted_yn),
    CONSTRAINT ck_student_guidance_achievements_year CHECK (evaluation_year ~ '^[0-9]{4}$' AND academic_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_student_guidance_achievements_status CHECK (achievement_status IN ('DRAFTING','SUBMITTED','DEPARTMENT_CONFIRMED','DEPARTMENT_REJECTED','CERTIFIED','CERTIFICATION_RETURNED','EVALUATION_CONFIRMED','DELETED')),
    CONSTRAINT ck_student_guidance_achievements_deleted CHECK (deleted_yn IN ('Y','N')),
    CONSTRAINT fk_student_guidance_achievements_faculty FOREIGN KEY (faculty_user_id) REFERENCES users(user_id),
    CONSTRAINT fk_student_guidance_achievements_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_student_guidance_achievements_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id),
    CONSTRAINT fk_student_guidance_achievements_deleted_by FOREIGN KEY (deleted_by) REFERENCES users(user_id)
);
COMMENT ON TABLE student_guidance_achievements IS '교육영역 학생지도 실적. 학생별 지도 유형·일자·내용과 Excel 일괄등록 대상 상태를 보존한다.';
COMMENT ON COLUMN student_guidance_achievements.guidance_type IS 'ADVISORY:상담지도|CAREER:진로지도|ACADEMIC:학업지도|OTHER:기타';
COMMENT ON COLUMN student_guidance_achievements.achievement_status IS 'DRAFTING:작성중|SUBMITTED:제출|DEPARTMENT_CONFIRMED:학과장확인|DEPARTMENT_REJECTED:학과장미승인|CERTIFIED:인증|CERTIFICATION_RETURNED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN student_guidance_achievements.management_item_setting_id IS 'evaluation_element_management_item_settings.setting_id 참조 의도 (동적 관리항목 연결, FK 미선언)';
COMMENT ON COLUMN student_guidance_achievements.attachment_ref IS '기존 FileStoragePort 첨부 참조값 (애플리케이션에서 갱신)';
COMMENT ON COLUMN student_guidance_achievements.deleted_yn IS 'Y:삭제|N:정상';
COMMENT ON COLUMN student_guidance_achievements.deleted_by IS 'users.user_id 참조 의도 (논리 삭제 처리자)';
CREATE INDEX IF NOT EXISTS idx_student_guidance_achievements_search
    ON student_guidance_achievements(faculty_user_id, evaluation_year, semester, guidance_type, achievement_status, deleted_yn, guidance_date DESC);
CREATE INDEX IF NOT EXISTS idx_student_guidance_achievements_student
    ON student_guidance_achievements(student_no, deleted_yn);

CREATE TABLE IF NOT EXISTS graduate_achievements (
    achievement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    faculty_user_id bigint NOT NULL,
    evaluation_year varchar(4) NOT NULL,
    academic_year varchar(4) NOT NULL,
    semester varchar(20) NOT NULL,
    student_no varchar(50) NOT NULL,
    student_name varchar(100) NOT NULL,
    degree_type varchar(20) NOT NULL,
    graduate_date date NOT NULL,
    graduate_status varchar(30) NOT NULL,
    thesis_title varchar(500),
    achievement_status varchar(30) NOT NULL DEFAULT 'DRAFTING',
    management_item_setting_id bigint,
    attachment_ref varchar(300),
    deleted_yn char(1) NOT NULL DEFAULT 'N',
    deleted_at timestamp,
    deleted_by bigint,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    CONSTRAINT uq_graduate_achievements UNIQUE (faculty_user_id, student_no, degree_type, graduate_date, deleted_yn),
    CONSTRAINT ck_graduate_achievements_year CHECK (evaluation_year ~ '^[0-9]{4}$' AND academic_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_graduate_achievements_degree CHECK (degree_type IN ('MASTER','DOCTOR')),
    CONSTRAINT ck_graduate_achievements_graduate_status CHECK (graduate_status IN ('COMPLETED','EXPECTED','WITHDRAWN')),
    CONSTRAINT ck_graduate_achievements_status CHECK (achievement_status IN ('DRAFTING','SUBMITTED','DEPARTMENT_CONFIRMED','DEPARTMENT_REJECTED','CERTIFIED','CERTIFICATION_RETURNED','EVALUATION_CONFIRMED','DELETED')),
    CONSTRAINT ck_graduate_achievements_deleted CHECK (deleted_yn IN ('Y','N')),
    CONSTRAINT fk_graduate_achievements_faculty FOREIGN KEY (faculty_user_id) REFERENCES users(user_id),
    CONSTRAINT fk_graduate_achievements_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_graduate_achievements_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id),
    CONSTRAINT fk_graduate_achievements_deleted_by FOREIGN KEY (deleted_by) REFERENCES users(user_id)
);
COMMENT ON TABLE graduate_achievements IS '교육영역 석·박사 배출 실적. 지도교원의 학생별 학위·졸업 결과와 인증 상태를 보존한다.';
COMMENT ON COLUMN graduate_achievements.degree_type IS 'MASTER:석사|DOCTOR:박사';
COMMENT ON COLUMN graduate_achievements.graduate_status IS 'COMPLETED:졸업완료|EXPECTED:졸업예정|WITHDRAWN:수료·중도포기';
COMMENT ON COLUMN graduate_achievements.achievement_status IS 'DRAFTING:작성중|SUBMITTED:제출|DEPARTMENT_CONFIRMED:학과장확인|DEPARTMENT_REJECTED:학과장미승인|CERTIFIED:인증|CERTIFICATION_RETURNED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN graduate_achievements.management_item_setting_id IS 'evaluation_element_management_item_settings.setting_id 참조 의도 (동적 관리항목 연결, FK 미선언)';
COMMENT ON COLUMN graduate_achievements.attachment_ref IS '기존 FileStoragePort 첨부 참조값 (애플리케이션에서 갱신)';
COMMENT ON COLUMN graduate_achievements.deleted_yn IS 'Y:삭제|N:정상';
COMMENT ON COLUMN graduate_achievements.deleted_by IS 'users.user_id 참조 의도 (논리 삭제 처리자)';
CREATE INDEX IF NOT EXISTS idx_graduate_achievements_search
    ON graduate_achievements(faculty_user_id, evaluation_year, semester, degree_type, achievement_status, deleted_yn, graduate_date DESC);
CREATE INDEX IF NOT EXISTS idx_graduate_achievements_student
    ON graduate_achievements(student_no, deleted_yn);

CREATE TABLE IF NOT EXISTS achievement_status_histories (
    history_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    achievement_type varchar(50) NOT NULL,
    achievement_id bigint NOT NULL,
    from_status varchar(30),
    to_status varchar(30) NOT NULL,
    processed_by bigint NOT NULL,
    processed_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reason varchar(1000),
    request_id varchar(100) NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    CONSTRAINT ck_achievement_status_histories_type CHECK (achievement_type IN ('TEACHING_EVALUATION','TEACHING','STUDENT_GUIDANCE','GRADUATE')),
    CONSTRAINT ck_achievement_status_histories_from_status CHECK (from_status IS NULL OR from_status IN ('DRAFTING','SUBMITTED','DEPARTMENT_CONFIRMED','DEPARTMENT_REJECTED','CERTIFIED','CERTIFICATION_RETURNED','EVALUATION_CONFIRMED','DELETED')),
    CONSTRAINT ck_achievement_status_histories_to_status CHECK (to_status IN ('DRAFTING','SUBMITTED','DEPARTMENT_CONFIRMED','DEPARTMENT_REJECTED','CERTIFIED','CERTIFICATION_RETURNED','EVALUATION_CONFIRMED','DELETED')),
    CONSTRAINT fk_achievement_status_histories_processed_by FOREIGN KEY (processed_by) REFERENCES users(user_id),
    CONSTRAINT fk_achievement_status_histories_created_by FOREIGN KEY (created_by) REFERENCES users(user_id)
);
COMMENT ON TABLE achievement_status_histories IS '교육영역 업적 상태 전이 이력. 모든 실적 유형의 처리자·처리일시·사유·요청 식별자를 공통으로 보존한다.';
COMMENT ON COLUMN achievement_status_histories.achievement_type IS 'TEACHING_EVALUATION:강의평가|TEACHING:강의실적|STUDENT_GUIDANCE:학생지도|GRADUATE:석박사배출';
COMMENT ON COLUMN achievement_status_histories.achievement_id IS '교육영역 업적 원천 테이블의 achievement_id 참조 의도 (다형 참조, FK 미선언)';
COMMENT ON COLUMN achievement_status_histories.from_status IS 'DRAFTING:작성중|SUBMITTED:제출|DEPARTMENT_CONFIRMED:학과장확인|DEPARTMENT_REJECTED:학과장미승인|CERTIFIED:인증|CERTIFICATION_RETURNED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN achievement_status_histories.to_status IS 'DRAFTING:작성중|SUBMITTED:제출|DEPARTMENT_CONFIRMED:학과장확인|DEPARTMENT_REJECTED:학과장미승인|CERTIFIED:인증|CERTIFICATION_RETURNED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN achievement_status_histories.processed_by IS 'users.user_id 참조 의도 (상태 전이 처리자)';
COMMENT ON COLUMN achievement_status_histories.request_id IS '전 구간 추적을 위한 요청 식별자';
CREATE INDEX IF NOT EXISTS idx_achievement_status_histories_lookup
    ON achievement_status_histories(achievement_type, achievement_id, processed_at DESC);
CREATE INDEX IF NOT EXISTS idx_achievement_status_histories_request
    ON achievement_status_histories(request_id);

WITH seed_users AS (
    SELECT user_id, row_number() OVER (ORDER BY user_id) AS row_no
    FROM users
), seed_actors AS (
    SELECT
        COALESCE((SELECT user_id FROM seed_users WHERE row_no = 1), (SELECT user_id FROM users ORDER BY user_id LIMIT 1)) AS actor_one,
        COALESCE((SELECT user_id FROM seed_users WHERE row_no = 2), (SELECT user_id FROM users ORDER BY user_id LIMIT 1)) AS actor_two,
        COALESCE((SELECT user_id FROM seed_users WHERE row_no = 3), (SELECT user_id FROM users ORDER BY user_id LIMIT 1)) AS actor_three
)
INSERT INTO teaching_evaluation_achievements (faculty_user_id, evaluation_year, academic_year, semester, course_code, course_name, evaluation_score, evaluation_status, created_by, updated_by)
SELECT actor_one, '2026', '2026', '1', 'B65-EVAL-001', '교육성과 분석', 92.50, 'DRAFTING', actor_one, actor_one FROM seed_actors
UNION ALL SELECT actor_two, '2026', '2026', '1', 'B65-EVAL-002', '교육과정 설계', 88.00, 'SUBMITTED', actor_two, actor_two FROM seed_actors
UNION ALL SELECT actor_three, '2026', '2026', '2', 'B65-EVAL-003', '학생성장 지원', 95.00, 'CERTIFIED', actor_three, actor_three FROM seed_actors
ON CONFLICT (faculty_user_id, academic_year, semester, course_code, deleted_yn) DO NOTHING;

WITH seed_users AS (
    SELECT user_id, row_number() OVER (ORDER BY user_id) AS row_no
    FROM users
), seed_actors AS (
    SELECT COALESCE((SELECT user_id FROM seed_users WHERE row_no = 1), (SELECT user_id FROM users ORDER BY user_id LIMIT 1)) AS actor_one,
           COALESCE((SELECT user_id FROM seed_users WHERE row_no = 2), (SELECT user_id FROM users ORDER BY user_id LIMIT 1)) AS actor_two,
           COALESCE((SELECT user_id FROM seed_users WHERE row_no = 3), (SELECT user_id FROM users ORDER BY user_id LIMIT 1)) AS actor_three
)
INSERT INTO teaching_achievements (faculty_user_id, evaluation_year, academic_year, semester, course_code, course_name, course_type, credit_hours, achievement_status, created_by, updated_by)
SELECT actor_one, '2026', '2026', '1', 'B65-TEACH-001', '교육성과 분석', 'MAJOR', 3.0, 'DRAFTING', actor_one, actor_one FROM seed_actors
UNION ALL SELECT actor_two, '2026', '2026', '1', 'B65-TEACH-002', '교육과정 설계', 'LIBERAL', 2.0, 'SUBMITTED', actor_two, actor_two FROM seed_actors
UNION ALL SELECT actor_three, '2026', '2026', '2', 'B65-TEACH-003', '학생성장 지원', 'MAJOR', 3.0, 'CERTIFIED', actor_three, actor_three FROM seed_actors
ON CONFLICT (faculty_user_id, academic_year, semester, course_code, deleted_yn) DO NOTHING;

WITH seed_users AS (
    SELECT user_id, row_number() OVER (ORDER BY user_id) AS row_no
    FROM users
), seed_actors AS (
    SELECT COALESCE((SELECT user_id FROM seed_users WHERE row_no = 1), (SELECT user_id FROM users ORDER BY user_id LIMIT 1)) AS actor_one,
           COALESCE((SELECT user_id FROM seed_users WHERE row_no = 2), (SELECT user_id FROM users ORDER BY user_id LIMIT 1)) AS actor_two,
           COALESCE((SELECT user_id FROM seed_users WHERE row_no = 3), (SELECT user_id FROM users ORDER BY user_id LIMIT 1)) AS actor_three
)
INSERT INTO student_guidance_achievements (faculty_user_id, evaluation_year, academic_year, semester, student_no, student_name, guidance_type, guidance_date, guidance_content, achievement_status, created_by, updated_by)
SELECT actor_one, '2026', '2026', '1', 'B65-STUDENT-001', '김학생', 'ADVISORY', DATE '2026-03-03', '학업 상담 지도', 'DRAFTING', actor_one, actor_one FROM seed_actors
UNION ALL SELECT actor_two, '2026', '2026', '1', 'B65-STUDENT-002', '이학생', 'CAREER', DATE '2026-04-10', '진로 상담 지도', 'SUBMITTED', actor_two, actor_two FROM seed_actors
UNION ALL SELECT actor_three, '2026', '2026', '2', 'B65-STUDENT-003', '박학생', 'ACADEMIC', DATE '2026-09-08', '학습 계획 지도', 'CERTIFIED', actor_three, actor_three FROM seed_actors
ON CONFLICT (faculty_user_id, student_no, guidance_type, guidance_date, deleted_yn) DO NOTHING;

WITH seed_users AS (
    SELECT user_id, row_number() OVER (ORDER BY user_id) AS row_no
    FROM users
), seed_actors AS (
    SELECT COALESCE((SELECT user_id FROM seed_users WHERE row_no = 1), (SELECT user_id FROM users ORDER BY user_id LIMIT 1)) AS actor_one,
           COALESCE((SELECT user_id FROM seed_users WHERE row_no = 2), (SELECT user_id FROM users ORDER BY user_id LIMIT 1)) AS actor_two,
           COALESCE((SELECT user_id FROM seed_users WHERE row_no = 3), (SELECT user_id FROM users ORDER BY user_id LIMIT 1)) AS actor_three
)
INSERT INTO graduate_achievements (faculty_user_id, evaluation_year, academic_year, semester, student_no, student_name, degree_type, graduate_date, graduate_status, thesis_title, achievement_status, created_by, updated_by)
SELECT actor_one, '2026', '2026', '1', 'B65-GRAD-001', '최대학원', 'MASTER', DATE '2026-02-20', 'COMPLETED', '교육성과 연구', 'DRAFTING', actor_one, actor_one FROM seed_actors
UNION ALL SELECT actor_two, '2026', '2026', '1', 'B65-GRAD-002', '윤대학원', 'DOCTOR', DATE '2026-02-20', 'COMPLETED', '교육과정 개선 연구', 'SUBMITTED', actor_two, actor_two FROM seed_actors
UNION ALL SELECT actor_three, '2026', '2026', '2', 'B65-GRAD-003', '한대학원', 'MASTER', DATE '2026-08-20', 'EXPECTED', '학생지도 연구', 'CERTIFIED', actor_three, actor_three FROM seed_actors
ON CONFLICT (faculty_user_id, student_no, degree_type, graduate_date, deleted_yn) DO NOTHING;

INSERT INTO achievement_status_histories (achievement_type, achievement_id, from_status, to_status, processed_by, reason, request_id, created_by)
SELECT 'TEACHING_EVALUATION', achievement_id, NULL, evaluation_status, faculty_user_id, 'BASIC-65 공통기반 seed', 'B65-SEED-EVAL-' || achievement_id, faculty_user_id
FROM teaching_evaluation_achievements
WHERE course_code LIKE 'B65-EVAL-%'
ON CONFLICT DO NOTHING;

INSERT INTO achievement_status_histories (achievement_type, achievement_id, from_status, to_status, processed_by, reason, request_id, created_by)
SELECT 'TEACHING', achievement_id, NULL, achievement_status, faculty_user_id, 'BASIC-65 공통기반 seed', 'B65-SEED-TEACH-' || achievement_id, faculty_user_id
FROM teaching_achievements
WHERE course_code LIKE 'B65-TEACH-%'
ON CONFLICT DO NOTHING;

INSERT INTO achievement_status_histories (achievement_type, achievement_id, from_status, to_status, processed_by, reason, request_id, created_by)
SELECT 'STUDENT_GUIDANCE', achievement_id, NULL, achievement_status, faculty_user_id, 'BASIC-65 공통기반 seed', 'B65-SEED-GUIDE-' || achievement_id, faculty_user_id
FROM student_guidance_achievements
WHERE student_no LIKE 'B65-STUDENT-%'
ON CONFLICT DO NOTHING;

INSERT INTO achievement_status_histories (achievement_type, achievement_id, from_status, to_status, processed_by, reason, request_id, created_by)
SELECT 'GRADUATE', achievement_id, NULL, achievement_status, faculty_user_id, 'BASIC-65 공통기반 seed', 'B65-SEED-GRAD-' || achievement_id, faculty_user_id
FROM graduate_achievements
WHERE student_no LIKE 'B65-GRAD-%'
ON CONFLICT DO NOTHING;
