CREATE TABLE IF NOT EXISTS function_permissions (
    function_permission_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    screen_id varchar(100) NOT NULL,
    role_code varchar(3) NOT NULL,
    function_type varchar(50) NOT NULL,
    permission_allowed varchar(10) NOT NULL,
    change_reason varchar(500),
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    CONSTRAINT uq_function_permissions_key UNIQUE (screen_id, role_code, function_type),
    CONSTRAINT ck_function_permissions_role CHECK (role_code IN ('R01','R02','R03','R04','R05','R06','R07','R08','R09')),
    CONSTRAINT ck_function_permissions_type CHECK (function_type IN ('READ','CREATE','UPDATE','DELETE','EXECUTE')),
    CONSTRAINT ck_function_permissions_allowed CHECK (permission_allowed IN ('ALLOW','DENY')),
    CONSTRAINT fk_function_permissions_role FOREIGN KEY (role_code) REFERENCES roles(role_code),
    CONSTRAINT fk_function_permissions_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_function_permissions_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE function_permissions IS '화면, 역할, 기능구분별 기능 권한 허용 또는 차단 설정. 메뉴 진입 권한과 데이터 범위 권한은 이 테이블에서 관리하지 않는다.';
COMMENT ON COLUMN function_permissions.function_type IS 'READ:조회|CREATE:등록|UPDATE:수정|DELETE:삭제|EXECUTE:실행';
COMMENT ON COLUMN function_permissions.permission_allowed IS 'ALLOW:허용|DENY:차단';
COMMENT ON COLUMN function_permissions.screen_id IS 'menus.screen_id 참조 의도 (FK 미선언)';

CREATE TABLE IF NOT EXISTS period_permission_links (
    period_permission_link_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_period_id varchar(100) NOT NULL,
    function_permission_id bigint NOT NULL,
    effective_start_at timestamp NOT NULL,
    effective_end_at timestamp,
    period_state varchar(20) NOT NULL DEFAULT 'BEFORE',
    change_reason varchar(500),
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    CONSTRAINT uq_period_permission_links_key UNIQUE (business_period_id, function_permission_id),
    CONSTRAINT ck_period_permission_range CHECK (effective_end_at IS NULL OR effective_end_at >= effective_start_at),
    CONSTRAINT ck_period_permission_state CHECK (period_state IN ('BEFORE','ACTIVE','AFTER')),
    CONSTRAINT fk_period_permission_function FOREIGN KEY (function_permission_id) REFERENCES function_permissions(function_permission_id),
    CONSTRAINT fk_period_permission_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_period_permission_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE period_permission_links IS '기존 업무기간 식별자와 기능 권한을 연결하고 서버 처리 시점의 기간 전, 기간 중, 기간 후 상태 판정을 지원한다.';
COMMENT ON COLUMN period_permission_links.business_period_id IS '기존 업무기간 식별자 참조 의도 (FK 미선언)';
COMMENT ON COLUMN period_permission_links.period_state IS 'BEFORE:기간전|ACTIVE:기간중|AFTER:기간후';

CREATE TABLE IF NOT EXISTS temporary_permissions (
    temporary_permission_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    work_data_ref varchar(200) NOT NULL,
    function_type varchar(50) NOT NULL,
    valid_start_at timestamp NOT NULL,
    valid_end_at timestamp NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'ACTIVE',
    change_reason varchar(500),
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    CONSTRAINT ck_temporary_permissions_function CHECK (function_type IN ('READ','CREATE','UPDATE','DELETE','EXECUTE')),
    CONSTRAINT ck_temporary_permissions_range CHECK (valid_end_at >= valid_start_at),
    CONSTRAINT ck_temporary_permissions_status CHECK (status IN ('ACTIVE','REVOKED','EXPIRED')),
    CONSTRAINT fk_temporary_permissions_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_temporary_permissions_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_temporary_permissions_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE temporary_permissions IS '특정 사용자, 업무자료, 기능, 유효기간에 한정된 임시 권한 예외. 사용자의 기본 역할과 상시 권한은 변경하지 않는다.';
COMMENT ON COLUMN temporary_permissions.work_data_ref IS '기존 업무자료 식별자 참조 의도 (FK 미선언)';
COMMENT ON COLUMN temporary_permissions.function_type IS 'READ:조회|CREATE:등록|UPDATE:수정|DELETE:삭제|EXECUTE:실행';
COMMENT ON COLUMN temporary_permissions.status IS 'ACTIVE:활성|REVOKED:회수|EXPIRED:만료';

CREATE TABLE IF NOT EXISTS permission_change_history (
    permission_history_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type varchar(50) NOT NULL,
    target_id varchar(200) NOT NULL,
    before_value jsonb,
    after_value jsonb,
    changed_by bigint NOT NULL,
    reason varchar(500) NOT NULL,
    changed_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_permission_history_target_type CHECK (target_type IN ('ROLE','MENU','FUNCTION','DATA_SCOPE','TEMPORARY')),
    CONSTRAINT fk_permission_history_changed_by FOREIGN KEY (changed_by) REFERENCES users(user_id)
);
COMMENT ON TABLE permission_change_history IS '역할, 메뉴, 기능, 데이터 범위, 임시 권한의 부여·변경·회수 전후 값과 처리자·사유를 영구 보존하는 조회 전용 이력.';
COMMENT ON COLUMN permission_change_history.target_type IS 'ROLE:역할|MENU:메뉴|FUNCTION:기능|DATA_SCOPE:데이터범위|TEMPORARY:임시권한';
COMMENT ON COLUMN permission_change_history.target_id IS '관련 권한 테이블 식별자 참조 의도 (복수 테이블 대상이므로 FK 미선언)';
COMMENT ON COLUMN permission_change_history.before_value IS '권한 변경 처리 직전 값의 JSON snapshot. PermissionChangeHistoryMapper.insertPermissionChangeHistory 시 애플리케이션에서 기록';
COMMENT ON COLUMN permission_change_history.after_value IS '권한 변경 처리 직후 값의 JSON snapshot. PermissionChangeHistoryMapper.insertPermissionChangeHistory 시 애플리케이션에서 기록';

CREATE INDEX IF NOT EXISTS idx_function_permissions_lookup ON function_permissions(screen_id, role_code, function_type);
CREATE INDEX IF NOT EXISTS idx_period_permission_function_time ON period_permission_links(function_permission_id, effective_start_at, effective_end_at);
CREATE INDEX IF NOT EXISTS idx_temporary_permissions_lookup ON temporary_permissions(user_id, work_data_ref, function_type, valid_start_at, valid_end_at, status);
CREATE INDEX IF NOT EXISTS idx_permission_change_history_filter ON permission_change_history(target_type, target_id, changed_at DESC);
CREATE INDEX IF NOT EXISTS idx_permission_change_history_changed_by ON permission_change_history(changed_by, changed_at DESC);

INSERT INTO menus (menu_id, parent_menu_id, menu_type, menu_name, display_order, screen_id, url, icon, business_category, description, system_use_yn, status, updated_by)
VALUES (128, 120, 'SCREEN', '기능 권한 관리', 4, 'SCR-FUNCTION-PERMISSION-MGMT', '/admin/function-permissions', 'lock-keyhole', 'SYSTEM', '화면·역할·기능구분별 기능 권한 관리', 'Y', 'ACTIVE', 1)
ON CONFLICT (menu_id) DO UPDATE SET menu_name = EXCLUDED.menu_name,
                                      parent_menu_id = EXCLUDED.parent_menu_id,
                                      display_order = EXCLUDED.display_order,
                                      screen_id = EXCLUDED.screen_id,
                                      url = EXCLUDED.url,
                                      updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_execution_info (menu_id, screen_id, url, icon, business_category, description, updated_by)
VALUES (128, 'SCR-FUNCTION-PERMISSION-MGMT', '/admin/function-permissions', 'lock-keyhole', 'SYSTEM', '화면·역할·기능구분별 기능 권한 관리', 1)
ON CONFLICT (menu_id) DO UPDATE SET screen_id = EXCLUDED.screen_id,
                                      url = EXCLUDED.url,
                                      icon = EXCLUDED.icon,
                                      business_category = EXCLUDED.business_category,
                                      description = EXCLUDED.description,
                                      updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_permissions (target_type, target_id, menu_id, access_allowed, status, created_by, updated_by, change_reason)
VALUES ('ROLE', 'R09', 128, 'ALLOW', 'ACTIVE', 1, 1, '시스템관리자 기능 권한 관리 메뉴 접근')
ON CONFLICT (target_type, target_id, menu_id) DO UPDATE SET access_allowed = EXCLUDED.access_allowed,
                                                            status = EXCLUDED.status,
                                                            updated_at = CURRENT_TIMESTAMP,
                                                            updated_by = EXCLUDED.updated_by,
                                                            change_reason = EXCLUDED.change_reason;

INSERT INTO function_permissions (screen_id, role_code, function_type, permission_allowed, change_reason, created_by, updated_by)
SELECT 'SCR-FUNCTION-PERMISSION-MGMT', 'R09', function_type, 'ALLOW', '시스템관리자 기능 권한 관리 기본 허용', 1, 1
FROM (VALUES ('READ'), ('CREATE'), ('UPDATE'), ('DELETE'), ('EXECUTE')) AS seed(function_type)
ON CONFLICT (screen_id, role_code, function_type) DO NOTHING;

INSERT INTO menus (menu_id, parent_menu_id, menu_type, menu_name, display_order, screen_id, url, icon, business_category, description, system_use_yn, status, updated_by)
VALUES (125, 120, 'SCREEN', '기간별 권한 관리', 5, 'SCR-PERIOD-PERMISSION-MGMT', '/admin/period-permissions', 'calendar-clock', 'SYSTEM', '업무기간과 기능 권한 연결 관리', 'Y', 'ACTIVE', 1)
ON CONFLICT (menu_id) DO UPDATE SET menu_name = EXCLUDED.menu_name,
                                      parent_menu_id = EXCLUDED.parent_menu_id,
                                      display_order = EXCLUDED.display_order,
                                      screen_id = EXCLUDED.screen_id,
                                      url = EXCLUDED.url,
                                      updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_execution_info (menu_id, screen_id, url, icon, business_category, description, updated_by)
VALUES (125, 'SCR-PERIOD-PERMISSION-MGMT', '/admin/period-permissions', 'calendar-clock', 'SYSTEM', '업무기간과 기능 권한 연결 관리', 1)
ON CONFLICT (menu_id) DO UPDATE SET screen_id = EXCLUDED.screen_id,
                                      url = EXCLUDED.url,
                                      icon = EXCLUDED.icon,
                                      business_category = EXCLUDED.business_category,
                                      description = EXCLUDED.description,
                                      updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_permissions (target_type, target_id, menu_id, access_allowed, status, created_by, updated_by, change_reason)
VALUES ('ROLE', 'R09', 125, 'ALLOW', 'ACTIVE', 1, 1, '시스템관리자 기간별 권한 관리 메뉴 접근')
ON CONFLICT (target_type, target_id, menu_id) DO UPDATE SET access_allowed = EXCLUDED.access_allowed,
                                                            status = EXCLUDED.status,
                                                            updated_at = CURRENT_TIMESTAMP,
                                                            updated_by = EXCLUDED.updated_by,
                                                            change_reason = EXCLUDED.change_reason;

INSERT INTO function_permissions (screen_id, role_code, function_type, permission_allowed, change_reason, created_by, updated_by)
SELECT 'SCR-PERIOD-PERMISSION-MGMT', 'R09', function_type, 'ALLOW', '시스템관리자 기간별 권한 관리 기본 허용', 1, 1
FROM (VALUES ('READ'), ('CREATE'), ('UPDATE'), ('DELETE'), ('EXECUTE')) AS seed(function_type)
ON CONFLICT (screen_id, role_code, function_type) DO NOTHING;

INSERT INTO menus (menu_id, parent_menu_id, menu_type, menu_name, display_order, screen_id, url, icon, business_category, description, system_use_yn, status, updated_by)
VALUES (126, 120, 'SCREEN', '임시 권한 관리', 6, 'SCR-TEMPORARY-PERMISSION-MGMT', '/admin/temporary-permissions', 'timer-reset', 'SYSTEM', '특정 교원·업무자료·기능·유효기간에 한정된 임시 권한 관리', 'Y', 'ACTIVE', 1)
ON CONFLICT (menu_id) DO UPDATE SET menu_name = EXCLUDED.menu_name,
                                      parent_menu_id = EXCLUDED.parent_menu_id,
                                      display_order = EXCLUDED.display_order,
                                      screen_id = EXCLUDED.screen_id,
                                      url = EXCLUDED.url,
                                      updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_execution_info (menu_id, screen_id, url, icon, business_category, description, updated_by)
VALUES (126, 'SCR-TEMPORARY-PERMISSION-MGMT', '/admin/temporary-permissions', 'timer-reset', 'SYSTEM', '특정 교원·업무자료·기능·유효기간에 한정된 임시 권한 관리', 1)
ON CONFLICT (menu_id) DO UPDATE SET screen_id = EXCLUDED.screen_id,
                                      url = EXCLUDED.url,
                                      icon = EXCLUDED.icon,
                                      business_category = EXCLUDED.business_category,
                                      description = EXCLUDED.description,
                                      updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_permissions (target_type, target_id, menu_id, access_allowed, status, created_by, updated_by, change_reason)
VALUES ('ROLE', 'R09', 126, 'ALLOW', 'ACTIVE', 1, 1, '시스템관리자 임시 권한 관리 메뉴 접근')
ON CONFLICT (target_type, target_id, menu_id) DO UPDATE SET access_allowed = EXCLUDED.access_allowed,
                                                            status = EXCLUDED.status,
                                                            updated_at = CURRENT_TIMESTAMP,
                                                            updated_by = EXCLUDED.updated_by,
                                                            change_reason = EXCLUDED.change_reason;

INSERT INTO function_permissions (screen_id, role_code, function_type, permission_allowed, change_reason, created_by, updated_by)
SELECT 'SCR-TEMPORARY-PERMISSION-MGMT', 'R09', function_type, 'ALLOW', '시스템관리자 임시 권한 관리 기본 허용', 1, 1
FROM (VALUES ('READ'), ('CREATE'), ('UPDATE'), ('DELETE'), ('EXECUTE')) AS seed(function_type)
ON CONFLICT (screen_id, role_code, function_type) DO NOTHING;

INSERT INTO menus (menu_id, parent_menu_id, menu_type, menu_name, display_order, screen_id, url, icon, business_category, description, system_use_yn, status, updated_by)
VALUES (127, 120, 'SCREEN', '권한 변경 이력 조회', 7, 'SCR-PERMISSION-HISTORY', '/admin/permission-history', 'history', 'SYSTEM', '권한 부여·변경·회수 이력 조회', 'Y', 'ACTIVE', 1)
ON CONFLICT (menu_id) DO UPDATE SET menu_name = EXCLUDED.menu_name,
                                      parent_menu_id = EXCLUDED.parent_menu_id,
                                      display_order = EXCLUDED.display_order,
                                      screen_id = EXCLUDED.screen_id,
                                      url = EXCLUDED.url,
                                      updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_execution_info (menu_id, screen_id, url, icon, business_category, description, updated_by)
VALUES (127, 'SCR-PERMISSION-HISTORY', '/admin/permission-history', 'history', 'SYSTEM', '권한 부여·변경·회수 이력 조회', 1)
ON CONFLICT (menu_id) DO UPDATE SET screen_id = EXCLUDED.screen_id,
                                      url = EXCLUDED.url,
                                      icon = EXCLUDED.icon,
                                      business_category = EXCLUDED.business_category,
                                      description = EXCLUDED.description,
                                      updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_permissions (target_type, target_id, menu_id, access_allowed, status, created_by, updated_by, change_reason)
VALUES ('ROLE', 'R09', 127, 'ALLOW', 'ACTIVE', 1, 1, '시스템관리자 권한 변경 이력 조회 메뉴 접근')
ON CONFLICT (target_type, target_id, menu_id) DO UPDATE SET access_allowed = EXCLUDED.access_allowed,
                                                            status = EXCLUDED.status,
                                                            updated_at = CURRENT_TIMESTAMP,
                                                            updated_by = EXCLUDED.updated_by,
                                                            change_reason = EXCLUDED.change_reason;
