-- BASIC-81 교육영역 실적 전반의 강의평가 원천과 공통 상태이력 기반을 추가한다.

CREATE TABLE IF NOT EXISTS lecture_evaluation_achievements (
    achievement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    management_no varchar(50) NOT NULL,
    target_user_id bigint NOT NULL,
    evaluation_year varchar(4) NOT NULL,
    management_item_code varchar(50) NOT NULL,
    occurred_date date NOT NULL,
    achievement_detail text,
    certification_status varchar(30) NOT NULL DEFAULT 'DRAFT',
    attachment_ref varchar(300),
    deleted_yn char(1) NOT NULL DEFAULT 'N',
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    CONSTRAINT uq_lecture_evaluation_achievements_management_no UNIQUE (management_no),
    CONSTRAINT ck_lecture_evaluation_achievements_year CHECK (evaluation_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_lecture_evaluation_achievements_status CHECK (
        certification_status IN (
            'DRAFT',
            'SUBMITTED',
            'DEPARTMENT_CONFIRMED',
            'DEPARTMENT_REJECTED',
            'CERTIFIED',
            'CERTIFICATION_REJECTED',
            'EVALUATION_CONFIRMED',
            'DELETED'
        )
    ),
    CONSTRAINT ck_lecture_evaluation_achievements_deleted CHECK (deleted_yn IN ('Y', 'N')),
    CONSTRAINT fk_lecture_evaluation_achievements_target_user
        FOREIGN KEY (target_user_id) REFERENCES users(user_id),
    CONSTRAINT fk_lecture_evaluation_achievements_created_by
        FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_lecture_evaluation_achievements_updated_by
        FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE lecture_evaluation_achievements IS '교육영역 강의평가 실적 원천. 교원별 발생일, 관리항목, 인증상태와 논리삭제 정보를 보존한다.';
COMMENT ON COLUMN lecture_evaluation_achievements.certification_status IS 'DRAFT:작성중|SUBMITTED:제출|DEPARTMENT_CONFIRMED:학과장확인|DEPARTMENT_REJECTED:학과장미승인|CERTIFIED:인증|CERTIFICATION_REJECTED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN lecture_evaluation_achievements.attachment_ref IS 'FileStoragePort의 외부 비노출 첨부 참조값';
COMMENT ON COLUMN lecture_evaluation_achievements.deleted_yn IS 'Y:삭제|N:정상';
COMMENT ON COLUMN lecture_evaluation_achievements.target_user_id IS 'users.user_id 참조 의도 (실적 대상 교원)';
COMMENT ON COLUMN lecture_evaluation_achievements.created_by IS 'users.user_id 참조 의도 (최초 입력자)';
COMMENT ON COLUMN lecture_evaluation_achievements.updated_by IS 'users.user_id 참조 의도 (최종 수정자)';

CREATE INDEX IF NOT EXISTS idx_lecture_evaluation_achievements_search
    ON lecture_evaluation_achievements (
        target_user_id,
        evaluation_year,
        management_item_code,
        occurred_date DESC,
        certification_status
    )
    WHERE deleted_yn = 'N';

CREATE TABLE IF NOT EXISTS education_achievement_status_histories (
    status_history_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    achievement_type varchar(30) NOT NULL,
    achievement_id bigint NOT NULL,
    previous_status varchar(30),
    next_status varchar(30) NOT NULL,
    action_type varchar(30) NOT NULL,
    reason_code varchar(100),
    opinion varchar(1000),
    processed_by bigint NOT NULL,
    processed_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_education_achievement_status_histories_type CHECK (
        achievement_type IN ('LECTURE_EVALUATION', 'LECTURE', 'STUDENT_GUIDANCE', 'DEGREE_COMPLETION')
    ),
    CONSTRAINT ck_education_achievement_status_histories_previous_status CHECK (
        previous_status IS NULL
        OR previous_status IN (
            'DRAFT',
            'SUBMITTED',
            'DEPARTMENT_CONFIRMED',
            'DEPARTMENT_REJECTED',
            'CERTIFIED',
            'CERTIFICATION_REJECTED',
            'EVALUATION_CONFIRMED',
            'DELETED'
        )
    ),
    CONSTRAINT ck_education_achievement_status_histories_next_status CHECK (
        next_status IN (
            'DRAFT',
            'SUBMITTED',
            'DEPARTMENT_CONFIRMED',
            'DEPARTMENT_REJECTED',
            'CERTIFIED',
            'CERTIFICATION_REJECTED',
            'EVALUATION_CONFIRMED',
            'DELETED'
        )
    ),
    CONSTRAINT fk_education_achievement_status_histories_processed_by
        FOREIGN KEY (processed_by) REFERENCES users(user_id)
);
COMMENT ON TABLE education_achievement_status_histories IS '교육영역 실적의 상태 전이 이력. 처리자, 처리일시, 사유와 의견을 변경 불가 이력으로 보관한다.';
COMMENT ON COLUMN education_achievement_status_histories.achievement_type IS 'LECTURE_EVALUATION:강의평가|LECTURE:강의실적|STUDENT_GUIDANCE:학생지도|DEGREE_COMPLETION:석박사배출';
COMMENT ON COLUMN education_achievement_status_histories.achievement_id IS '각 achievement_type의 원천 achievement_id 참조 의도 (다형 FK 미선언)';
COMMENT ON COLUMN education_achievement_status_histories.previous_status IS 'DRAFT:작성중|SUBMITTED:제출|DEPARTMENT_CONFIRMED:학과장확인|DEPARTMENT_REJECTED:학과장미승인|CERTIFIED:인증|CERTIFICATION_REJECTED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN education_achievement_status_histories.next_status IS 'DRAFT:작성중|SUBMITTED:제출|DEPARTMENT_CONFIRMED:학과장확인|DEPARTMENT_REJECTED:학과장미승인|CERTIFIED:인증|CERTIFICATION_REJECTED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN education_achievement_status_histories.processed_by IS 'users.user_id 참조 의도 (상태 처리자)';

CREATE INDEX IF NOT EXISTS idx_education_achievement_status_histories_lookup
    ON education_achievement_status_histories (achievement_type, achievement_id, processed_at DESC);

INSERT INTO lecture_evaluation_achievements (
    management_no,
    target_user_id,
    evaluation_year,
    management_item_code,
    occurred_date,
    achievement_detail,
    certification_status,
    attachment_ref,
    deleted_yn,
    created_by,
    updated_by
)
SELECT
    seed.management_no,
    owner.user_id,
    seed.evaluation_year,
    seed.management_item_code,
    seed.occurred_date,
    seed.achievement_detail,
    seed.certification_status,
    seed.attachment_ref,
    'N',
    owner.user_id,
    owner.user_id
FROM (
    VALUES
        ('B77-LE-001', 'professor1', '2026', 'LECTURE_EVALUATION', DATE '2026-04-10', 'B77-LE-001 정상 강의평가 실적', 'DRAFT', NULL),
        ('B77-LE-002', 'professor2', '2026', 'LECTURE_EVALUATION', DATE '2025-12-31', 'B77-LE-001 기간 외 경고 검증 실적', 'SUBMITTED', 'files/opaque/b77-le-002'),
        ('B77-LE-003', 'business-owner', '2026', 'LECTURE_EVALUATION', DATE '2026-04-12', 'B77-LE-001 인증 상태 검증 실적', 'CERTIFIED', NULL)
) AS seed (
    management_no,
    login_id,
    evaluation_year,
    management_item_code,
    occurred_date,
    achievement_detail,
    certification_status,
    attachment_ref
)
JOIN users owner
    ON owner.login_id = seed.login_id
ON CONFLICT (management_no) DO UPDATE SET
    target_user_id = EXCLUDED.target_user_id,
    evaluation_year = EXCLUDED.evaluation_year,
    management_item_code = EXCLUDED.management_item_code,
    occurred_date = EXCLUDED.occurred_date,
    achievement_detail = EXCLUDED.achievement_detail,
    certification_status = EXCLUDED.certification_status,
    attachment_ref = EXCLUDED.attachment_ref,
    deleted_yn = EXCLUDED.deleted_yn,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = EXCLUDED.updated_by;

INSERT INTO education_achievement_status_histories (
    achievement_type,
    achievement_id,
    previous_status,
    next_status,
    action_type,
    reason_code,
    opinion,
    processed_by
)
SELECT
    'LECTURE_EVALUATION',
    achievement.achievement_id,
    seed.previous_status,
    seed.next_status,
    seed.action_type,
    seed.reason_code,
    seed.opinion,
    processor.user_id
FROM (
    VALUES
        ('B77-LE-001', NULL::varchar(30), 'DRAFT', 'CREATE', NULL::varchar(100), 'B77-LE-001 최초 입력', 'professor1'),
        ('B77-LE-002', 'DRAFT', 'SUBMITTED', 'SUBMIT', NULL::varchar(100), 'B77-LE-001 제출 fixture', 'professor2'),
        ('B77-LE-003', 'DEPARTMENT_CONFIRMED', 'CERTIFIED', 'CERTIFY', 'EVIDENCE_OK', 'B77-LE-001 인증 fixture', 'business-owner')
) AS seed (
    management_no,
    previous_status,
    next_status,
    action_type,
    reason_code,
    opinion,
    processor_login_id
)
JOIN lecture_evaluation_achievements achievement
    ON achievement.management_no = seed.management_no
JOIN users processor
    ON processor.login_id = seed.processor_login_id
WHERE NOT EXISTS (
    SELECT 1
    FROM education_achievement_status_histories history
    WHERE history.achievement_type = 'LECTURE_EVALUATION'
      AND history.achievement_id = achievement.achievement_id
      AND history.action_type = seed.action_type
);
