CREATE TABLE IF NOT EXISTS lecture_evaluation_achievements (
    achievement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    management_no varchar(50) NOT NULL UNIQUE,
    evaluation_year varchar(4) NOT NULL,
    organization_code varchar(50) NOT NULL,
    teacher_user_id bigint NOT NULL,
    management_item_code varchar(100) NOT NULL,
    achievement_date date NOT NULL,
    achievement_status varchar(30) NOT NULL DEFAULT 'DRAFTING',
    detail_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    attachment_count integer NOT NULL DEFAULT 0,
    occurrence_date_warning_yn varchar(1) NOT NULL DEFAULT 'N',
    deleted_at timestamp,
    deleted_by bigint,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint NOT NULL,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint NOT NULL,
    change_reason varchar(500) NOT NULL,
    CONSTRAINT ck_lecture_evaluation_achievements_year CHECK (evaluation_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_lecture_evaluation_achievements_status CHECK (achievement_status IN ('DRAFTING','SUBMITTED','DEPARTMENT_CONFIRMED','DEPARTMENT_REJECTED','CERTIFIED','CERTIFICATION_RETURNED','EVALUATION_CONFIRMED','DELETED')),
    CONSTRAINT ck_lecture_evaluation_achievements_attachment_count CHECK (attachment_count >= 0),
    CONSTRAINT ck_lecture_evaluation_achievements_warning CHECK (occurrence_date_warning_yn IN ('Y','N')),
    CONSTRAINT fk_lecture_evaluation_achievements_organization FOREIGN KEY (organization_code) REFERENCES organizations(organization_code),
    CONSTRAINT fk_lecture_evaluation_achievements_teacher FOREIGN KEY (teacher_user_id) REFERENCES users(user_id),
    CONSTRAINT fk_lecture_evaluation_achievements_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_lecture_evaluation_achievements_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id),
    CONSTRAINT fk_lecture_evaluation_achievements_deleted_by FOREIGN KEY (deleted_by) REFERENCES users(user_id)
);
COMMENT ON TABLE lecture_evaluation_achievements IS '교육영역 강의평가 실적의 원천, 인증상태 및 논리삭제 정보를 보존한다.';
COMMENT ON COLUMN lecture_evaluation_achievements.management_item_code IS 'evaluation_element_management_item_settings의 활성 관리항목 코드 참조 의도 (FK 미선언)';
COMMENT ON COLUMN lecture_evaluation_achievements.achievement_status IS 'DRAFTING:작성중|SUBMITTED:제출|DEPARTMENT_CONFIRMED:학과장확인|DEPARTMENT_REJECTED:학과장미승인|CERTIFIED:인증|CERTIFICATION_RETURNED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN lecture_evaluation_achievements.detail_payload IS 'FR-018 활성 관리항목 설정에 따라 애플리케이션이 검증·저장하는 유형별 상세값';
COMMENT ON COLUMN lecture_evaluation_achievements.occurrence_date_warning_yn IS 'Y:평가대상 기간 밖 발생일 경고|N:경고없음';
COMMENT ON COLUMN lecture_evaluation_achievements.deleted_by IS 'users.user_id 참조 의도 (논리삭제 처리자)';

CREATE TABLE IF NOT EXISTS education_achievement_status_histories (
    status_history_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    achievement_type varchar(50) NOT NULL,
    achievement_id bigint NOT NULL,
    previous_status varchar(30) NOT NULL,
    next_status varchar(30) NOT NULL,
    transition_reason varchar(500),
    processed_by bigint NOT NULL,
    processed_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    request_id varchar(100),
    CONSTRAINT ck_education_achievement_status_histories_type CHECK (achievement_type IN ('LECTURE_EVALUATION','LECTURE','STUDENT_GUIDANCE','DEGREE_COMPLETION')),
    CONSTRAINT ck_education_achievement_status_histories_previous_status CHECK (previous_status IN ('DRAFTING','SUBMITTED','DEPARTMENT_CONFIRMED','DEPARTMENT_REJECTED','CERTIFIED','CERTIFICATION_RETURNED','EVALUATION_CONFIRMED','DELETED')),
    CONSTRAINT ck_education_achievement_status_histories_next_status CHECK (next_status IN ('DRAFTING','SUBMITTED','DEPARTMENT_CONFIRMED','DEPARTMENT_REJECTED','CERTIFIED','CERTIFICATION_RETURNED','EVALUATION_CONFIRMED','DELETED')),
    CONSTRAINT fk_education_achievement_status_histories_processed_by FOREIGN KEY (processed_by) REFERENCES users(user_id)
);
COMMENT ON TABLE education_achievement_status_histories IS '교육영역 실적 유형별 인증상태 전이의 이전·이후 상태, 처리자, 처리시각 및 사유를 보존한다.';
COMMENT ON COLUMN education_achievement_status_histories.achievement_id IS 'achievement_type에 따라 교육영역 실적 원천 테이블의 achievement_id 참조 의도 (다형 FK 미선언)';
COMMENT ON COLUMN education_achievement_status_histories.previous_status IS 'DRAFTING:작성중|SUBMITTED:제출|DEPARTMENT_CONFIRMED:학과장확인|DEPARTMENT_REJECTED:학과장미승인|CERTIFIED:인증|CERTIFICATION_RETURNED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN education_achievement_status_histories.next_status IS 'DRAFTING:작성중|SUBMITTED:제출|DEPARTMENT_CONFIRMED:학과장확인|DEPARTMENT_REJECTED:학과장미승인|CERTIFIED:인증|CERTIFICATION_RETURNED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN education_achievement_status_histories.request_id IS '요청 식별자 추적값';

CREATE INDEX IF NOT EXISTS idx_lecture_evaluation_achievements_list
    ON lecture_evaluation_achievements (evaluation_year, organization_code, teacher_user_id, achievement_status, achievement_date DESC)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_education_achievement_status_histories_lookup
    ON education_achievement_status_histories (achievement_type, achievement_id, processed_at DESC);

INSERT INTO lecture_evaluation_achievements (
    management_no, evaluation_year, organization_code, teacher_user_id, management_item_code,
    achievement_date, achievement_status, detail_payload, attachment_count, occurrence_date_warning_yn,
    created_by, updated_by, change_reason
)
SELECT seed.management_no, seed.evaluation_year, 'KNUE-DEPT-COMP', u.user_id, seed.management_item_code,
       seed.achievement_date, seed.achievement_status, seed.detail_payload::jsonb, seed.attachment_count,
       seed.occurrence_date_warning_yn, u.user_id, u.user_id, seed.change_reason
FROM users u
CROSS JOIN (VALUES
    ('B77-LE-001', '2026', 'LECTURE_EVALUATION', DATE '2026-04-10', 'DRAFTING', '{"lectureName":"교육평가론","score":4.8}', 0, 'N', 'BASIC-81 정상 강의평가 fixture'),
    ('B77-LE-002', '2026', 'LECTURE_EVALUATION', DATE '2026-01-15', 'SUBMITTED', '{"lectureName":"교육과정론","score":4.5}', 1, 'Y', 'BASIC-81 발생일 경계 강의평가 fixture'),
    ('B77-LE-003', '2025', 'LECTURE_EVALUATION', DATE '2025-11-20', 'EVALUATION_CONFIRMED', '{"lectureName":"교수학습방법론","score":4.9}', 2, 'N', 'BASIC-81 평가확정 강의평가 fixture')
) AS seed(management_no, evaluation_year, management_item_code, achievement_date, achievement_status, detail_payload, attachment_count, occurrence_date_warning_yn, change_reason)
WHERE u.login_id = 'professor1'
ON CONFLICT (management_no) DO NOTHING;

INSERT INTO education_achievement_status_histories (
    achievement_type, achievement_id, previous_status, next_status, transition_reason, processed_by, request_id
)
SELECT 'LECTURE_EVALUATION', achievement_id,
       CASE achievement_status WHEN 'EVALUATION_CONFIRMED' THEN 'CERTIFIED' ELSE 'DRAFTING' END,
       achievement_status, change_reason, created_by, 'BASIC-81-SEED'
FROM lecture_evaluation_achievements
WHERE management_no IN ('B77-LE-001', 'B77-LE-002', 'B77-LE-003')
  AND achievement_status <> 'DRAFTING'
  AND NOT EXISTS (
      SELECT 1
      FROM education_achievement_status_histories history
      WHERE history.achievement_type = 'LECTURE_EVALUATION'
        AND history.achievement_id = lecture_evaluation_achievements.achievement_id
        AND history.request_id = 'BASIC-81-SEED'
  );
