-- BASIC-73 교육영역 4개 실적의 공통 원장, 상세, 상태·변경이력과 메뉴 기반을 추가한다.
-- 기존 FACULTY_ACHIEVEMENT 상태정의, 변경이력, 역할·권한 테이블을 재사용하며 새 공통 기반은 만들지 않는다.

CREATE TABLE IF NOT EXISTS education_achievements (
    achievement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    achievement_key varchar(100) NOT NULL UNIQUE,
    achievement_type varchar(50) NOT NULL,
    business_type varchar(50) NOT NULL DEFAULT 'FACULTY_ACHIEVEMENT',
    status_definition_version varchar(30) NOT NULL DEFAULT 'CONFIRMED',
    achievement_status varchar(50) NOT NULL DEFAULT 'DRAFTING',
    evaluation_year varchar(4) NOT NULL,
    owner_user_id bigint NOT NULL,
    organization_code varchar(50),
    management_number varchar(100),
    achievement_title varchar(300) NOT NULL,
    occurred_on date,
    evaluation_confirmed_yn varchar(1) NOT NULL DEFAULT 'N',
    deleted_yn varchar(1) NOT NULL DEFAULT 'N',
    deleted_at timestamp,
    deleted_by bigint,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint NOT NULL,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint NOT NULL,
    change_reason varchar(500),
    CONSTRAINT ck_education_achievements_type CHECK (achievement_type IN ('LECTURE_EVALUATION', 'LECTURE', 'STUDENT_GUIDANCE', 'DEGREE_COMPLETION')),
    CONSTRAINT ck_education_achievements_business_type CHECK (business_type = 'FACULTY_ACHIEVEMENT'),
    CONSTRAINT ck_education_achievements_year CHECK (evaluation_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_education_achievements_confirmed CHECK (evaluation_confirmed_yn IN ('Y', 'N')),
    CONSTRAINT ck_education_achievements_deleted CHECK (deleted_yn IN ('Y', 'N')),
    CONSTRAINT fk_education_achievements_status FOREIGN KEY (business_type, status_definition_version, achievement_status)
        REFERENCES business_status_codes (business_type, definition_version, status_code),
    CONSTRAINT fk_education_achievements_owner FOREIGN KEY (owner_user_id) REFERENCES users(user_id),
    CONSTRAINT fk_education_achievements_organization FOREIGN KEY (organization_code) REFERENCES organizations(organization_code),
    CONSTRAINT fk_education_achievements_deleted_by FOREIGN KEY (deleted_by) REFERENCES users(user_id),
    CONSTRAINT fk_education_achievements_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_education_achievements_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE education_achievements IS '교육영역 강의평가·강의·학생지도·석박사 배출 실적의 공통 원장. 상태, 평가확정 잠금, 논리삭제와 감사정보를 보존한다.';
COMMENT ON COLUMN education_achievements.achievement_type IS 'LECTURE_EVALUATION:강의평가|LECTURE:강의실적|STUDENT_GUIDANCE:학생지도|DEGREE_COMPLETION:석박사배출';
COMMENT ON COLUMN education_achievements.business_type IS 'FACULTY_ACHIEVEMENT:교수업적평가 공통 상태코드 연결';
COMMENT ON COLUMN education_achievements.achievement_status IS 'business_status_codes.status_code 참조 (FACULTY_ACHIEVEMENT 상태)';
COMMENT ON COLUMN education_achievements.evaluation_confirmed_yn IS 'Y:평가확정|N:미확정';
COMMENT ON COLUMN education_achievements.deleted_yn IS 'Y:논리삭제|N:정상';

CREATE TABLE IF NOT EXISTS education_achievement_management_values (
    management_value_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    achievement_id bigint NOT NULL,
    management_item_code varchar(100) NOT NULL,
    value_text text,
    value_json jsonb,
    display_order integer NOT NULL DEFAULT 0,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint NOT NULL,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint NOT NULL,
    CONSTRAINT uq_education_achievement_management_values UNIQUE (achievement_id, management_item_code),
    CONSTRAINT fk_education_achievement_management_values_achievement FOREIGN KEY (achievement_id) REFERENCES education_achievements(achievement_id),
    CONSTRAINT fk_education_achievement_management_values_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_education_achievement_management_values_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE education_achievement_management_values IS 'FR-018 관리항목 설정에 따라 교육영역 실적별 동적 입력값을 보존한다.';
COMMENT ON COLUMN education_achievement_management_values.value_json IS '동적 관리항목의 구조화 값. EducationAchievementService 저장 시 갱신';

CREATE TABLE IF NOT EXISTS student_guidance_details (
    student_guidance_detail_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    achievement_id bigint NOT NULL,
    student_name varchar(100) NOT NULL,
    guidance_start_date date NOT NULL,
    guidance_end_date date NOT NULL,
    student_count integer NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint NOT NULL,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint NOT NULL,
    CONSTRAINT ck_student_guidance_details_period CHECK (guidance_end_date >= guidance_start_date),
    CONSTRAINT ck_student_guidance_details_count CHECK (student_count > 0),
    CONSTRAINT fk_student_guidance_details_achievement FOREIGN KEY (achievement_id) REFERENCES education_achievements(achievement_id),
    CONSTRAINT fk_student_guidance_details_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_student_guidance_details_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE student_guidance_details IS '학생지도 실적의 지도학생, 지도기간, 학생수 상세를 보존한다.';

CREATE TABLE IF NOT EXISTS degree_completion_student_details (
    degree_completion_student_detail_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    achievement_id bigint NOT NULL,
    degree_type varchar(20) NOT NULL,
    student_name varchar(100) NOT NULL,
    thesis_title varchar(500) NOT NULL,
    degree_awarded_on date NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint NOT NULL,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint NOT NULL,
    CONSTRAINT ck_degree_completion_student_details_degree CHECK (degree_type IN ('MASTER', 'DOCTOR')),
    CONSTRAINT fk_degree_completion_student_details_achievement FOREIGN KEY (achievement_id) REFERENCES education_achievements(achievement_id),
    CONSTRAINT fk_degree_completion_student_details_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_degree_completion_student_details_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE degree_completion_student_details IS '석사·박사 배출 실적의 지도학생 학위구분, 논문제목, 수여일 상세를 보존한다.';
COMMENT ON COLUMN degree_completion_student_details.degree_type IS 'MASTER:석사|DOCTOR:박사';

CREATE TABLE IF NOT EXISTS education_achievement_status_histories (
    education_achievement_status_history_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    achievement_id bigint NOT NULL,
    previous_status varchar(50),
    next_status varchar(50) NOT NULL,
    processed_by bigint NOT NULL,
    processed_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reason varchar(500),
    source_data_change_history_id bigint,
    request_id varchar(100),
    CONSTRAINT fk_education_achievement_status_histories_achievement FOREIGN KEY (achievement_id) REFERENCES education_achievements(achievement_id),
    CONSTRAINT fk_education_achievement_status_histories_processed_by FOREIGN KEY (processed_by) REFERENCES users(user_id),
    CONSTRAINT fk_education_achievement_status_histories_change FOREIGN KEY (source_data_change_history_id) REFERENCES data_change_histories(history_id)
);
COMMENT ON TABLE education_achievement_status_histories IS '교육영역 실적의 상태 전이 전후값, 처리자, 처리일시, 사유와 공통 변경이력 연결을 보존한다.';
COMMENT ON COLUMN education_achievement_status_histories.previous_status IS 'business_status_transitions.from_status_code 참조 의도 (전이 전 상태)';
COMMENT ON COLUMN education_achievement_status_histories.next_status IS 'business_status_transitions.to_status_code 참조 의도 (전이 후 상태)';
COMMENT ON COLUMN education_achievement_status_histories.source_data_change_history_id IS 'data_change_histories.history_id 참조 (상태변경 공통 감사이력)';

CREATE INDEX IF NOT EXISTS idx_education_achievements_type_status ON education_achievements (achievement_type, achievement_status, deleted_yn, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_education_achievements_owner_year ON education_achievements (owner_user_id, evaluation_year, achievement_type);
CREATE INDEX IF NOT EXISTS idx_education_achievement_management_values_achievement ON education_achievement_management_values (achievement_id, display_order);
CREATE INDEX IF NOT EXISTS idx_student_guidance_details_achievement ON student_guidance_details (achievement_id, guidance_start_date);
CREATE INDEX IF NOT EXISTS idx_degree_completion_student_details_achievement ON degree_completion_student_details (achievement_id, degree_awarded_on);
CREATE INDEX IF NOT EXISTS idx_education_achievement_status_histories_achievement ON education_achievement_status_histories (achievement_id, processed_at DESC);

-- B73-SEED-001: 정상, 기간 경계, 인증 상태 차이를 강의평가 3건으로 제공한다.
INSERT INTO education_achievements (
    achievement_key, achievement_type, business_type, status_definition_version, achievement_status,
    evaluation_year, owner_user_id, organization_code, management_number, achievement_title, occurred_on,
    evaluation_confirmed_yn, deleted_yn, created_by, updated_by, change_reason
)
SELECT seed.achievement_key, seed.achievement_type, 'FACULTY_ACHIEVEMENT', 'CONFIRMED', seed.achievement_status,
       '2026', 1, NULL, seed.management_number, seed.achievement_title, seed.occurred_on,
       seed.evaluation_confirmed_yn, 'N', 1, 1, seed.change_reason
FROM (VALUES
    ('B73-SEED-001', 'LECTURE_EVALUATION', 'DRAFTING', 'LE-2026-001', '강의평가 정상 입력 사례', DATE '2026-03-15', 'N', '정상 작성중 강의평가 fixture'),
    ('B73-SEED-002', 'LECTURE_EVALUATION', 'SUBMITTED', 'LE-2026-002', '강의평가 기간 경계 사례', DATE '2026-12-31', 'N', '평가기간 경계 제출 강의평가 fixture'),
    ('B73-SEED-003', 'LECTURE_EVALUATION', 'CERTIFIED', 'LE-2026-003', '강의평가 인증 상태 사례', DATE '2026-06-30', 'N', '인증 완료 강의평가 fixture'),
    ('B73-SEED-004', 'STUDENT_GUIDANCE', 'DRAFTING', 'SG-2026-001', '학생지도 정상 사례', DATE '2026-03-01', 'N', '학생지도 상세 fixture'),
    ('B73-SEED-005', 'STUDENT_GUIDANCE', 'SUBMITTED', 'SG-2026-002', '학생지도 기간 경계 사례', DATE '2026-12-31', 'N', '학생지도 경계 fixture'),
    ('B73-SEED-006', 'STUDENT_GUIDANCE', 'CERTIFIED', 'SG-2026-003', '학생지도 인증 사례', DATE '2026-06-30', 'N', '학생지도 상태 fixture'),
    ('B73-SEED-007', 'DEGREE_COMPLETION', 'DRAFTING', 'DC-2026-001', '석사 배출 정상 사례', DATE '2026-02-28', 'N', '석박사 상세 fixture'),
    ('B73-SEED-008', 'DEGREE_COMPLETION', 'SUBMITTED', 'DC-2026-002', '박사 배출 경계 사례', DATE '2026-12-31', 'N', '석박사 경계 fixture'),
    ('B73-SEED-009', 'DEGREE_COMPLETION', 'CERTIFIED', 'DC-2026-003', '석박사 인증 사례', DATE '2026-08-31', 'N', '석박사 상태 fixture')
) AS seed(achievement_key, achievement_type, achievement_status, management_number, achievement_title, occurred_on, evaluation_confirmed_yn, change_reason)
WHERE NOT EXISTS (
    SELECT 1 FROM education_achievements existing WHERE existing.achievement_key = seed.achievement_key
);

INSERT INTO education_achievement_management_values (achievement_id, management_item_code, value_text, display_order, created_by, updated_by)
SELECT achievement_id, seed.management_item_code, seed.value_text, seed.display_order, 1, 1
FROM education_achievements achievement
JOIN (VALUES
    ('B73-SEED-001', 'LECTURE_EVALUATION_SCORE', '4.8', 1),
    ('B73-SEED-002', 'LECTURE_EVALUATION_SCORE', '4.5', 1),
    ('B73-SEED-003', 'LECTURE_EVALUATION_SCORE', '4.9', 1)
) AS seed(achievement_key, management_item_code, value_text, display_order)
    ON achievement.achievement_key = seed.achievement_key
ON CONFLICT (achievement_id, management_item_code) DO NOTHING;

INSERT INTO student_guidance_details (achievement_id, student_name, guidance_start_date, guidance_end_date, student_count, created_by, updated_by)
SELECT achievement.achievement_id, seed.student_name, seed.guidance_start_date, seed.guidance_end_date, seed.student_count, 1, 1
FROM education_achievements achievement
JOIN (VALUES
    ('B73-SEED-004', '김학생', DATE '2026-03-01', DATE '2026-06-30', 1),
    ('B73-SEED-005', '이학생', DATE '2026-09-01', DATE '2026-12-31', 2),
    ('B73-SEED-006', '박학생', DATE '2026-01-01', DATE '2026-12-15', 3)
) AS seed(achievement_key, student_name, guidance_start_date, guidance_end_date, student_count)
    ON achievement.achievement_key = seed.achievement_key
WHERE NOT EXISTS (
    SELECT 1 FROM student_guidance_details existing
    WHERE existing.achievement_id = achievement.achievement_id AND existing.student_name = seed.student_name
);

INSERT INTO degree_completion_student_details (achievement_id, degree_type, student_name, thesis_title, degree_awarded_on, created_by, updated_by)
SELECT achievement.achievement_id, seed.degree_type, seed.student_name, seed.thesis_title, seed.degree_awarded_on, 1, 1
FROM education_achievements achievement
JOIN (VALUES
    ('B73-SEED-007', 'MASTER', '최석사', '교육성과 분석 연구', DATE '2026-02-28'),
    ('B73-SEED-008', 'DOCTOR', '정박사', '교육평가 모형 연구', DATE '2026-12-31'),
    ('B73-SEED-009', 'MASTER', '한석사', '수업개선 방법 연구', DATE '2026-08-31')
) AS seed(achievement_key, degree_type, student_name, thesis_title, degree_awarded_on)
    ON achievement.achievement_key = seed.achievement_key
WHERE NOT EXISTS (
    SELECT 1 FROM degree_completion_student_details existing
    WHERE existing.achievement_id = achievement.achievement_id AND existing.student_name = seed.student_name
);

INSERT INTO data_change_histories (target_business, target_key, change_type, field_name, before_value, after_value, changed_by, change_reason, request_id)
SELECT 'EDUCATION_ACHIEVEMENT', achievement.achievement_key, 'CREATE', 'achievement_status', NULL, achievement.achievement_status,
       1, 'BASIC-73 교육영역 실적 fixture 생성', 'BASIC73-SEED'
FROM education_achievements achievement
WHERE achievement.achievement_key IN ('B73-SEED-001', 'B73-SEED-002', 'B73-SEED-003')
  AND NOT EXISTS (
      SELECT 1 FROM data_change_histories history
      WHERE history.target_business = 'EDUCATION_ACHIEVEMENT'
        AND history.target_key = achievement.achievement_key
        AND history.change_type = 'CREATE'
  );

INSERT INTO education_achievement_status_histories (
    achievement_id, previous_status, next_status, processed_by, reason, source_data_change_history_id, request_id
)
SELECT achievement.achievement_id, seed.previous_status, seed.next_status, 1, seed.reason, history.history_id, 'BASIC73-SEED'
FROM education_achievements achievement
JOIN (VALUES
    ('B73-SEED-001', NULL::varchar(50), 'DRAFTING', '정상 작성중 상태 fixture'),
    ('B73-SEED-002', 'DRAFTING', 'SUBMITTED', '기간 경계 제출 상태 fixture'),
    ('B73-SEED-003', 'DEPARTMENT_CONFIRMED', 'CERTIFIED', '인증 상태 fixture')
) AS seed(achievement_key, previous_status, next_status, reason)
    ON achievement.achievement_key = seed.achievement_key
JOIN data_change_histories history
    ON history.target_business = 'EDUCATION_ACHIEVEMENT'
   AND history.target_key = achievement.achievement_key
   AND history.change_type = 'CREATE'
WHERE NOT EXISTS (
    SELECT 1 FROM education_achievement_status_histories existing
    WHERE existing.achievement_id = achievement.achievement_id
      AND existing.next_status = seed.next_status
);

-- 신규 leaf menu ID는 실행 시점의 현재 MAX(menu_id) 뒤에서 배정해 기존 메뉴와 충돌하지 않는다.
WITH menu_base AS (
    SELECT COALESCE(MAX(menu_id), 0) AS max_menu_id FROM menus
), menu_seed AS (
    SELECT * FROM (VALUES
        (1, '강의평가 실적', 'SCR-LECTURE-EVALUATION-ACHIEVEMENT', '/faculty/education/lecture-evaluation-achievements', 'clipboard-check', '강의평가 실적 등록·조회'),
        (2, '강의 실적', 'SCR-LECTURE-ACHIEVEMENT', '/faculty/education/lecture-achievements', 'book-open-check', '강의 실적 등록·조회'),
        (3, '학생지도 실적', 'SCR-STUDENT-GUIDANCE-ACHIEVEMENT', '/faculty/education/student-guidance-achievements', 'users-round', '학생지도 실적과 Excel 일괄등록'),
        (4, '석·박사 배출 실적', 'SCR-DEGREE-COMPLETION-ACHIEVEMENT', '/faculty/education/degree-completion-achievements', 'graduation-cap', '석사·박사 배출 실적 등록·조회')
    ) AS seed(display_order, menu_name, screen_id, url, icon, description)
)
INSERT INTO menus (menu_id, parent_menu_id, menu_type, menu_name, display_order, screen_id, url, icon, business_category, description, system_use_yn, status, updated_by, change_reason)
SELECT menu_base.max_menu_id + menu_seed.display_order, 300, 'SCREEN', menu_seed.menu_name, menu_seed.display_order,
       menu_seed.screen_id, menu_seed.url, menu_seed.icon, 'EDUCATION', menu_seed.description, 'Y', 'ACTIVE', 1,
       'BASIC-73 교육영역 실적 메뉴 seed'
FROM menu_base
CROSS JOIN menu_seed
WHERE NOT EXISTS (SELECT 1 FROM menus existing WHERE existing.screen_id = menu_seed.screen_id);

INSERT INTO menu_execution_info (menu_id, screen_id, url, icon, business_category, description, updated_by)
SELECT menu_id, screen_id, url, icon, business_category, description, 1
FROM menus
WHERE screen_id IN (
    'SCR-LECTURE-EVALUATION-ACHIEVEMENT',
    'SCR-LECTURE-ACHIEVEMENT',
    'SCR-STUDENT-GUIDANCE-ACHIEVEMENT',
    'SCR-DEGREE-COMPLETION-ACHIEVEMENT'
)
ON CONFLICT (menu_id) DO UPDATE SET
    screen_id = EXCLUDED.screen_id,
    url = EXCLUDED.url,
    icon = EXCLUDED.icon,
    business_category = EXCLUDED.business_category,
    description = EXCLUDED.description,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = EXCLUDED.updated_by;

INSERT INTO menu_permissions (target_type, target_id, menu_id, access_allowed, status, created_by, updated_by, change_reason)
SELECT 'ROLE', role_seed.role_code, menu.menu_id, 'ALLOW', 'ACTIVE', 1, 1, 'BASIC-73 교육영역 실적 메뉴 접근'
FROM menus menu
JOIN (VALUES
    ('SCR-LECTURE-EVALUATION-ACHIEVEMENT', 'R01'),
    ('SCR-LECTURE-EVALUATION-ACHIEVEMENT', 'R02'),
    ('SCR-LECTURE-EVALUATION-ACHIEVEMENT', 'R04'),
    ('SCR-LECTURE-ACHIEVEMENT', 'R01'),
    ('SCR-LECTURE-ACHIEVEMENT', 'R02'),
    ('SCR-LECTURE-ACHIEVEMENT', 'R04'),
    ('SCR-STUDENT-GUIDANCE-ACHIEVEMENT', 'R01'),
    ('SCR-STUDENT-GUIDANCE-ACHIEVEMENT', 'R07'),
    ('SCR-DEGREE-COMPLETION-ACHIEVEMENT', 'R01'),
    ('SCR-DEGREE-COMPLETION-ACHIEVEMENT', 'R02'),
    ('SCR-DEGREE-COMPLETION-ACHIEVEMENT', 'R04')
) AS role_seed(screen_id, role_code) ON menu.screen_id = role_seed.screen_id
WHERE NOT EXISTS (
    SELECT 1 FROM menu_permissions existing
    WHERE existing.target_type = 'ROLE'
      AND existing.target_id = role_seed.role_code
      AND existing.menu_id = menu.menu_id
);

INSERT INTO function_permissions (screen_id, role_code, function_type, permission_allowed, change_reason, created_by, updated_by)
SELECT permission_seed.screen_id, permission_seed.role_code, permission_seed.function_type, 'ALLOW',
       'BASIC-73 교육영역 실적 기능 기본 허용', 1, 1
FROM (VALUES
    ('SCR-LECTURE-EVALUATION-ACHIEVEMENT', 'R01', 'READ'),
    ('SCR-LECTURE-EVALUATION-ACHIEVEMENT', 'R01', 'CREATE'),
    ('SCR-LECTURE-EVALUATION-ACHIEVEMENT', 'R01', 'UPDATE'),
    ('SCR-LECTURE-EVALUATION-ACHIEVEMENT', 'R01', 'DELETE'),
    ('SCR-LECTURE-EVALUATION-ACHIEVEMENT', 'R02', 'READ'),
    ('SCR-LECTURE-EVALUATION-ACHIEVEMENT', 'R02', 'EXECUTE'),
    ('SCR-LECTURE-EVALUATION-ACHIEVEMENT', 'R04', 'READ'),
    ('SCR-LECTURE-EVALUATION-ACHIEVEMENT', 'R04', 'EXECUTE'),
    ('SCR-LECTURE-ACHIEVEMENT', 'R01', 'READ'),
    ('SCR-LECTURE-ACHIEVEMENT', 'R01', 'CREATE'),
    ('SCR-LECTURE-ACHIEVEMENT', 'R01', 'UPDATE'),
    ('SCR-LECTURE-ACHIEVEMENT', 'R01', 'DELETE'),
    ('SCR-LECTURE-ACHIEVEMENT', 'R02', 'READ'),
    ('SCR-LECTURE-ACHIEVEMENT', 'R02', 'EXECUTE'),
    ('SCR-LECTURE-ACHIEVEMENT', 'R04', 'READ'),
    ('SCR-LECTURE-ACHIEVEMENT', 'R04', 'EXECUTE'),
    ('SCR-STUDENT-GUIDANCE-ACHIEVEMENT', 'R01', 'READ'),
    ('SCR-STUDENT-GUIDANCE-ACHIEVEMENT', 'R01', 'CREATE'),
    ('SCR-STUDENT-GUIDANCE-ACHIEVEMENT', 'R01', 'UPDATE'),
    ('SCR-STUDENT-GUIDANCE-ACHIEVEMENT', 'R07', 'READ'),
    ('SCR-STUDENT-GUIDANCE-ACHIEVEMENT', 'R07', 'EXECUTE'),
    ('SCR-DEGREE-COMPLETION-ACHIEVEMENT', 'R01', 'READ'),
    ('SCR-DEGREE-COMPLETION-ACHIEVEMENT', 'R01', 'CREATE'),
    ('SCR-DEGREE-COMPLETION-ACHIEVEMENT', 'R01', 'UPDATE'),
    ('SCR-DEGREE-COMPLETION-ACHIEVEMENT', 'R01', 'DELETE'),
    ('SCR-DEGREE-COMPLETION-ACHIEVEMENT', 'R02', 'READ'),
    ('SCR-DEGREE-COMPLETION-ACHIEVEMENT', 'R02', 'EXECUTE'),
    ('SCR-DEGREE-COMPLETION-ACHIEVEMENT', 'R04', 'READ'),
    ('SCR-DEGREE-COMPLETION-ACHIEVEMENT', 'R04', 'EXECUTE')
) AS permission_seed(screen_id, role_code, function_type)
WHERE NOT EXISTS (
    SELECT 1 FROM function_permissions existing
    WHERE existing.screen_id = permission_seed.screen_id
      AND existing.role_code = permission_seed.role_code
      AND existing.function_type = permission_seed.function_type
);
