CREATE TABLE IF NOT EXISTS lecture_evaluation_achievements (
    achievement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluation_year varchar(4) NOT NULL,
    owner_user_id bigint NOT NULL,
    organization_code varchar(50) NOT NULL,
    management_item_code varchar(100) NOT NULL,
    occurred_date date NOT NULL,
    achievement_detail jsonb NOT NULL DEFAULT '{}'::jsonb,
    certification_status varchar(50) NOT NULL DEFAULT 'DRAFTING',
    attachment_ref varchar(300),
    deleted_yn varchar(1) NOT NULL DEFAULT 'N',
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint NOT NULL,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint NOT NULL,
    CONSTRAINT ck_lecture_evaluation_achievements_year CHECK (evaluation_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_lecture_evaluation_achievements_status CHECK (certification_status IN ('DRAFTING','SUBMITTED','DEPARTMENT_CONFIRMED','DEPARTMENT_REJECTED','CERTIFIED','CERTIFICATION_RETURNED','EVALUATION_CONFIRMED','DELETED')),
    CONSTRAINT ck_lecture_evaluation_achievements_deleted CHECK (deleted_yn IN ('Y','N')),
    CONSTRAINT fk_lecture_evaluation_achievements_owner FOREIGN KEY (owner_user_id) REFERENCES users(user_id),
    CONSTRAINT fk_lecture_evaluation_achievements_organization FOREIGN KEY (organization_code) REFERENCES organizations(organization_code),
    CONSTRAINT fk_lecture_evaluation_achievements_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_lecture_evaluation_achievements_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE lecture_evaluation_achievements IS 'BASIC-79 강의평가 원천 실적과 인증상태를 보존하는 업무 테이블.';
COMMENT ON COLUMN lecture_evaluation_achievements.owner_user_id IS 'users.user_id 참조 의도 (강의평가 실적 소유 교원)';
COMMENT ON COLUMN lecture_evaluation_achievements.certification_status IS 'DRAFTING:작성중|SUBMITTED:제출|DEPARTMENT_CONFIRMED:학과장확인|DEPARTMENT_REJECTED:학과장미승인|CERTIFIED:인증|CERTIFICATION_RETURNED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN lecture_evaluation_achievements.attachment_ref IS '기존 FileStoragePort 또는 첨부 서비스의 비공개 참조값';
COMMENT ON COLUMN lecture_evaluation_achievements.deleted_yn IS 'Y:논리삭제|N:정상';
COMMENT ON COLUMN lecture_evaluation_achievements.created_by IS 'users.user_id 참조 의도 (최초 입력자)';
COMMENT ON COLUMN lecture_evaluation_achievements.updated_by IS 'users.user_id 참조 의도 (최종 수정자)';

CREATE TABLE IF NOT EXISTS education_achievement_status_histories (
    status_history_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    achievement_type varchar(50) NOT NULL,
    achievement_id bigint NOT NULL,
    previous_status varchar(50) NOT NULL,
    next_status varchar(50) NOT NULL,
    action_type varchar(50) NOT NULL,
    reason_code varchar(50),
    opinion varchar(1000),
    processed_by bigint NOT NULL,
    processed_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_education_achievement_status_histories_type CHECK (achievement_type IN ('LECTURE_EVALUATION','LECTURE','STUDENT_GUIDANCE','DEGREE_COMPLETION')),
    CONSTRAINT ck_education_achievement_status_histories_previous CHECK (previous_status IN ('DRAFTING','SUBMITTED','DEPARTMENT_CONFIRMED','DEPARTMENT_REJECTED','CERTIFIED','CERTIFICATION_RETURNED','EVALUATION_CONFIRMED','DELETED')),
    CONSTRAINT ck_education_achievement_status_histories_next CHECK (next_status IN ('DRAFTING','SUBMITTED','DEPARTMENT_CONFIRMED','DEPARTMENT_REJECTED','CERTIFIED','CERTIFICATION_RETURNED','EVALUATION_CONFIRMED','DELETED')),
    CONSTRAINT ck_education_achievement_status_histories_rejection_reason CHECK (next_status NOT IN ('DEPARTMENT_REJECTED','CERTIFICATION_RETURNED') OR reason_code IS NOT NULL OR opinion IS NOT NULL),
    CONSTRAINT fk_education_achievement_status_histories_processed_by FOREIGN KEY (processed_by) REFERENCES users(user_id)
);
COMMENT ON TABLE education_achievement_status_histories IS 'BASIC-79 교육영역 실적의 상태 전이 처리자·처리일시·사유를 보존하는 불변 이력 테이블.';
COMMENT ON COLUMN education_achievement_status_histories.achievement_type IS 'LECTURE_EVALUATION:강의평가|LECTURE:강의실적|STUDENT_GUIDANCE:학생지도|DEGREE_COMPLETION:석박사배출';
COMMENT ON COLUMN education_achievement_status_histories.previous_status IS 'DRAFTING:작성중|SUBMITTED:제출|DEPARTMENT_CONFIRMED:학과장확인|DEPARTMENT_REJECTED:학과장미승인|CERTIFIED:인증|CERTIFICATION_RETURNED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN education_achievement_status_histories.next_status IS 'DRAFTING:작성중|SUBMITTED:제출|DEPARTMENT_CONFIRMED:학과장확인|DEPARTMENT_REJECTED:학과장미승인|CERTIFIED:인증|CERTIFICATION_RETURNED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN education_achievement_status_histories.processed_by IS 'users.user_id 참조 의도 (상태 전이 처리자)';

CREATE INDEX IF NOT EXISTS idx_lecture_evaluation_achievements_list
    ON lecture_evaluation_achievements(evaluation_year, owner_user_id, organization_code, certification_status, occurred_date DESC)
    WHERE deleted_yn = 'N';
CREATE INDEX IF NOT EXISTS idx_education_achievement_status_histories_lookup
    ON education_achievement_status_histories(achievement_type, achievement_id, processed_at DESC);

INSERT INTO lecture_evaluation_achievements (
    evaluation_year, owner_user_id, organization_code, management_item_code, occurred_date,
    achievement_detail, certification_status, deleted_yn, created_by, updated_by
)
SELECT '2026', owner_user.user_id, owner_org.organization_code, fixture.management_item_code,
       fixture.occurred_date, fixture.achievement_detail::jsonb, fixture.certification_status,
       'N', admin_user.user_id, admin_user.user_id
FROM (VALUES
    ('B77-LE-001', DATE '2026-03-15', '{"fixtureId":"B77-LE-001"}', 'DRAFTING'),
    ('B77-LE-002', DATE '2026-06-20', '{"fixtureId":"B77-LE-002"}', 'SUBMITTED'),
    ('B77-LE-003', DATE '2026-08-31', '{"fixtureId":"B77-LE-003"}', 'CERTIFIED')
) AS fixture(management_item_code, occurred_date, achievement_detail, certification_status)
CROSS JOIN LATERAL (SELECT user_id FROM users WHERE login_id = 'admin' LIMIT 1) admin_user
CROSS JOIN LATERAL (SELECT user_id FROM users WHERE login_id <> 'admin' ORDER BY user_id LIMIT 1) owner_user
CROSS JOIN LATERAL (
    SELECT organization_code
    FROM organization_user_mappings
    WHERE user_id = owner_user.user_id AND status = 'ACTIVE'
    ORDER BY effective_start_date DESC
    LIMIT 1
) owner_org
WHERE NOT EXISTS (
    SELECT 1
    FROM lecture_evaluation_achievements existing
    WHERE existing.management_item_code = fixture.management_item_code
      AND existing.evaluation_year = '2026'
);

INSERT INTO function_permissions (
    screen_id, role_code, function_type, permission_allowed, change_reason, created_by, updated_by
)
SELECT 'SCR-LECTURE-EVALUATION-ACHIEVEMENT-MGMT', role_seed.role_code, function_seed.function_type,
       'ALLOW', 'BASIC-79 강의평가 공통 검증 권한', 1, 1
FROM (VALUES ('R01'), ('R02'), ('R04')) AS role_seed(role_code)
CROSS JOIN (VALUES ('READ'), ('CREATE'), ('UPDATE'), ('DELETE')) AS function_seed(function_type)
ON CONFLICT (screen_id, role_code, function_type) DO NOTHING;
