CREATE TABLE IF NOT EXISTS lecture_evaluation_achievements (
    achievement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluation_year varchar(4) NOT NULL,
    teacher_user_id bigint NOT NULL,
    organization_code varchar(50),
    management_item_code varchar(50) NOT NULL,
    occurred_date date NOT NULL,
    achievement_detail jsonb NOT NULL DEFAULT '{}'::jsonb,
    certification_status varchar(30) NOT NULL DEFAULT 'DRAFT',
    attachment_ref varchar(300),
    deleted_yn char(1) NOT NULL DEFAULT 'N',
    deleted_at timestamp,
    deleted_by bigint,
    delete_reason varchar(500),
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    CONSTRAINT ck_lecture_evaluation_achievements_year
        CHECK (evaluation_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_lecture_evaluation_achievements_status
        CHECK (certification_status IN (
            'DRAFT',
            'SUBMITTED',
            'DEPARTMENT_CONFIRMED',
            'DEPARTMENT_REJECTED',
            'CERTIFIED',
            'CERTIFICATION_REJECTED',
            'EVALUATION_CONFIRMED',
            'DELETED'
        )),
    CONSTRAINT ck_lecture_evaluation_achievements_deleted
        CHECK (deleted_yn IN ('Y', 'N')),
    CONSTRAINT ck_lecture_evaluation_achievements_delete_state
        CHECK (deleted_yn = 'N' OR certification_status = 'DELETED'),
    CONSTRAINT fk_lecture_evaluation_achievements_teacher
        FOREIGN KEY (teacher_user_id) REFERENCES users(user_id),
    CONSTRAINT fk_lecture_evaluation_achievements_organization
        FOREIGN KEY (organization_code) REFERENCES organizations(organization_code),
    CONSTRAINT fk_lecture_evaluation_achievements_deleted_by
        FOREIGN KEY (deleted_by) REFERENCES users(user_id),
    CONSTRAINT fk_lecture_evaluation_achievements_created_by
        FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_lecture_evaluation_achievements_updated_by
        FOREIGN KEY (updated_by) REFERENCES users(user_id)
);

COMMENT ON TABLE lecture_evaluation_achievements IS 'FR-025 교육영역 강의평가 실적 원천. 교원별 입력값, 인증 상태, 논리삭제와 변경 추적의 기준을 보존한다.';
COMMENT ON COLUMN lecture_evaluation_achievements.teacher_user_id IS 'users.user_id 참조 의도 (실적 소유 교원 및 데이터 범위 판단)';
COMMENT ON COLUMN lecture_evaluation_achievements.organization_code IS 'organizations.organization_code 참조 의도 (소속 기반 데이터 범위 판단)';
COMMENT ON COLUMN lecture_evaluation_achievements.management_item_code IS 'evaluation_management_items.management_item_code 참조 의도 (활성 관리항목 검증)';
COMMENT ON COLUMN lecture_evaluation_achievements.achievement_detail IS 'FR-018에서 결정되는 동적 입력 항목을 저장하는 JSONB 원천값';
COMMENT ON COLUMN lecture_evaluation_achievements.certification_status IS 'DRAFT:작성중|SUBMITTED:제출|DEPARTMENT_CONFIRMED:학과장확인|DEPARTMENT_REJECTED:학과장미승인|CERTIFIED:인증|CERTIFICATION_REJECTED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN lecture_evaluation_achievements.attachment_ref IS 'FileStoragePort가 발급한 외부 비노출 첨부 참조값';
COMMENT ON COLUMN lecture_evaluation_achievements.deleted_yn IS 'Y:삭제|N:정상';
COMMENT ON COLUMN lecture_evaluation_achievements.deleted_by IS 'users.user_id 참조 의도 (논리삭제 처리자)';

CREATE TABLE IF NOT EXISTS education_achievement_status_histories (
    status_history_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    achievement_type varchar(30) NOT NULL,
    achievement_id bigint NOT NULL,
    previous_status varchar(30),
    next_status varchar(30) NOT NULL,
    action_type varchar(30) NOT NULL,
    reason_code varchar(100),
    opinion varchar(1000),
    processed_by bigint NOT NULL,
    processed_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    CONSTRAINT ck_education_achievement_status_histories_type
        CHECK (achievement_type IN (
            'LECTURE_EVALUATION',
            'LECTURE',
            'STUDENT_GUIDANCE',
            'DEGREE_COMPLETION'
        )),
    CONSTRAINT ck_education_achievement_status_histories_status
        CHECK (next_status IN (
            'DRAFT',
            'SUBMITTED',
            'DEPARTMENT_CONFIRMED',
            'DEPARTMENT_REJECTED',
            'CERTIFIED',
            'CERTIFICATION_REJECTED',
            'EVALUATION_CONFIRMED',
            'DELETED'
        )),
    CONSTRAINT ck_education_achievement_status_histories_rejection_reason
        CHECK (
            action_type NOT IN ('DEPARTMENT_REJECT', 'CERTIFICATION_REJECT')
            OR (reason_code IS NOT NULL AND opinion IS NOT NULL)
        ),
    CONSTRAINT fk_education_achievement_status_histories_processed_by
        FOREIGN KEY (processed_by) REFERENCES users(user_id),
    CONSTRAINT fk_education_achievement_status_histories_created_by
        FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_education_achievement_status_histories_updated_by
        FOREIGN KEY (updated_by) REFERENCES users(user_id)
);

COMMENT ON TABLE education_achievement_status_histories IS '교육영역 전반 실적의 상태 전이 이력. 처리자·처리일시·반려사유·의견을 append-only 방식으로 보존한다.';
COMMENT ON COLUMN education_achievement_status_histories.achievement_type IS 'LECTURE_EVALUATION:강의평가|LECTURE:강의실적|STUDENT_GUIDANCE:학생지도|DEGREE_COMPLETION:석박사배출';
COMMENT ON COLUMN education_achievement_status_histories.achievement_id IS '각 achievement header의 achievement_id 참조 의도 (다형 업무키라 FK 미선언)';
COMMENT ON COLUMN education_achievement_status_histories.previous_status IS '상태 전이 직전 인증상태';
COMMENT ON COLUMN education_achievement_status_histories.next_status IS 'DRAFT:작성중|SUBMITTED:제출|DEPARTMENT_CONFIRMED:학과장확인|DEPARTMENT_REJECTED:학과장미승인|CERTIFIED:인증|CERTIFICATION_REJECTED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN education_achievement_status_histories.action_type IS 'SUBMIT:제출|DEPARTMENT_CONFIRM:학과장확인|DEPARTMENT_REJECT:학과장미승인|CERTIFY:인증|CERTIFICATION_REJECT:인증반려|CONFIRM_EVALUATION:평가확정|CANCEL_EVALUATION_CONFIRMATION:평가확정취소|DELETE:삭제';
COMMENT ON COLUMN education_achievement_status_histories.processed_by IS 'users.user_id 참조 의도 (상태 전이 처리자)';

CREATE INDEX IF NOT EXISTS idx_lecture_evaluation_achievements_search
    ON lecture_evaluation_achievements(
        evaluation_year,
        teacher_user_id,
        organization_code,
        management_item_code,
        occurred_date DESC
    )
    WHERE deleted_yn = 'N';

CREATE INDEX IF NOT EXISTS idx_lecture_evaluation_achievements_status
    ON lecture_evaluation_achievements(certification_status, updated_at DESC)
    WHERE deleted_yn = 'N';

CREATE INDEX IF NOT EXISTS idx_education_achievement_status_histories_target
    ON education_achievement_status_histories(
        achievement_type,
        achievement_id,
        processed_at DESC
    );

INSERT INTO lecture_evaluation_achievements (
    achievement_id,
    evaluation_year,
    teacher_user_id,
    organization_code,
    management_item_code,
    occurred_date,
    achievement_detail,
    certification_status,
    deleted_yn,
    created_by,
    updated_by
)
SELECT seed.achievement_id,
       seed.evaluation_year,
       professor.user_id,
       'KNUE-COL-EDU',
       seed.management_item_code,
       seed.occurred_date,
       seed.achievement_detail::jsonb,
       seed.certification_status,
       'N',
       admin.user_id,
       admin.user_id
FROM users admin
CROSS JOIN users professor
CROSS JOIN (
    VALUES
        (
            790001,
            '2026',
            'EDU-LECTURE-EVALUATION-A',
            DATE '2026-03-15',
            '{"fixtureId":"B77-LE-001","case":"normal"}',
            'DRAFT'
        ),
        (
            790002,
            '2026',
            'EDU-LECTURE-EVALUATION-B',
            DATE '2026-02-28',
            '{"fixtureId":"B77-LE-001","case":"outside-period-warning"}',
            'SUBMITTED'
        ),
        (
            790003,
            '2026',
            'EDU-LECTURE-EVALUATION-C',
            DATE '2026-03-20',
            '{"fixtureId":"B77-LE-001","case":"finalization-lock"}',
            'EVALUATION_CONFIRMED'
        )
) AS seed(
    achievement_id,
    evaluation_year,
    management_item_code,
    occurred_date,
    achievement_detail,
    certification_status
)
WHERE admin.login_id = 'admin'
  AND professor.login_id = 'professor1'
ON CONFLICT (achievement_id) DO UPDATE SET
    evaluation_year = EXCLUDED.evaluation_year,
    teacher_user_id = EXCLUDED.teacher_user_id,
    organization_code = EXCLUDED.organization_code,
    management_item_code = EXCLUDED.management_item_code,
    occurred_date = EXCLUDED.occurred_date,
    achievement_detail = EXCLUDED.achievement_detail,
    certification_status = EXCLUDED.certification_status,
    deleted_yn = EXCLUDED.deleted_yn,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = EXCLUDED.updated_by;

SELECT setval(
    pg_get_serial_sequence('lecture_evaluation_achievements', 'achievement_id'),
    COALESCE((SELECT MAX(achievement_id) FROM lecture_evaluation_achievements), 1),
    true
);

INSERT INTO education_achievement_status_histories (
    achievement_type,
    achievement_id,
    previous_status,
    next_status,
    action_type,
    processed_by,
    created_by,
    updated_by
)
SELECT 'LECTURE_EVALUATION',
       achievement.achievement_id,
       CASE achievement.certification_status
           WHEN 'DRAFT' THEN NULL
           WHEN 'SUBMITTED' THEN 'DRAFT'
           ELSE 'CERTIFIED'
       END,
       achievement.certification_status,
       CASE achievement.certification_status
           WHEN 'DRAFT' THEN 'CREATE'
           WHEN 'SUBMITTED' THEN 'SUBMIT'
           ELSE 'CONFIRM_EVALUATION'
       END,
       admin.user_id,
       admin.user_id,
       admin.user_id
FROM lecture_evaluation_achievements achievement
CROSS JOIN users admin
WHERE achievement.achievement_id IN (790001, 790002, 790003)
  AND admin.login_id = 'admin'
  AND NOT EXISTS (
      SELECT 1
      FROM education_achievement_status_histories history
      WHERE history.achievement_type = 'LECTURE_EVALUATION'
        AND history.achievement_id = achievement.achievement_id
        AND history.next_status = achievement.certification_status
  );
