CREATE TABLE IF NOT EXISTS lecture_evaluation_achievements (
    achievement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    management_no varchar(100) NOT NULL,
    teacher_user_id bigint NOT NULL,
    evaluation_year varchar(4) NOT NULL,
    organization_code varchar(50) NOT NULL,
    management_item_code varchar(50) NOT NULL,
    occurred_date date NOT NULL,
    achievement_detail jsonb NOT NULL DEFAULT '{}'::jsonb,
    certification_status varchar(50) NOT NULL DEFAULT 'DRAFT',
    attachment_ref varchar(300),
    deleted_yn char(1) NOT NULL DEFAULT 'N',
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    change_reason varchar(500),
    CONSTRAINT uq_lecture_evaluation_achievements_management_no UNIQUE (management_no),
    CONSTRAINT ck_lecture_evaluation_achievements_year CHECK (evaluation_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_lecture_evaluation_achievements_status CHECK (
        certification_status IN (
            'DRAFT',
            'SUBMITTED',
            'DEPARTMENT_CONFIRMED',
            'DEPARTMENT_REJECTED',
            'CERTIFIED',
            'CERTIFICATION_REJECTED',
            'EVALUATION_CONFIRMED',
            'DELETED'
        )
    ),
    CONSTRAINT ck_lecture_evaluation_achievements_deleted CHECK (deleted_yn IN ('Y', 'N')),
    CONSTRAINT fk_lecture_evaluation_achievements_teacher FOREIGN KEY (teacher_user_id) REFERENCES users(user_id),
    CONSTRAINT fk_lecture_evaluation_achievements_organization FOREIGN KEY (organization_code) REFERENCES organizations(organization_code),
    CONSTRAINT fk_lecture_evaluation_achievements_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_lecture_evaluation_achievements_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE lecture_evaluation_achievements IS 'BASIC-79 교육영역 강의평가 원천 실적을 논리 삭제와 생성·수정 메타정보로 보존한다.';
COMMENT ON COLUMN lecture_evaluation_achievements.teacher_user_id IS 'users.user_id 참조 의도 (실적 대상 교원)';
COMMENT ON COLUMN lecture_evaluation_achievements.organization_code IS 'organizations.organization_code 참조 의도 (실적 대상 소속)';
COMMENT ON COLUMN lecture_evaluation_achievements.achievement_detail IS 'FR-018 활성 관리항목 기준의 가변 강의평가 상세값';
COMMENT ON COLUMN lecture_evaluation_achievements.certification_status IS 'DRAFT:작성중|SUBMITTED:제출|DEPARTMENT_CONFIRMED:학과장확인|DEPARTMENT_REJECTED:학과장미승인|CERTIFIED:인증|CERTIFICATION_REJECTED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN lecture_evaluation_achievements.attachment_ref IS 'FileStoragePort가 발급한 외부 비노출 첨부 참조값';
COMMENT ON COLUMN lecture_evaluation_achievements.deleted_yn IS 'Y:논리삭제|N:정상';
COMMENT ON COLUMN lecture_evaluation_achievements.created_by IS 'users.user_id 참조 의도 (최초 입력자)';
COMMENT ON COLUMN lecture_evaluation_achievements.updated_by IS 'users.user_id 참조 의도 (최종 수정자)';

CREATE TABLE IF NOT EXISTS education_achievement_status_histories (
    status_history_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    achievement_type varchar(50) NOT NULL,
    achievement_id bigint NOT NULL,
    previous_status varchar(50) NOT NULL,
    next_status varchar(50) NOT NULL,
    action_type varchar(50) NOT NULL,
    reason_code varchar(100),
    opinion varchar(1000),
    processed_by bigint NOT NULL,
    processed_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    change_reason varchar(500),
    request_id varchar(100),
    CONSTRAINT ck_education_achievement_status_histories_type CHECK (
        achievement_type IN ('LECTURE_EVALUATION', 'LECTURE', 'STUDENT_GUIDANCE', 'DEGREE_COMPLETION')
    ),
    CONSTRAINT ck_education_achievement_status_histories_previous_status CHECK (
        previous_status IN (
            'DRAFT',
            'SUBMITTED',
            'DEPARTMENT_CONFIRMED',
            'DEPARTMENT_REJECTED',
            'CERTIFIED',
            'CERTIFICATION_REJECTED',
            'EVALUATION_CONFIRMED',
            'DELETED'
        )
    ),
    CONSTRAINT ck_education_achievement_status_histories_next_status CHECK (
        next_status IN (
            'DRAFT',
            'SUBMITTED',
            'DEPARTMENT_CONFIRMED',
            'DEPARTMENT_REJECTED',
            'CERTIFIED',
            'CERTIFICATION_REJECTED',
            'EVALUATION_CONFIRMED',
            'DELETED'
        )
    ),
    CONSTRAINT ck_education_achievement_status_histories_rejection_reason CHECK (
        next_status NOT IN ('DEPARTMENT_REJECTED', 'CERTIFICATION_REJECTED')
        OR NULLIF(BTRIM(COALESCE(reason_code, '')), '') IS NOT NULL
        OR NULLIF(BTRIM(COALESCE(opinion, '')), '') IS NOT NULL
    ),
    CONSTRAINT fk_education_achievement_status_histories_processed_by FOREIGN KEY (processed_by) REFERENCES users(user_id)
);
COMMENT ON TABLE education_achievement_status_histories IS 'BASIC-79 교육영역 네 실적 유형의 인증상태 전이 처리자·처리일시·사유를 append-only로 보존한다.';
COMMENT ON COLUMN education_achievement_status_histories.achievement_type IS 'LECTURE_EVALUATION:강의평가|LECTURE:강의실적|STUDENT_GUIDANCE:학생지도|DEGREE_COMPLETION:석박사배출';
COMMENT ON COLUMN education_achievement_status_histories.achievement_id IS '각 achievement header의 achievement_id 참조 의도 (복수 테이블이므로 FK 미선언)';
COMMENT ON COLUMN education_achievement_status_histories.previous_status IS 'DRAFT:작성중|SUBMITTED:제출|DEPARTMENT_CONFIRMED:학과장확인|DEPARTMENT_REJECTED:학과장미승인|CERTIFIED:인증|CERTIFICATION_REJECTED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN education_achievement_status_histories.next_status IS 'DRAFT:작성중|SUBMITTED:제출|DEPARTMENT_CONFIRMED:학과장확인|DEPARTMENT_REJECTED:학과장미승인|CERTIFIED:인증|CERTIFICATION_REJECTED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN education_achievement_status_histories.processed_by IS 'users.user_id 참조 의도 (상태 처리자)';
COMMENT ON COLUMN education_achievement_status_histories.request_id IS '요청 식별자 전 구간 추적을 위해 상태 전이 서비스에서 기록';

CREATE INDEX IF NOT EXISTS idx_lecture_evaluation_achievements_search
    ON lecture_evaluation_achievements(
        evaluation_year,
        organization_code,
        teacher_user_id,
        certification_status,
        occurred_date DESC
    );
CREATE INDEX IF NOT EXISTS idx_lecture_evaluation_achievements_management_item
    ON lecture_evaluation_achievements(management_item_code, deleted_yn);
CREATE INDEX IF NOT EXISTS idx_education_achievement_status_histories_target
    ON education_achievement_status_histories(achievement_type, achievement_id, processed_at DESC);

INSERT INTO user_roles (
    user_id,
    role_code,
    assignment_type,
    approver_user_id,
    status,
    change_reason
)
SELECT
    professor.user_id,
    'R01',
    'MANUAL',
    administrator.user_id,
    'ACTIVE',
    'B77-LE-001 강의평가 본인 범위 fixture'
FROM users professor
JOIN users administrator ON administrator.login_id = 'admin'
WHERE professor.login_id = 'professor1'
  AND NOT EXISTS (
      SELECT 1
      FROM user_roles existing_role
      WHERE existing_role.user_id = professor.user_id
        AND existing_role.role_code = 'R01'
        AND existing_role.status = 'ACTIVE'
  );

INSERT INTO lecture_evaluation_achievements (
    achievement_id,
    management_no,
    teacher_user_id,
    evaluation_year,
    organization_code,
    management_item_code,
    occurred_date,
    achievement_detail,
    certification_status,
    attachment_ref,
    deleted_yn,
    created_by,
    updated_by,
    change_reason
)
SELECT
    fixture.achievement_id,
    fixture.management_no,
    professor.user_id,
    '2026',
    'KNUE-DEPT-COMP',
    fixture.management_item_code,
    fixture.occurred_date,
    fixture.achievement_detail::jsonb,
    fixture.certification_status,
    fixture.attachment_ref,
    'N',
    administrator.user_id,
    administrator.user_id,
    'B77-LE-001 강의평가 정상·경계·상태 fixture'
FROM users professor
JOIN users administrator ON administrator.login_id = 'admin'
CROSS JOIN (
    VALUES
        (790001::bigint, 'B77-LE-001-01', 'EDU-LECTURE-EVALUATION', DATE '2026-04-10', '{"lectureName":"교육방법론","score":95}', 'DRAFT', 'ATTACHMENT-B77-LE-001-01'),
        (790002::bigint, 'B77-LE-001-02', 'EDU-LECTURE-EVALUATION', DATE '2026-02-28', '{"lectureName":"교육과정","score":89,"boundary":"evaluation-period-warning"}', 'DEPARTMENT_REJECTED', NULL),
        (790003::bigint, 'B77-LE-001-03', 'EDU-LECTURE-EVALUATION', DATE '2026-04-20', '{"lectureName":"교수학습이론","score":92,"lock":"evaluation-confirmed"}', 'EVALUATION_CONFIRMED', 'ATTACHMENT-B77-LE-001-03')
) AS fixture(
    achievement_id,
    management_no,
    management_item_code,
    occurred_date,
    achievement_detail,
    certification_status,
    attachment_ref
)
WHERE professor.login_id = 'professor1'
ON CONFLICT (achievement_id) DO UPDATE SET
    management_no = EXCLUDED.management_no,
    teacher_user_id = EXCLUDED.teacher_user_id,
    evaluation_year = EXCLUDED.evaluation_year,
    organization_code = EXCLUDED.organization_code,
    management_item_code = EXCLUDED.management_item_code,
    occurred_date = EXCLUDED.occurred_date,
    achievement_detail = EXCLUDED.achievement_detail,
    certification_status = EXCLUDED.certification_status,
    attachment_ref = EXCLUDED.attachment_ref,
    deleted_yn = EXCLUDED.deleted_yn,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = EXCLUDED.updated_by,
    change_reason = EXCLUDED.change_reason;

INSERT INTO education_achievement_status_histories (
    achievement_type,
    achievement_id,
    previous_status,
    next_status,
    action_type,
    reason_code,
    opinion,
    processed_by,
    change_reason,
    request_id
)
SELECT
    'LECTURE_EVALUATION',
    fixture.achievement_id,
    fixture.previous_status,
    fixture.next_status,
    fixture.action_type,
    fixture.reason_code,
    fixture.opinion,
    administrator.user_id,
    'B77-LE-001 상태 이력 fixture',
    fixture.request_id
FROM users administrator
CROSS JOIN (
    VALUES
        (790001::bigint, 'DRAFT', 'SUBMITTED', 'SUBMIT', NULL, NULL, 'REQ-B77-LE-001-01'),
        (790002::bigint, 'SUBMITTED', 'DEPARTMENT_REJECTED', 'DEPARTMENT_REJECT', 'INCOMPLETE_EVIDENCE', '강의평가 증빙을 보완하세요.', 'REQ-B77-LE-001-02'),
        (790003::bigint, 'CERTIFIED', 'EVALUATION_CONFIRMED', 'FINALIZE', NULL, NULL, 'REQ-B77-LE-001-03')
) AS fixture(
    achievement_id,
    previous_status,
    next_status,
    action_type,
    reason_code,
    opinion,
    request_id
)
WHERE administrator.login_id = 'admin'
  AND NOT EXISTS (
      SELECT 1
      FROM education_achievement_status_histories existing_history
      WHERE existing_history.achievement_type = 'LECTURE_EVALUATION'
        AND existing_history.achievement_id = fixture.achievement_id
        AND existing_history.request_id = fixture.request_id
  );

SELECT setval(
    pg_get_serial_sequence('lecture_evaluation_achievements', 'achievement_id'),
    COALESCE((SELECT MAX(achievement_id) FROM lecture_evaluation_achievements), 1),
    true
);
