CREATE TABLE IF NOT EXISTS education_achievements (
    education_achievement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    achievement_type varchar(50) NOT NULL,
    management_number varchar(100) NOT NULL,
    teacher_user_id bigint NOT NULL,
    management_item_code varchar(100) NOT NULL,
    achievement_date date NOT NULL,
    achievement_name varchar(300) NOT NULL,
    achievement_detail_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    achievement_status varchar(30) NOT NULL DEFAULT 'DRAFT',
    attachment_ref varchar(200),
    deleted_yn varchar(1) NOT NULL DEFAULT 'N',
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint NOT NULL,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint NOT NULL,
    change_reason varchar(500),
    CONSTRAINT uq_education_achievements_management_number UNIQUE (management_number),
    CONSTRAINT ck_education_achievements_type CHECK (achievement_type IN ('LECTURE_EVALUATION', 'LECTURE_PERFORMANCE', 'STUDENT_GUIDANCE', 'GRADUATE_DEGREE')),
    CONSTRAINT ck_education_achievements_status CHECK (achievement_status IN ('DRAFT', 'SUBMITTED', 'CHAIR_CONFIRMED', 'CHAIR_REJECTED', 'CERTIFIED', 'CERTIFICATION_REJECTED', 'EVALUATION_CONFIRMED', 'DELETED')),
    CONSTRAINT ck_education_achievements_deleted_yn CHECK (deleted_yn IN ('Y', 'N')),
    CONSTRAINT fk_education_achievements_teacher FOREIGN KEY (teacher_user_id) REFERENCES users(user_id),
    CONSTRAINT fk_education_achievements_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_education_achievements_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE education_achievements IS 'FR-025~028 교육영역 실적의 공통 원천 데이터와 인증상태, 논리삭제, 감사정보를 보관한다.';
COMMENT ON COLUMN education_achievements.achievement_type IS 'LECTURE_EVALUATION:강의평가|LECTURE_PERFORMANCE:강의실적|STUDENT_GUIDANCE:학생지도|GRADUATE_DEGREE:석박사배출';
COMMENT ON COLUMN education_achievements.teacher_user_id IS 'users.user_id 참조 의도 (실적 소유 교원)';
COMMENT ON COLUMN education_achievements.achievement_status IS 'DRAFT:작성중|SUBMITTED:제출|CHAIR_CONFIRMED:학과장확인|CHAIR_REJECTED:학과장미승인|CERTIFIED:인증|CERTIFICATION_REJECTED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN education_achievements.deleted_yn IS 'Y:논리삭제|N:정상';
COMMENT ON COLUMN education_achievements.achievement_detail_json IS '항목별 동적 입력값을 EducationAchievementService 저장 시 기록';

CREATE TABLE IF NOT EXISTS education_achievement_status_histories (
    status_history_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    education_achievement_id bigint NOT NULL,
    from_status varchar(30),
    to_status varchar(30) NOT NULL,
    processed_by bigint NOT NULL,
    processed_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reason varchar(500),
    request_id varchar(100),
    CONSTRAINT fk_education_achievement_status_histories_achievement FOREIGN KEY (education_achievement_id) REFERENCES education_achievements(education_achievement_id),
    CONSTRAINT fk_education_achievement_status_histories_processed_by FOREIGN KEY (processed_by) REFERENCES users(user_id)
);
COMMENT ON TABLE education_achievement_status_histories IS '교육영역 실적의 상태 전이별 이전·이후 상태, 처리자, 처리시각, 사유와 요청 식별자를 보관한다.';
COMMENT ON COLUMN education_achievement_status_histories.processed_by IS 'users.user_id 참조 의도 (상태 전이 처리자)';
COMMENT ON COLUMN education_achievement_status_histories.to_status IS 'DRAFT:작성중|SUBMITTED:제출|CHAIR_CONFIRMED:학과장확인|CHAIR_REJECTED:학과장미승인|CERTIFIED:인증|CERTIFICATION_REJECTED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN education_achievement_status_histories.request_id IS 'EducationAchievementService 처리 요청의 X-Request-Id 또는 서버 생성 요청 식별자';

CREATE TABLE IF NOT EXISTS student_guidance_achievement_details (
    student_guidance_detail_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    education_achievement_id bigint NOT NULL,
    student_name varchar(100) NOT NULL,
    student_number varchar(50),
    guidance_start_date date NOT NULL,
    guidance_end_date date,
    student_count integer NOT NULL DEFAULT 1,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint NOT NULL,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint NOT NULL,
    CONSTRAINT uq_student_guidance_achievement_details_achievement UNIQUE (education_achievement_id),
    CONSTRAINT ck_student_guidance_achievement_details_dates CHECK (guidance_end_date IS NULL OR guidance_end_date >= guidance_start_date),
    CONSTRAINT ck_student_guidance_achievement_details_count CHECK (student_count > 0),
    CONSTRAINT fk_student_guidance_achievement_details_achievement FOREIGN KEY (education_achievement_id) REFERENCES education_achievements(education_achievement_id),
    CONSTRAINT fk_student_guidance_achievement_details_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_student_guidance_achievement_details_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE student_guidance_achievement_details IS '학생지도 실적의 지도학생, 지도기간, 학생 수 상세정보를 실적 원천과 연결해 보관한다.';
COMMENT ON COLUMN student_guidance_achievement_details.education_achievement_id IS 'education_achievements.education_achievement_id 참조 의도 (학생지도 실적 원천)';

CREATE TABLE IF NOT EXISTS graduate_degree_achievement_students (
    graduate_degree_student_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    education_achievement_id bigint NOT NULL,
    student_name varchar(100) NOT NULL,
    student_number varchar(50),
    degree_type varchar(20) NOT NULL,
    thesis_title varchar(500),
    degree_awarded_date date NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint NOT NULL,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint NOT NULL,
    CONSTRAINT ck_graduate_degree_achievement_students_type CHECK (degree_type IN ('MASTER', 'DOCTOR')),
    CONSTRAINT fk_graduate_degree_achievement_students_achievement FOREIGN KEY (education_achievement_id) REFERENCES education_achievements(education_achievement_id),
    CONSTRAINT fk_graduate_degree_achievement_students_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_graduate_degree_achievement_students_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE graduate_degree_achievement_students IS '석사·박사 배출 실적의 지도학생, 학위구분, 논문제목과 학위수여일을 보관한다.';
COMMENT ON COLUMN graduate_degree_achievement_students.education_achievement_id IS 'education_achievements.education_achievement_id 참조 의도 (석박사 배출 실적 원천)';
COMMENT ON COLUMN graduate_degree_achievement_students.degree_type IS 'MASTER:석사|DOCTOR:박사';

CREATE INDEX IF NOT EXISTS idx_education_achievements_teacher_type_status ON education_achievements(teacher_user_id, achievement_type, achievement_status) WHERE deleted_yn = 'N';
CREATE INDEX IF NOT EXISTS idx_education_achievements_management_item_date ON education_achievements(management_item_code, achievement_date DESC) WHERE deleted_yn = 'N';
CREATE INDEX IF NOT EXISTS idx_education_achievement_status_histories_achievement ON education_achievement_status_histories(education_achievement_id, processed_at DESC);
CREATE INDEX IF NOT EXISTS idx_student_guidance_achievement_details_student ON student_guidance_achievement_details(student_number, guidance_start_date DESC);
CREATE INDEX IF NOT EXISTS idx_graduate_degree_achievement_students_achievement ON graduate_degree_achievement_students(education_achievement_id, degree_awarded_date DESC);

INSERT INTO education_achievements (
    achievement_type, management_number, teacher_user_id, management_item_code, achievement_date,
    achievement_name, achievement_detail_json, achievement_status, deleted_yn, created_by, updated_by, change_reason
)
SELECT seed.achievement_type, seed.management_number, admin_user.user_id, seed.management_item_code,
       seed.achievement_date, seed.achievement_name, seed.achievement_detail_json::jsonb,
       seed.achievement_status, 'N', admin_user.user_id, admin_user.user_id, seed.change_reason
FROM users admin_user
CROSS JOIN (
    VALUES
        ('LECTURE_EVALUATION', 'EDU-LE-2026-001', 'EDU-LE-ITEM-01', DATE '2026-03-15', '2026학년도 1학기 강의평가', '{"semester":"2026-1","score":4.8}', 'DRAFT', '정상 작성중 강의평가 fixture'),
        ('LECTURE_EVALUATION', 'EDU-LE-2026-002', 'EDU-LE-ITEM-01', DATE '2025-12-31', '기간경계 강의평가', '{"semester":"2025-2","score":4.2}', 'CHAIR_REJECTED', '경계일 및 미승인 강의평가 fixture'),
        ('LECTURE_PERFORMANCE', 'EDU-LP-2026-001', 'EDU-LP-ITEM-01', DATE '2026-04-01', '강의실적 강좌 운영', '{"courseCode":"EDU101"}', 'CERTIFIED', '인증 강의실적 fixture'),
        ('STUDENT_GUIDANCE', 'EDU-SG-2026-001', 'EDU-SG-ITEM-01', DATE '2026-03-02', '학생지도 실적 A', '{"guidanceType":"ACADEMIC"}', 'DRAFT', '정상 학생지도 fixture'),
        ('STUDENT_GUIDANCE', 'EDU-SG-2026-002', 'EDU-SG-ITEM-01', DATE '2026-02-28', '학생지도 실적 B', '{"guidanceType":"CAREER"}', 'SUBMITTED', '제출 학생지도 fixture'),
        ('STUDENT_GUIDANCE', 'EDU-SG-2026-003', 'EDU-SG-ITEM-01', DATE '2026-01-15', '학생지도 실적 C', '{"guidanceType":"ACADEMIC"}', 'CERTIFICATION_REJECTED', '반려 학생지도 fixture'),
        ('GRADUATE_DEGREE', 'EDU-GD-2026-001', 'EDU-GD-ITEM-01', DATE '2026-02-20', '석사 배출 실적', '{"degreeType":"MASTER"}', 'CERTIFIED', '정상 석사 배출 fixture'),
        ('GRADUATE_DEGREE', 'EDU-GD-2026-002', 'EDU-GD-ITEM-01', DATE '2026-02-21', '박사 배출 실적', '{"degreeType":"DOCTOR"}', 'EVALUATION_CONFIRMED', '평가확정 잠금 fixture'),
        ('GRADUATE_DEGREE', 'EDU-GD-2026-003', 'EDU-GD-ITEM-01', DATE '2026-02-22', '권한 경계 배출 실적', '{"degreeType":"MASTER"}', 'CHAIR_REJECTED', '권한 및 상태 경계 fixture')
) AS seed(achievement_type, management_number, management_item_code, achievement_date, achievement_name, achievement_detail_json, achievement_status, change_reason)
WHERE admin_user.login_id = 'admin'
ON CONFLICT (management_number) DO NOTHING;

INSERT INTO education_achievement_status_histories (education_achievement_id, from_status, to_status, processed_by, reason, request_id)
SELECT achievement.education_achievement_id, seed.from_status, seed.to_status, admin_user.user_id, seed.reason, seed.request_id
FROM users admin_user
JOIN (VALUES
    ('EDU-LE-2026-001', NULL::varchar, 'DRAFT', '초기 작성', 'seed-basic74-le-001'),
    ('EDU-LE-2026-002', 'SUBMITTED', 'CHAIR_REJECTED', '보완 필요', 'seed-basic74-le-002'),
    ('EDU-SG-2026-003', 'CHAIR_CONFIRMED', 'CERTIFICATION_REJECTED', '증빙 보완 필요', 'seed-basic74-sg-003'),
    ('EDU-GD-2026-002', 'CERTIFIED', 'EVALUATION_CONFIRMED', '평가확정', 'seed-basic74-gd-002')
) AS seed(management_number, from_status, to_status, reason, request_id) ON TRUE
JOIN education_achievements achievement ON achievement.management_number = seed.management_number
WHERE admin_user.login_id = 'admin'
  AND NOT EXISTS (
      SELECT 1 FROM education_achievement_status_histories history
      WHERE history.education_achievement_id = achievement.education_achievement_id
        AND history.request_id = seed.request_id
  );

INSERT INTO student_guidance_achievement_details (
    education_achievement_id, student_name, student_number, guidance_start_date, guidance_end_date,
    student_count, created_by, updated_by
)
SELECT achievement.education_achievement_id, seed.student_name, seed.student_number, seed.guidance_start_date,
       seed.guidance_end_date, seed.student_count, admin_user.user_id, admin_user.user_id
FROM users admin_user
JOIN (VALUES
    ('EDU-SG-2026-001', '김학생', 'S2026001', DATE '2026-03-02', DATE '2026-06-30', 1),
    ('EDU-SG-2026-002', '이학생', 'S2026002', DATE '2026-02-28', DATE '2026-06-30', 2),
    ('EDU-SG-2026-003', '박학생', 'S2026003', DATE '2026-01-15', DATE '2026-06-30', 1)
) AS seed(management_number, student_name, student_number, guidance_start_date, guidance_end_date, student_count) ON TRUE
JOIN education_achievements achievement ON achievement.management_number = seed.management_number
WHERE admin_user.login_id = 'admin'
ON CONFLICT (education_achievement_id) DO NOTHING;

INSERT INTO graduate_degree_achievement_students (
    education_achievement_id, student_name, student_number, degree_type, thesis_title, degree_awarded_date,
    created_by, updated_by
)
SELECT achievement.education_achievement_id, seed.student_name, seed.student_number, seed.degree_type,
       seed.thesis_title, seed.degree_awarded_date, admin_user.user_id, admin_user.user_id
FROM users admin_user
JOIN (VALUES
    ('EDU-GD-2026-001', '최학생', 'G2026001', 'MASTER', '교육성과 분석 연구', DATE '2026-02-20'),
    ('EDU-GD-2026-002', '정학생', 'G2026002', 'DOCTOR', '교수학습 모형 연구', DATE '2026-02-21'),
    ('EDU-GD-2026-003', '윤학생', 'G2026003', 'MASTER', '교육정책 효과 연구', DATE '2026-02-22')
) AS seed(management_number, student_name, student_number, degree_type, thesis_title, degree_awarded_date) ON TRUE
JOIN education_achievements achievement ON achievement.management_number = seed.management_number
WHERE admin_user.login_id = 'admin'
ON CONFLICT DO NOTHING;

WITH menu_base AS (
    SELECT COALESCE(MAX(menu_id), 0) AS max_menu_id
    FROM menus
), menu_seed AS (
    SELECT menu_base.max_menu_id + seed.menu_offset AS menu_id, seed.menu_type, seed.menu_name,
           seed.display_order, seed.screen_id, seed.url, seed.icon, seed.description
    FROM menu_base
    CROSS JOIN (VALUES
        (1, 'MIDDLE', '교육영역 실적 관리', 20, NULL::varchar, NULL::varchar, 'graduation-cap', '교육영역 실적 입력 화면의 공통 메뉴'),
        (2, 'SCREEN', '강의평가 실적', 1, 'SCR-LECTURE-EVALUATION-ACHIEVEMENT', '/achievement/lecture-evaluations', 'clipboard-list', '강의평가 실적 조회·입력'),
        (3, 'SCREEN', '강의실적', 2, 'SCR-LECTURE-PERFORMANCE-ACHIEVEMENT', '/achievement/lecture-performances', 'book-open', '강의실적 조회·입력'),
        (4, 'SCREEN', '학생지도 실적', 3, 'SCR-STUDENT-GUIDANCE-ACHIEVEMENT', '/achievement/student-guidance', 'users', '학생지도 실적 조회·입력·일괄등록'),
        (5, 'SCREEN', '석박사 배출 실적', 4, 'SCR-GRADUATE-DEGREE-ACHIEVEMENT', '/achievement/graduate-degrees', 'award', '석박사 배출 실적 조회·입력')
    ) AS seed(menu_offset, menu_type, menu_name, display_order, screen_id, url, icon, description)
)
INSERT INTO menus (menu_id, parent_menu_id, menu_type, menu_name, display_order, screen_id, url, icon, business_category, description, system_use_yn, status, updated_by, change_reason)
SELECT menu_seed.menu_id,
       CASE WHEN menu_seed.menu_type = 'MIDDLE' THEN 300 ELSE (SELECT menu_id FROM menu_seed WHERE menu_type = 'MIDDLE') END,
       menu_seed.menu_type, menu_seed.menu_name, menu_seed.display_order, menu_seed.screen_id, menu_seed.url,
       menu_seed.icon, 'EDUCATION_ACHIEVEMENT', menu_seed.description, 'Y', 'ACTIVE', admin_user.user_id,
       'BASIC-74 교육영역 실적 메뉴 seed'
FROM menu_seed
CROSS JOIN users admin_user
WHERE admin_user.login_id = 'admin';

INSERT INTO menu_execution_info (menu_id, screen_id, url, icon, business_category, description, updated_by)
SELECT menu.menu_id, menu.screen_id, menu.url, menu.icon, menu.business_category, menu.description, admin_user.user_id
FROM menus menu
CROSS JOIN users admin_user
WHERE menu.screen_id IN ('SCR-LECTURE-EVALUATION-ACHIEVEMENT', 'SCR-LECTURE-PERFORMANCE-ACHIEVEMENT', 'SCR-STUDENT-GUIDANCE-ACHIEVEMENT', 'SCR-GRADUATE-DEGREE-ACHIEVEMENT')
  AND admin_user.login_id = 'admin'
ON CONFLICT (menu_id) DO UPDATE SET screen_id = EXCLUDED.screen_id, url = EXCLUDED.url, icon = EXCLUDED.icon,
    business_category = EXCLUDED.business_category, description = EXCLUDED.description, updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_permissions (target_type, target_id, menu_id, access_allowed, status, created_by, updated_by, change_reason)
SELECT 'ROLE', role.role_code, menu.menu_id, 'ALLOW', 'ACTIVE', admin_user.user_id, admin_user.user_id,
       'BASIC-74 교육영역 실적 메뉴 접근'
FROM menus menu
CROSS JOIN roles role
CROSS JOIN users admin_user
WHERE menu.screen_id IN ('SCR-LECTURE-EVALUATION-ACHIEVEMENT', 'SCR-LECTURE-PERFORMANCE-ACHIEVEMENT', 'SCR-STUDENT-GUIDANCE-ACHIEVEMENT', 'SCR-GRADUATE-DEGREE-ACHIEVEMENT')
  AND (
      role.role_code IN ('R01', 'R02', 'R04')
      OR (role.role_code = 'R07' AND menu.screen_id = 'SCR-STUDENT-GUIDANCE-ACHIEVEMENT')
  )
  AND admin_user.login_id = 'admin'
ON CONFLICT (target_type, target_id, menu_id) DO UPDATE SET access_allowed = EXCLUDED.access_allowed,
    status = EXCLUDED.status, updated_at = CURRENT_TIMESTAMP, updated_by = EXCLUDED.updated_by,
    change_reason = EXCLUDED.change_reason;
