CREATE TABLE IF NOT EXISTS lecture_achievements (
    achievement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    achievement_number varchar(50) NOT NULL UNIQUE,
    employee_no varchar(50) NOT NULL,
    evaluation_year varchar(4) NOT NULL,
    management_item_code varchar(50) NOT NULL,
    occurred_date date NOT NULL,
    achievement_detail jsonb NOT NULL DEFAULT '{}'::jsonb,
    certification_status varchar(30) NOT NULL DEFAULT 'DRAFT',
    attachment_ref varchar(200),
    deleted_yn char(1) NOT NULL DEFAULT 'N',
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint NOT NULL,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint NOT NULL,
    CONSTRAINT ck_lecture_achievements_year CHECK (evaluation_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_lecture_achievements_status CHECK (certification_status IN (
        'DRAFT', 'SUBMITTED', 'CHAIR_CONFIRMED', 'CHAIR_REJECTED',
        'CERTIFIED', 'CERTIFICATION_REJECTED', 'EVALUATION_CONFIRMED', 'DELETED'
    )),
    CONSTRAINT ck_lecture_achievements_deleted CHECK (deleted_yn IN ('Y', 'N')),
    CONSTRAINT fk_lecture_achievements_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_lecture_achievements_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE lecture_achievements IS '교육영역 강의실적 원천. 인증상태, 논리삭제, 입력 및 수정 메타정보를 보존한다.';
COMMENT ON COLUMN lecture_achievements.employee_no IS 'korus_personnel_snapshots.employee_no 참조 의도 (FK 미선언)';
COMMENT ON COLUMN lecture_achievements.management_item_code IS 'evaluation_element_management_item_settings.management_item_code 참조 의도 (FK 미선언)';
COMMENT ON COLUMN lecture_achievements.achievement_detail IS '강의실적 활성 관리항목의 동적 입력값을 애플리케이션에서 기록';
COMMENT ON COLUMN lecture_achievements.certification_status IS 'DRAFT:작성중|SUBMITTED:제출|CHAIR_CONFIRMED:학과장확인|CHAIR_REJECTED:학과장미승인|CERTIFIED:인증|CERTIFICATION_REJECTED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN lecture_achievements.attachment_ref IS '기존 FileStoragePort가 발급한 외부 노출용 첨부 식별자';
COMMENT ON COLUMN lecture_achievements.deleted_yn IS 'Y:논리삭제|N:정상';

CREATE INDEX IF NOT EXISTS idx_lecture_achievements_lookup
    ON lecture_achievements (evaluation_year, employee_no, certification_status, occurred_date DESC)
    WHERE deleted_yn = 'N';

WITH fixture_user AS (
    SELECT user_id
    FROM users
    WHERE login_id = 'admin'
)
INSERT INTO lecture_achievements (
    achievement_number, employee_no, evaluation_year, management_item_code, occurred_date,
    achievement_detail, certification_status, attachment_ref, deleted_yn, created_by, updated_by
)
SELECT fixture.achievement_number, fixture.employee_no, fixture.evaluation_year, fixture.management_item_code,
       fixture.occurred_date, fixture.achievement_detail::jsonb, fixture.certification_status,
       fixture.attachment_ref, 'N', fixture_user.user_id, fixture_user.user_id
FROM fixture_user
CROSS JOIN (VALUES
    ('B77-LA-001', 'E1001', '2026', 'EDU_LECTURE', DATE '2026-03-15', '{"courseName":"교육평가론","credit":"3"}', 'DRAFT', NULL),
    ('B77-LA-002', 'E1001', '2026', 'EDU_LECTURE', DATE '2026-04-01', '{"courseName":"교육과정론","credit":"3"}', 'SUBMITTED', 'b77-la-attachment-002'),
    ('B77-LA-003', 'E1001', '2026', 'EDU_LECTURE', DATE '2025-12-31', '{"courseName":"교육행정론","credit":"2"}', 'EVALUATION_CONFIRMED', 'b77-la-attachment-003')
) AS fixture(achievement_number, employee_no, evaluation_year, management_item_code, occurred_date, achievement_detail, certification_status, attachment_ref)
ON CONFLICT (achievement_number) DO UPDATE SET
    employee_no = EXCLUDED.employee_no,
    evaluation_year = EXCLUDED.evaluation_year,
    management_item_code = EXCLUDED.management_item_code,
    occurred_date = EXCLUDED.occurred_date,
    achievement_detail = EXCLUDED.achievement_detail,
    certification_status = EXCLUDED.certification_status,
    attachment_ref = EXCLUDED.attachment_ref,
    deleted_yn = EXCLUDED.deleted_yn,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = EXCLUDED.updated_by;
