CREATE TABLE IF NOT EXISTS student_guidance_achievements (
    achievement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    management_no varchar(50) NOT NULL UNIQUE,
    evaluation_year varchar(4) NOT NULL,
    organization_code varchar(50) NOT NULL,
    teacher_user_id bigint NOT NULL REFERENCES users(user_id),
    management_item_code varchar(100) NOT NULL,
    guidance_start_date date NOT NULL,
    guidance_end_date date NOT NULL,
    student_count integer NOT NULL DEFAULT 0 CHECK (student_count >= 0),
    achievement_status varchar(30) NOT NULL DEFAULT 'DRAFTING' CHECK (achievement_status IN ('DRAFTING','SUBMITTED','DEPARTMENT_CONFIRMED','DEPARTMENT_REJECTED','CERTIFIED','CERTIFICATION_RETURNED','EVALUATION_CONFIRMED','DELETED')),
    detail_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    deleted_at timestamp,
    deleted_by bigint REFERENCES users(user_id),
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint NOT NULL REFERENCES users(user_id),
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint NOT NULL REFERENCES users(user_id),
    change_reason varchar(500) NOT NULL,
    CONSTRAINT ck_student_guidance_achievements_year CHECK (evaluation_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_student_guidance_achievements_dates CHECK (guidance_end_date >= guidance_start_date)
);
COMMENT ON TABLE student_guidance_achievements IS '교육영역 학생지도 실적의 헤더와 인증상태, 논리삭제 정보를 보존한다.';
COMMENT ON COLUMN student_guidance_achievements.management_item_code IS 'evaluation_element_management_item_settings의 활성 관리항목 코드 참조 의도 (FK 미선언)';
COMMENT ON COLUMN student_guidance_achievements.achievement_status IS 'DRAFTING:작성중|SUBMITTED:제출|DEPARTMENT_CONFIRMED:학과장확인|DEPARTMENT_REJECTED:학과장미승인|CERTIFIED:인증|CERTIFICATION_RETURNED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN student_guidance_achievements.deleted_by IS 'users.user_id 참조 의도 (논리삭제 처리자)';

CREATE TABLE IF NOT EXISTS student_guidance_students (
    student_guidance_student_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    achievement_id bigint NOT NULL REFERENCES student_guidance_achievements(achievement_id),
    student_no varchar(50) NOT NULL,
    student_name varchar(100) NOT NULL,
    guidance_type varchar(50) NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint NOT NULL REFERENCES users(user_id),
    CONSTRAINT uq_student_guidance_students_achievement_student UNIQUE (achievement_id, student_no)
);
COMMENT ON TABLE student_guidance_students IS '학생지도 실적에 연결된 지도학생의 식별정보와 지도유형을 보존한다.';
COMMENT ON COLUMN student_guidance_students.achievement_id IS 'student_guidance_achievements.achievement_id 참조';
CREATE INDEX IF NOT EXISTS idx_student_guidance_achievements_list ON student_guidance_achievements (evaluation_year, organization_code, teacher_user_id, guidance_start_date DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_student_guidance_students_achievement ON student_guidance_students (achievement_id);

INSERT INTO student_guidance_achievements (management_no, evaluation_year, organization_code, teacher_user_id, management_item_code, guidance_start_date, guidance_end_date, student_count, achievement_status, detail_payload, created_by, updated_by, change_reason)
SELECT seed.management_no, seed.evaluation_year, 'KNUE-DEPT-COMP', u.user_id, 'STUDENT_GUIDANCE', seed.guidance_start_date, seed.guidance_end_date, seed.student_count, seed.achievement_status, seed.detail_payload::jsonb, u.user_id, u.user_id, seed.change_reason
FROM users u CROSS JOIN (VALUES
 ('B77-SG-001','2026',DATE '2026-03-01',DATE '2026-06-30',1,'DRAFTING','{"guidanceCategory":"학부"}','BASIC-81 정상 학생지도 fixture'),
 ('B77-SG-002','2026',DATE '2026-01-01',DATE '2026-02-28',1,'SUBMITTED','{"guidanceCategory":"대학원"}','BASIC-81 기간 경계 학생지도 fixture'),
 ('B77-SG-003','2025',DATE '2025-03-01',DATE '2025-12-31',1,'EVALUATION_CONFIRMED','{"guidanceCategory":"학부"}','BASIC-81 확정 학생지도 fixture')
) seed(management_no,evaluation_year,guidance_start_date,guidance_end_date,student_count,achievement_status,detail_payload,change_reason)
WHERE u.login_id = 'professor1' ON CONFLICT (management_no) DO NOTHING;
INSERT INTO student_guidance_students (achievement_id, student_no, student_name, guidance_type, created_by)
SELECT a.achievement_id, 'S-' || a.management_no, '학생지도 대상', 'ADVISORY', a.created_by FROM student_guidance_achievements a WHERE a.management_no IN ('B77-SG-001','B77-SG-002','B77-SG-003') ON CONFLICT (achievement_id, student_no) DO NOTHING;
INSERT INTO excel_upload_templates (template_id,business_type,template_version,effective_date,created_by,updated_by,change_reason)
SELECT 'B77-STUDENT-GUIDANCE-TEMPLATE','STUDENT_GUIDANCE','v1.0',DATE '2026-01-01',u.user_id,u.user_id,'BASIC-81 학생지도 Excel 양식' FROM users u WHERE u.login_id='admin' ON CONFLICT (template_id) DO NOTHING;
INSERT INTO excel_upload_template_rules (rule_id,template_id,required_column,column_order,code_rule_ref,created_by,updated_by)
SELECT 'B77-SG-RULE-' || seed.column_order,'B77-STUDENT-GUIDANCE-TEMPLATE',seed.required_column,seed.column_order,seed.code_rule_ref,u.user_id,u.user_id FROM users u CROSS JOIN (VALUES
 ('교번',1,'users.employee_no'),('학생학번',2,'student_guidance_students.student_no'),('학생명',3,'student_guidance_students.student_name'),('지도유형',4,'STUDENT_GUIDANCE_TYPE'),('지도시작일',5,'YYYY-MM-DD'),('지도종료일',6,'YYYY-MM-DD')
) seed(required_column,column_order,code_rule_ref) WHERE u.login_id='admin' ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO excel_upload_template_files (file_token,template_id,original_file_name,content_type,file_size_bytes,created_by)
SELECT 'B77-STUDENT-GUIDANCE-TEMPLATE-FILE','B77-STUDENT-GUIDANCE-TEMPLATE','학생지도_일괄등록_양식.csv','text/csv',0,u.user_id FROM users u WHERE u.login_id='admin' ON CONFLICT (file_token) DO NOTHING;
