-- BASIC-81 학생지도 실적과 지도학생 상세, R07 Excel 양식 fixture를 추가한다.

CREATE TABLE IF NOT EXISTS student_guidance_achievements (
    achievement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    management_no varchar(50) NOT NULL,
    target_user_id bigint NOT NULL,
    evaluation_year varchar(4) NOT NULL,
    management_item_code varchar(50) NOT NULL,
    guidance_start_date date NOT NULL,
    guidance_end_date date NOT NULL,
    student_count integer NOT NULL DEFAULT 0,
    certification_status varchar(30) NOT NULL DEFAULT 'DRAFT',
    attachment_ref varchar(300),
    deleted_yn char(1) NOT NULL DEFAULT 'N',
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    CONSTRAINT uq_student_guidance_achievements_management_no UNIQUE (management_no),
    CONSTRAINT ck_student_guidance_achievements_year CHECK (evaluation_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_student_guidance_achievements_period CHECK (guidance_end_date >= guidance_start_date),
    CONSTRAINT ck_student_guidance_achievements_count CHECK (student_count >= 0),
    CONSTRAINT ck_student_guidance_achievements_status CHECK (
        certification_status IN ('DRAFT', 'SUBMITTED', 'DEPARTMENT_CONFIRMED',
            'DEPARTMENT_REJECTED', 'CERTIFIED', 'CERTIFICATION_REJECTED',
            'EVALUATION_CONFIRMED', 'DELETED')
    ),
    CONSTRAINT ck_student_guidance_achievements_deleted CHECK (deleted_yn IN ('Y', 'N')),
    CONSTRAINT fk_student_guidance_achievements_target
        FOREIGN KEY (target_user_id) REFERENCES users(user_id),
    CONSTRAINT fk_student_guidance_achievements_created_by
        FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_student_guidance_achievements_updated_by
        FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE student_guidance_achievements IS '교육영역 학생지도 실적의 헤더 원천. 지도기간, 대상 교원, 학생 수와 인증상태를 보존한다.';
COMMENT ON COLUMN student_guidance_achievements.certification_status IS 'DRAFT:작성중|SUBMITTED:제출|DEPARTMENT_CONFIRMED:학과장확인|DEPARTMENT_REJECTED:학과장미승인|CERTIFIED:인증|CERTIFICATION_REJECTED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN student_guidance_achievements.attachment_ref IS 'FileStoragePort의 외부 비노출 첨부 참조값';
COMMENT ON COLUMN student_guidance_achievements.deleted_yn IS 'Y:삭제|N:정상';
COMMENT ON COLUMN student_guidance_achievements.target_user_id IS 'users.user_id 참조 의도 (실적 대상 교원)';
COMMENT ON COLUMN student_guidance_achievements.created_by IS 'users.user_id 참조 의도 (최초 입력자)';
COMMENT ON COLUMN student_guidance_achievements.updated_by IS 'users.user_id 참조 의도 (최종 수정자)';

CREATE TABLE IF NOT EXISTS student_guidance_students (
    student_guidance_student_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    achievement_id bigint NOT NULL,
    student_detail_jsonb jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    CONSTRAINT fk_student_guidance_students_achievement
        FOREIGN KEY (achievement_id) REFERENCES student_guidance_achievements(achievement_id),
    CONSTRAINT fk_student_guidance_students_created_by
        FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_student_guidance_students_updated_by
        FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE student_guidance_students IS '학생지도 실적에 속한 반복 지도학생 상세. 개인정보 세부 항목은 기존 개인정보 계약 전 JSON 원문으로 보존한다.';
COMMENT ON COLUMN student_guidance_students.achievement_id IS 'student_guidance_achievements.achievement_id 참조';
COMMENT ON COLUMN student_guidance_students.student_detail_jsonb IS '학생지도 저장 및 Excel 반영 시 애플리케이션이 검증한 지도학생 상세 JSON을 저장';
COMMENT ON COLUMN student_guidance_students.created_by IS 'users.user_id 참조 의도 (최초 입력자)';
COMMENT ON COLUMN student_guidance_students.updated_by IS 'users.user_id 참조 의도 (최종 수정자)';

CREATE INDEX IF NOT EXISTS idx_student_guidance_achievements_search
    ON student_guidance_achievements (
        target_user_id,
        evaluation_year,
        guidance_start_date DESC,
        certification_status
    )
    WHERE deleted_yn = 'N';
CREATE INDEX IF NOT EXISTS idx_student_guidance_students_achievement
    ON student_guidance_students (achievement_id);

INSERT INTO excel_upload_templates (
    template_id, business_type, template_version, effective_date, created_by, updated_by, change_reason
)
SELECT 'B77-SG-TEMPLATE-001', 'STUDENT_GUIDANCE', 'v1.0', DATE '2026-01-01', user_id, user_id,
       'BASIC-81 학생지도 현행 Excel 양식'
FROM users
WHERE login_id = 'admin'
ON CONFLICT (template_id) DO NOTHING;

INSERT INTO excel_upload_template_rules (
    rule_id, template_id, required_column, column_order, code_rule_ref, created_by, updated_by
)
SELECT seed.rule_id, 'B77-SG-TEMPLATE-001', seed.required_column, seed.column_order,
       seed.code_rule_ref, admin_user.user_id, admin_user.user_id
FROM users admin_user
CROSS JOIN (
    VALUES
        ('B77-SG-TEMPLATE-RULE-001', 'templateVersion', 1, 'EXCEL_TEMPLATE.VERSION'),
        ('B77-SG-TEMPLATE-RULE-002', 'managementItemCode', 2, 'EVALUATION_MANAGEMENT_ITEM.ACTIVE'),
        ('B77-SG-TEMPLATE-RULE-003', 'guidanceStartDate', 3, 'DATE.YYYY-MM-DD'),
        ('B77-SG-TEMPLATE-RULE-004', 'guidanceEndDate', 4, 'DATE.YYYY-MM-DD'),
        ('B77-SG-TEMPLATE-RULE-005', 'studentName', 5, 'STUDENT.NAME')
) AS seed(rule_id, required_column, column_order, code_rule_ref)
WHERE admin_user.login_id = 'admin'
ON CONFLICT (rule_id) DO NOTHING;

INSERT INTO excel_upload_template_files (
    file_token, template_id, original_file_name, content_type, file_size_bytes, created_by
)
SELECT 'b77-sg-template-file-001', 'B77-SG-TEMPLATE-001', '학생지도_일괄등록_양식.csv',
       'text/csv', 0, user_id
FROM users
WHERE login_id = 'admin'
ON CONFLICT (file_token) DO NOTHING;

INSERT INTO student_guidance_achievements (
    management_no, target_user_id, evaluation_year, management_item_code,
    guidance_start_date, guidance_end_date, student_count, certification_status,
    deleted_yn, created_by, updated_by
)
SELECT seed.management_no, owner.user_id, seed.evaluation_year, seed.management_item_code,
       seed.guidance_start_date, seed.guidance_end_date, seed.student_count,
       seed.certification_status, 'N', owner.user_id, owner.user_id
FROM (
    VALUES
        ('B77-SG-001', 'professor1', '2026', 'STUDENT_GUIDANCE', DATE '2026-03-01', DATE '2026-03-31', 1, 'DRAFT'),
        ('B77-SG-002', 'professor2', '2026', 'STUDENT_GUIDANCE', DATE '2026-04-01', DATE '2026-04-30', 2, 'SUBMITTED'),
        ('B77-SG-003', 'business-owner', '2026', 'STUDENT_GUIDANCE', DATE '2026-05-01', DATE '2026-05-31', 1, 'CERTIFIED')
) AS seed(management_no, login_id, evaluation_year, management_item_code, guidance_start_date,
          guidance_end_date, student_count, certification_status)
JOIN users owner ON owner.login_id = seed.login_id
ON CONFLICT (management_no) DO NOTHING;

INSERT INTO student_guidance_students (achievement_id, student_detail_jsonb, created_by, updated_by)
SELECT achievement.achievement_id, seed.student_detail_jsonb::jsonb, owner.user_id, owner.user_id
FROM (
    VALUES
        ('B77-SG-001', 'professor1', '{"studentName":"학생지도 정상 fixture"}'),
        ('B77-SG-002', 'professor2', '{"studentName":"학생지도 제출 fixture"}'),
        ('B77-SG-003', 'business-owner', '{"studentName":"학생지도 인증 fixture"}')
) AS seed(management_no, login_id, student_detail_jsonb)
JOIN student_guidance_achievements achievement ON achievement.management_no = seed.management_no
JOIN users owner ON owner.login_id = seed.login_id
WHERE NOT EXISTS (
    SELECT 1
    FROM student_guidance_students detail
    WHERE detail.achievement_id = achievement.achievement_id
);

INSERT INTO menus (
    menu_id, parent_menu_id, menu_type, menu_name, display_order, screen_id, url, icon,
    business_category, description, system_use_yn, status, updated_by, change_reason
)
SELECT COALESCE(MAX(menu_id), 0) + 1, NULL, 'SCREEN', '학생지도 Excel 일괄등록', 999,
       'SCR-STUDENT-GUIDANCE-EXCEL-UPLOAD', '/achievements/education/student-guidance-uploads',
       'file-spreadsheet', 'EDUCATION_ACHIEVEMENT', 'R07 학생지도 Excel 검증·반영·이력 화면',
       'Y', 'ACTIVE', admin_user.user_id, 'BASIC-81 학생지도 Excel 메뉴'
FROM menus
CROSS JOIN users admin_user
WHERE admin_user.login_id = 'admin'
  AND NOT EXISTS (
      SELECT 1 FROM menus
      WHERE screen_id = 'SCR-STUDENT-GUIDANCE-EXCEL-UPLOAD'
  )
GROUP BY admin_user.user_id;

INSERT INTO menu_permissions (
    target_type, target_id, menu_id, access_allowed, status, created_by, updated_by, change_reason
)
SELECT 'ROLE', 'R07', menu_id, 'ALLOW', 'ACTIVE', admin_user.user_id, admin_user.user_id,
       'BASIC-81 학생지도 Excel R07 접근'
FROM menus
CROSS JOIN users admin_user
WHERE menus.screen_id = 'SCR-STUDENT-GUIDANCE-EXCEL-UPLOAD'
  AND admin_user.login_id = 'admin'
ON CONFLICT (target_type, target_id, menu_id) DO UPDATE
SET access_allowed = EXCLUDED.access_allowed,
    status = EXCLUDED.status,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = EXCLUDED.updated_by,
    change_reason = EXCLUDED.change_reason;
