CREATE TABLE IF NOT EXISTS student_guidance_achievements (
    achievement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    achievement_number varchar(50) NOT NULL UNIQUE,
    employee_no varchar(50) NOT NULL,
    evaluation_year varchar(4) NOT NULL,
    management_item_code varchar(50) NOT NULL,
    occurred_date date NOT NULL,
    guidance_start_date date NOT NULL,
    guidance_end_date date NOT NULL,
    student_count integer NOT NULL,
    student_detail_jsonb jsonb NOT NULL DEFAULT '[]'::jsonb,
    achievement_detail jsonb NOT NULL DEFAULT '{}'::jsonb,
    certification_status varchar(30) NOT NULL DEFAULT 'DRAFT',
    attachment_ref varchar(200),
    deleted_yn char(1) NOT NULL DEFAULT 'N',
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint NOT NULL REFERENCES users(user_id),
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint NOT NULL REFERENCES users(user_id),
    CONSTRAINT ck_student_guidance_achievements_year CHECK (evaluation_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_student_guidance_achievements_period CHECK (guidance_end_date >= guidance_start_date),
    CONSTRAINT ck_student_guidance_achievements_count CHECK (student_count > 0),
    CONSTRAINT ck_student_guidance_achievements_status CHECK (certification_status IN ('DRAFT', 'SUBMITTED', 'CHAIR_CONFIRMED', 'CHAIR_REJECTED', 'CERTIFIED', 'CERTIFICATION_REJECTED', 'EVALUATION_CONFIRMED', 'DELETED')),
    CONSTRAINT ck_student_guidance_achievements_deleted CHECK (deleted_yn IN ('Y', 'N'))
);
COMMENT ON TABLE student_guidance_achievements IS '교육영역 학생지도 실적 헤더. 지도기간, 학생수, 인증상태와 논리삭제 이력을 보존한다.';
COMMENT ON COLUMN student_guidance_achievements.employee_no IS 'korus_personnel_snapshots.employee_no 참조 의도 (FK 미선언)';
COMMENT ON COLUMN student_guidance_achievements.management_item_code IS 'evaluation_element_management_item_settings.management_item_code 참조 의도 (FK 미선언)';
COMMENT ON COLUMN student_guidance_achievements.student_detail_jsonb IS '학생 개인정보 계약을 확인할 때까지 학생 반복 상세의 최소 식별값을 애플리케이션에서 기록';
COMMENT ON COLUMN student_guidance_achievements.certification_status IS 'DRAFT:작성중|SUBMITTED:제출|CHAIR_CONFIRMED:학과장확인|CHAIR_REJECTED:학과장미승인|CERTIFIED:인증|CERTIFICATION_REJECTED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN student_guidance_achievements.attachment_ref IS '기존 FileStoragePort가 발급한 외부 노출용 첨부 식별자';
COMMENT ON COLUMN student_guidance_achievements.deleted_yn IS 'Y:논리삭제|N:정상';

CREATE TABLE IF NOT EXISTS student_guidance_students (
    student_guidance_student_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    achievement_id bigint NOT NULL REFERENCES student_guidance_achievements(achievement_id),
    student_no varchar(50) NOT NULL,
    student_name varchar(100) NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint NOT NULL REFERENCES users(user_id),
    CONSTRAINT uq_student_guidance_students_achievement_student UNIQUE (achievement_id, student_no)
);
COMMENT ON TABLE student_guidance_students IS '학생지도 실적별 지도학생 반복 상세. 헤더와 함께 저장되어 학생수 산정 근거를 제공한다.';
COMMENT ON COLUMN student_guidance_students.achievement_id IS 'student_guidance_achievements.achievement_id 참조';

CREATE INDEX IF NOT EXISTS idx_student_guidance_achievements_lookup
    ON student_guidance_achievements (evaluation_year, employee_no, certification_status, occurred_date DESC)
    WHERE deleted_yn = 'N';
CREATE INDEX IF NOT EXISTS idx_student_guidance_students_achievement
    ON student_guidance_students (achievement_id, student_no);

WITH fixture_user AS (
    SELECT user_id FROM users WHERE login_id = 'admin'
), inserted AS (
    INSERT INTO student_guidance_achievements (
        achievement_number, employee_no, evaluation_year, management_item_code, occurred_date,
        guidance_start_date, guidance_end_date, student_count, student_detail_jsonb, achievement_detail,
        certification_status, deleted_yn, created_by, updated_by
    )
    SELECT achievement_number, 'E1001', '2026', 'EDU_STUDENT_GUIDANCE', occurred_date,
           guidance_start_date, guidance_end_date, student_count, student_detail_jsonb::jsonb, '{}'::jsonb,
           certification_status, 'N', fixture_user.user_id, fixture_user.user_id
    FROM fixture_user
    CROSS JOIN (VALUES
        ('B77-SG-001', DATE '2026-03-15', DATE '2026-03-01', DATE '2026-06-30', 2, '[{"studentNo":"S2026001","studentName":"김학생"},{"studentNo":"S2026002","studentName":"이학생"}]', 'DRAFT'),
        ('B77-SG-002', DATE '2026-04-01', DATE '2026-03-01', DATE '2026-06-30', 1, '[{"studentNo":"S2026003","studentName":"박학생"}]', 'SUBMITTED'),
        ('B77-SG-003', DATE '2025-12-31', DATE '2025-09-01', DATE '2025-12-31', 1, '[{"studentNo":"S2025001","studentName":"최학생"}]', 'EVALUATION_CONFIRMED')
    ) AS fixture(achievement_number, occurred_date, guidance_start_date, guidance_end_date, student_count, student_detail_jsonb, certification_status)
    ON CONFLICT (achievement_number) DO UPDATE SET
        occurred_date = EXCLUDED.occurred_date,
        guidance_start_date = EXCLUDED.guidance_start_date,
        guidance_end_date = EXCLUDED.guidance_end_date,
        student_count = EXCLUDED.student_count,
        student_detail_jsonb = EXCLUDED.student_detail_jsonb,
        certification_status = EXCLUDED.certification_status,
        updated_at = CURRENT_TIMESTAMP,
        updated_by = EXCLUDED.updated_by
    RETURNING achievement_id, achievement_number
)
INSERT INTO student_guidance_students (achievement_id, student_no, student_name, created_by)
SELECT inserted.achievement_id, student.student_no, student.student_name, fixture_user.user_id
FROM inserted
CROSS JOIN fixture_user
CROSS JOIN LATERAL (
    SELECT * FROM (VALUES
        ('B77-SG-001', 'S2026001', '김학생'),
        ('B77-SG-001', 'S2026002', '이학생'),
        ('B77-SG-002', 'S2026003', '박학생'),
        ('B77-SG-003', 'S2025001', '최학생')
    ) AS rows(achievement_number, student_no, student_name)
    WHERE rows.achievement_number = inserted.achievement_number
) AS student
ON CONFLICT (achievement_id, student_no) DO UPDATE SET student_name = EXCLUDED.student_name;

WITH fixture_user AS (
    SELECT user_id FROM users WHERE login_id = 'admin'
)
INSERT INTO excel_upload_templates (template_id, business_type, template_version, effective_date, created_by, updated_by, change_reason)
SELECT 'B77-STUDENT-GUIDANCE-V1', 'STUDENT_GUIDANCE', 'v1.0', DATE '2026-01-01', user_id, user_id, 'BASIC-77 학생지도 Excel 양식'
FROM fixture_user
ON CONFLICT (template_id) DO UPDATE SET template_version = EXCLUDED.template_version, effective_date = EXCLUDED.effective_date, updated_at = CURRENT_TIMESTAMP, updated_by = EXCLUDED.updated_by;

WITH fixture_user AS (
    SELECT user_id FROM users WHERE login_id = 'admin'
)
INSERT INTO excel_upload_template_rules (rule_id, template_id, required_column, column_order, code_rule_ref, created_by, updated_by)
SELECT rule_id, 'B77-STUDENT-GUIDANCE-V1', required_column, column_order, code_rule_ref, fixture_user.user_id, fixture_user.user_id
FROM fixture_user
CROSS JOIN (VALUES
    ('B77-SG-RULE-001', '관리번호', 1, 'STUDENT_GUIDANCE.MANAGEMENT_NO'),
    ('B77-SG-RULE-002', '지도시작일', 2, 'DATE.YYYY_MM_DD'),
    ('B77-SG-RULE-003', '지도종료일', 3, 'DATE.YYYY_MM_DD'),
    ('B77-SG-RULE-004', '학번', 4, 'KORUS.STUDENT_NO'),
    ('B77-SG-RULE-005', '학생명', 5, 'KORUS.STUDENT_NAME')
) AS rules(rule_id, required_column, column_order, code_rule_ref)
ON CONFLICT (rule_id) DO UPDATE SET required_column = EXCLUDED.required_column, column_order = EXCLUDED.column_order, code_rule_ref = EXCLUDED.code_rule_ref, updated_by = EXCLUDED.updated_by;
