CREATE TABLE IF NOT EXISTS degree_completion_achievements (
    achievement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluation_year varchar(4) NOT NULL,
    owner_user_id bigint NOT NULL REFERENCES users(user_id),
    organization_code varchar(50) NOT NULL REFERENCES organizations(organization_code),
    management_item_code varchar(100) NOT NULL,
    occurred_date date NOT NULL,
    achievement_detail jsonb NOT NULL DEFAULT '{}'::jsonb,
    certification_status varchar(50) NOT NULL DEFAULT 'DRAFTING',
    attachment_ref varchar(300),
    deleted_yn varchar(1) NOT NULL DEFAULT 'N',
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint NOT NULL REFERENCES users(user_id),
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint NOT NULL REFERENCES users(user_id),
    CONSTRAINT ck_degree_completion_achievements_year CHECK (evaluation_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_degree_completion_achievements_status CHECK (certification_status IN ('DRAFTING','SUBMITTED','DEPARTMENT_CONFIRMED','DEPARTMENT_REJECTED','CERTIFIED','CERTIFICATION_RETURNED','EVALUATION_CONFIRMED','DELETED')),
    CONSTRAINT ck_degree_completion_achievements_deleted CHECK (deleted_yn IN ('Y','N'))
);
COMMENT ON TABLE degree_completion_achievements IS 'FR-028 석·박사 배출 실적의 원천과 인증상태를 보존하는 업무 헤더 테이블.';
COMMENT ON COLUMN degree_completion_achievements.owner_user_id IS 'users.user_id 참조 의도 (석·박사 배출 실적 소유 교원)';
COMMENT ON COLUMN degree_completion_achievements.certification_status IS 'DRAFTING:작성중|SUBMITTED:제출|DEPARTMENT_CONFIRMED:학과장확인|DEPARTMENT_REJECTED:학과장미승인|CERTIFIED:인증|CERTIFICATION_RETURNED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN degree_completion_achievements.attachment_ref IS '기존 FileStoragePort 또는 첨부 서비스의 비공개 참조값';
COMMENT ON COLUMN degree_completion_achievements.deleted_yn IS 'Y:논리삭제|N:정상';
COMMENT ON COLUMN degree_completion_achievements.created_by IS 'users.user_id 참조 의도 (최초 입력자)';
COMMENT ON COLUMN degree_completion_achievements.updated_by IS 'users.user_id 참조 의도 (최종 수정자)';

CREATE TABLE IF NOT EXISTS degree_completion_students (
    degree_completion_student_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    achievement_id bigint NOT NULL REFERENCES degree_completion_achievements(achievement_id),
    degree_type varchar(20) NOT NULL,
    student_name varchar(100) NOT NULL,
    thesis_title varchar(500) NOT NULL,
    degree_awarded_date date NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint NOT NULL REFERENCES users(user_id),
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint NOT NULL REFERENCES users(user_id),
    CONSTRAINT ck_degree_completion_students_type CHECK (degree_type IN ('MASTER','DOCTORAL')),
    CONSTRAINT uq_degree_completion_students_identity UNIQUE (achievement_id, degree_type, student_name, thesis_title, degree_awarded_date)
);
COMMENT ON TABLE degree_completion_students IS '석·박사 배출 실적에 연결된 지도학생의 학위·논문·수여일 상세를 보존하는 업무 테이블.';
COMMENT ON COLUMN degree_completion_students.achievement_id IS 'degree_completion_achievements.achievement_id 참조 의도 (석·박사 배출 실적 헤더)';
COMMENT ON COLUMN degree_completion_students.degree_type IS 'MASTER:석사|DOCTORAL:박사';
COMMENT ON COLUMN degree_completion_students.created_by IS 'users.user_id 참조 의도 (최초 입력자)';
COMMENT ON COLUMN degree_completion_students.updated_by IS 'users.user_id 참조 의도 (최종 수정자)';

CREATE INDEX IF NOT EXISTS idx_degree_completion_achievements_list
    ON degree_completion_achievements(evaluation_year, owner_user_id, organization_code, certification_status, occurred_date DESC)
    WHERE deleted_yn = 'N';
CREATE INDEX IF NOT EXISTS idx_degree_completion_students_achievement
    ON degree_completion_students(achievement_id, degree_awarded_date DESC, degree_completion_student_id);

INSERT INTO degree_completion_achievements (evaluation_year, owner_user_id, organization_code, management_item_code, occurred_date, achievement_detail, certification_status, created_by, updated_by)
SELECT '2026', owner_user.user_id, owner_org.organization_code, fixture.management_item_code, fixture.occurred_date, fixture.detail::jsonb, fixture.certification_status, admin_user.user_id, admin_user.user_id
FROM (VALUES
    ('B77-DC-001', DATE '2026-02-20', '{"fixtureId":"B77-DC-001"}', 'DRAFTING'),
    ('B77-DC-002', DATE '2026-06-30', '{"fixtureId":"B77-DC-002"}', 'SUBMITTED'),
    ('B77-DC-003', DATE '2026-08-31', '{"fixtureId":"B77-DC-003"}', 'CERTIFIED')
) fixture(management_item_code, occurred_date, detail, certification_status)
CROSS JOIN LATERAL (SELECT user_id FROM users WHERE login_id = 'admin' LIMIT 1) admin_user
CROSS JOIN LATERAL (SELECT user_id FROM users WHERE login_id <> 'admin' ORDER BY user_id LIMIT 1) owner_user
CROSS JOIN LATERAL (SELECT organization_code FROM organization_user_mappings WHERE user_id = owner_user.user_id AND status = 'ACTIVE' ORDER BY effective_start_date DESC LIMIT 1) owner_org
WHERE NOT EXISTS (SELECT 1 FROM degree_completion_achievements existing WHERE existing.management_item_code = fixture.management_item_code AND existing.evaluation_year = '2026');

INSERT INTO degree_completion_students (achievement_id, degree_type, student_name, thesis_title, degree_awarded_date, created_by, updated_by)
SELECT achievement.achievement_id, fixture.degree_type, fixture.student_name, fixture.thesis_title, fixture.degree_awarded_date, achievement.created_by, achievement.updated_by
FROM degree_completion_achievements achievement
JOIN (VALUES
    ('B77-DC-001', 'MASTER', '석사 지도학생', '교육성과 분석', DATE '2026-02-20'),
    ('B77-DC-002', 'DOCTORAL', '박사 지도학생', '교수학습 연구', DATE '2026-06-30'),
    ('B77-DC-003', 'MASTER', '경계 지도학생', '교육과정 연구', DATE '2026-08-31')
) fixture(management_item_code, degree_type, student_name, thesis_title, degree_awarded_date)
    ON achievement.management_item_code = fixture.management_item_code AND achievement.evaluation_year = '2026'
ON CONFLICT (achievement_id, degree_type, student_name, thesis_title, degree_awarded_date) DO NOTHING;

INSERT INTO function_permissions (screen_id, role_code, function_type, permission_allowed, change_reason, created_by, updated_by)
SELECT 'SCR-MASTERS-DOCTORAL-GRADUATION-ACHIEVEMENT-MGMT', role_seed.role_code, function_seed.function_type, 'ALLOW', 'BASIC-79 석·박사 배출 실적 권한', 1, 1
FROM (VALUES ('R01'), ('R02'), ('R04')) AS role_seed(role_code)
CROSS JOIN (VALUES ('READ'), ('CREATE'), ('UPDATE'), ('DELETE')) AS function_seed(function_type)
ON CONFLICT (screen_id, role_code, function_type) DO NOTHING;
