CREATE TABLE IF NOT EXISTS student_guidance_achievements (
    achievement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    management_no varchar(100) NOT NULL,
    teacher_user_id bigint NOT NULL,
    evaluation_year varchar(4) NOT NULL,
    organization_code varchar(50) NOT NULL,
    management_item_code varchar(50) NOT NULL,
    guidance_start_date date NOT NULL,
    guidance_end_date date NOT NULL,
    attachment_ref varchar(300),
    certification_status varchar(50) NOT NULL DEFAULT 'DRAFT',
    deleted_yn char(1) NOT NULL DEFAULT 'N',
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    change_reason varchar(500),
    CONSTRAINT uq_student_guidance_achievements_management_no UNIQUE (management_no),
    CONSTRAINT ck_student_guidance_achievements_year CHECK (evaluation_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_student_guidance_achievements_dates CHECK (guidance_end_date >= guidance_start_date),
    CONSTRAINT ck_student_guidance_achievements_status CHECK (certification_status IN ('DRAFT', 'SUBMITTED', 'DEPARTMENT_CONFIRMED', 'DEPARTMENT_REJECTED', 'CERTIFIED', 'CERTIFICATION_REJECTED', 'EVALUATION_CONFIRMED', 'DELETED')),
    CONSTRAINT ck_student_guidance_achievements_deleted CHECK (deleted_yn IN ('Y', 'N')),
    CONSTRAINT fk_student_guidance_achievements_teacher FOREIGN KEY (teacher_user_id) REFERENCES users(user_id),
    CONSTRAINT fk_student_guidance_achievements_organization FOREIGN KEY (organization_code) REFERENCES organizations(organization_code),
    CONSTRAINT fk_student_guidance_achievements_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_student_guidance_achievements_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE student_guidance_achievements IS 'BASIC-79 학생지도 실적 header와 지도기간, 인증상태, 논리삭제 메타정보를 보존한다.';
COMMENT ON COLUMN student_guidance_achievements.teacher_user_id IS 'users.user_id 참조 의도 (실적 대상 교원)';
COMMENT ON COLUMN student_guidance_achievements.organization_code IS 'organizations.organization_code 참조 의도 (실적 대상 소속)';
COMMENT ON COLUMN student_guidance_achievements.attachment_ref IS 'FileStoragePort가 발급한 외부 비노출 첨부 참조값';
COMMENT ON COLUMN student_guidance_achievements.certification_status IS 'DRAFT:작성중|SUBMITTED:제출|DEPARTMENT_CONFIRMED:학과장확인|DEPARTMENT_REJECTED:학과장미승인|CERTIFIED:인증|CERTIFICATION_REJECTED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN student_guidance_achievements.deleted_yn IS 'Y:논리삭제|N:정상';
COMMENT ON COLUMN student_guidance_achievements.created_by IS 'users.user_id 참조 의도 (최초 입력자)';
COMMENT ON COLUMN student_guidance_achievements.updated_by IS 'users.user_id 참조 의도 (최종 수정자)';

CREATE TABLE IF NOT EXISTS student_guidance_students (
    guidance_student_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    achievement_id bigint NOT NULL,
    student_no varchar(50),
    student_name varchar(100) NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    CONSTRAINT uq_student_guidance_students_identity UNIQUE (achievement_id, student_no, student_name),
    CONSTRAINT fk_student_guidance_students_achievement FOREIGN KEY (achievement_id) REFERENCES student_guidance_achievements(achievement_id),
    CONSTRAINT fk_student_guidance_students_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_student_guidance_students_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE student_guidance_students IS '학생지도 실적별 지도학생을 header와 함께 영속화한다.';
COMMENT ON COLUMN student_guidance_students.achievement_id IS 'student_guidance_achievements.achievement_id 참조 의도';
COMMENT ON COLUMN student_guidance_students.created_by IS 'users.user_id 참조 의도 (최초 입력자)';
COMMENT ON COLUMN student_guidance_students.updated_by IS 'users.user_id 참조 의도 (최종 수정자)';

CREATE INDEX IF NOT EXISTS idx_student_guidance_achievements_search ON student_guidance_achievements (evaluation_year, organization_code, teacher_user_id, guidance_start_date DESC);
CREATE INDEX IF NOT EXISTS idx_student_guidance_students_achievement ON student_guidance_students (achievement_id);

INSERT INTO excel_upload_templates (template_id, business_type, template_version, effective_date, created_by, updated_by, change_reason)
SELECT 'B79-STUDENT-GUIDANCE-V1', 'STUDENT_GUIDANCE', 'v1.0', DATE '2026-01-01', user_id, user_id, 'BASIC-79 학생지도 Excel 양식'
FROM users WHERE login_id = 'admin'
ON CONFLICT (template_id) DO NOTHING;
INSERT INTO excel_upload_template_rules (rule_id, template_id, required_column, column_order, code_rule_ref, created_by, updated_by)
SELECT seed.rule_id, 'B79-STUDENT-GUIDANCE-V1', seed.required_column, seed.column_order, seed.code_rule_ref, users.user_id, users.user_id
FROM users CROSS JOIN (VALUES
    ('B79-SG-RULE-01', '교번', 1, 'users.employee_no'),
    ('B79-SG-RULE-02', '관리항목코드', 2, 'evaluation_management_items.management_item_code'),
    ('B79-SG-RULE-03', '지도시작일', 3, 'date'),
    ('B79-SG-RULE-04', '지도종료일', 4, 'date'),
    ('B79-SG-RULE-05', '학생명', 5, 'required')
) AS seed(rule_id, required_column, column_order, code_rule_ref)
WHERE users.login_id = 'admin'
ON CONFLICT (rule_id) DO NOTHING;
INSERT INTO student_guidance_achievements (achievement_id, management_no, teacher_user_id, evaluation_year, organization_code, management_item_code, guidance_start_date, guidance_end_date, certification_status, created_by, updated_by, change_reason)
SELECT seed.achievement_id, seed.management_no, professor.user_id, '2026', 'KNUE-DEPT-COMP', seed.management_item_code, seed.guidance_start_date, seed.guidance_end_date, seed.certification_status, admin.user_id, admin.user_id, 'B79-SG-001 정상 fixture'
FROM users professor JOIN users admin ON admin.login_id = 'admin'
CROSS JOIN (VALUES
    (793001::bigint, 'B79-SG-001-01', 'EDU-STUDENT-GUIDANCE', DATE '2026-04-01', DATE '2026-04-30', 'DRAFT'),
    (793002::bigint, 'B79-SG-001-02', 'EDU-STUDENT-GUIDANCE', DATE '2026-03-01', DATE '2026-03-31', 'SUBMITTED'),
    (793003::bigint, 'B79-SG-001-03', 'EDU-STUDENT-GUIDANCE', DATE '2026-02-01', DATE '2026-02-28', 'EVALUATION_CONFIRMED')
) AS seed(achievement_id, management_no, management_item_code, guidance_start_date, guidance_end_date, certification_status)
WHERE professor.login_id = 'professor1'
ON CONFLICT (achievement_id) DO NOTHING;
INSERT INTO student_guidance_students (achievement_id, student_no, student_name, created_by, updated_by)
SELECT seed.achievement_id, seed.student_no, seed.student_name, admin.user_id, admin.user_id
FROM users admin CROSS JOIN (VALUES
    (793001::bigint, 'S2026001', '학생가'), (793002::bigint, 'S2026002', '학생나'), (793003::bigint, 'S2026003', '학생다')
) AS seed(achievement_id, student_no, student_name)
WHERE admin.login_id = 'admin'
ON CONFLICT (achievement_id, student_no, student_name) DO NOTHING;
SELECT setval(pg_get_serial_sequence('student_guidance_achievements', 'achievement_id'), COALESCE((SELECT MAX(achievement_id) FROM student_guidance_achievements), 1), true);
