CREATE TABLE IF NOT EXISTS degree_completion_achievements (
    achievement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    management_no varchar(50) NOT NULL UNIQUE,
    evaluation_year varchar(4) NOT NULL,
    organization_code varchar(50) NOT NULL REFERENCES organizations(organization_code),
    teacher_user_id bigint NOT NULL REFERENCES users(user_id),
    management_item_code varchar(100) NOT NULL,
    achievement_date date NOT NULL,
    achievement_status varchar(30) NOT NULL DEFAULT 'DRAFTING',
    detail_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    attachment_count integer NOT NULL DEFAULT 0,
    occurrence_date_warning_yn varchar(1) NOT NULL DEFAULT 'N',
    deleted_at timestamp,
    deleted_by bigint REFERENCES users(user_id),
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint NOT NULL REFERENCES users(user_id),
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint NOT NULL REFERENCES users(user_id),
    change_reason varchar(500) NOT NULL,
    CONSTRAINT ck_degree_completion_achievements_year CHECK (evaluation_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_degree_completion_achievements_status CHECK (achievement_status IN ('DRAFTING','SUBMITTED','DEPARTMENT_CONFIRMED','DEPARTMENT_REJECTED','CERTIFIED','CERTIFICATION_RETURNED','EVALUATION_CONFIRMED','DELETED')),
    CONSTRAINT ck_degree_completion_achievements_attachment_count CHECK (attachment_count >= 0),
    CONSTRAINT ck_degree_completion_achievements_warning CHECK (occurrence_date_warning_yn IN ('Y','N'))
);
COMMENT ON TABLE degree_completion_achievements IS '교육영역 석·박사 배출 실적의 헤더, 인증상태 및 논리삭제 정보를 보존한다.';
COMMENT ON COLUMN degree_completion_achievements.management_item_code IS 'evaluation_element_management_item_settings의 활성 관리항목 코드 참조 의도 (FK 미선언)';
COMMENT ON COLUMN degree_completion_achievements.achievement_status IS 'DRAFTING:작성중|SUBMITTED:제출|DEPARTMENT_CONFIRMED:학과장확인|DEPARTMENT_REJECTED:학과장미승인|CERTIFIED:인증|CERTIFICATION_RETURNED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN degree_completion_achievements.detail_payload IS 'FR-018 활성 관리항목 설정에 따라 애플리케이션이 검증·저장하는 유형별 상세값';
COMMENT ON COLUMN degree_completion_achievements.occurrence_date_warning_yn IS 'Y:평가대상 기간 밖 발생일 경고|N:경고없음';
COMMENT ON COLUMN degree_completion_achievements.deleted_by IS 'users.user_id 참조 의도 (논리삭제 처리자)';

CREATE TABLE IF NOT EXISTS degree_completion_students (
    degree_completion_student_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    achievement_id bigint NOT NULL REFERENCES degree_completion_achievements(achievement_id),
    degree_type varchar(20) NOT NULL,
    student_name varchar(100) NOT NULL,
    thesis_title varchar(500) NOT NULL,
    degree_awarded_date date NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint NOT NULL REFERENCES users(user_id),
    CONSTRAINT ck_degree_completion_students_type CHECK (degree_type IN ('MASTER','DOCTOR')),
    CONSTRAINT uq_degree_completion_students_award UNIQUE (achievement_id, student_name, degree_type, degree_awarded_date)
);
COMMENT ON TABLE degree_completion_students IS '석·박사 배출 실적에 연결된 지도학생의 학위·논문·학위수여일 상세를 보존한다.';
COMMENT ON COLUMN degree_completion_students.achievement_id IS 'degree_completion_achievements.achievement_id 참조';
COMMENT ON COLUMN degree_completion_students.degree_type IS 'MASTER:석사|DOCTOR:박사';

CREATE INDEX IF NOT EXISTS idx_degree_completion_achievements_list
    ON degree_completion_achievements (evaluation_year, organization_code, teacher_user_id, achievement_status, achievement_date DESC)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_degree_completion_students_achievement
    ON degree_completion_students (achievement_id, degree_awarded_date DESC);

INSERT INTO degree_completion_achievements (
    management_no, evaluation_year, organization_code, teacher_user_id, management_item_code,
    achievement_date, achievement_status, detail_payload, attachment_count, occurrence_date_warning_yn,
    created_by, updated_by, change_reason
)
SELECT seed.management_no, seed.evaluation_year, 'KNUE-DEPT-COMP', u.user_id, 'DEGREE_COMPLETION',
       seed.achievement_date, seed.achievement_status, seed.detail_payload::jsonb, seed.attachment_count,
       seed.occurrence_date_warning_yn, u.user_id, u.user_id, seed.change_reason
FROM users u
CROSS JOIN (VALUES
    ('B77-DC-001', '2026', DATE '2026-02-20', 'DRAFTING', '{"graduationSemester":"2026-1"}', 0, 'N', 'BASIC-81 정상 석박사 배출 fixture'),
    ('B77-DC-002', '2026', DATE '2026-01-15', 'SUBMITTED', '{"graduationSemester":"2025-2"}', 1, 'Y', 'BASIC-81 발생일 경계 석박사 배출 fixture'),
    ('B77-DC-003', '2025', DATE '2025-08-20', 'EVALUATION_CONFIRMED', '{"graduationSemester":"2025-1"}', 2, 'N', 'BASIC-81 평가확정 석박사 배출 fixture')
) AS seed(management_no, evaluation_year, achievement_date, achievement_status, detail_payload, attachment_count, occurrence_date_warning_yn, change_reason)
WHERE u.login_id = 'professor1'
ON CONFLICT (management_no) DO NOTHING;

INSERT INTO degree_completion_students (achievement_id, degree_type, student_name, thesis_title, degree_awarded_date, created_by)
SELECT a.achievement_id, seed.degree_type, seed.student_name, seed.thesis_title, seed.degree_awarded_date, a.created_by
FROM degree_completion_achievements a
JOIN (VALUES
    ('B77-DC-001', 'MASTER', '김석사', '교육평가 개선 연구', DATE '2026-02-20'),
    ('B77-DC-002', 'DOCTOR', '이박사', '교수학습 모형 연구', DATE '2026-01-15'),
    ('B77-DC-003', 'MASTER', '박졸업', '교육과정 개발 연구', DATE '2025-08-20')
) AS seed(management_no, degree_type, student_name, thesis_title, degree_awarded_date)
ON a.management_no = seed.management_no
ON CONFLICT (achievement_id, student_name, degree_type, degree_awarded_date) DO NOTHING;

INSERT INTO education_achievement_status_histories (
    achievement_type, achievement_id, previous_status, next_status, transition_reason, processed_by, request_id
)
SELECT 'DEGREE_COMPLETION', achievement_id,
       CASE achievement_status WHEN 'EVALUATION_CONFIRMED' THEN 'CERTIFIED' ELSE 'DRAFTING' END,
       achievement_status, change_reason, created_by, 'BASIC-81-DEGREE-SEED'
FROM degree_completion_achievements
WHERE management_no IN ('B77-DC-001', 'B77-DC-002', 'B77-DC-003')
  AND achievement_status <> 'DRAFTING'
  AND NOT EXISTS (
      SELECT 1 FROM education_achievement_status_histories history
      WHERE history.achievement_type = 'DEGREE_COMPLETION'
        AND history.achievement_id = degree_completion_achievements.achievement_id
        AND history.request_id = 'BASIC-81-DEGREE-SEED'
  );
