-- 통합 교육실적 원천. 기존 네 교육실적 원장과 이력은 변경하지 않는다.
CREATE TABLE IF NOT EXISTS education_achievements (
    achievement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    achievement_type varchar(50) NOT NULL,
    management_no varchar(50) NOT NULL UNIQUE,
    teacher_user_id bigint NOT NULL REFERENCES users(user_id),
    organization_code varchar(50) NOT NULL REFERENCES organizations(organization_code),
    evaluation_year varchar(4) NOT NULL CHECK (evaluation_year ~ '^[0-9]{4}$'),
    management_item_code varchar(50) NOT NULL CHECK (btrim(management_item_code) <> ''),
    achievement_date date NOT NULL,
    achievement_status varchar(30) NOT NULL DEFAULT 'DRAFT',
    deleted_yn char(1) NOT NULL DEFAULT 'N' CHECK (deleted_yn IN ('Y', 'N')),
    attachment_ref text NOT NULL DEFAULT '[]',
    achievement_detail text NOT NULL DEFAULT '{}',
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint REFERENCES users(user_id),
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint REFERENCES users(user_id),
    CONSTRAINT ck_education_achievements_type CHECK (
        achievement_type IN (
            'EMPLOYMENT_RATE_IMPROVEMENT', 'COURSE_OPERATION',
            'LECTURE_IMPROVEMENT', 'EMPLOYMENT_RATE_ACHIEVEMENT'
        )
    ),
    CONSTRAINT ck_education_achievements_status CHECK (
        achievement_status IN (
            'DRAFT', 'SUBMITTED', 'DEPARTMENT_CONFIRMED', 'DEPARTMENT_REJECTED',
            'CERTIFIED', 'CERTIFICATION_REJECTED', 'EVALUATION_CONFIRMED', 'DELETED'
        )
    ),
    CONSTRAINT ck_education_achievements_attachments CHECK (jsonb_typeof(attachment_ref::jsonb) = 'array'),
    CONSTRAINT ck_education_achievements_detail CHECK (jsonb_typeof(achievement_detail::jsonb) = 'object')
);
COMMENT ON TABLE education_achievements IS '교육영역 후반 네 업무의 공통 실적 원천. 교원·조직·평가년도와 상태 및 첨부 참조를 보존한다.';
COMMENT ON COLUMN education_achievements.management_item_code IS
    'evaluation_management_items.management_item_code 참조 의도 (요소별 코드이므로 단독 FK 미선언)';
COMMENT ON COLUMN education_achievements.attachment_ref IS '검증된 attachmentIds 배열의 JSON 직렬화. 파일 경로가 아닌 opaque 참조만 저장';
COMMENT ON COLUMN education_achievements.achievement_detail IS '동적 입력값 JSON 객체. 취업률 achievementName은 동일 키로 보존';

CREATE INDEX IF NOT EXISTS idx_education_achievements_owner_search
    ON education_achievements (teacher_user_id, evaluation_year, achievement_type, achievement_date DESC)
    WHERE deleted_yn = 'N';
CREATE INDEX IF NOT EXISTS idx_education_achievements_scope_search
    ON education_achievements (organization_code, evaluation_year, achievement_type, achievement_status)
    WHERE deleted_yn = 'N';
-- 승인 전 안전한 취업률 중복 판별. 다른 세 업무에 같은 발생일의 반복실적 제한을 전파하지 않는다.
CREATE UNIQUE INDEX IF NOT EXISTS uq_education_achievements_employment_identity
    ON education_achievements (
        teacher_user_id, evaluation_year, management_item_code, achievement_date, achievement_type
    )
    WHERE deleted_yn = 'N' AND achievement_type = 'EMPLOYMENT_RATE_ACHIEVEMENT';

CREATE TABLE IF NOT EXISTS employment_rate_improvement_achievement_details (
    achievement_id bigint PRIMARY KEY REFERENCES education_achievements(achievement_id),
    special_lecture_start_date date,
    special_lecture_end_date date,
    mock_exam_question_period text,
    CONSTRAINT ck_employment_improvement_lecture_period CHECK (
        special_lecture_end_date >= special_lecture_start_date
    )
);
COMMENT ON TABLE employment_rate_improvement_achievement_details IS
    '취업률 제고 실적의 특강기간 및 모의시험 출제기간 상세. 공통 실적과 동일 트랜잭션으로 저장한다.';

CREATE TABLE IF NOT EXISTS course_operation_achievement_details (
    achievement_id bigint PRIMARY KEY REFERENCES education_achievements(achievement_id),
    performance_detail text NOT NULL CHECK (btrim(performance_detail) <> '')
);
COMMENT ON TABLE course_operation_achievement_details IS '강좌 개설·운영 실적내역. 승인 API performanceDetails를 보존한다.';

CREATE TABLE IF NOT EXISTS lecture_improvement_achievement_details (
    achievement_id bigint PRIMARY KEY REFERENCES education_achievements(achievement_id),
    performance_content text NOT NULL CHECK (btrim(performance_content) <> ''),
    academic_year integer NOT NULL CHECK (academic_year >= 2000),
    semester_code varchar(1) NOT NULL CHECK (semester_code IN ('1', '2'))
);
COMMENT ON TABLE lecture_improvement_achievement_details IS '강의개선 실적내용과 학년도·학기 상세. 학년도는 공통 평가년도와 독립적으로 보존한다.';
COMMENT ON COLUMN lecture_improvement_achievement_details.semester_code IS '1:1학기|2:2학기';

CREATE TABLE IF NOT EXISTS employment_rate_batch_jobs (
    batch_job_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluation_year varchar(4) NOT NULL CHECK (evaluation_year ~ '^[0-9]{4}$'),
    organization_code varchar(50) NOT NULL REFERENCES organizations(organization_code),
    target_condition_json text NOT NULL DEFAULT '{}',
    action_type varchar(20) NOT NULL CHECK (action_type IN ('GENERATE', 'DELETE')),
    job_status varchar(30) NOT NULL DEFAULT 'REQUESTED'
        CHECK (job_status IN ('REQUESTED', 'PROCESSING', 'COMPLETED', 'FAILED')),
    total_count integer NOT NULL DEFAULT 0 CHECK (total_count >= 0),
    processed_count integer NOT NULL DEFAULT 0 CHECK (processed_count >= 0),
    unprocessed_count integer NOT NULL DEFAULT 0 CHECK (unprocessed_count >= 0),
    request_id varchar(100) NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint NOT NULL REFERENCES users(user_id),
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint REFERENCES users(user_id),
    CONSTRAINT ck_employment_batch_condition CHECK (jsonb_typeof(target_condition_json::jsonb) = 'object'),
    CONSTRAINT ck_employment_batch_counts CHECK (processed_count + unprocessed_count <= total_count)
);
COMMENT ON TABLE employment_rate_batch_jobs IS
    '취업률 일괄 작업의 실행자·범위·결과 보존. 현재 신규 실행 정책 미승인으로 실행 차단; 시드는 결과조회 검증용이다.';
COMMENT ON COLUMN employment_rate_batch_jobs.total_count IS '일괄 서비스가 검증 완료 및 결과 확정 시 갱신하는 대상 건수';
COMMENT ON COLUMN employment_rate_batch_jobs.processed_count IS '일괄 서비스가 결과 확정 시 갱신하는 처리 건수';
COMMENT ON COLUMN employment_rate_batch_jobs.unprocessed_count IS '일괄 서비스가 결과 확정 시 갱신하는 미처리 건수';
CREATE INDEX IF NOT EXISTS idx_employment_rate_batch_jobs_scope
    ON employment_rate_batch_jobs (created_by, organization_code, evaluation_year, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uq_employment_rate_batch_jobs_request
    ON employment_rate_batch_jobs (request_id);

CREATE TABLE IF NOT EXISTS employment_rate_batch_job_items (
    batch_job_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_job_id bigint NOT NULL REFERENCES employment_rate_batch_jobs(batch_job_id),
    target_user_id bigint NOT NULL REFERENCES users(user_id),
    processed_yn char(1) NOT NULL DEFAULT 'N' CHECK (processed_yn IN ('Y', 'N')),
    unprocessed_reason text,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint REFERENCES users(user_id),
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint REFERENCES users(user_id),
    CONSTRAINT uq_employment_batch_target UNIQUE (batch_job_id, target_user_id)
);
COMMENT ON TABLE employment_rate_batch_job_items IS '취업률 일괄 작업의 대상 교원별 처리 여부와 미처리 사유. 현재 결과조회 시드만 제공하고 실행 정책은 미승인이다.';

ALTER TABLE education_achievement_status_histories
    ALTER COLUMN achievement_type TYPE varchar(50);
ALTER TABLE education_achievement_status_histories
    ADD COLUMN IF NOT EXISTS request_id varchar(100);
ALTER TABLE education_achievement_status_histories
    DROP CONSTRAINT ck_education_achievement_status_histories_type;
ALTER TABLE education_achievement_status_histories
    ADD CONSTRAINT ck_education_achievement_status_histories_type CHECK (
        achievement_type IN (
            'LECTURE_EVALUATION', 'LECTURE', 'STUDENT_GUIDANCE', 'DEGREE_COMPLETION',
            'EMPLOYMENT_RATE_IMPROVEMENT', 'COURSE_OPERATION',
            'LECTURE_IMPROVEMENT', 'EMPLOYMENT_RATE_ACHIEVEMENT'
        )
    );
COMMENT ON COLUMN education_achievement_status_histories.request_id IS '상태 변경 서비스가 감사와 동일 요청 식별자로 저장';
