-- 교육영역 후반 실적은 별도 header를 사용하며 기존 교육 실적 원장은 이관하지 않는다.
CREATE TABLE IF NOT EXISTS education_achievements (
    achievement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    achievement_type varchar(30) NOT NULL,
    management_no varchar(100) NOT NULL DEFAULT ('EDU-' || gen_random_uuid()::text),
    teacher_user_id bigint NOT NULL REFERENCES users(user_id),
    organization_code varchar(50) NOT NULL REFERENCES organizations(organization_code),
    evaluation_year varchar(4) NOT NULL,
    management_item_code varchar(50) NOT NULL,
    achievement_date date NOT NULL,
    achievement_name text NOT NULL DEFAULT '',
    achievement_detail jsonb NOT NULL DEFAULT '{}'::jsonb,
    achievement_status varchar(30) NOT NULL DEFAULT 'DRAFT',
    deleted_yn char(1) NOT NULL DEFAULT 'N',
    attachment_ref varchar(300),
    request_id varchar(100),
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint REFERENCES users(user_id),
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint REFERENCES users(user_id),
    CONSTRAINT uq_education_achievements_management_no UNIQUE (management_no),
    CONSTRAINT uq_education_achievements_id_type UNIQUE (achievement_id, achievement_type),
    CONSTRAINT ck_education_achievements_type CHECK (
        achievement_type IN (
            'EMPLOYMENT_RATE_IMPROVEMENT', 'COURSE_OPERATION',
            'LECTURE_IMPROVEMENT', 'EMPLOYMENT_RATE_ACHIEVEMENT'
        )
    ),
    CONSTRAINT ck_education_achievements_year CHECK (evaluation_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_education_achievements_item CHECK (btrim(management_item_code) <> ''),
    CONSTRAINT ck_education_achievements_status CHECK (
        achievement_status IN (
            'DRAFT', 'SUBMITTED', 'DEPARTMENT_CONFIRMED', 'DEPARTMENT_REJECTED',
            'CERTIFIED', 'CERTIFICATION_REJECTED', 'EVALUATION_CONFIRMED', 'DELETED'
        )
    ),
    CONSTRAINT ck_education_achievements_deleted CHECK (deleted_yn IN ('Y', 'N')),
    CONSTRAINT ck_education_achievements_delete_state CHECK (
        (deleted_yn = 'Y') = (achievement_status = 'DELETED')
    )
);
COMMENT ON TABLE education_achievements IS '교육영역 취업률 제고·강좌 운영·강의개선·취업률 실적 공통 원장. 기존 교육실적 원장과 독립적으로 상태와 논리삭제를 보존한다.';
COMMENT ON COLUMN education_achievements.achievement_type IS
    'EMPLOYMENT_RATE_IMPROVEMENT:취업률제고|COURSE_OPERATION:강좌운영|LECTURE_IMPROVEMENT:강의개선|EMPLOYMENT_RATE_ACHIEVEMENT:취업률';
COMMENT ON COLUMN education_achievements.achievement_status IS
    'DRAFT:작성중|SUBMITTED:제출|DEPARTMENT_CONFIRMED:학과장확인|DEPARTMENT_REJECTED:학과장미승인|CERTIFIED:인증|CERTIFICATION_REJECTED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN education_achievements.deleted_yn IS 'Y:삭제|N:정상';
COMMENT ON COLUMN education_achievements.management_item_code IS
    'evaluation_element_management_item_settings.management_item_code 참조 의도 (평가연도·범위별 복합 설정, FK 미선언)';
COMMENT ON COLUMN education_achievements.achievement_name IS '실적명. 저장 서비스가 JSON 대표 실적명과 함께 저장하며 Excel 중복키에 사용한다.';
COMMENT ON COLUMN education_achievements.achievement_detail IS 'DB 관리항목 설정에서 허용한 교원 입력 필드의 JSON 원문';
COMMENT ON COLUMN education_achievements.attachment_ref IS '공통 파일 저장 서비스의 비노출 첨부 참조값';
COMMENT ON COLUMN education_achievements.request_id IS '등록·수정 서비스가 해당 요청의 동일 추적 식별자로 갱신';

-- 활성 원장의 자연키로 동시 Excel commit 중복을 차단한다. 삭제 이력은 재등록과 별개로 보존한다.
CREATE UNIQUE INDEX IF NOT EXISTS uq_education_achievements_active_identity
    ON education_achievements (
        achievement_type, teacher_user_id, management_item_code, achievement_date, achievement_name
    )
    WHERE deleted_yn = 'N';
CREATE INDEX IF NOT EXISTS idx_education_achievements_teacher_search
    ON education_achievements (teacher_user_id, achievement_type, evaluation_year, achievement_date DESC, achievement_id)
    WHERE deleted_yn = 'N';
CREATE INDEX IF NOT EXISTS idx_education_achievements_org_search
    ON education_achievements (organization_code, achievement_type, evaluation_year, achievement_status, achievement_id)
    WHERE deleted_yn = 'N';

CREATE TABLE IF NOT EXISTS employment_rate_improvement_achievement_details (
    achievement_id bigint PRIMARY KEY,
    achievement_type varchar(30) NOT NULL DEFAULT 'EMPLOYMENT_RATE_IMPROVEMENT',
    special_lecture_start_date date,
    special_lecture_end_date date,
    mock_exam_question_period text,
    CONSTRAINT ck_employment_rate_improvement_dates CHECK (
        special_lecture_end_date >= special_lecture_start_date
    ),
    CHECK (achievement_type = 'EMPLOYMENT_RATE_IMPROVEMENT'),
    FOREIGN KEY (achievement_id, achievement_type)
        REFERENCES education_achievements(achievement_id, achievement_type)
);
COMMENT ON TABLE employment_rate_improvement_achievement_details IS '취업률 제고 실적의 특강 기간과 모의고사 출제기간을 저장한다.';

CREATE TABLE IF NOT EXISTS course_operation_achievement_details (
    achievement_id bigint PRIMARY KEY,
    achievement_type varchar(30) NOT NULL DEFAULT 'COURSE_OPERATION',
    performance_detail text NOT NULL,
    CONSTRAINT ck_course_operation_performance CHECK (btrim(performance_detail) <> ''),
    CHECK (achievement_type = 'COURSE_OPERATION'),
    FOREIGN KEY (achievement_id, achievement_type)
        REFERENCES education_achievements(achievement_id, achievement_type)
);
COMMENT ON TABLE course_operation_achievement_details IS '강좌 개설·운영 실적의 실적내역을 공통 원장과 일대일로 저장한다.';

CREATE TABLE IF NOT EXISTS lecture_improvement_achievement_details (
    achievement_id bigint PRIMARY KEY,
    achievement_type varchar(30) NOT NULL DEFAULT 'LECTURE_IMPROVEMENT',
    performance_content text,
    academic_year varchar(4),
    semester_code varchar(50),
    CONSTRAINT ck_lecture_improvement_academic_year CHECK (academic_year ~ '^[0-9]{4}$'),
    CHECK (achievement_type = 'LECTURE_IMPROVEMENT'),
    FOREIGN KEY (achievement_id, achievement_type)
        REFERENCES education_achievements(achievement_id, achievement_type)
);
COMMENT ON TABLE lecture_improvement_achievement_details IS '강의개선 실적의 학년도·학기와 실적내용을 보존한다. 학기 선택값은 기존 DB 코드 설정으로 검증한다.';

COMMENT ON COLUMN lecture_improvement_achievement_details.semester_code IS
    'detail_codes.code_value 참조 의도 (학기 그룹 미확정, FK 미선언). 코드 설정 없는 과거 fixture는 NULL로 보존';
COMMENT ON COLUMN employment_rate_improvement_achievement_details.mock_exam_question_period IS
    '출제기간 원문 문자열. 승인되지 않은 날짜 범위 형식으로 분해하지 않는다';

CREATE TABLE IF NOT EXISTS employment_rate_batch_jobs (
    batch_job_id varchar(100) PRIMARY KEY,
    evaluation_year varchar(4) NOT NULL CHECK (evaluation_year ~ '^[0-9]{4}$'),
    target_condition_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    action_type varchar(20) NOT NULL CHECK (action_type IN ('GENERATE', 'DELETE')),
    requester_user_id bigint NOT NULL REFERENCES users(user_id),
    job_status varchar(20) NOT NULL DEFAULT 'COMPLETED',
    total_count integer NOT NULL DEFAULT 0 CHECK (total_count >= 0),
    processed_count integer NOT NULL DEFAULT 0 CHECK (processed_count >= 0),
    unprocessed_count integer NOT NULL DEFAULT 0 CHECK (unprocessed_count >= 0),
    request_id varchar(100),
    started_at timestamp,
    completed_at timestamp,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint REFERENCES users(user_id),
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint REFERENCES users(user_id),
    CONSTRAINT ck_employment_rate_batch_job_counts CHECK (total_count = processed_count + unprocessed_count),
    CONSTRAINT ck_employment_rate_batch_job_times CHECK (completed_at >= started_at),
    CONSTRAINT ck_employment_rate_batch_job_status CHECK (
        job_status IN ('WAITING', 'RUNNING', 'COMPLETED', 'FAILED')
    )
);
COMMENT ON TABLE employment_rate_batch_jobs IS '취업률 실적 일괄 작업의 요청자와 처리건수 결과를 보존한다. 현재 실행 정책 미승인으로 신규 실행은 거부하며 보존 결과만 조회한다.';
COMMENT ON COLUMN employment_rate_batch_jobs.action_type IS 'GENERATE:생성|DELETE:삭제';
COMMENT ON COLUMN employment_rate_batch_jobs.job_status IS 'WAITING:대기|RUNNING:실행중|COMPLETED:완료|FAILED:실패';
COMMENT ON COLUMN employment_rate_batch_jobs.total_count IS '일괄 서비스가 승인된 작업 완료 시 대상 결과에서 집계하여 갱신';
COMMENT ON COLUMN employment_rate_batch_jobs.processed_count IS '일괄 서비스가 승인된 작업 완료 시 processed_yn=Y 결과에서 집계하여 갱신';
COMMENT ON COLUMN employment_rate_batch_jobs.unprocessed_count IS '일괄 서비스가 승인된 작업 완료 시 processed_yn=N 결과에서 집계하여 갱신';
COMMENT ON COLUMN employment_rate_batch_jobs.request_id IS '작업 접수 서비스가 최초 요청의 추적 식별자로 기록';
CREATE INDEX IF NOT EXISTS idx_employment_rate_batch_jobs_requester
    ON employment_rate_batch_jobs (requester_user_id, created_at DESC, batch_job_id);

CREATE TABLE IF NOT EXISTS employment_rate_batch_job_items (
    batch_job_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_job_id varchar(100) NOT NULL REFERENCES employment_rate_batch_jobs(batch_job_id),
    target_user_id bigint NOT NULL REFERENCES users(user_id),
    processed_yn char(1) NOT NULL CHECK (processed_yn IN ('Y', 'N')),
    unprocessed_reason text,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_employment_rate_batch_job_target UNIQUE (batch_job_id, target_user_id),
    CONSTRAINT ck_employment_rate_batch_job_reason CHECK (
        (processed_yn = 'Y' AND unprocessed_reason IS NULL)
        OR (processed_yn = 'N' AND NULLIF(btrim(unprocessed_reason), '') IS NOT NULL)
    )
);
COMMENT ON TABLE employment_rate_batch_job_items IS '취업률 일괄 작업의 대상 교원별 처리 여부와 미처리 사유를 보존한다. 현재는 보존 결과 조회용이며 실행 정책을 정의하지 않는다.';
COMMENT ON COLUMN employment_rate_batch_job_items.processed_yn IS 'Y:처리|N:미처리';

ALTER TABLE education_achievement_status_histories
    DROP CONSTRAINT ck_education_achievement_status_histories_type;
ALTER TABLE education_achievement_status_histories
    ADD CONSTRAINT ck_education_achievement_status_histories_type CHECK (
        achievement_type IN (
            'LECTURE_EVALUATION', 'LECTURE', 'STUDENT_GUIDANCE', 'DEGREE_COMPLETION',
            'EMPLOYMENT_RATE_IMPROVEMENT', 'COURSE_OPERATION',
            'LECTURE_IMPROVEMENT', 'EMPLOYMENT_RATE_ACHIEVEMENT'
        )
    );
ALTER TABLE education_achievement_status_histories
    ADD COLUMN IF NOT EXISTS request_id varchar(100);
COMMENT ON COLUMN education_achievement_status_histories.achievement_type IS
    'LECTURE_EVALUATION:강의평가|LECTURE:강의실적|STUDENT_GUIDANCE:학생지도|DEGREE_COMPLETION:석박사배출|EMPLOYMENT_RATE_IMPROVEMENT:취업률제고|COURSE_OPERATION:강좌운영|LECTURE_IMPROVEMENT:강의개선|EMPLOYMENT_RATE_ACHIEVEMENT:취업률';
COMMENT ON COLUMN education_achievement_status_histories.request_id IS '호출 서비스가 원장 변경과 같은 트랜잭션에서 동일 요청 식별자로 기록';

-- 기존 교수의 실제 학과 범위를 사용한다. 단과대학 period를 학과 period로 오인하지 않는다.
-- 기존 기간은 수정하지 않고 부재한 학과 입력기간만 추가한다.
INSERT INTO input_period_settings (
    evaluation_year, area_code, organization_code, user_type_code,
    start_at, end_at, base_date, active_yn, created_by, updated_by, change_reason
)
SELECT
    source.evaluation_year,
    source.area_code,
    organization.organization_code,
    source.user_type_code,
    to_date(source.evaluation_year || '-01-01', 'YYYY-MM-DD')::timestamp,
    to_date(source.evaluation_year || '-12-31', 'YYYY-MM-DD')::timestamp + INTERVAL '1 day - 1 second',
    to_date(source.evaluation_year || '-01-01', 'YYYY-MM-DD'),
    'Y',
    actor.user_id,
    actor.user_id,
    '교육영역 후반 실적의 기존 학과 교원 입력 검증 fixture'
FROM input_period_settings source
JOIN organizations organization
    ON organization.organization_code = 'KNUE-DEPT-COMP'
JOIN users actor
    ON actor.login_id = 'admin'
WHERE source.setting_id = 1
  AND NOT EXISTS (
      SELECT 1
      FROM input_period_settings existing
      WHERE existing.evaluation_year = source.evaluation_year
        AND existing.area_code = source.area_code
        AND existing.organization_code = organization.organization_code
        AND existing.active_yn = 'Y'
  );

-- 이미 존재하는 규정버전·평가요소·입력기간의 연도와 학과를 재사용한다.
INSERT INTO evaluation_element_management_item_settings (
    rule_version_id, target_scope, area_code, item_code, evaluation_year, element_code,
    management_item_code, management_item_name, sort_order, active_yn, teacher_editable_yn,
    teacher_editable_part, effective_start_date, effective_end_date, evaluation_confirmed_yn,
    change_reason, created_by, updated_by
)
SELECT
    source.rule_version_id,
    period.organization_code,
    period.area_code,
    seed.achievement_type,
    period.evaluation_year,
    source.element_code,
    seed.achievement_type,
    seed.item_name,
    seed.sort_order,
    'Y',
    'Y',
    source.teacher_editable_part,
    period.start_at::date,
    period.end_at::date,
    'N',
    '교육영역 후반 실적 교원 입력 관리항목 fixture',
    actor.user_id,
    actor.user_id
FROM evaluation_element_management_item_settings source
JOIN input_period_settings period
    ON period.organization_code = 'KNUE-DEPT-COMP'
    AND period.area_code = 'EDUCATION'
    AND period.evaluation_year = source.evaluation_year
    AND period.active_yn = 'Y'
JOIN users actor
    ON actor.login_id = 'admin'
CROSS JOIN (
    VALUES
        ('EMPLOYMENT_RATE_IMPROVEMENT', '취업률 제고', 101),
        ('COURSE_OPERATION', '강좌 개설·운영', 102),
        ('LECTURE_IMPROVEMENT', '강의개선', 103),
        ('EMPLOYMENT_RATE_ACHIEVEMENT', '취업률', 104)
) AS seed(achievement_type, item_name, sort_order)
WHERE source.management_item_code = 'ATTENDANCE'
  AND source.active_yn = 'Y'
  AND source.teacher_editable_yn = 'Y'
ON CONFLICT (
    rule_version_id, target_scope, area_code, item_code,
    evaluation_year, element_code, management_item_code
) DO NOTHING;

INSERT INTO education_achievements (
    achievement_type, management_no, teacher_user_id, organization_code,
    evaluation_year, management_item_code, achievement_date, achievement_name,
    achievement_detail, achievement_status, created_by, updated_by, request_id
)
SELECT
    kind.achievement_type,
    'EDU-SEED-' || kind.achievement_type || '-' || seed.case_no,
    teacher.user_id,
    mapping.organization_code,
    period.evaluation_year,
    kind.achievement_type,
    seed.achievement_date,
    seed.achievement_name,
    jsonb_build_object('achievementName', seed.achievement_name),
    seed.achievement_status,
    teacher.user_id,
    teacher.user_id,
    'education-seed-' || seed.case_no
FROM (
    VALUES
        ('EMPLOYMENT_RATE_IMPROVEMENT'), ('COURSE_OPERATION'),
        ('LECTURE_IMPROVEMENT'), ('EMPLOYMENT_RATE_ACHIEVEMENT')
) AS kind(achievement_type)
CROSS JOIN (
    VALUES
        (1, 'professor1', DATE '2026-04-10', '정상 입력 실적', 'DRAFT'),
        (2, 'professor2', DATE '2025-12-31', '평가대상 기간 경계 실적', 'SUBMITTED'),
        (3, 'professor1', DATE '2026-04-12', '평가확정 잠금 실적', 'EVALUATION_CONFIRMED')
) AS seed(case_no, login_id, achievement_date, achievement_name, achievement_status)
JOIN users teacher
    ON teacher.login_id = seed.login_id
JOIN organization_user_mappings mapping
    ON mapping.user_id = teacher.user_id
    AND mapping.mapping_type = 'ORGANIZATION'
    AND mapping.status = 'ACTIVE'
    AND mapping.organization_code = 'KNUE-DEPT-COMP'
JOIN input_period_settings period
    ON period.organization_code = mapping.organization_code
    AND period.evaluation_year = '2026'
    AND period.area_code = 'EDUCATION'
    AND period.active_yn = 'Y'
ON CONFLICT (management_no) DO NOTHING;

INSERT INTO employment_rate_improvement_achievement_details (
    achievement_id, special_lecture_start_date, special_lecture_end_date, mock_exam_question_period
)
SELECT
    a.achievement_id,
    a.achievement_date,
    a.achievement_date + 7,
    '출제기간 원문 예시'
FROM education_achievements a
WHERE a.achievement_type = 'EMPLOYMENT_RATE_IMPROVEMENT'
  AND a.management_no LIKE 'EDU-SEED-%'
ON CONFLICT (achievement_id) DO NOTHING;

INSERT INTO course_operation_achievement_details (achievement_id, performance_detail)
SELECT
    a.achievement_id,
    a.achievement_name || ' 강좌 운영 내역'
FROM education_achievements a
WHERE a.achievement_type = 'COURSE_OPERATION'
  AND a.management_no LIKE 'EDU-SEED-%'
ON CONFLICT (achievement_id) DO NOTHING;

-- 학기 코드가 존재한다는 근거가 없으므로 새 그룹이나 임의 학기 enum을 만들지 않는다.
INSERT INTO lecture_improvement_achievement_details (achievement_id, performance_content, academic_year)
SELECT
    a.achievement_id,
    a.achievement_name || ' 강의개선 내용',
    '2025'
FROM education_achievements a
WHERE a.achievement_type = 'LECTURE_IMPROVEMENT'
  AND a.management_no LIKE 'EDU-SEED-%'
ON CONFLICT (achievement_id) DO NOTHING;

INSERT INTO education_achievement_status_histories (
    achievement_type, achievement_id, previous_status, next_status, action_type, processed_by, request_id
)
SELECT
    a.achievement_type,
    a.achievement_id,
    NULL,
    a.achievement_status,
    'SEED',
    a.created_by,
    a.request_id
FROM education_achievements a
WHERE a.management_no LIKE 'EDU-SEED-%';

-- 기존 계정에 기존 R07 역할을 부여한다. 새 사용자·역할·인증체계는 만들지 않는다.
INSERT INTO user_roles (user_id, role_code, assignment_type, approver_user_id, status, change_reason)
SELECT
    actor.user_id,
    'R07',
    'MANUAL',
    admin_user.user_id,
    'ACTIVE',
    '취업률 Excel 및 보존된 일괄 결과 조회 fixture'
FROM users actor
JOIN users admin_user
    ON admin_user.login_id = 'admin'
WHERE actor.login_id = 'business-owner'
  AND NOT EXISTS (
      SELECT 1
      FROM user_roles assignment
      WHERE assignment.user_id = actor.user_id
        AND assignment.role_code = 'R07'
        AND assignment.status = 'ACTIVE'
  );

-- 이 결과는 보존 조회 fixture이며 미승인 실행 정책을 승인하거나 실행하지 않는다.
INSERT INTO employment_rate_batch_jobs (
    batch_job_id, evaluation_year, target_condition_json, action_type, requester_user_id,
    job_status, total_count, processed_count, unprocessed_count, request_id,
    started_at, completed_at, created_by, updated_by
)
SELECT
    seed.job_id,
    '2026',
    jsonb_build_object('fixture', true, 'organizationCode', 'KNUE-DEPT-COMP'),
    seed.action_type,
    actor.user_id,
    'COMPLETED',
    3,
    seed.processed_count,
    3 - seed.processed_count,
    seed.job_id,
    TIMESTAMP '2026-04-15 10:00:00',
    TIMESTAMP '2026-04-15 10:01:00',
    actor.user_id,
    actor.user_id
FROM users actor
CROSS JOIN (
    VALUES
        ('employment-rate-seed-normal', 'GENERATE', 2),
        ('employment-rate-seed-boundary', 'GENERATE', 0),
        ('employment-rate-seed-delete', 'DELETE', 3)
) AS seed(job_id, action_type, processed_count)
WHERE actor.login_id = 'business-owner';

INSERT INTO employment_rate_batch_job_items (
    batch_job_id, target_user_id, processed_yn, unprocessed_reason
)
SELECT
    job.batch_job_id,
    target.user_id,
    CASE WHEN seed.row_no <= job.processed_count THEN 'Y' ELSE 'N' END,
    CASE WHEN seed.row_no <= job.processed_count THEN NULL ELSE '보존 결과의 미처리 대상 예시' END
FROM employment_rate_batch_jobs job
CROSS JOIN (
    VALUES (1, 'professor1'), (2, 'professor2'), (3, 'business-owner')
) AS seed(row_no, login_id)
JOIN users target
    ON target.login_id = seed.login_id
WHERE job.batch_job_id LIKE 'employment-rate-seed-%';

INSERT INTO excel_upload_templates (
    template_id, business_type, template_version, effective_date, system_use_yn,
    status, created_by, updated_by, change_reason
)
SELECT
    'employment-rate-achievement-v1',
    'EMPLOYMENT_RATE_ACHIEVEMENT',
    '1',
    DATE '2026-01-01',
    'Y',
    'ACTIVE',
    actor.user_id,
    actor.user_id,
    '취업률 실적 공통열 템플릿; 실제 XLSX는 업무 codec에서 생성'
FROM users actor
WHERE actor.login_id = 'admin'
ON CONFLICT (business_type, template_version, effective_date) DO NOTHING;

INSERT INTO excel_upload_template_rules (
    rule_id, template_id, required_column, column_order, code_rule_ref, created_by, updated_by
)
SELECT
    'employment-rate-column-' || seed.column_order,
    template.template_id,
    seed.column_name,
    seed.column_order,
    seed.rule_ref,
    template.created_by,
    template.updated_by
FROM excel_upload_templates template
CROSS JOIN (
    VALUES
        (1, '교번', 'users.employee_no'),
        (2, '관리항목코드', 'evaluation_element_management_item_settings.management_item_code'),
        (3, '업적발생일', 'ISO_DATE'),
        (4, '실적명', 'REQUIRED_TEXT'),
        (5, '첨부참조', 'OPTIONAL_ATTACHMENT_REF')
) AS seed(column_order, column_name, rule_ref)
WHERE template.business_type = 'EMPLOYMENT_RATE_ACHIEVEMENT'
  AND template.template_version = '1'
ON CONFLICT (template_id, column_order) DO NOTHING;

-- DB가 실제 최대 menu_id 다음 값을 할당한다. 고정 ID로 기존 메뉴를 덮어쓰지 않는다.
INSERT INTO menus (
    menu_id, parent_menu_id, menu_type, menu_name, display_order,
    business_category, system_use_yn, status, change_reason
)
SELECT
    COALESCE(MAX(m.menu_id), 0) + 1,
    NULL,
    'MAIN',
    '업적 입력 관리',
    10,
    'EDUCATION_ACHIEVEMENT',
    'Y',
    'ACTIVE',
    '교육영역 실적 메뉴 계층'
FROM menus m
HAVING NOT EXISTS (
    SELECT 1
    FROM menus existing
    WHERE existing.menu_name = '업적 입력 관리'
      AND existing.menu_type = 'MAIN'
      AND existing.status = 'ACTIVE'
);

INSERT INTO menus (
    menu_id, parent_menu_id, menu_type, menu_name, display_order,
    business_category, system_use_yn, status, change_reason
)
SELECT
    (SELECT COALESCE(MAX(m.menu_id), 0) + 1 FROM menus m),
    parent.menu_id,
    'MIDDLE',
    '교육영역',
    1,
    'EDUCATION_ACHIEVEMENT',
    'Y',
    'ACTIVE',
    '교육영역 실적 메뉴 계층'
FROM menus parent
WHERE parent.menu_name = '업적 입력 관리'
  AND parent.menu_type = 'MAIN'
  AND parent.status = 'ACTIVE'
  AND NOT EXISTS (
      SELECT 1
      FROM menus existing
      WHERE existing.parent_menu_id = parent.menu_id
        AND existing.menu_name = '교육영역'
        AND existing.status = 'ACTIVE'
  )
ORDER BY parent.menu_id
LIMIT 1;

INSERT INTO menus (
    menu_id, parent_menu_id, menu_type, menu_name, display_order, screen_id,
    url, icon, business_category, system_use_yn, status, change_reason
)
SELECT
    next_id.max_id + seed.row_no,
    parent.menu_id,
    'SCREEN',
    seed.menu_name,
    seed.row_no,
    seed.screen_id,
    seed.url,
    'graduation-cap',
    'EDUCATION_ACHIEVEMENT',
    'Y',
    'ACTIVE',
    '교육영역 후반 실적 업무 화면'
FROM (
    SELECT m.menu_id
    FROM menus m
    JOIN menus main_menu
        ON main_menu.menu_id = m.parent_menu_id
    WHERE m.menu_name = '교육영역'
      AND main_menu.menu_name = '업적 입력 관리'
      AND m.status = 'ACTIVE'
    ORDER BY m.menu_id
    LIMIT 1
) AS parent
CROSS JOIN (SELECT COALESCE(MAX(m.menu_id), 0) AS max_id FROM menus m) AS next_id
CROSS JOIN (
    VALUES
        (1, '취업률 제고 실적 관리', 'SCR-EMPLOYMENT-RATE-IMPROVEMENT-ACHIEVEMENT',
            '/faculty/employment-rate-improvement-achievements'),
        (2, '강좌 개설·운영 실적 관리', 'SCR-COURSE-OFFERING-OPERATION-ACHIEVEMENT',
            '/faculty/course-offering-operation-achievements'),
        (3, '강의개선 실적 관리', 'SCR-TEACHING-IMPROVEMENT-ACHIEVEMENT',
            '/faculty/teaching-improvement-achievements'),
        (4, '취업률 실적 관리', 'SCR-EMPLOYMENT-RATE-ACHIEVEMENT',
            '/faculty/employment-rate-achievements')
) AS seed(row_no, menu_name, screen_id, url)
WHERE NOT EXISTS (
    SELECT 1
    FROM menus existing
    WHERE existing.screen_id = seed.screen_id
       OR existing.url = seed.url
);

INSERT INTO menu_execution_info (menu_id, screen_id, url, icon, business_category, description)
SELECT
    m.menu_id,
    m.screen_id,
    m.url,
    m.icon,
    m.business_category,
    m.menu_name
FROM menus m
WHERE m.screen_id IN (
    'SCR-EMPLOYMENT-RATE-IMPROVEMENT-ACHIEVEMENT', 'SCR-COURSE-OFFERING-OPERATION-ACHIEVEMENT',
    'SCR-TEACHING-IMPROVEMENT-ACHIEVEMENT', 'SCR-EMPLOYMENT-RATE-ACHIEVEMENT'
)
ON CONFLICT (menu_id) DO NOTHING;

INSERT INTO menu_permissions (
    target_type, target_id, menu_id, access_allowed, status, change_reason
)
SELECT
    'ROLE',
    role_seed.role_code,
    m.menu_id,
    'ALLOW',
    'ACTIVE',
    '교육영역 후반 업무 화면 접근; endpoint 권한은 업무 서비스에서 별도 검증'
FROM menus m
CROSS JOIN (VALUES ('R01'), ('R02'), ('R04'), ('R07'), ('R09')) AS role_seed(role_code)
WHERE (
    m.screen_id IN (
        'SCR-EMPLOYMENT-RATE-IMPROVEMENT-ACHIEVEMENT', 'SCR-COURSE-OFFERING-OPERATION-ACHIEVEMENT',
        'SCR-TEACHING-IMPROVEMENT-ACHIEVEMENT', 'SCR-EMPLOYMENT-RATE-ACHIEVEMENT'
    )
    OR (m.menu_name IN ('업적 입력 관리', '교육영역') AND m.business_category = 'EDUCATION_ACHIEVEMENT')
)
  AND (
      role_seed.role_code <> 'R07'
      OR m.screen_id = 'SCR-EMPLOYMENT-RATE-ACHIEVEMENT'
      OR m.screen_id IS NULL
  )
ON CONFLICT (target_type, target_id, menu_id) DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('menus', 'menu_id'),
    (SELECT MAX(m.menu_id) FROM menus m),
    true
);
