-- 교육영역 후반 실적의 공통 원장과 유형별 상세. 기존 교육영역 원천은 변경하지 않는다.
CREATE TABLE IF NOT EXISTS education_achievements (
    achievement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    management_no varchar(50) NOT NULL UNIQUE,
    achievement_type varchar(30) NOT NULL,
    teacher_user_id bigint NOT NULL REFERENCES users(user_id),
    organization_code varchar(50) NOT NULL REFERENCES organizations(organization_code),
    evaluation_year varchar(4) NOT NULL CHECK (evaluation_year ~ '^[0-9]{4}$'),
    management_item_code varchar(50) NOT NULL CHECK (btrim(management_item_code) <> ''),
    achievement_date date NOT NULL,
    achievement_name varchar(500),
    achievement_status varchar(30) NOT NULL DEFAULT 'DRAFT',
    attachment_ids jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(attachment_ids) = 'array'),
    deleted_yn char(1) NOT NULL DEFAULT 'N' CHECK (deleted_yn IN ('Y', 'N')),
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint REFERENCES users(user_id),
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint REFERENCES users(user_id),
    request_id varchar(100),
    CONSTRAINT ck_education_achievements_type CHECK (
        achievement_type IN (
            'employment-rate-improvements',
            'course-operations',
            'lecture-improvements',
            'employment-rate-achievements'
        )
    ),
    CONSTRAINT ck_education_achievements_status CHECK (
        achievement_status IN (
            'DRAFT', 'SUBMITTED', 'DEPARTMENT_CONFIRMED', 'DEPARTMENT_REJECTED',
            'CERTIFIED', 'CERTIFICATION_REJECTED', 'EVALUATION_CONFIRMED', 'DELETED'
        )
    )
);
COMMENT ON TABLE education_achievements IS '교육영역 후반 4개 실적의 공통 원장. 교원 소유권, 평가연도, 첨부 식별자와 상태를 보존한다.';
COMMENT ON COLUMN education_achievements.management_item_code IS
    'evaluation_management_items.management_item_code 및 연도·대상별 운영 설정 참조 의도 (복합키이므로 FK 미선언)';
COMMENT ON COLUMN education_achievements.attachment_ids IS
    'FileStoragePort의 실제 소유 파일 식별자 배열 참조 의도 (FK 미선언), 실적 서비스가 저장 transaction에서 갱신';
COMMENT ON COLUMN education_achievements.request_id IS '처리 요청 추적 식별자 참조 의도 (FK 미선언)';
CREATE INDEX IF NOT EXISTS idx_education_achievements_owner_search
    ON education_achievements (teacher_user_id, evaluation_year, achievement_type, achievement_date DESC)
    WHERE deleted_yn = 'N';
CREATE INDEX IF NOT EXISTS idx_education_achievements_organization_search
    ON education_achievements (organization_code, evaluation_year, achievement_type, achievement_status)
    WHERE deleted_yn = 'N';
-- 취업률 파일/DB 중복 검증의 최종 경합 방어. 다른 실적의 동일 날짜 등록을 제한하지 않는다.
CREATE UNIQUE INDEX IF NOT EXISTS uq_education_achievements_employment_identity
    ON education_achievements (
        teacher_user_id, evaluation_year, management_item_code, achievement_date,
        COALESCE(achievement_name, '')
    )
    WHERE achievement_type = 'employment-rate-achievements' AND deleted_yn = 'N';

CREATE TABLE IF NOT EXISTS employment_rate_improvement_achievement_details (
    achievement_id bigint PRIMARY KEY REFERENCES education_achievements(achievement_id),
    special_lecture_start_date date,
    special_lecture_end_date date,
    mock_exam_question_period text,
    CONSTRAINT ck_employment_improvement_special_lecture_dates CHECK (
        (special_lecture_start_date IS NULL AND special_lecture_end_date IS NULL)
        OR (special_lecture_start_date IS NOT NULL AND special_lecture_end_date IS NOT NULL
            AND special_lecture_end_date >= special_lecture_start_date)
    )
);
COMMENT ON TABLE employment_rate_improvement_achievement_details IS '취업률 제고 실적의 특강기간 및 모의시험 출제기간 상세.';
CREATE TABLE IF NOT EXISTS course_operation_achievement_details (
    achievement_id bigint PRIMARY KEY REFERENCES education_achievements(achievement_id),
    performance_detail text NOT NULL CHECK (btrim(performance_detail) <> '')
);
COMMENT ON TABLE course_operation_achievement_details IS '강좌 개설·운영 실적의 실적내역 상세.';
CREATE TABLE IF NOT EXISTS lecture_improvement_achievement_details (
    achievement_id bigint PRIMARY KEY REFERENCES education_achievements(achievement_id),
    performance_content text NOT NULL CHECK (btrim(performance_content) <> ''),
    academic_year integer NOT NULL CHECK (academic_year >= 2000),
    semester_code varchar(1) NOT NULL CHECK (semester_code IN ('1', '2'))
);
COMMENT ON TABLE lecture_improvement_achievement_details IS '강의개선 실적의 내용, 학년도 및 학기 상세. 학년도는 원장 평가연도와 별개다.';

CREATE TABLE IF NOT EXISTS employment_rate_batch_jobs (
    batch_job_id varchar(100) PRIMARY KEY,
    evaluation_year varchar(4) NOT NULL CHECK (evaluation_year ~ '^[0-9]{4}$'),
    target_condition_json jsonb NOT NULL DEFAULT '{}'::jsonb
        CHECK (jsonb_typeof(target_condition_json) = 'object'),
    action_type varchar(20) NOT NULL CHECK (action_type IN ('GENERATE', 'DELETE')),
    job_status varchar(30) NOT NULL DEFAULT 'BLOCKED' CHECK (
        job_status IN ('BLOCKED', 'REQUESTED', 'RUNNING', 'COMPLETED', 'FAILED')
    ),
    total_count integer NOT NULL DEFAULT 0 CHECK (total_count >= 0),
    processed_count integer NOT NULL DEFAULT 0 CHECK (processed_count >= 0),
    unprocessed_count integer NOT NULL DEFAULT 0 CHECK (unprocessed_count >= 0),
    requester_user_id bigint NOT NULL REFERENCES users(user_id),
    request_id varchar(100),
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint REFERENCES users(user_id),
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint REFERENCES users(user_id),
    CONSTRAINT ck_employment_batch_counts CHECK (processed_count + unprocessed_count <= total_count)
);
COMMENT ON TABLE employment_rate_batch_jobs IS
    '취업률 일괄 작업 진단·결과 보존. 현재 실행 정책 미승인으로 생성·삭제 미실행이며 seed는 차단 진단 조회 전용이다.';
COMMENT ON COLUMN employment_rate_batch_jobs.request_id IS '처리 요청 추적 식별자 참조 의도 (FK 미선언)';
COMMENT ON COLUMN employment_rate_batch_jobs.processed_count IS
    'EmploymentRateBulkJobService가 작업 transaction 종료 시 갱신하는 처리 건수';
COMMENT ON COLUMN employment_rate_batch_jobs.unprocessed_count IS
    'EmploymentRateBulkJobService가 작업 transaction 종료 시 갱신하는 미처리 건수';
CREATE INDEX IF NOT EXISTS idx_employment_batch_jobs_owner
    ON employment_rate_batch_jobs (requester_user_id, created_at DESC);
CREATE TABLE IF NOT EXISTS employment_rate_batch_job_items (
    batch_job_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_job_id varchar(100) NOT NULL REFERENCES employment_rate_batch_jobs(batch_job_id),
    target_user_id bigint NOT NULL REFERENCES users(user_id),
    achievement_id bigint REFERENCES education_achievements(achievement_id),
    processed_yn char(1) NOT NULL DEFAULT 'N' CHECK (processed_yn IN ('Y', 'N')),
    unprocessed_reason varchar(1000),
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_employment_batch_job_target UNIQUE (batch_job_id, target_user_id),
    CONSTRAINT ck_employment_batch_item_reason CHECK (
        processed_yn = 'Y' OR NULLIF(btrim(unprocessed_reason), '') IS NOT NULL
    )
);
COMMENT ON TABLE employment_rate_batch_job_items IS
    '취업률 일괄 작업의 대상 snapshot 및 건별 결과. 현재 정책 미승인 seed는 미처리 진단만 보존한다.';
CREATE INDEX IF NOT EXISTS idx_employment_batch_items_target
    ON employment_rate_batch_job_items (target_user_id, batch_job_id);

ALTER TABLE education_achievement_status_histories
    DROP CONSTRAINT ck_education_achievement_status_histories_type;
ALTER TABLE education_achievement_status_histories
    ADD CONSTRAINT ck_education_achievement_status_histories_type CHECK (
        achievement_type IN (
            'LECTURE_EVALUATION', 'LECTURE', 'STUDENT_GUIDANCE', 'DEGREE_COMPLETION',
            'employment-rate-improvements',
            'course-operations',
            'lecture-improvements',
            'employment-rate-achievements'
        )
    );
-- 공통 이력의 requestId도 원장·변경이력과 동일한 요청에 연결한다.
ALTER TABLE education_achievement_status_histories ADD COLUMN IF NOT EXISTS request_id varchar(100);
COMMENT ON COLUMN education_achievement_status_histories.request_id IS '처리 요청 추적 식별자 참조 의도 (FK 미선언)';

-- 분류 코드가 비어 있는 기존 설치에도 운영 관리항목 seed의 부모를 제공한다.
INSERT INTO evaluation_areas (
    rule_version_id, area_code, area_name, sort_order, period_apply_method,
    change_reason, created_by, updated_by
)
SELECT v.rule_version_id, 'EDUCATION', '교육영역', 1, 'AREA', '교육실적 분류 seed', 1, 1
FROM evaluation_rule_versions v
WHERE v.version_code = 'B33-DRAFT-2026'
ON CONFLICT (rule_version_id, area_code) DO NOTHING;
INSERT INTO evaluation_items (
    area_id, item_code, item_name, sort_order, score_apply_method, change_reason, created_by, updated_by
)
SELECT a.area_id, 'LECTURE', '교육실적', 1, 'MANAGEMENT_ITEM', '교육실적 분류 seed', 1, 1
FROM evaluation_areas a
JOIN evaluation_rule_versions v ON v.rule_version_id = a.rule_version_id
WHERE v.version_code = 'B33-DRAFT-2026' AND a.area_code = 'EDUCATION'
ON CONFLICT (area_id, item_code) DO NOTHING;

INSERT INTO evaluation_elements (
    item_id, evaluation_year, element_code, element_name, sort_order, change_reason, created_by, updated_by
)
SELECT i.item_id, '2026', 'EDUCATION_OPERATIONS', '교육영역 후반 실적', 90, '교육실적 운영 기반', 1, 1
FROM evaluation_items i
JOIN evaluation_areas a ON a.area_id = i.area_id
JOIN evaluation_rule_versions v ON v.rule_version_id = a.rule_version_id
WHERE v.version_code = 'B33-DRAFT-2026' AND a.area_code = 'EDUCATION' AND i.item_code = 'LECTURE'
ON CONFLICT (item_id, evaluation_year, element_code) DO NOTHING;

INSERT INTO evaluation_management_items (
    element_id, management_item_code, management_item_name, sort_order,
    teacher_editable_yn, required_yn, data_type, change_reason, created_by, updated_by
)
SELECT e.element_id, s.code, s.name, s.sort_order, 'Y', 'Y', 'TEXT', '교육실적 관리항목 seed', 1, 1
FROM evaluation_elements e
CROSS JOIN (VALUES
        ('employment-rate-improvements', '취업률 제고', 1),
        ('course-operations', '강좌 개설·운영', 2),
        ('lecture-improvements', '강의개선', 3),
        ('employment-rate-achievements', '취업률 실적', 4)
) AS s(code, name, sort_order)
WHERE e.element_code = 'EDUCATION_OPERATIONS' AND e.evaluation_year = '2026'
ON CONFLICT (element_id, management_item_code) DO NOTHING;

INSERT INTO evaluation_element_management_item_settings (
    rule_version_id, target_scope, area_code, item_code, evaluation_year, element_code,
    management_item_code, management_item_name, sort_order, teacher_editable_yn, teacher_editable_part,
    effective_start_date, effective_end_date, change_reason, created_by, updated_by
)
SELECT a.rule_version_id, 'KNUE-DEPT-COMP', a.area_code, i.item_code, e.evaluation_year, e.element_code,
       m.management_item_code, m.management_item_name, m.sort_order, 'Y', 'SELF_REPORT',
       DATE '2026-01-01', DATE '2026-12-31', '교육실적 운영 항목 seed', 1, 1
FROM evaluation_management_items m
JOIN evaluation_elements e ON e.element_id = m.element_id
JOIN evaluation_items i ON i.item_id = e.item_id
JOIN evaluation_areas a ON a.area_id = i.area_id
WHERE e.element_code = 'EDUCATION_OPERATIONS' AND e.evaluation_year = '2026'
ON CONFLICT (rule_version_id, target_scope, area_code, item_code,
             evaluation_year, element_code, management_item_code) DO NOTHING;

INSERT INTO education_achievements (
    management_no, achievement_type, teacher_user_id, organization_code, evaluation_year,
    management_item_code, achievement_date, achievement_name, achievement_status, created_by, updated_by
)
SELECT s.management_no, 'employment-rate-improvements', u.user_id, 'KNUE-DEPT-COMP', '2026',
       'employment-rate-improvements', s.achievement_date, s.name, s.achievement_status, u.user_id, u.user_id
FROM (VALUES
    ('employment-rate-improvements-01', 'professor1', DATE '2026-04-10', '취업률 제고 정상 실적', 'DRAFT'),
    ('employment-rate-improvements-02', 'professor2', DATE '2025-12-31', '취업률 제고 기간 경계', 'SUBMITTED'),
    ('employment-rate-improvements-03', 'business-owner', DATE '2026-04-12', '취업률 제고 확정 잠금', 'EVALUATION_CONFIRMED')
) AS s(management_no, login_id, achievement_date, name, achievement_status)
JOIN users u ON u.login_id = s.login_id
ON CONFLICT (management_no) DO NOTHING;

INSERT INTO education_achievements (
    management_no, achievement_type, teacher_user_id, organization_code, evaluation_year,
    management_item_code, achievement_date, achievement_name, achievement_status, created_by, updated_by
)
SELECT s.management_no, 'course-operations', u.user_id, 'KNUE-DEPT-COMP', '2026',
       'course-operations', s.achievement_date, s.name, s.achievement_status, u.user_id, u.user_id
FROM (VALUES
    ('course-operations-01', 'professor1', DATE '2026-04-10', '강좌 개설·운영 정상 실적', 'DRAFT'),
    ('course-operations-02', 'professor2', DATE '2025-12-31', '강좌 개설·운영 기간 경계', 'SUBMITTED'),
    ('course-operations-03', 'business-owner', DATE '2026-04-12', '강좌 개설·운영 확정 잠금', 'EVALUATION_CONFIRMED')
) AS s(management_no, login_id, achievement_date, name, achievement_status)
JOIN users u ON u.login_id = s.login_id
ON CONFLICT (management_no) DO NOTHING;

INSERT INTO education_achievements (
    management_no, achievement_type, teacher_user_id, organization_code, evaluation_year,
    management_item_code, achievement_date, achievement_name, achievement_status, created_by, updated_by
)
SELECT s.management_no, 'lecture-improvements', u.user_id, 'KNUE-DEPT-COMP', '2026',
       'lecture-improvements', s.achievement_date, s.name, s.achievement_status, u.user_id, u.user_id
FROM (VALUES
    ('lecture-improvements-01', 'professor1', DATE '2026-04-10', '강의개선 정상 실적', 'DRAFT'),
    ('lecture-improvements-02', 'professor2', DATE '2025-12-31', '강의개선 기간 경계', 'SUBMITTED'),
    ('lecture-improvements-03', 'business-owner', DATE '2026-04-12', '강의개선 확정 잠금', 'EVALUATION_CONFIRMED')
) AS s(management_no, login_id, achievement_date, name, achievement_status)
JOIN users u ON u.login_id = s.login_id
ON CONFLICT (management_no) DO NOTHING;

INSERT INTO education_achievements (
    management_no, achievement_type, teacher_user_id, organization_code, evaluation_year,
    management_item_code, achievement_date, achievement_name, achievement_status, created_by, updated_by
)
SELECT s.management_no, 'employment-rate-achievements', u.user_id, 'KNUE-DEPT-COMP', '2026',
       'employment-rate-achievements', s.achievement_date, s.name, s.achievement_status, u.user_id, u.user_id
FROM (VALUES
    ('employment-rate-achievements-01', 'professor1', DATE '2026-04-10', '취업률 실적 정상 실적', 'DRAFT'),
    ('employment-rate-achievements-02', 'professor2', DATE '2025-12-31', '취업률 실적 기간 경계', 'SUBMITTED'),
    ('employment-rate-achievements-03', 'business-owner', DATE '2026-04-12', '취업률 실적 확정 잠금', 'EVALUATION_CONFIRMED')
) AS s(management_no, login_id, achievement_date, name, achievement_status)
JOIN users u ON u.login_id = s.login_id
ON CONFLICT (management_no) DO NOTHING;

INSERT INTO employment_rate_improvement_achievement_details (
    achievement_id, special_lecture_start_date, special_lecture_end_date, mock_exam_question_period
)
SELECT a.achievement_id,
       CASE WHEN a.achievement_status = 'DRAFT' THEN NULL ELSE a.achievement_date END,
       CASE WHEN a.achievement_status = 'DRAFT' THEN NULL ELSE a.achievement_date END,
       '모의시험 출제기간 확인 seed'
FROM education_achievements a
WHERE a.management_no IN ('employment-rate-improvements-01',
                         'employment-rate-improvements-02', 'employment-rate-improvements-03');
INSERT INTO course_operation_achievement_details (achievement_id, performance_detail)
SELECT a.achievement_id, a.achievement_name
FROM education_achievements a
WHERE a.management_no IN ('course-operations-01', 'course-operations-02', 'course-operations-03');
INSERT INTO lecture_improvement_achievement_details (
    achievement_id, performance_content, academic_year, semester_code
)
SELECT a.achievement_id, a.achievement_name, 2026,
       CASE WHEN a.achievement_status = 'DRAFT' THEN '1' ELSE '2' END
FROM education_achievements a
WHERE a.management_no IN ('lecture-improvements-01', 'lecture-improvements-02', 'lecture-improvements-03');

INSERT INTO education_achievement_status_histories (
    achievement_type, achievement_id, previous_status, next_status, action_type, opinion, processed_by, request_id
)
SELECT a.achievement_type, a.achievement_id, NULL, a.achievement_status,
       'CREATE', '교육실적 상태 차이 seed (실행 증거 아님)', a.created_by, 'education-foundation-seed'
FROM education_achievements a;
INSERT INTO data_change_histories (
    target_business, target_key, change_type, field_name, before_value,
    after_value, changed_by, change_reason, request_id
)
SELECT 'education_achievements', a.achievement_id::text, 'CREATE', 'snapshot', NULL,
       to_jsonb(a)::text, a.created_by, '교육실적 초기 snapshot', 'education-foundation-seed'
FROM education_achievements a;

INSERT INTO employment_rate_batch_jobs (
    batch_job_id, evaluation_year, target_condition_json, action_type, job_status,
    total_count, processed_count, unprocessed_count, requester_user_id, created_by, updated_by, request_id
)
SELECT s.id, '2026', '{"fixture":true}'::jsonb, s.action_type, 'BLOCKED',
       1, 0, 1, u.user_id, u.user_id, u.user_id, 'education-foundation-seed'
FROM (VALUES
    ('employment-diagnostic-01', 'GENERATE', 'professor1'),
    ('employment-diagnostic-02', 'DELETE', 'professor2'),
    ('employment-diagnostic-03', 'GENERATE', 'business-owner')
) AS s(id, action_type, login_id)
JOIN users u ON u.login_id = s.login_id;
INSERT INTO employment_rate_batch_job_items (
    batch_job_id, target_user_id, processed_yn, unprocessed_reason
)
SELECT j.batch_job_id, j.requester_user_id, 'N', '생성자격·삭제상태 정책 미승인: 조회 전용 진단 fixture'
FROM employment_rate_batch_jobs j;

INSERT INTO excel_upload_templates (
    template_id, business_type, template_version, effective_date, created_by, updated_by, change_reason
)
VALUES ('EMPLOYMENT_RATE_ACHIEVEMENT-v1', 'EMPLOYMENT_RATE_ACHIEVEMENT', 'v1.0',
        DATE '2026-01-01', 1, 1, '취업률 실적 XLSX 양식');
INSERT INTO excel_upload_template_rules (
    rule_id, template_id, required_column, column_order, code_rule_ref, created_by, updated_by
)
SELECT 'employment-rate-column-' || s.sort_order, 'EMPLOYMENT_RATE_ACHIEVEMENT-v1',
       s.column_name, s.sort_order, s.rule_ref, 1, 1
FROM (VALUES
    (1, '교번', 'users.employee_no'),
    (2, '관리항목코드', 'evaluation_management_items.management_item_code'),
    (3, '업적발생일', 'DATE'),
    (4, '실적명', 'TEXT_OPTIONAL'),
    (5, '첨부참조', 'FILE_OPTIONAL')
) AS s(sort_order, column_name, rule_ref);

INSERT INTO menus (
    menu_id, menu_type, menu_name, display_order, screen_id, url, icon,
    business_category, description, system_use_yn, status, updated_by, change_reason
)
SELECT COALESCE(MAX(m.menu_id), 0) + 1, 'SCREEN', '취업률 제고', 1101, 'SCR-EMPLOYMENT-RATE-IMPROVEMENT-ACHIEVEMENT',
       '/faculty/education/employment-rate-improvements', 'book-open', 'EDUCATION_ACHIEVEMENT',
       '교육영역 실적 관리', 'Y', 'ACTIVE', 1, '교육실적 화면 접근'
FROM menus m;

INSERT INTO menus (
    menu_id, menu_type, menu_name, display_order, screen_id, url, icon,
    business_category, description, system_use_yn, status, updated_by, change_reason
)
SELECT COALESCE(MAX(m.menu_id), 0) + 1, 'SCREEN', '강좌 개설·운영', 1102, 'SCR-COURSE-OFFERING-OPERATION-ACHIEVEMENT',
       '/faculty/education/course-operations', 'book-open', 'EDUCATION_ACHIEVEMENT',
       '교육영역 실적 관리', 'Y', 'ACTIVE', 1, '교육실적 화면 접근'
FROM menus m;

INSERT INTO menus (
    menu_id, menu_type, menu_name, display_order, screen_id, url, icon,
    business_category, description, system_use_yn, status, updated_by, change_reason
)
SELECT COALESCE(MAX(m.menu_id), 0) + 1, 'SCREEN', '강의개선', 1103, 'SCR-TEACHING-IMPROVEMENT-ACHIEVEMENT',
       '/faculty/education/lecture-improvements', 'book-open', 'EDUCATION_ACHIEVEMENT',
       '교육영역 실적 관리', 'Y', 'ACTIVE', 1, '교육실적 화면 접근'
FROM menus m;

INSERT INTO menus (
    menu_id, menu_type, menu_name, display_order, screen_id, url, icon,
    business_category, description, system_use_yn, status, updated_by, change_reason
)
SELECT COALESCE(MAX(m.menu_id), 0) + 1, 'SCREEN', '취업률 실적', 1104, 'SCR-EMPLOYMENT-RATE-ACHIEVEMENT',
       '/faculty/education/employment-rate-achievements', 'book-open', 'EDUCATION_ACHIEVEMENT',
       '교육영역 실적 관리', 'Y', 'ACTIVE', 1, '교육실적 화면 접근'
FROM menus m;

SELECT setval(pg_get_serial_sequence('menus', 'menu_id'), (SELECT MAX(menu_id) FROM menus), true);
INSERT INTO menu_execution_info (menu_id, screen_id, url, icon, business_category, description, updated_by)
SELECT m.menu_id, m.screen_id, m.url, m.icon, m.business_category, m.description, 1
FROM menus m
WHERE m.screen_id IN (
    'SCR-EMPLOYMENT-RATE-IMPROVEMENT-ACHIEVEMENT',
    'SCR-COURSE-OFFERING-OPERATION-ACHIEVEMENT',
    'SCR-TEACHING-IMPROVEMENT-ACHIEVEMENT',
    'SCR-EMPLOYMENT-RATE-ACHIEVEMENT'
);
INSERT INTO menu_permissions (
    target_type, target_id, menu_id, access_allowed, status, created_by, updated_by, change_reason
)
SELECT 'ROLE', r.role_code, m.menu_id, 'ALLOW', 'ACTIVE', 1, 1, '교육실적 역할별 화면 접근'
FROM menus m
CROSS JOIN (VALUES ('R01'), ('R02'), ('R04'), ('R07'), ('R09')) AS r(role_code)
WHERE m.screen_id IN (
    'SCR-EMPLOYMENT-RATE-IMPROVEMENT-ACHIEVEMENT',
    'SCR-COURSE-OFFERING-OPERATION-ACHIEVEMENT',
    'SCR-TEACHING-IMPROVEMENT-ACHIEVEMENT',
    'SCR-EMPLOYMENT-RATE-ACHIEVEMENT'
)
  AND (r.role_code <> 'R07' OR m.screen_id = 'SCR-EMPLOYMENT-RATE-ACHIEVEMENT');
INSERT INTO function_permissions (
    screen_id, role_code, function_type, permission_allowed, change_reason, created_by, updated_by
)
SELECT m.screen_id, r.role_code, f.function_type, 'ALLOW', '교육실적 기능 접근', 1, 1
FROM menus m
CROSS JOIN (VALUES ('R01'), ('R02'), ('R04'), ('R07'), ('R09')) AS r(role_code)
CROSS JOIN (VALUES ('READ'), ('CREATE'), ('UPDATE'), ('EXECUTE')) AS f(function_type)
WHERE m.screen_id IN (
    'SCR-EMPLOYMENT-RATE-IMPROVEMENT-ACHIEVEMENT',
    'SCR-COURSE-OFFERING-OPERATION-ACHIEVEMENT',
    'SCR-TEACHING-IMPROVEMENT-ACHIEVEMENT',
    'SCR-EMPLOYMENT-RATE-ACHIEVEMENT'
)
  AND (
      r.role_code = 'R09'
      OR (r.role_code = 'R01' AND f.function_type IN ('READ', 'CREATE', 'UPDATE'))
      OR (r.role_code IN ('R02', 'R04') AND f.function_type = 'READ')
      OR (r.role_code = 'R07' AND m.screen_id = 'SCR-EMPLOYMENT-RATE-ACHIEVEMENT'
          AND f.function_type IN ('READ', 'EXECUTE'))
  );
