-- 교육영역 후반 네 유형의 공통 원장과 상세를 추가한다. 기존 교육 원장은 변경하지 않는다.
CREATE TABLE IF NOT EXISTS education_achievements (
    achievement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    achievement_type varchar(30) NOT NULL,
    management_no varchar(50) NOT NULL,
    teacher_user_id bigint NOT NULL REFERENCES users(user_id),
    organization_code varchar(50) NOT NULL REFERENCES organizations(organization_code),
    evaluation_year varchar(4) NOT NULL,
    management_item_code varchar(50) NOT NULL,
    achievement_date date NOT NULL,
    achievement_name varchar(500),
    achievement_detail text,
    achievement_status varchar(30) NOT NULL DEFAULT 'DRAFT',
    attachment_ref varchar(300),
    deleted_yn char(1) NOT NULL DEFAULT 'N',
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint REFERENCES users(user_id),
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint REFERENCES users(user_id),
    request_id varchar(100),
    CONSTRAINT uq_education_achievements_management_no UNIQUE (management_no),
    CONSTRAINT ck_education_achievements_type CHECK (
        achievement_type IN ('FR-029', 'FR-030', 'FR-031', 'FR-032')
    ),
    CONSTRAINT ck_education_achievements_year CHECK (evaluation_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_education_achievements_status CHECK (
        achievement_status IN (
            'DRAFT', 'SUBMITTED', 'DEPARTMENT_CONFIRMED', 'DEPARTMENT_REJECTED',
            'CERTIFIED', 'CERTIFICATION_REJECTED', 'EVALUATION_CONFIRMED', 'DELETED'
        )
    ),
    CONSTRAINT ck_education_achievements_deleted CHECK (deleted_yn IN ('Y', 'N'))
);
COMMENT ON TABLE education_achievements IS
    '교육영역 취업률 제고·강좌 개설운영·강의개선·취업률 실적의 공통 원장. 유형별 상태·첨부·논리삭제·입력자를 보존한다.';
COMMENT ON COLUMN education_achievements.achievement_type IS
    'FR-029:취업률제고|FR-030:강좌개설운영|FR-031:강의개선|FR-032:취업률실적';
COMMENT ON COLUMN education_achievements.achievement_status IS
    'DRAFT:작성중|SUBMITTED:제출|DEPARTMENT_CONFIRMED:학과장확인|DEPARTMENT_REJECTED:학과장미승인|CERTIFIED:인증|CERTIFICATION_REJECTED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN education_achievements.management_item_code IS
    'evaluation_management_items.management_item_code 참조 의도 (규정별 중복 코드이므로 FK 미선언)';
COMMENT ON COLUMN education_achievements.achievement_name IS 'FR-032 개별 입력과 Excel 공통열 실적명';
COMMENT ON COLUMN education_achievements.achievement_detail IS '동적 관리항목 입력값을 서비스에서 직렬화하여 저장';
COMMENT ON COLUMN education_achievements.attachment_ref IS '첨부 서비스의 외부 비노출 파일 token 참조 의도 (FK 미선언)';
COMMENT ON COLUMN education_achievements.request_id IS '저장 서비스에서 최종 변경 요청 식별자를 기록 (FK 미선언)';
COMMENT ON COLUMN education_achievements.deleted_yn IS 'Y:삭제|N:정상';

CREATE INDEX IF NOT EXISTS idx_education_achievements_owner_search
    ON education_achievements (
        achievement_type, teacher_user_id, evaluation_year, achievement_date DESC, achievement_id DESC
    )
    WHERE deleted_yn = 'N';
CREATE INDEX IF NOT EXISTS idx_education_achievements_scope_search
    ON education_achievements (
        achievement_type, organization_code, evaluation_year, achievement_status, achievement_date DESC
    )
    WHERE deleted_yn = 'N';
-- Excel commit의 재검증 이후에도 동시 반영 중복을 DB에서 차단한다. 논리삭제된 행은 새 입력을 막지 않는다.
CREATE UNIQUE INDEX IF NOT EXISTS uq_education_achievements_employment_rate_identity
    ON education_achievements (
        teacher_user_id, evaluation_year, management_item_code, achievement_date, achievement_type
    )
    WHERE achievement_type = 'FR-032' AND deleted_yn = 'N';

CREATE TABLE IF NOT EXISTS employment_rate_improvement_achievement_details (
    achievement_id bigint PRIMARY KEY REFERENCES education_achievements(achievement_id),
    special_lecture_start_date date,
    special_lecture_end_date date,
    mock_exam_question_period varchar(500),
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint REFERENCES users(user_id),
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint REFERENCES users(user_id),
    CONSTRAINT ck_employment_rate_improvement_lecture_period CHECK (
        special_lecture_start_date IS NULL
        OR special_lecture_end_date IS NULL
        OR special_lecture_end_date >= special_lecture_start_date
    )
);
COMMENT ON TABLE employment_rate_improvement_achievement_details IS
    '취업률 제고 실적의 특강기간과 모의평가 출제기간. 공통 원장과 동일 트랜잭션으로 저장한다.';
COMMENT ON COLUMN employment_rate_improvement_achievement_details.mock_exam_question_period IS
    '관리항목 설정에 따라 입력하는 문자열 기간 (날짜형으로 임의 변환하지 않음)';

CREATE TABLE IF NOT EXISTS course_operation_achievement_details (
    achievement_id bigint PRIMARY KEY REFERENCES education_achievements(achievement_id),
    performance_detail text NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint REFERENCES users(user_id),
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint REFERENCES users(user_id),
    CONSTRAINT ck_course_operation_detail_required CHECK (length(btrim(performance_detail)) > 0)
);
COMMENT ON TABLE course_operation_achievement_details IS
    '강좌 개설·운영의 실적내역. 공통 원장과 동일 식별자로 연결하여 상세 값을 보존한다.';

CREATE TABLE IF NOT EXISTS lecture_improvement_achievement_details (
    achievement_id bigint PRIMARY KEY REFERENCES education_achievements(achievement_id),
    performance_content text NOT NULL,
    academic_year varchar(4) NOT NULL,
    semester_code varchar(1) NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint REFERENCES users(user_id),
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint REFERENCES users(user_id),
    CONSTRAINT ck_lecture_improvement_content_required CHECK (length(btrim(performance_content)) > 0),
    CONSTRAINT ck_lecture_improvement_academic_year CHECK (academic_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_lecture_improvement_semester CHECK (semester_code IN ('1', '2'))
);
COMMENT ON TABLE lecture_improvement_achievement_details IS
    '강의개선 실적내용·학년도·학기. 학년도와 학기는 평가연도와 별도의 원문 입력값으로 보존한다.';
COMMENT ON COLUMN lecture_improvement_achievement_details.semester_code IS '1:1학기|2:2학기';

-- 기존 Excel/job token 규약에 맞추어 batch_job_id는 opaque 문자열로 사용한다.
-- 정책 승인을 나타내는 입력/기본값은 두지 않는다. 실행 서비스가 승인 부재 시 insert 전에 409로 종료한다.
CREATE TABLE IF NOT EXISTS employment_rate_batch_jobs (
    batch_job_id varchar(100) PRIMARY KEY,
    evaluation_year varchar(4) NOT NULL,
    target_condition_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    action_type varchar(20) NOT NULL,
    requester_user_id bigint NOT NULL REFERENCES users(user_id),
    organization_code varchar(50) REFERENCES organizations(organization_code),
    status varchar(20) NOT NULL DEFAULT 'REQUESTED',
    total_count integer NOT NULL DEFAULT 0,
    processed_count integer NOT NULL DEFAULT 0,
    unprocessed_count integer NOT NULL DEFAULT 0,
    seed_yn char(1) NOT NULL DEFAULT 'N',
    request_id varchar(100),
    requested_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at timestamp,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint REFERENCES users(user_id),
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint REFERENCES users(user_id),
    CONSTRAINT ck_employment_rate_batch_jobs_year CHECK (evaluation_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_employment_rate_batch_jobs_condition CHECK (jsonb_typeof(target_condition_json) = 'object'),
    CONSTRAINT ck_employment_rate_batch_jobs_action CHECK (action_type IN ('GENERATE', 'DELETE')),
    CONSTRAINT ck_employment_rate_batch_jobs_status CHECK (
        status IN ('REQUESTED', 'PROCESSING', 'COMPLETED', 'FAILED', 'SEED')
    ),
    CONSTRAINT ck_employment_rate_batch_jobs_seed CHECK (seed_yn IN ('Y', 'N')),
    CONSTRAINT ck_employment_rate_batch_jobs_counts CHECK (
        total_count >= 0 AND processed_count >= 0 AND unprocessed_count >= 0
        AND processed_count + unprocessed_count <= total_count
    )
);
COMMENT ON TABLE employment_rate_batch_jobs IS
    '취업률 실적 일괄 생성·삭제의 대상 조건과 처리건수를 보존한다. SEED는 검토용 사례이며 승인된 실행 결과가 아니다.';
COMMENT ON COLUMN employment_rate_batch_jobs.status IS
    'REQUESTED:접수|PROCESSING:처리중|COMPLETED:완료|FAILED:실패|SEED:검토용시드';
COMMENT ON COLUMN employment_rate_batch_jobs.action_type IS 'GENERATE:생성|DELETE:삭제';
COMMENT ON COLUMN employment_rate_batch_jobs.seed_yn IS 'Y:검토용시드|N:실제작업';
COMMENT ON COLUMN employment_rate_batch_jobs.request_id IS '실행 서비스에서 기록한 요청 식별자 (FK 미선언)';
COMMENT ON COLUMN employment_rate_batch_jobs.total_count IS '일괄 서비스가 대상 확정 시 갱신하는 파생 대상건수';
COMMENT ON COLUMN employment_rate_batch_jobs.processed_count IS '일괄 서비스가 건별 결과 저장 시 갱신하는 파생 처리건수';
COMMENT ON COLUMN employment_rate_batch_jobs.unprocessed_count IS '일괄 서비스가 건별 결과 저장 시 갱신하는 파생 미처리건수';
CREATE INDEX IF NOT EXISTS idx_employment_rate_batch_jobs_requester
    ON employment_rate_batch_jobs (requester_user_id, requested_at DESC, batch_job_id);
CREATE INDEX IF NOT EXISTS idx_employment_rate_batch_jobs_scope
    ON employment_rate_batch_jobs (organization_code, evaluation_year, requested_at DESC);

CREATE TABLE IF NOT EXISTS employment_rate_batch_job_items (
    batch_job_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_job_id varchar(100) NOT NULL REFERENCES employment_rate_batch_jobs(batch_job_id),
    target_user_id bigint NOT NULL REFERENCES users(user_id),
    achievement_id bigint REFERENCES education_achievements(achievement_id),
    processed_yn char(1) NOT NULL DEFAULT 'N',
    unprocessed_reason varchar(1000),
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint REFERENCES users(user_id),
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint REFERENCES users(user_id),
    CONSTRAINT uq_employment_rate_batch_job_items_target UNIQUE (batch_job_id, target_user_id),
    CONSTRAINT ck_employment_rate_batch_job_items_processed CHECK (processed_yn IN ('Y', 'N'))
);
COMMENT ON TABLE employment_rate_batch_job_items IS
    '취업률 일괄 작업의 대상별 처리 여부와 미처리 사유. 상위 SEED 작업의 결과는 실제 실행으로 해석하지 않는다.';
COMMENT ON COLUMN employment_rate_batch_job_items.processed_yn IS 'Y:처리|N:미처리';
CREATE INDEX IF NOT EXISTS idx_employment_rate_batch_job_items_target
    ON employment_rate_batch_job_items (target_user_id, batch_job_id);

ALTER TABLE education_achievement_status_histories
    DROP CONSTRAINT ck_education_achievement_status_histories_type;
ALTER TABLE education_achievement_status_histories
    ADD CONSTRAINT ck_education_achievement_status_histories_type CHECK (
        achievement_type IN (
            'LECTURE_EVALUATION', 'LECTURE', 'STUDENT_GUIDANCE', 'DEGREE_COMPLETION',
            'FR-029', 'FR-030', 'FR-031', 'FR-032'
        )
    );
ALTER TABLE education_achievement_status_histories
    ADD COLUMN IF NOT EXISTS request_id varchar(100);
COMMENT ON COLUMN education_achievement_status_histories.achievement_type IS
    'LECTURE_EVALUATION:강의평가|LECTURE:강의실적|STUDENT_GUIDANCE:학생지도|DEGREE_COMPLETION:석박사배출|FR-029:취업률제고|FR-030:강좌개설운영|FR-031:강의개선|FR-032:취업률실적';
COMMENT ON COLUMN education_achievement_status_histories.request_id IS
    '교육영역 상태 처리 서비스에서 기록한 요청 식별자 (FK 미선언, 기존 이력은 NULL 유지)';
