-- BASIC-83 교육영역 실적 후반 공통 헤더, 세부 실적, 취업률 일괄처리와 메뉴 fixture를 추가한다.

ALTER TABLE education_achievement_status_histories
    DROP CONSTRAINT IF EXISTS ck_education_achievement_status_histories_type;

ALTER TABLE education_achievement_status_histories
    ADD CONSTRAINT ck_education_achievement_status_histories_type CHECK (
        achievement_type IN (
            'LECTURE_EVALUATION',
            'LECTURE',
            'STUDENT_GUIDANCE',
            'DEGREE_COMPLETION',
            'EMPLOYMENT_RATE_IMPROVEMENT',
            'COURSE_OPERATION',
            'LECTURE_IMPROVEMENT',
            'EMPLOYMENT_RATE'
        )
    );

COMMENT ON COLUMN education_achievement_status_histories.achievement_type IS
    'LECTURE_EVALUATION:강의평가|LECTURE:강의실적|STUDENT_GUIDANCE:학생지도|DEGREE_COMPLETION:석박사배출|'
    'EMPLOYMENT_RATE_IMPROVEMENT:취업률제고|COURSE_OPERATION:강좌개설운영|'
    'LECTURE_IMPROVEMENT:강의개선|EMPLOYMENT_RATE:취업률실적';

CREATE TABLE IF NOT EXISTS education_achievements (
    achievement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    management_no varchar(50) NOT NULL,
    achievement_type varchar(30) NOT NULL,
    teacher_user_id bigint NOT NULL,
    organization_code varchar(50) NOT NULL,
    evaluation_year varchar(4) NOT NULL,
    management_item_code varchar(50) NOT NULL,
    achievement_date date NOT NULL,
    achievement_name varchar(500),
    attachment_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
    achievement_status varchar(30) NOT NULL DEFAULT 'DRAFT',
    deleted_yn char(1) NOT NULL DEFAULT 'N',
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    CONSTRAINT uq_education_achievements_management_no UNIQUE (management_no),
    CONSTRAINT ck_education_achievements_type CHECK (
        achievement_type IN (
            'EMPLOYMENT_RATE_IMPROVEMENT',
            'COURSE_OPERATION',
            'LECTURE_IMPROVEMENT',
            'EMPLOYMENT_RATE'
        )
    ),
    CONSTRAINT ck_education_achievements_year CHECK (evaluation_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_education_achievements_status CHECK (
        achievement_status IN (
            'DRAFT',
            'SUBMITTED',
            'DEPARTMENT_CONFIRMED',
            'DEPARTMENT_REJECTED',
            'CERTIFIED',
            'CERTIFICATION_REJECTED',
            'EVALUATION_CONFIRMED',
            'DELETED'
        )
    ),
    CONSTRAINT ck_education_achievements_deleted CHECK (deleted_yn IN ('Y', 'N')),
    CONSTRAINT fk_education_achievements_teacher
        FOREIGN KEY (teacher_user_id) REFERENCES users(user_id),
    CONSTRAINT fk_education_achievements_organization
        FOREIGN KEY (organization_code) REFERENCES organizations(organization_code),
    CONSTRAINT fk_education_achievements_created_by
        FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_education_achievements_updated_by
        FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE education_achievements IS 'BASIC-83 교육영역 취업률 제고, 강좌 운영, 강의개선, 취업률 실적의 공통 헤더와 생명주기를 보존한다.';
COMMENT ON COLUMN education_achievements.achievement_type IS
    'EMPLOYMENT_RATE_IMPROVEMENT:취업률제고|COURSE_OPERATION:강좌개설운영|'
    'LECTURE_IMPROVEMENT:강의개선|EMPLOYMENT_RATE:취업률실적';
COMMENT ON COLUMN education_achievements.teacher_user_id IS 'users.user_id 참조 의도 (실적 대상 교원)';
COMMENT ON COLUMN education_achievements.organization_code IS 'organizations.organization_code 참조 의도 (실적 대상 교원 소속)';
COMMENT ON COLUMN education_achievements.attachment_ids IS 'FileStoragePort가 발급한 외부 비노출 첨부 식별자 배열';
COMMENT ON COLUMN education_achievements.achievement_status IS
    'DRAFT:작성중|SUBMITTED:제출|DEPARTMENT_CONFIRMED:학과장확인|DEPARTMENT_REJECTED:학과장미승인|'
    'CERTIFIED:인증|CERTIFICATION_REJECTED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN education_achievements.deleted_yn IS 'Y:삭제|N:정상';

CREATE TABLE IF NOT EXISTS employment_rate_improvement_achievement_details (
    achievement_id bigint PRIMARY KEY,
    special_lecture_start_date date,
    special_lecture_end_date date,
    mock_exam_question_period varchar(100),
    CONSTRAINT ck_employment_rate_improvement_dates CHECK (
        special_lecture_end_date IS NULL
        OR special_lecture_start_date IS NULL
        OR special_lecture_end_date >= special_lecture_start_date
    ),
    CONSTRAINT fk_employment_rate_improvement_achievement
        FOREIGN KEY (achievement_id) REFERENCES education_achievements(achievement_id)
);
COMMENT ON TABLE employment_rate_improvement_achievement_details IS
    '취업률 제고 실적의 특강 기간과 모의고사 출제 기간을 공통 실적 헤더에 연결해 보존한다.';
COMMENT ON COLUMN employment_rate_improvement_achievement_details.achievement_id IS
    'education_achievements.achievement_id 참조';

CREATE TABLE IF NOT EXISTS course_operation_achievement_details (
    achievement_id bigint PRIMARY KEY,
    performance_detail text NOT NULL,
    CONSTRAINT fk_course_operation_achievement
        FOREIGN KEY (achievement_id) REFERENCES education_achievements(achievement_id)
);
COMMENT ON TABLE course_operation_achievement_details IS '강좌 개설·운영 실적의 업무 상세를 공통 실적 헤더에 연결해 보존한다.';
COMMENT ON COLUMN course_operation_achievement_details.achievement_id IS 'education_achievements.achievement_id 참조';

CREATE TABLE IF NOT EXISTS lecture_improvement_achievement_details (
    achievement_id bigint PRIMARY KEY,
    performance_content text NOT NULL,
    academic_year integer NOT NULL,
    semester_code integer NOT NULL,
    CONSTRAINT ck_lecture_improvement_academic_year CHECK (academic_year >= 2000),
    CONSTRAINT ck_lecture_improvement_semester CHECK (semester_code IN (1, 2)),
    CONSTRAINT fk_lecture_improvement_achievement
        FOREIGN KEY (achievement_id) REFERENCES education_achievements(achievement_id)
);
COMMENT ON TABLE lecture_improvement_achievement_details IS '강의개선 실적의 개선 내용, 학년도와 학기를 공통 실적 헤더에 연결해 보존한다.';
COMMENT ON COLUMN lecture_improvement_achievement_details.achievement_id IS
    'education_achievements.achievement_id 참조';
COMMENT ON COLUMN lecture_improvement_achievement_details.semester_code IS '1:1학기|2:2학기';

CREATE TABLE IF NOT EXISTS employment_rate_batch_jobs (
    batch_job_id varchar(100) PRIMARY KEY,
    evaluation_year varchar(4) NOT NULL,
    target_condition_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    action_type varchar(20) NOT NULL,
    job_status varchar(30) NOT NULL DEFAULT 'REQUESTED',
    total_count integer NOT NULL DEFAULT 0,
    success_count integer NOT NULL DEFAULT 0,
    failure_count integer NOT NULL DEFAULT 0,
    excluded_count integer NOT NULL DEFAULT 0,
    requested_by bigint NOT NULL,
    requested_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    request_id varchar(100) NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    CONSTRAINT ck_employment_rate_batch_jobs_year CHECK (evaluation_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_employment_rate_batch_jobs_action CHECK (action_type IN ('GENERATE', 'DELETE')),
    CONSTRAINT ck_employment_rate_batch_jobs_status CHECK (
        job_status IN ('REQUESTED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED')
    ),
    CONSTRAINT ck_employment_rate_batch_jobs_counts CHECK (
        total_count >= 0
        AND success_count >= 0
        AND failure_count >= 0
        AND excluded_count >= 0
    ),
    CONSTRAINT fk_employment_rate_batch_jobs_requested_by
        FOREIGN KEY (requested_by) REFERENCES users(user_id),
    CONSTRAINT fk_employment_rate_batch_jobs_created_by
        FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_employment_rate_batch_jobs_updated_by
        FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE employment_rate_batch_jobs IS '취업률 실적의 대상 조건, 요청 식별자, 처리 건수와 상태를 보존하는 R07 일괄 처리 작업 테이블이다.';
COMMENT ON COLUMN employment_rate_batch_jobs.action_type IS 'GENERATE:생성|DELETE:삭제';
COMMENT ON COLUMN employment_rate_batch_jobs.job_status IS
    'REQUESTED:요청됨|RUNNING:실행중|COMPLETED:완료|FAILED:실패|CANCELLED:취소';
COMMENT ON COLUMN employment_rate_batch_jobs.target_condition_json IS '일괄 처리 대상 미리보기와 사용자 확인을 통과한 조건 snapshot';
COMMENT ON COLUMN employment_rate_batch_jobs.request_id IS '요청 식별자 전 구간 추적을 위해 업무 서비스에서 기록';

CREATE TABLE IF NOT EXISTS employment_rate_batch_job_items (
    batch_job_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_job_id varchar(100) NOT NULL,
    target_user_id bigint NOT NULL,
    processed_yn char(1) NOT NULL DEFAULT 'N',
    unprocessed_reason varchar(500),
    processed_at timestamp,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    CONSTRAINT uq_employment_rate_batch_job_items_target UNIQUE (batch_job_id, target_user_id),
    CONSTRAINT ck_employment_rate_batch_job_items_processed CHECK (processed_yn IN ('Y', 'N')),
    CONSTRAINT fk_employment_rate_batch_job_items_job
        FOREIGN KEY (batch_job_id) REFERENCES employment_rate_batch_jobs(batch_job_id),
    CONSTRAINT fk_employment_rate_batch_job_items_target
        FOREIGN KEY (target_user_id) REFERENCES users(user_id),
    CONSTRAINT fk_employment_rate_batch_job_items_created_by
        FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_employment_rate_batch_job_items_updated_by
        FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE employment_rate_batch_job_items IS '취업률 일괄 처리의 대상별 처리 여부와 미처리 사유를 보존하는 결과 상세 테이블이다.';
COMMENT ON COLUMN employment_rate_batch_job_items.processed_yn IS 'Y:처리완료|N:미처리';
COMMENT ON COLUMN employment_rate_batch_job_items.unprocessed_reason IS '정책 미확정, 권한, 중복 등 대상별 미처리 사유';

CREATE INDEX IF NOT EXISTS idx_education_achievements_search
    ON education_achievements (
        achievement_type,
        teacher_user_id,
        evaluation_year,
        achievement_date DESC,
        achievement_status
    )
    WHERE deleted_yn = 'N';

CREATE INDEX IF NOT EXISTS idx_education_achievements_organization
    ON education_achievements (
        organization_code,
        evaluation_year,
        achievement_type,
        achievement_date DESC
    )
    WHERE deleted_yn = 'N';

CREATE INDEX IF NOT EXISTS idx_employment_rate_batch_jobs_search
    ON employment_rate_batch_jobs (evaluation_year, job_status, requested_at DESC);

CREATE INDEX IF NOT EXISTS idx_employment_rate_batch_jobs_request
    ON employment_rate_batch_jobs (request_id);

CREATE INDEX IF NOT EXISTS idx_employment_rate_batch_job_items_job
    ON employment_rate_batch_job_items (batch_job_id, processed_yn, batch_job_item_id);

INSERT INTO education_achievements (
    management_no,
    achievement_type,
    teacher_user_id,
    organization_code,
    evaluation_year,
    management_item_code,
    achievement_date,
    achievement_name,
    attachment_ids,
    achievement_status,
    deleted_yn,
    created_by,
    updated_by
)
SELECT
    seed.management_no,
    'EMPLOYMENT_RATE_IMPROVEMENT',
    owner.user_id,
    'KNUE-DEPT-COMP',
    seed.evaluation_year,
    'EMPLOYMENT_RATE_IMPROVEMENT',
    seed.achievement_date,
    seed.achievement_name,
    seed.attachment_ids::jsonb,
    seed.achievement_status,
    'N',
    owner.user_id,
    owner.user_id
FROM (
    VALUES
        (
            'B83-ERI-001',
            'professor1',
            '2026',
            DATE '2026-04-10',
            '정상 취업률 제고 실적',
            '[]',
            'DRAFT'
        ),
        (
            'B83-ERI-002',
            'professor2',
            '2026',
            DATE '2025-12-31',
            '평가기간 외 경고 취업률 제고 실적',
            '["files/opaque/b83-eri-002"]',
            'SUBMITTED'
        ),
        (
            'B83-ERI-003',
            'business-owner',
            '2026',
            DATE '2026-04-12',
            '인증 상태 취업률 제고 실적',
            '[]',
            'CERTIFIED'
        )
) AS seed (
    management_no,
    login_id,
    evaluation_year,
    achievement_date,
    achievement_name,
    attachment_ids,
    achievement_status
)
JOIN users owner
    ON owner.login_id = seed.login_id
ON CONFLICT (management_no) DO UPDATE SET
    teacher_user_id = EXCLUDED.teacher_user_id,
    organization_code = EXCLUDED.organization_code,
    evaluation_year = EXCLUDED.evaluation_year,
    management_item_code = EXCLUDED.management_item_code,
    achievement_date = EXCLUDED.achievement_date,
    achievement_name = EXCLUDED.achievement_name,
    attachment_ids = EXCLUDED.attachment_ids,
    achievement_status = EXCLUDED.achievement_status,
    deleted_yn = EXCLUDED.deleted_yn,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = EXCLUDED.updated_by;

INSERT INTO employment_rate_improvement_achievement_details (
    achievement_id,
    special_lecture_start_date,
    special_lecture_end_date,
    mock_exam_question_period
)
SELECT
    achievement.achievement_id,
    seed.special_lecture_start_date,
    seed.special_lecture_end_date,
    seed.mock_exam_question_period
FROM (
    VALUES
        ('B83-ERI-001', DATE '2026-04-01', DATE '2026-04-10', '2026-1차'),
        ('B83-ERI-002', DATE '2025-12-20', DATE '2025-12-31', '2025-동계'),
        ('B83-ERI-003', DATE '2026-04-05', DATE '2026-04-12', '2026-2차')
) AS seed (
    management_no,
    special_lecture_start_date,
    special_lecture_end_date,
    mock_exam_question_period
)
JOIN education_achievements achievement
    ON achievement.management_no = seed.management_no
ON CONFLICT (achievement_id) DO UPDATE SET
    special_lecture_start_date = EXCLUDED.special_lecture_start_date,
    special_lecture_end_date = EXCLUDED.special_lecture_end_date,
    mock_exam_question_period = EXCLUDED.mock_exam_question_period;

INSERT INTO education_achievement_status_histories (
    achievement_type,
    achievement_id,
    previous_status,
    next_status,
    action_type,
    reason_code,
    opinion,
    processed_by
)
SELECT
    'EMPLOYMENT_RATE_IMPROVEMENT',
    achievement.achievement_id,
    seed.previous_status,
    seed.next_status,
    seed.action_type,
    seed.reason_code,
    seed.opinion,
    processor.user_id
FROM (
    VALUES
        (
            'B83-ERI-001',
            NULL::varchar(30),
            'DRAFT',
            'CREATE',
            NULL::varchar(100),
            '정상 입력 fixture',
            'professor1'
        ),
        (
            'B83-ERI-002',
            'DRAFT',
            'SUBMITTED',
            'SUBMIT',
            NULL::varchar(100),
            '기간 경고 fixture',
            'professor2'
        ),
        (
            'B83-ERI-003',
            'DEPARTMENT_CONFIRMED',
            'CERTIFIED',
            'CERTIFY',
            'EVIDENCE_OK',
            '인증 상태 fixture',
            'business-owner'
        )
) AS seed (
    management_no,
    previous_status,
    next_status,
    action_type,
    reason_code,
    opinion,
    processor_login_id
)
JOIN education_achievements achievement
    ON achievement.management_no = seed.management_no
JOIN users processor
    ON processor.login_id = seed.processor_login_id
WHERE NOT EXISTS (
    SELECT 1
    FROM education_achievement_status_histories history
    WHERE history.achievement_type = 'EMPLOYMENT_RATE_IMPROVEMENT'
      AND history.achievement_id = achievement.achievement_id
      AND history.action_type = seed.action_type
);

INSERT INTO data_change_histories (
    target_business,
    target_key,
    change_type,
    field_name,
    before_value,
    after_value,
    changed_by,
    change_reason
)
SELECT
    'education_achievements',
    achievement.achievement_id::text,
    'CREATE',
    'achievement_status',
    NULL,
    achievement.achievement_status,
    owner.user_id,
    'BASIC-83 취업률 제고 실적 fixture 생성'
FROM education_achievements achievement
JOIN users owner
    ON owner.user_id = achievement.created_by
WHERE achievement.management_no IN ('B83-ERI-001', 'B83-ERI-002', 'B83-ERI-003')
  AND NOT EXISTS (
      SELECT 1
      FROM data_change_histories history
      WHERE history.target_business = 'education_achievements'
        AND history.target_key = achievement.achievement_id::text
        AND history.change_type = 'CREATE'
  );

INSERT INTO menus (
    menu_id,
    parent_menu_id,
    menu_type,
    menu_name,
    display_order,
    screen_id,
    url,
    icon,
    business_category,
    description,
    system_use_yn,
    status,
    updated_by,
    change_reason
)
SELECT
    COALESCE((SELECT MAX(menu_id) FROM menus), 0) + seed.row_number,
    NULL,
    'SCREEN',
    seed.menu_name,
    1100 + seed.row_number,
    seed.screen_id,
    seed.url,
    seed.icon,
    'EDUCATION_ACHIEVEMENT',
    seed.description,
    'Y',
    'ACTIVE',
    admin_user.user_id,
    'BASIC-83 교육영역 실적 후반 메뉴'
FROM users admin_user
CROSS JOIN (
    VALUES
        (1, '취업률 제고 실적 관리', 'SCR-EMPLOYMENT-RATE-IMPROVEMENTS',
            '/faculty/education/employment-rate-improvements', 'trending-up',
            'R01, R02, R04 취업률 제고 실적 조회 및 저장 화면'),
        (2, '강좌 개설·운영 실적 관리', 'SCR-COURSE-OPERATIONS',
            '/faculty/education/course-operations', 'book-open',
            'R01, R02, R04 강좌 개설·운영 실적 조회 및 저장 화면'),
        (3, '강의개선 실적 관리', 'SCR-LECTURE-IMPROVEMENTS',
            '/faculty/education/lecture-improvements', 'clipboard-check',
            'R01, R02, R04 강의개선 실적 조회 및 저장 화면'),
        (4, '취업률 실적 관리', 'SCR-EMPLOYMENT-RATE-ACHIEVEMENTS',
            '/faculty/education/employment-rate-achievements', 'file-spreadsheet',
            'R01, R02, R04, R07 취업률 실적, Excel 및 일괄처리 화면')
) AS seed (row_number, menu_name, screen_id, url, icon, description)
WHERE admin_user.login_id = 'admin'
  AND NOT EXISTS (
      SELECT 1
      FROM menus existing_menu
      WHERE existing_menu.screen_id = seed.screen_id
  );

INSERT INTO menu_permissions (
    target_type,
    target_id,
    menu_id,
    access_allowed,
    status,
    created_by,
    updated_by,
    change_reason
)
SELECT
    'ROLE',
    role_seed.role_code,
    menu.menu_id,
    'ALLOW',
    'ACTIVE',
    admin_user.user_id,
    admin_user.user_id,
    'BASIC-83 교육영역 실적 후반 접근'
FROM menus menu
CROSS JOIN users admin_user
CROSS JOIN (
    VALUES
        ('SCR-EMPLOYMENT-RATE-IMPROVEMENTS', 'R01'),
        ('SCR-EMPLOYMENT-RATE-IMPROVEMENTS', 'R02'),
        ('SCR-EMPLOYMENT-RATE-IMPROVEMENTS', 'R04'),
        ('SCR-COURSE-OPERATIONS', 'R01'),
        ('SCR-COURSE-OPERATIONS', 'R02'),
        ('SCR-COURSE-OPERATIONS', 'R04'),
        ('SCR-LECTURE-IMPROVEMENTS', 'R01'),
        ('SCR-LECTURE-IMPROVEMENTS', 'R02'),
        ('SCR-LECTURE-IMPROVEMENTS', 'R04'),
        ('SCR-EMPLOYMENT-RATE-ACHIEVEMENTS', 'R01'),
        ('SCR-EMPLOYMENT-RATE-ACHIEVEMENTS', 'R02'),
        ('SCR-EMPLOYMENT-RATE-ACHIEVEMENTS', 'R04'),
        ('SCR-EMPLOYMENT-RATE-ACHIEVEMENTS', 'R07')
) AS role_seed (screen_id, role_code)
WHERE menu.screen_id = role_seed.screen_id
  AND admin_user.login_id = 'admin'
ON CONFLICT (target_type, target_id, menu_id) DO UPDATE SET
    access_allowed = EXCLUDED.access_allowed,
    status = EXCLUDED.status,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = EXCLUDED.updated_by,
    change_reason = EXCLUDED.change_reason;
