-- FR-029~032 share one ledger; the existing FR-025~028 ledgers remain unchanged.
-- JSON attachment IDs are opaque references, never filesystem paths.
CREATE TABLE IF NOT EXISTS education_achievements (
    achievement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    management_no varchar(50) NOT NULL UNIQUE,
    achievement_type varchar(30) NOT NULL,
    teacher_user_id bigint NOT NULL REFERENCES users(user_id),
    organization_code varchar(50) NOT NULL REFERENCES organizations(organization_code),
    evaluation_year varchar(4) NOT NULL,
    management_item_code varchar(50) NOT NULL,
    achievement_date date NOT NULL,
    achievement_name varchar(500),
    achievement_detail jsonb NOT NULL DEFAULT '{}'::jsonb,
    attachment_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
    achievement_status varchar(30) NOT NULL DEFAULT 'DRAFT',
    deleted_yn char(1) NOT NULL DEFAULT 'N',
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint REFERENCES users(user_id),
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint REFERENCES users(user_id),
    CONSTRAINT ck_education_achievements_type CHECK (
        achievement_type IN ('FR-029', 'FR-030', 'FR-031', 'FR-032')
    ),
    CONSTRAINT ck_education_achievements_year CHECK (evaluation_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_education_achievements_status CHECK (
        achievement_status IN (
            'DRAFT', 'SUBMITTED', 'DEPARTMENT_CONFIRMED', 'DEPARTMENT_REJECTED',
            'CERTIFIED', 'CERTIFICATION_REJECTED', 'EVALUATION_CONFIRMED', 'DELETED'
        )
    ),
    CONSTRAINT ck_education_achievements_deleted CHECK (deleted_yn IN ('Y', 'N')),
    CONSTRAINT ck_education_achievements_detail CHECK (jsonb_typeof(achievement_detail) = 'object'),
    CONSTRAINT ck_education_achievements_attachments CHECK (jsonb_typeof(attachment_ids) = 'array')
);
COMMENT ON TABLE education_achievements IS '교육영역 후반 네 유형의 공통 실적 원장. 상태, 첨부 참조, 작성 메타데이터와 논리삭제를 보존한다.';
COMMENT ON COLUMN education_achievements.management_item_code IS
    'evaluation_management_items.management_item_code 참조 의도 (복합 업무키이므로 FK 미선언)';
COMMENT ON COLUMN education_achievements.organization_code IS
    '실적 등록 시 서비스가 대상 교원의 소속으로 저장하는 snapshot; 사용자 입력으로 소속을 변경하지 않는다.';
COMMENT ON COLUMN education_achievements.achievement_detail IS
    '관리항목 DB 설정으로 검증한 추가 입력값; 업무 서비스의 단건 저장 또는 Excel commit 시 갱신';
COMMENT ON COLUMN education_achievements.attachment_ids IS
    'FileStoragePort에서 발급한 opaque 참조 배열. 저장/commit 시 소유권을 검증하며 경로와 파일 내용은 저장하지 않는다.';
COMMENT ON COLUMN education_achievements.achievement_type IS
    'FR-029:취업률제고|FR-030:강좌개설운영|FR-031:강의개선|FR-032:취업률실적';
COMMENT ON COLUMN education_achievements.achievement_status IS
    'DRAFT:작성중|SUBMITTED:제출|DEPARTMENT_CONFIRMED:학과장확인|DEPARTMENT_REJECTED:학과장미승인|'
    'CERTIFIED:인증|CERTIFICATION_REJECTED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';

CREATE INDEX IF NOT EXISTS idx_education_achievements_owner_search
    ON education_achievements (
        achievement_type, teacher_user_id, evaluation_year, achievement_date DESC, achievement_id DESC
    )
    WHERE deleted_yn = 'N';
CREATE INDEX IF NOT EXISTS idx_education_achievements_org_search
    ON education_achievements (
        achievement_type, organization_code, evaluation_year, achievement_status, achievement_date DESC
    )
    WHERE deleted_yn = 'N';
-- The same natural key is checked during staging and commit; concurrent commits cannot auto-update it.
CREATE UNIQUE INDEX IF NOT EXISTS uq_education_achievements_employment_identity
    ON education_achievements (
        teacher_user_id, management_item_code, achievement_date, (COALESCE(achievement_name, ''))
    )
    WHERE achievement_type = 'FR-032' AND deleted_yn = 'N';

CREATE TABLE IF NOT EXISTS employment_rate_improvement_achievement_details (
    achievement_id bigint PRIMARY KEY REFERENCES education_achievements(achievement_id),
    special_lecture_start_date date,
    special_lecture_end_date date,
    mock_exam_question_period varchar(500),
    CONSTRAINT ck_employment_improvement_lecture_period CHECK (
        special_lecture_end_date >= special_lecture_start_date
    )
);
COMMENT ON TABLE employment_rate_improvement_achievement_details IS
    '취업률 제고 실적의 특강기간과 모의평가 출제기간. 공통 원장과 같은 단건 트랜잭션에서 저장한다.';

CREATE TABLE IF NOT EXISTS course_operation_achievement_details (
    achievement_id bigint PRIMARY KEY REFERENCES education_achievements(achievement_id),
    performance_detail text NOT NULL,
    CONSTRAINT ck_course_operation_performance CHECK (BTRIM(performance_detail) <> '')
);
COMMENT ON TABLE course_operation_achievement_details IS
    '강좌 개설·운영 실적의 실적내역. API performanceDetails를 performance_detail에 매핑한다.';

CREATE TABLE IF NOT EXISTS lecture_improvement_achievement_details (
    achievement_id bigint PRIMARY KEY REFERENCES education_achievements(achievement_id),
    performance_content text NOT NULL,
    academic_year integer NOT NULL,
    semester_code varchar(50) NOT NULL,
    CONSTRAINT ck_lecture_improvement_content CHECK (BTRIM(performance_content) <> ''),
    CONSTRAINT ck_lecture_improvement_year CHECK (academic_year BETWEEN 1000 AND 9999),
    CONSTRAINT ck_lecture_improvement_semester CHECK (BTRIM(semester_code) <> '')
);
COMMENT ON TABLE lecture_improvement_achievement_details IS
    '강의개선 실적의 내용·학년도·학기. API achievementContent는 performance_content, semester는 semester_code로 매핑한다.';
COMMENT ON COLUMN lecture_improvement_achievement_details.semester_code IS
    'detail_codes의 SEMESTER group_id/code_value 참조 의도 (FK 미선언); 활성·유효기간은 저장 서비스에서 검증';
COMMENT ON COLUMN lecture_improvement_achievement_details.academic_year IS
    'detail_codes의 ACADEMIC_YEAR group_id/code_value 참조 의도 (문자코드를 정수 학년도로 검증하여 저장)';

CREATE TABLE IF NOT EXISTS employment_rate_batch_jobs (
    batch_job_id varchar(100) PRIMARY KEY,
    evaluation_year varchar(4) NOT NULL,
    target_condition_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    action_type varchar(30) NOT NULL,
    job_status varchar(30) NOT NULL DEFAULT 'REQUESTED',
    total_count integer NOT NULL DEFAULT 0,
    processed_count integer NOT NULL DEFAULT 0,
    unprocessed_count integer NOT NULL DEFAULT 0,
    requested_by bigint NOT NULL REFERENCES users(user_id),
    requested_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at timestamp,
    completed_at timestamp,
    request_id varchar(100),
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint REFERENCES users(user_id),
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint REFERENCES users(user_id),
    CONSTRAINT ck_employment_rate_batch_year CHECK (evaluation_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_employment_rate_batch_action CHECK (action_type IN ('GENERATE', 'DELETE')),
    CONSTRAINT ck_employment_rate_batch_status CHECK (
        job_status IN ('REQUESTED', 'RUNNING', 'COMPLETED', 'FAILED')
    ),
    CONSTRAINT ck_employment_rate_batch_target CHECK (jsonb_typeof(target_condition_json) = 'object'),
    CONSTRAINT ck_employment_rate_batch_counts CHECK (
        total_count >= 0 AND processed_count >= 0 AND unprocessed_count >= 0
        AND processed_count + unprocessed_count <= total_count
    )
);
COMMENT ON TABLE employment_rate_batch_jobs IS
    '취업률 일괄 처리결과와 대상조건 snapshot. 현재 실행은 정책 미승인으로 차단되며 예시 결과 조회만 제공한다.';
COMMENT ON COLUMN employment_rate_batch_jobs.batch_job_id IS 'API bulk-jobs/{jobId}의 외부 작업 식별자';
COMMENT ON COLUMN employment_rate_batch_jobs.request_id IS '업무 요청 X-Request-Id 또는 서버 발급 식별자 참조 의도 (FK 미선언)';
COMMENT ON COLUMN employment_rate_batch_jobs.target_condition_json IS
    '작업 접수 시 서비스가 저장하는 대상조건 snapshot; 정책 승인 여부를 대신하지 않는다.';
COMMENT ON COLUMN employment_rate_batch_jobs.total_count IS '작업 서비스가 대상 snapshot 확정 시 갱신하는 파생 대상 건수';
COMMENT ON COLUMN employment_rate_batch_jobs.processed_count IS '작업 서비스가 건별 처리결과 저장 시 갱신하는 파생 처리 건수';
COMMENT ON COLUMN employment_rate_batch_jobs.unprocessed_count IS '작업 서비스가 건별 처리결과 저장 시 갱신하는 파생 미처리 건수';
CREATE INDEX IF NOT EXISTS idx_employment_rate_batch_jobs_owner
    ON employment_rate_batch_jobs (requested_by, requested_at DESC, batch_job_id);

CREATE TABLE IF NOT EXISTS employment_rate_batch_job_items (
    batch_job_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_job_id varchar(100) NOT NULL REFERENCES employment_rate_batch_jobs(batch_job_id),
    target_user_id bigint NOT NULL REFERENCES users(user_id),
    achievement_id bigint REFERENCES education_achievements(achievement_id),
    processed_yn char(1) NOT NULL DEFAULT 'N',
    unprocessed_reason varchar(1000),
    processed_at timestamp,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint REFERENCES users(user_id),
    CONSTRAINT uq_employment_rate_batch_job_target UNIQUE (batch_job_id, target_user_id),
    CONSTRAINT ck_employment_rate_batch_item_processed CHECK (processed_yn IN ('Y', 'N'))
);
COMMENT ON TABLE employment_rate_batch_job_items IS
    '취업률 작업 대상별 처리 여부와 미처리 사유. 현재 정책 미승인으로 신규 실행은 차단되며 예시 결과를 보존한다.';
COMMENT ON COLUMN employment_rate_batch_job_items.achievement_id IS
    '연결 실적이 없는 미처리 결과는 NULL; 실행 성공 시 해당 공통 원장 FK를 저장';
CREATE INDEX IF NOT EXISTS idx_employment_rate_batch_items_result
    ON employment_rate_batch_job_items (batch_job_id, processed_yn, batch_job_item_id);

-- Extend the existing polymorphic history without redeploying or changing V60.
ALTER TABLE education_achievement_status_histories
    DROP CONSTRAINT ck_education_achievement_status_histories_type;
ALTER TABLE education_achievement_status_histories
    ADD CONSTRAINT ck_education_achievement_status_histories_type CHECK (
        achievement_type IN (
            'LECTURE_EVALUATION', 'LECTURE', 'STUDENT_GUIDANCE', 'DEGREE_COMPLETION',
            'FR-029', 'FR-030', 'FR-031', 'FR-032'
        )
    );
COMMENT ON COLUMN education_achievement_status_histories.achievement_type IS
    'LECTURE_EVALUATION:강의평가|LECTURE:강의실적|STUDENT_GUIDANCE:학생지도|DEGREE_COMPLETION:석박사배출|'
    'FR-029:취업률제고|FR-030:강좌개설운영|FR-031:강의개선|FR-032:취업률실적';
