-- BASIC-83 교육영역 후반 실적의 공통 헤더, 유형별 상세 및 취업률 일괄 작업 저장 기반을 추가한다.
-- 일괄 생성·삭제의 업무 정책은 OQ-83-01 확정 전이므로 상태와 요청 조건만 보존한다.

CREATE TABLE IF NOT EXISTS education_achievements (
    achievement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    management_no varchar(50) NOT NULL,
    achievement_type varchar(40) NOT NULL,
    teacher_user_id bigint NOT NULL,
    organization_code varchar(50) NOT NULL,
    evaluation_year varchar(4) NOT NULL,
    management_item_code varchar(50) NOT NULL,
    achievement_date date NOT NULL,
    achievement_name varchar(300),
    attachment_ref varchar(300),
    achievement_status varchar(30) NOT NULL DEFAULT 'DRAFT',
    deleted_yn char(1) NOT NULL DEFAULT 'N',
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    CONSTRAINT uq_education_achievements_management_no UNIQUE (management_no),
    CONSTRAINT ck_education_achievements_type CHECK (
        achievement_type IN (
            'EMPLOYMENT_RATE_IMPROVEMENT',
            'COURSE_OPERATION',
            'LECTURE_IMPROVEMENT',
            'EMPLOYMENT_RATE'
        )
    ),
    CONSTRAINT ck_education_achievements_year CHECK (evaluation_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_education_achievements_status CHECK (
        achievement_status IN (
            'DRAFT',
            'SUBMITTED',
            'DEPARTMENT_CONFIRMED',
            'DEPARTMENT_REJECTED',
            'CERTIFIED',
            'CERTIFICATION_REJECTED',
            'EVALUATION_CONFIRMED',
            'DELETED'
        )
    ),
    CONSTRAINT ck_education_achievements_deleted CHECK (deleted_yn IN ('Y', 'N')),
    CONSTRAINT fk_education_achievements_teacher
        FOREIGN KEY (teacher_user_id) REFERENCES users(user_id),
    CONSTRAINT fk_education_achievements_organization
        FOREIGN KEY (organization_code) REFERENCES organizations(organization_code),
    CONSTRAINT fk_education_achievements_created_by
        FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_education_achievements_updated_by
        FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE education_achievements IS '교육영역 후반 실적의 공통 헤더. 유형별 상세와 공통 대상 교원, 관리항목, 상태 및 논리삭제 정보를 보존한다.';
COMMENT ON COLUMN education_achievements.achievement_type IS
    'EMPLOYMENT_RATE_IMPROVEMENT:취업률제고|COURSE_OPERATION:강좌개설운영|LECTURE_IMPROVEMENT:강의개선|EMPLOYMENT_RATE:취업률실적';
COMMENT ON COLUMN education_achievements.teacher_user_id IS 'users.user_id 참조 의도 (실적 대상 교원)';
COMMENT ON COLUMN education_achievements.organization_code IS 'organizations.organization_code 참조 의도 (실적 발생 조직)';
COMMENT ON COLUMN education_achievements.management_item_code IS
    'evaluation_management_items.management_item_code 참조 의도 (FK 미선언)';
COMMENT ON COLUMN education_achievements.attachment_ref IS 'FileStoragePort의 외부 비노출 첨부 참조값';
COMMENT ON COLUMN education_achievements.achievement_status IS
    'DRAFT:작성중|SUBMITTED:제출|DEPARTMENT_CONFIRMED:학과장확인|DEPARTMENT_REJECTED:학과장미승인|'
    'CERTIFIED:인증|CERTIFICATION_REJECTED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN education_achievements.deleted_yn IS 'Y:삭제|N:정상';
COMMENT ON COLUMN education_achievements.created_by IS 'users.user_id 참조 의도 (최초 입력자)';
COMMENT ON COLUMN education_achievements.updated_by IS 'users.user_id 참조 의도 (최종 수정자)';

CREATE INDEX IF NOT EXISTS idx_education_achievements_search
    ON education_achievements (
        achievement_type,
        teacher_user_id,
        evaluation_year,
        management_item_code,
        achievement_date DESC,
        achievement_status
    )
    WHERE deleted_yn = 'N';
CREATE INDEX IF NOT EXISTS idx_education_achievements_organization
    ON education_achievements (
        organization_code,
        achievement_type,
        achievement_date DESC
    )
    WHERE deleted_yn = 'N';

CREATE TABLE IF NOT EXISTS course_operation_achievement_details (
    achievement_id bigint PRIMARY KEY,
    performance_detail text NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    CONSTRAINT fk_course_operation_achievement_details_achievement
        FOREIGN KEY (achievement_id) REFERENCES education_achievements(achievement_id),
    CONSTRAINT fk_course_operation_achievement_details_created_by
        FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_course_operation_achievement_details_updated_by
        FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE course_operation_achievement_details IS '강좌 개설·운영 실적의 유형별 상세. 공통 교육실적 헤더와 일대일로 연결해 실적 내역을 보존한다.';
COMMENT ON COLUMN course_operation_achievement_details.achievement_id IS 'education_achievements.achievement_id 참조';
COMMENT ON COLUMN course_operation_achievement_details.created_by IS 'users.user_id 참조 의도 (최초 입력자)';
COMMENT ON COLUMN course_operation_achievement_details.updated_by IS 'users.user_id 참조 의도 (최종 수정자)';

CREATE TABLE IF NOT EXISTS employment_rate_improvement_achievement_details (
    achievement_id bigint PRIMARY KEY,
    special_lecture_start_date date,
    special_lecture_end_date date,
    mock_exam_question_period varchar(300),
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    CONSTRAINT ck_employment_rate_improvement_special_lecture_dates
        CHECK (
            special_lecture_end_date IS NULL
            OR special_lecture_start_date IS NULL
            OR special_lecture_end_date >= special_lecture_start_date
        ),
    CONSTRAINT fk_employment_rate_improvement_details_achievement
        FOREIGN KEY (achievement_id) REFERENCES education_achievements(achievement_id),
    CONSTRAINT fk_employment_rate_improvement_details_created_by
        FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_employment_rate_improvement_details_updated_by
        FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE employment_rate_improvement_achievement_details IS
    '취업률 제고 실적의 유형별 상세. 공통 교육실적 헤더와 일대일로 연결해 특강 및 모의시험 출제 정보를 보존한다.';
COMMENT ON COLUMN employment_rate_improvement_achievement_details.achievement_id IS
    'education_achievements.achievement_id 참조';
COMMENT ON COLUMN employment_rate_improvement_achievement_details.created_by IS
    'users.user_id 참조 의도 (최초 입력자)';
COMMENT ON COLUMN employment_rate_improvement_achievement_details.updated_by IS
    'users.user_id 참조 의도 (최종 수정자)';

CREATE TABLE IF NOT EXISTS lecture_improvement_achievement_details (
    achievement_id bigint PRIMARY KEY,
    performance_content text NOT NULL,
    academic_year integer NOT NULL,
    semester_code integer NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    CONSTRAINT ck_lecture_improvement_achievement_details_academic_year
        CHECK (academic_year >= 2000),
    CONSTRAINT ck_lecture_improvement_achievement_details_semester
        CHECK (semester_code IN (1, 2)),
    CONSTRAINT fk_lecture_improvement_achievement_details_achievement
        FOREIGN KEY (achievement_id) REFERENCES education_achievements(achievement_id),
    CONSTRAINT fk_lecture_improvement_achievement_details_created_by
        FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_lecture_improvement_achievement_details_updated_by
        FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE lecture_improvement_achievement_details IS
    '강의개선 실적의 유형별 상세. 공통 교육실적 헤더와 일대일로 연결해 실적내용, 학년도 및 학기를 보존한다.';
COMMENT ON COLUMN lecture_improvement_achievement_details.achievement_id IS 'education_achievements.achievement_id 참조';
COMMENT ON COLUMN lecture_improvement_achievement_details.semester_code IS '1:1학기|2:2학기';
COMMENT ON COLUMN lecture_improvement_achievement_details.created_by IS 'users.user_id 참조 의도 (최초 입력자)';
COMMENT ON COLUMN lecture_improvement_achievement_details.updated_by IS 'users.user_id 참조 의도 (최종 수정자)';

CREATE TABLE IF NOT EXISTS employment_rate_batch_jobs (
    batch_job_id varchar(100) PRIMARY KEY,
    evaluation_year varchar(4) NOT NULL,
    target_condition_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    action_type varchar(20) NOT NULL,
    job_status varchar(20) NOT NULL DEFAULT 'QUEUED',
    total_count integer NOT NULL DEFAULT 0,
    processed_count integer NOT NULL DEFAULT 0,
    success_count integer NOT NULL DEFAULT 0,
    failure_count integer NOT NULL DEFAULT 0,
    requested_by bigint NOT NULL,
    request_id varchar(100),
    requested_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at timestamp,
    CONSTRAINT ck_employment_rate_batch_jobs_year CHECK (evaluation_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_employment_rate_batch_jobs_action CHECK (action_type IN ('GENERATE', 'DELETE')),
    CONSTRAINT ck_employment_rate_batch_jobs_status CHECK (
        job_status IN ('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'PARTIAL_FAILED')
    ),
    CONSTRAINT ck_employment_rate_batch_jobs_counts CHECK (
        total_count >= 0
        AND processed_count >= 0
        AND success_count >= 0
        AND failure_count >= 0
        AND processed_count <= total_count
        AND success_count + failure_count <= processed_count
    ),
    CONSTRAINT fk_employment_rate_batch_jobs_requested_by
        FOREIGN KEY (requested_by) REFERENCES users(user_id)
);
COMMENT ON TABLE employment_rate_batch_jobs IS '취업률 실적 일괄 작업의 요청 조건, 진행 상태 및 처리 집계를 보존한다. 대상별 결과는 승인된 별도 결과 계약에서 관리한다.';
COMMENT ON COLUMN employment_rate_batch_jobs.target_condition_json IS '취업률 일괄 작업 접수 시 API targetCondition을 애플리케이션에서 저장';
COMMENT ON COLUMN employment_rate_batch_jobs.action_type IS 'GENERATE:생성요청|DELETE:삭제요청';
COMMENT ON COLUMN employment_rate_batch_jobs.job_status IS
    'QUEUED:대기|RUNNING:진행중|COMPLETED:완료|FAILED:실패|PARTIAL_FAILED:일부실패';
COMMENT ON COLUMN employment_rate_batch_jobs.requested_by IS 'users.user_id 참조 의도 (일괄 작업 요청자)';
COMMENT ON COLUMN employment_rate_batch_jobs.request_id IS 'X-Request-Id 또는 서버 생성 요청 식별자';
COMMENT ON COLUMN employment_rate_batch_jobs.total_count IS '일괄 작업 대상 확정 시 애플리케이션에서 갱신';
COMMENT ON COLUMN employment_rate_batch_jobs.processed_count IS '일괄 작업 실행 중 애플리케이션에서 갱신';
COMMENT ON COLUMN employment_rate_batch_jobs.success_count IS '일괄 작업 실행 중 성공 건수로 애플리케이션에서 갱신';
COMMENT ON COLUMN employment_rate_batch_jobs.failure_count IS '일괄 작업 실행 중 실패 건수로 애플리케이션에서 갱신';

INSERT INTO menus (
    menu_id,
    parent_menu_id,
    menu_type,
    menu_name,
    display_order,
    screen_id,
    url,
    icon,
    business_category,
    description,
    system_use_yn,
    status,
    updated_by,
    change_reason
)
SELECT
    COALESCE((SELECT MAX(menu_id) FROM menus), 0) + seed.row_number,
    NULL,
    'SCREEN',
    seed.menu_name,
    1100 + seed.row_number,
    seed.screen_id,
    seed.url,
    seed.icon,
    'EDUCATION_ACHIEVEMENT',
    seed.description,
    'Y',
    'ACTIVE',
    admin_user.user_id,
    'BASIC-83 교육영역 후반 실적 화면 권한 연결'
FROM users admin_user
CROSS JOIN (
    VALUES
        (1, '강좌 개설·운영 실적 관리', 'SCR-COURSE-OPERATIONS',
            '/faculty/education/course-operations', 'book-open',
            'R01, R02, R04 강좌 개설·운영 실적 조회 및 저장 화면'),
        (2, '취업률 제고 실적 관리', 'SCR-EMPLOYMENT-RATE-IMPROVEMENTS',
            '/faculty/education/employment-rate-improvements', 'trending-up',
            'R01, R02, R04 취업률 제고 실적 조회 및 저장 화면'),
        (3, '강의개선 실적 관리', 'SCR-LECTURE-IMPROVEMENTS',
            '/faculty/education/lecture-improvements', 'clipboard-check',
            'R01, R02, R04 강의개선 실적 조회 및 저장 화면'),
        (4, '취업률 실적 관리', 'SCR-EMPLOYMENT-RATE-ACHIEVEMENTS',
            '/faculty/education/employment-rate-achievements', 'chart-bar',
            'R01, R02, R04 취업률 실적 조회 및 저장 화면')
) AS seed(row_number, menu_name, screen_id, url, icon, description)
WHERE admin_user.login_id = 'admin'
  AND NOT EXISTS (
      SELECT 1
      FROM menus existing_menu
      WHERE existing_menu.screen_id = seed.screen_id
  );

INSERT INTO menu_permissions (
    target_type,
    target_id,
    menu_id,
    access_allowed,
    status,
    created_by,
    updated_by,
    change_reason
)
SELECT
    'ROLE',
    role_seed.role_code,
    menu.menu_id,
    'ALLOW',
    'ACTIVE',
    admin_user.user_id,
    admin_user.user_id,
    'BASIC-83 교육영역 후반 실적 R01/R02/R04 접근'
FROM menus menu
CROSS JOIN users admin_user
CROSS JOIN (
    VALUES ('R01'), ('R02'), ('R04'), ('R07')
) AS role_seed(role_code)
WHERE menu.screen_id IN (
        'SCR-COURSE-OPERATIONS',
        'SCR-EMPLOYMENT-RATE-IMPROVEMENTS',
        'SCR-LECTURE-IMPROVEMENTS',
        'SCR-EMPLOYMENT-RATE-ACHIEVEMENTS'
    )
  AND (
      role_seed.role_code <> 'R07'
      OR menu.screen_id = 'SCR-EMPLOYMENT-RATE-ACHIEVEMENTS'
  )
  AND admin_user.login_id = 'admin'
ON CONFLICT (target_type, target_id, menu_id) DO UPDATE
SET access_allowed = EXCLUDED.access_allowed,
    status = EXCLUDED.status,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = EXCLUDED.updated_by,
    change_reason = EXCLUDED.change_reason;

CREATE INDEX IF NOT EXISTS idx_employment_rate_batch_jobs_search
    ON employment_rate_batch_jobs (requested_by, job_status, requested_at DESC);
CREATE INDEX IF NOT EXISTS idx_employment_rate_batch_jobs_evaluation_year
    ON employment_rate_batch_jobs (evaluation_year, requested_at DESC);

ALTER TABLE education_achievement_status_histories
    DROP CONSTRAINT IF EXISTS ck_education_achievement_status_histories_type;
ALTER TABLE education_achievement_status_histories
    ADD CONSTRAINT ck_education_achievement_status_histories_type
    CHECK (
        achievement_type IN (
            'LECTURE_EVALUATION',
            'LECTURE',
            'STUDENT_GUIDANCE',
            'DEGREE_COMPLETION',
            'EMPLOYMENT_RATE_IMPROVEMENT',
            'COURSE_OPERATION',
            'LECTURE_IMPROVEMENT',
            'EMPLOYMENT_RATE'
        )
    );
COMMENT ON COLUMN education_achievement_status_histories.achievement_type IS
    'LECTURE_EVALUATION:강의평가|LECTURE:강의실적|STUDENT_GUIDANCE:학생지도|DEGREE_COMPLETION:석박사배출|'
    'EMPLOYMENT_RATE_IMPROVEMENT:취업률제고|COURSE_OPERATION:강좌개설운영|'
    'LECTURE_IMPROVEMENT:강의개선|EMPLOYMENT_RATE:취업률실적';

INSERT INTO education_achievements (
    management_no,
    achievement_type,
    teacher_user_id,
    organization_code,
    evaluation_year,
    management_item_code,
    achievement_date,
    achievement_name,
    attachment_ref,
    achievement_status,
    deleted_yn,
    created_by,
    updated_by
)
SELECT
    seed.management_no,
    seed.achievement_type,
    owner.user_id,
    seed.organization_code,
    seed.evaluation_year,
    seed.management_item_code,
    seed.achievement_date,
    seed.achievement_name,
    seed.attachment_ref,
    seed.achievement_status,
    'N',
    owner.user_id,
    owner.user_id
FROM (
    VALUES
        ('B83-CO-001', 'COURSE_OPERATION', 'professor1', 'KNUE-DEPT-COMP', '2026',
            'COURSE_OPERATION', DATE '2026-03-02', '강좌 운영 정상 실적', NULL, 'DRAFT'),
        ('B83-CO-002', 'COURSE_OPERATION', 'admin', 'KNUE', '2026',
            'COURSE_OPERATION', DATE '2025-12-31', '기간 경계 강좌 운영 실적', NULL, 'SUBMITTED'),
        ('B83-CO-003', 'COURSE_OPERATION', 'professor1', 'KNUE-DEPT-COMP', '2026',
            'COURSE_OPERATION', DATE '2026-05-20', '확정 강좌 운영 실적', 'files/opaque/b83-co-003', 'EVALUATION_CONFIRMED'),
        ('B83-LI-001', 'LECTURE_IMPROVEMENT', 'professor1', 'KNUE-DEPT-COMP', '2026',
            'LECTURE_IMPROVEMENT', DATE '2026-03-03', '강의개선 정상 실적', NULL, 'DRAFT'),
        ('B83-LI-002', 'LECTURE_IMPROVEMENT', 'admin', 'KNUE', '2026',
            'LECTURE_IMPROVEMENT', DATE '2025-12-31', '기간 경계 강의개선 실적', NULL, 'SUBMITTED'),
        ('B83-LI-003', 'LECTURE_IMPROVEMENT', 'professor1', 'KNUE-DEPT-COMP', '2026',
            'LECTURE_IMPROVEMENT', DATE '2026-06-01', '확정 강의개선 실적', 'files/opaque/b83-li-003', 'EVALUATION_CONFIRMED'),
        ('B83-ER-001', 'EMPLOYMENT_RATE', 'professor1', 'KNUE-DEPT-COMP', '2026',
            'EMPLOYMENT_RATE', DATE '2026-04-01', '취업률 실적 foundation fixture', NULL, 'DRAFT')
) AS seed(
    management_no,
    achievement_type,
    login_id,
    organization_code,
    evaluation_year,
    management_item_code,
    achievement_date,
    achievement_name,
    attachment_ref,
    achievement_status
)
JOIN users owner
    ON owner.login_id = seed.login_id
ON CONFLICT (management_no) DO NOTHING;

INSERT INTO course_operation_achievement_details (
    achievement_id,
    performance_detail,
    created_by,
    updated_by
)
SELECT
    achievement.achievement_id,
    seed.performance_detail,
    owner.user_id,
    owner.user_id
FROM (
    VALUES
        ('B83-CO-001', '정상 강좌 개설 및 운영 실적'),
        ('B83-CO-002', '평가기간 경계 강좌 운영 실적'),
        ('B83-CO-003', '평가확정 강좌 운영 실적')
) AS seed(management_no, performance_detail)
JOIN education_achievements achievement
    ON achievement.management_no = seed.management_no
JOIN users owner
    ON owner.login_id = CASE WHEN seed.management_no = 'B83-CO-002' THEN 'admin' ELSE 'professor1' END
ON CONFLICT (achievement_id) DO NOTHING;

INSERT INTO lecture_improvement_achievement_details (
    achievement_id,
    performance_content,
    academic_year,
    semester_code,
    created_by,
    updated_by
)
SELECT
    achievement.achievement_id,
    seed.performance_content,
    seed.academic_year,
    seed.semester_code,
    owner.user_id,
    owner.user_id
FROM (
    VALUES
        ('B83-LI-001', '정상 강의개선 실적내용', 2026, 1),
        ('B83-LI-002', '평가기간 경계 강의개선 실적내용', 2025, 2),
        ('B83-LI-003', '평가확정 강의개선 실적내용', 2026, 2)
) AS seed(management_no, performance_content, academic_year, semester_code)
JOIN education_achievements achievement
    ON achievement.management_no = seed.management_no
JOIN users owner
    ON owner.login_id = CASE WHEN seed.management_no = 'B83-LI-002' THEN 'admin' ELSE 'professor1' END
ON CONFLICT (achievement_id) DO NOTHING;

INSERT INTO employment_rate_batch_jobs (
    batch_job_id,
    evaluation_year,
    target_condition_json,
    action_type,
    job_status,
    total_count,
    processed_count,
    success_count,
    failure_count,
    requested_by,
    request_id,
    requested_at,
    completed_at
)
SELECT
    seed.batch_job_id,
    seed.evaluation_year,
    seed.target_condition_json::jsonb,
    seed.action_type,
    seed.job_status,
    seed.total_count,
    seed.processed_count,
    seed.success_count,
    seed.failure_count,
    requester.user_id,
    seed.request_id,
    CURRENT_TIMESTAMP,
    CASE WHEN seed.job_status IN ('COMPLETED', 'PARTIAL_FAILED') THEN CURRENT_TIMESTAMP END
FROM (
    VALUES
        ('B83-BATCH-001', '2026', '{"organizationCode":"KNUE-DEPT-COMP"}', 'GENERATE',
            'COMPLETED', 3, 3, 3, 0, 'B83-SEED-BATCH-001'),
        ('B83-BATCH-002', '2026', '{"organizationCode":"KNUE"}', 'GENERATE',
            'PARTIAL_FAILED', 3, 3, 2, 1, 'B83-SEED-BATCH-002'),
        ('B83-BATCH-003', '2026', '{}' , 'DELETE',
            'QUEUED', 0, 0, 0, 0, 'B83-SEED-BATCH-003')
) AS seed(
    batch_job_id,
    evaluation_year,
    target_condition_json,
    action_type,
    job_status,
    total_count,
    processed_count,
    success_count,
    failure_count,
    request_id
)
JOIN users requester
    ON requester.login_id = 'admin'
ON CONFLICT (batch_job_id) DO NOTHING;
