-- BASIC-83 교육영역 후반 실적 원장, 일괄 처리 결과, 상태 이력 유형과 검증 fixture를 추가한다.

ALTER TABLE education_achievement_status_histories
    DROP CONSTRAINT ck_education_achievement_status_histories_type;

ALTER TABLE education_achievement_status_histories
    ADD CONSTRAINT ck_education_achievement_status_histories_type CHECK (
        achievement_type IN (
            'LECTURE_EVALUATION',
            'LECTURE',
            'STUDENT_GUIDANCE',
            'DEGREE_COMPLETION',
            'EMPLOYMENT_RATE_IMPROVEMENT',
            'COURSE_OPERATION',
            'LECTURE_IMPROVEMENT',
            'EMPLOYMENT_RATE'
        )
    );

COMMENT ON COLUMN education_achievement_status_histories.achievement_type IS
    'LECTURE_EVALUATION:강의평가|LECTURE:강의실적|STUDENT_GUIDANCE:학생지도|DEGREE_COMPLETION:석박사배출|EMPLOYMENT_RATE_IMPROVEMENT:취업률제고|COURSE_OPERATION:강좌개설운영|LECTURE_IMPROVEMENT:강의개선|EMPLOYMENT_RATE:취업률실적';

CREATE TABLE IF NOT EXISTS employment_rate_improvement_achievements (
    achievement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    management_no varchar(50) NOT NULL,
    target_user_id bigint NOT NULL,
    evaluation_year varchar(4) NOT NULL,
    management_item_code varchar(50) NOT NULL,
    occurred_date date NOT NULL,
    special_lecture_start_date date,
    special_lecture_end_date date,
    mock_exam_question_period varchar(200),
    certification_status varchar(30) NOT NULL DEFAULT 'DRAFT',
    attachment_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
    deleted_yn char(1) NOT NULL DEFAULT 'N',
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    CONSTRAINT uq_employment_rate_improvement_achievements_management_no UNIQUE (management_no),
    CONSTRAINT ck_employment_rate_improvement_achievements_year CHECK (evaluation_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_employment_rate_improvement_achievements_dates CHECK (
        special_lecture_end_date IS NULL
        OR special_lecture_start_date IS NULL
        OR special_lecture_end_date >= special_lecture_start_date
    ),
    CONSTRAINT ck_employment_rate_improvement_achievements_status CHECK (
        certification_status IN (
            'DRAFT',
            'SUBMITTED',
            'DEPARTMENT_CONFIRMED',
            'DEPARTMENT_REJECTED',
            'CERTIFIED',
            'CERTIFICATION_REJECTED',
            'EVALUATION_CONFIRMED',
            'DELETED'
        )
    ),
    CONSTRAINT ck_employment_rate_improvement_achievements_deleted CHECK (deleted_yn IN ('Y', 'N')),
    CONSTRAINT fk_employment_rate_improvement_achievements_target_user
        FOREIGN KEY (target_user_id) REFERENCES users(user_id),
    CONSTRAINT fk_employment_rate_improvement_achievements_created_by
        FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_employment_rate_improvement_achievements_updated_by
        FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE employment_rate_improvement_achievements IS
    '교육영역 취업률 제고 실적 원장. 대상 교원, 특강·모의평가 정보와 인증 상태를 논리 삭제 방식으로 보존한다.';
COMMENT ON COLUMN employment_rate_improvement_achievements.certification_status IS 'DRAFT:작성중|SUBMITTED:제출|DEPARTMENT_CONFIRMED:학과장확인|DEPARTMENT_REJECTED:학과장미승인|CERTIFIED:인증|CERTIFICATION_REJECTED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN employment_rate_improvement_achievements.attachment_ids IS 'FileStoragePort가 발급한 외부 비노출 첨부 식별자 배열';
COMMENT ON COLUMN employment_rate_improvement_achievements.deleted_yn IS 'Y:삭제|N:정상';
COMMENT ON COLUMN employment_rate_improvement_achievements.target_user_id IS 'users.user_id 참조 의도 (실적 대상 교원)';
COMMENT ON COLUMN employment_rate_improvement_achievements.created_by IS 'users.user_id 참조 의도 (최초 입력자)';
COMMENT ON COLUMN employment_rate_improvement_achievements.updated_by IS 'users.user_id 참조 의도 (최종 수정자)';

CREATE INDEX IF NOT EXISTS idx_employment_rate_improvement_achievements_search
    ON employment_rate_improvement_achievements (
        target_user_id,
        evaluation_year,
        management_item_code,
        occurred_date DESC,
        certification_status
    )
    WHERE deleted_yn = 'N';

CREATE TABLE IF NOT EXISTS course_offering_operation_achievements (
    achievement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    management_no varchar(50) NOT NULL,
    target_user_id bigint NOT NULL,
    evaluation_year varchar(4) NOT NULL,
    management_item_code varchar(50) NOT NULL,
    occurred_date date NOT NULL,
    performance_detail text NOT NULL,
    certification_status varchar(30) NOT NULL DEFAULT 'DRAFT',
    attachment_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
    deleted_yn char(1) NOT NULL DEFAULT 'N',
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    CONSTRAINT uq_course_offering_operation_achievements_management_no UNIQUE (management_no),
    CONSTRAINT ck_course_offering_operation_achievements_year CHECK (evaluation_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_course_offering_operation_achievements_status CHECK (
        certification_status IN (
            'DRAFT',
            'SUBMITTED',
            'DEPARTMENT_CONFIRMED',
            'DEPARTMENT_REJECTED',
            'CERTIFIED',
            'CERTIFICATION_REJECTED',
            'EVALUATION_CONFIRMED',
            'DELETED'
        )
    ),
    CONSTRAINT ck_course_offering_operation_achievements_deleted CHECK (deleted_yn IN ('Y', 'N')),
    CONSTRAINT fk_course_offering_operation_achievements_target_user
        FOREIGN KEY (target_user_id) REFERENCES users(user_id),
    CONSTRAINT fk_course_offering_operation_achievements_created_by
        FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_course_offering_operation_achievements_updated_by
        FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE course_offering_operation_achievements IS '교육영역 강좌 개설·운영 실적 원장. 대상 교원과 실적내역, 인증 상태를 논리 삭제 방식으로 보존한다.';
COMMENT ON COLUMN course_offering_operation_achievements.certification_status IS 'DRAFT:작성중|SUBMITTED:제출|DEPARTMENT_CONFIRMED:학과장확인|DEPARTMENT_REJECTED:학과장미승인|CERTIFIED:인증|CERTIFICATION_REJECTED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN course_offering_operation_achievements.attachment_ids IS 'FileStoragePort가 발급한 외부 비노출 첨부 식별자 배열';
COMMENT ON COLUMN course_offering_operation_achievements.deleted_yn IS 'Y:삭제|N:정상';
COMMENT ON COLUMN course_offering_operation_achievements.target_user_id IS 'users.user_id 참조 의도 (실적 대상 교원)';
COMMENT ON COLUMN course_offering_operation_achievements.created_by IS 'users.user_id 참조 의도 (최초 입력자)';
COMMENT ON COLUMN course_offering_operation_achievements.updated_by IS 'users.user_id 참조 의도 (최종 수정자)';

CREATE INDEX IF NOT EXISTS idx_course_offering_operation_achievements_search
    ON course_offering_operation_achievements (
        target_user_id,
        evaluation_year,
        management_item_code,
        occurred_date DESC,
        certification_status
    )
    WHERE deleted_yn = 'N';

CREATE TABLE IF NOT EXISTS teaching_improvement_achievements (
    achievement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    management_no varchar(50) NOT NULL,
    target_user_id bigint NOT NULL,
    evaluation_year varchar(4) NOT NULL,
    management_item_code varchar(50) NOT NULL,
    occurred_date date NOT NULL,
    performance_content text NOT NULL,
    academic_year integer NOT NULL,
    semester_code integer NOT NULL,
    certification_status varchar(30) NOT NULL DEFAULT 'DRAFT',
    attachment_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
    deleted_yn char(1) NOT NULL DEFAULT 'N',
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    CONSTRAINT uq_teaching_improvement_achievements_management_no UNIQUE (management_no),
    CONSTRAINT ck_teaching_improvement_achievements_year CHECK (evaluation_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_teaching_improvement_achievements_academic_year CHECK (academic_year >= 2000),
    CONSTRAINT ck_teaching_improvement_achievements_semester CHECK (semester_code IN (1, 2)),
    CONSTRAINT ck_teaching_improvement_achievements_status CHECK (
        certification_status IN (
            'DRAFT',
            'SUBMITTED',
            'DEPARTMENT_CONFIRMED',
            'DEPARTMENT_REJECTED',
            'CERTIFIED',
            'CERTIFICATION_REJECTED',
            'EVALUATION_CONFIRMED',
            'DELETED'
        )
    ),
    CONSTRAINT ck_teaching_improvement_achievements_deleted CHECK (deleted_yn IN ('Y', 'N')),
    CONSTRAINT fk_teaching_improvement_achievements_target_user
        FOREIGN KEY (target_user_id) REFERENCES users(user_id),
    CONSTRAINT fk_teaching_improvement_achievements_created_by
        FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_teaching_improvement_achievements_updated_by
        FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE teaching_improvement_achievements IS '교육영역 강의개선 실적 원장. 실적 내용과 학년도·학기, 인증 상태를 논리 삭제 방식으로 보존한다.';
COMMENT ON COLUMN teaching_improvement_achievements.certification_status IS 'DRAFT:작성중|SUBMITTED:제출|DEPARTMENT_CONFIRMED:학과장확인|DEPARTMENT_REJECTED:학과장미승인|CERTIFIED:인증|CERTIFICATION_REJECTED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN teaching_improvement_achievements.semester_code IS '1:1학기|2:2학기';
COMMENT ON COLUMN teaching_improvement_achievements.attachment_ids IS 'FileStoragePort가 발급한 외부 비노출 첨부 식별자 배열';
COMMENT ON COLUMN teaching_improvement_achievements.deleted_yn IS 'Y:삭제|N:정상';
COMMENT ON COLUMN teaching_improvement_achievements.target_user_id IS 'users.user_id 참조 의도 (실적 대상 교원)';
COMMENT ON COLUMN teaching_improvement_achievements.created_by IS 'users.user_id 참조 의도 (최초 입력자)';
COMMENT ON COLUMN teaching_improvement_achievements.updated_by IS 'users.user_id 참조 의도 (최종 수정자)';

CREATE INDEX IF NOT EXISTS idx_teaching_improvement_achievements_search
    ON teaching_improvement_achievements (
        target_user_id,
        evaluation_year,
        management_item_code,
        occurred_date DESC,
        certification_status
    )
    WHERE deleted_yn = 'N';

CREATE TABLE IF NOT EXISTS employment_rate_achievements (
    achievement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    management_no varchar(50) NOT NULL,
    target_user_id bigint NOT NULL,
    evaluation_year varchar(4) NOT NULL,
    management_item_code varchar(50) NOT NULL,
    occurred_date date NOT NULL,
    achievement_name varchar(500),
    certification_status varchar(30) NOT NULL DEFAULT 'DRAFT',
    attachment_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
    deleted_yn char(1) NOT NULL DEFAULT 'N',
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    CONSTRAINT uq_employment_rate_achievements_management_no UNIQUE (management_no),
    CONSTRAINT ck_employment_rate_achievements_year CHECK (evaluation_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_employment_rate_achievements_status CHECK (
        certification_status IN (
            'DRAFT',
            'SUBMITTED',
            'DEPARTMENT_CONFIRMED',
            'DEPARTMENT_REJECTED',
            'CERTIFIED',
            'CERTIFICATION_REJECTED',
            'EVALUATION_CONFIRMED',
            'DELETED'
        )
    ),
    CONSTRAINT ck_employment_rate_achievements_deleted CHECK (deleted_yn IN ('Y', 'N')),
    CONSTRAINT fk_employment_rate_achievements_target_user
        FOREIGN KEY (target_user_id) REFERENCES users(user_id),
    CONSTRAINT fk_employment_rate_achievements_created_by
        FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_employment_rate_achievements_updated_by
        FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE employment_rate_achievements IS '교육영역 취업률 실적 원장. 개별 등록과 Excel·일괄 처리 결과의 대상 실적을 논리 삭제 방식으로 보존한다.';
COMMENT ON COLUMN employment_rate_achievements.certification_status IS 'DRAFT:작성중|SUBMITTED:제출|DEPARTMENT_CONFIRMED:학과장확인|DEPARTMENT_REJECTED:학과장미승인|CERTIFIED:인증|CERTIFICATION_REJECTED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN employment_rate_achievements.attachment_ids IS 'FileStoragePort가 발급한 외부 비노출 첨부 식별자 배열';
COMMENT ON COLUMN employment_rate_achievements.deleted_yn IS 'Y:삭제|N:정상';
COMMENT ON COLUMN employment_rate_achievements.target_user_id IS 'users.user_id 참조 의도 (실적 대상 교원)';
COMMENT ON COLUMN employment_rate_achievements.created_by IS 'users.user_id 참조 의도 (최초 입력자)';
COMMENT ON COLUMN employment_rate_achievements.updated_by IS 'users.user_id 참조 의도 (최종 수정자)';

CREATE INDEX IF NOT EXISTS idx_employment_rate_achievements_search
    ON employment_rate_achievements (
        target_user_id,
        evaluation_year,
        management_item_code,
        occurred_date DESC,
        certification_status
    )
    WHERE deleted_yn = 'N';

CREATE TABLE IF NOT EXISTS employment_rate_bulk_jobs (
    batch_job_id varchar(100) PRIMARY KEY,
    evaluation_year varchar(4) NOT NULL,
    target_condition_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    action_type varchar(20) NOT NULL,
    total_count integer NOT NULL DEFAULT 0,
    processed_count integer NOT NULL DEFAULT 0,
    unprocessed_count integer NOT NULL DEFAULT 0,
    job_status varchar(20) NOT NULL DEFAULT 'PENDING',
    requested_by bigint NOT NULL,
    requested_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at timestamp,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    CONSTRAINT ck_employment_rate_bulk_jobs_year CHECK (evaluation_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_employment_rate_bulk_jobs_action CHECK (action_type IN ('GENERATE', 'DELETE')),
    CONSTRAINT ck_employment_rate_bulk_jobs_status CHECK (
        job_status IN ('PENDING', 'REJECTED', 'COMPLETED', 'FAILED')
    ),
    CONSTRAINT ck_employment_rate_bulk_jobs_counts CHECK (
        total_count >= 0
        AND processed_count >= 0
        AND unprocessed_count >= 0
        AND processed_count + unprocessed_count <= total_count
    ),
    CONSTRAINT fk_employment_rate_bulk_jobs_requested_by
        FOREIGN KEY (requested_by) REFERENCES users(user_id),
    CONSTRAINT fk_employment_rate_bulk_jobs_created_by
        FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_employment_rate_bulk_jobs_updated_by
        FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE employment_rate_bulk_jobs IS '취업률 실적 일괄 생성·삭제 요청과 대상 조건, 처리 건수를 보존한다. 실행 정책 미확정 요청은 REJECTED로 진단한다.';
COMMENT ON COLUMN employment_rate_bulk_jobs.action_type IS 'GENERATE:일괄생성|DELETE:일괄삭제';
COMMENT ON COLUMN employment_rate_bulk_jobs.job_status IS 'PENDING:대기|REJECTED:실행거부|COMPLETED:완료|FAILED:실패';
COMMENT ON COLUMN employment_rate_bulk_jobs.target_condition_json IS '일괄 작업 요청 시 선택한 대상·실행 조건을 애플리케이션에서 보존';
COMMENT ON COLUMN employment_rate_bulk_jobs.requested_by IS 'users.user_id 참조 의도 (일괄 작업 요청자)';
COMMENT ON COLUMN employment_rate_bulk_jobs.created_by IS 'users.user_id 참조 의도 (최초 생성자)';
COMMENT ON COLUMN employment_rate_bulk_jobs.updated_by IS 'users.user_id 참조 의도 (최종 수정자)';

CREATE INDEX IF NOT EXISTS idx_employment_rate_bulk_jobs_lookup
    ON employment_rate_bulk_jobs (requested_by, requested_at DESC, job_status);

CREATE TABLE IF NOT EXISTS employment_rate_bulk_job_items (
    batch_job_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_job_id varchar(100) NOT NULL,
    target_user_id bigint NOT NULL,
    processed_yn char(1) NOT NULL DEFAULT 'N',
    achievement_id bigint,
    unprocessed_reason varchar(1000),
    processed_at timestamp,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    CONSTRAINT uq_employment_rate_bulk_job_items_target UNIQUE (batch_job_id, target_user_id),
    CONSTRAINT ck_employment_rate_bulk_job_items_processed CHECK (processed_yn IN ('Y', 'N')),
    CONSTRAINT fk_employment_rate_bulk_job_items_job
        FOREIGN KEY (batch_job_id) REFERENCES employment_rate_bulk_jobs(batch_job_id),
    CONSTRAINT fk_employment_rate_bulk_job_items_target_user
        FOREIGN KEY (target_user_id) REFERENCES users(user_id),
    CONSTRAINT fk_employment_rate_bulk_job_items_achievement
        FOREIGN KEY (achievement_id) REFERENCES employment_rate_achievements(achievement_id),
    CONSTRAINT fk_employment_rate_bulk_job_items_created_by
        FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_employment_rate_bulk_job_items_updated_by
        FOREIGN KEY (updated_by) REFERENCES users(user_id)
);
COMMENT ON TABLE employment_rate_bulk_job_items IS '취업률 실적 일괄 작업의 대상별 처리 결과와 미처리 사유를 보존한다.';
COMMENT ON COLUMN employment_rate_bulk_job_items.processed_yn IS 'Y:처리됨|N:미처리';
COMMENT ON COLUMN employment_rate_bulk_job_items.target_user_id IS 'users.user_id 참조 의도 (일괄 작업 대상 교원)';
COMMENT ON COLUMN employment_rate_bulk_job_items.created_by IS 'users.user_id 참조 의도 (최초 생성자)';
COMMENT ON COLUMN employment_rate_bulk_job_items.updated_by IS 'users.user_id 참조 의도 (최종 수정자)';

CREATE INDEX IF NOT EXISTS idx_employment_rate_bulk_job_items_lookup
    ON employment_rate_bulk_job_items (batch_job_id, processed_yn, batch_job_item_id);

INSERT INTO employment_rate_improvement_achievements (
    management_no,
    target_user_id,
    evaluation_year,
    management_item_code,
    occurred_date,
    special_lecture_start_date,
    special_lecture_end_date,
    mock_exam_question_period,
    certification_status,
    attachment_ids,
    created_by,
    updated_by
)
SELECT
    seed.management_no,
    owner.user_id,
    seed.evaluation_year,
    seed.management_item_code,
    seed.occurred_date,
    seed.special_lecture_start_date,
    seed.special_lecture_end_date,
    seed.mock_exam_question_period,
    seed.certification_status,
    seed.attachment_ids,
    owner.user_id,
    owner.user_id
FROM (
    VALUES
        ('B83-ERI-001', 'professor1', '2026', 'EMPLOYMENT_RATE_IMPROVEMENT', DATE '2026-04-10',
            DATE '2026-04-01', DATE '2026-04-03', '2026-1 모의평가 출제', 'DRAFT', '[]'::jsonb),
        ('B83-ERI-002', 'professor2', '2026', 'EMPLOYMENT_RATE_IMPROVEMENT', DATE '2025-12-31',
            NULL::date, NULL::date, '평가대상 기간 외 경고 fixture', 'SUBMITTED', '["files/opaque/b83-eri-002"]'::jsonb),
        ('B83-ERI-003', 'business-owner', '2026', 'EMPLOYMENT_RATE_IMPROVEMENT', DATE '2026-04-12',
            DATE '2026-04-10', DATE '2026-04-12', NULL::varchar(200), 'EVALUATION_CONFIRMED', '[]'::jsonb)
) AS seed (
    management_no,
    login_id,
    evaluation_year,
    management_item_code,
    occurred_date,
    special_lecture_start_date,
    special_lecture_end_date,
    mock_exam_question_period,
    certification_status,
    attachment_ids
)
JOIN users owner
    ON owner.login_id = seed.login_id
ON CONFLICT (management_no) DO UPDATE SET
    target_user_id = EXCLUDED.target_user_id,
    evaluation_year = EXCLUDED.evaluation_year,
    management_item_code = EXCLUDED.management_item_code,
    occurred_date = EXCLUDED.occurred_date,
    special_lecture_start_date = EXCLUDED.special_lecture_start_date,
    special_lecture_end_date = EXCLUDED.special_lecture_end_date,
    mock_exam_question_period = EXCLUDED.mock_exam_question_period,
    certification_status = EXCLUDED.certification_status,
    attachment_ids = EXCLUDED.attachment_ids,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = EXCLUDED.updated_by;

INSERT INTO course_offering_operation_achievements (
    management_no,
    target_user_id,
    evaluation_year,
    management_item_code,
    occurred_date,
    performance_detail,
    certification_status,
    created_by,
    updated_by
)
SELECT
    seed.management_no,
    owner.user_id,
    '2026',
    'COURSE_OPERATION',
    seed.occurred_date,
    seed.performance_detail,
    seed.certification_status,
    owner.user_id,
    owner.user_id
FROM (
    VALUES
        ('B83-COO-001', 'professor1', DATE '2026-03-10', '정상 강좌 개설·운영 fixture', 'DRAFT'),
        ('B83-COO-002', 'professor2', DATE '2026-03-11', '제출 상태 강좌 개설·운영 fixture', 'SUBMITTED'),
        ('B83-COO-003', 'business-owner', DATE '2026-03-12', '확정 잠금 강좌 개설·운영 fixture', 'EVALUATION_CONFIRMED')
) AS seed (management_no, login_id, occurred_date, performance_detail, certification_status)
JOIN users owner
    ON owner.login_id = seed.login_id
ON CONFLICT (management_no) DO UPDATE SET
    target_user_id = EXCLUDED.target_user_id,
    occurred_date = EXCLUDED.occurred_date,
    performance_detail = EXCLUDED.performance_detail,
    certification_status = EXCLUDED.certification_status,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = EXCLUDED.updated_by;

INSERT INTO teaching_improvement_achievements (
    management_no,
    target_user_id,
    evaluation_year,
    management_item_code,
    occurred_date,
    performance_content,
    academic_year,
    semester_code,
    certification_status,
    created_by,
    updated_by
)
SELECT
    seed.management_no,
    owner.user_id,
    '2026',
    'LECTURE_IMPROVEMENT',
    seed.occurred_date,
    seed.performance_content,
    seed.academic_year,
    seed.semester_code,
    seed.certification_status,
    owner.user_id,
    owner.user_id
FROM (
    VALUES
        ('B83-TIA-001', 'professor1', DATE '2026-03-10', '정상 강의개선 fixture', 2025, 1, 'DRAFT'),
        ('B83-TIA-002', 'professor2', DATE '2026-03-11', '학기 경계 강의개선 fixture', 2025, 2, 'SUBMITTED'),
        ('B83-TIA-003', 'business-owner', DATE '2026-03-12', '확정 잠금 강의개선 fixture', 2026, 1, 'EVALUATION_CONFIRMED')
) AS seed (
    management_no,
    login_id,
    occurred_date,
    performance_content,
    academic_year,
    semester_code,
    certification_status
)
JOIN users owner
    ON owner.login_id = seed.login_id
ON CONFLICT (management_no) DO UPDATE SET
    target_user_id = EXCLUDED.target_user_id,
    occurred_date = EXCLUDED.occurred_date,
    performance_content = EXCLUDED.performance_content,
    academic_year = EXCLUDED.academic_year,
    semester_code = EXCLUDED.semester_code,
    certification_status = EXCLUDED.certification_status,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = EXCLUDED.updated_by;

INSERT INTO employment_rate_achievements (
    management_no,
    target_user_id,
    evaluation_year,
    management_item_code,
    occurred_date,
    achievement_name,
    certification_status,
    created_by,
    updated_by
)
SELECT
    seed.management_no,
    owner.user_id,
    '2026',
    'EMPLOYMENT_RATE',
    seed.occurred_date,
    seed.achievement_name,
    seed.certification_status,
    owner.user_id,
    owner.user_id
FROM (
    VALUES
        ('B83-ERA-001', 'professor1', DATE '2026-03-10', '정상 취업률 실적 fixture', 'DRAFT'),
        ('B83-ERA-002', 'professor2', DATE '2026-03-11', 'Excel 중복 검증 대상 fixture', 'SUBMITTED'),
        ('B83-ERA-003', 'business-owner', DATE '2026-03-12', '확정 잠금 취업률 실적 fixture', 'EVALUATION_CONFIRMED')
) AS seed (management_no, login_id, occurred_date, achievement_name, certification_status)
JOIN users owner
    ON owner.login_id = seed.login_id
ON CONFLICT (management_no) DO UPDATE SET
    target_user_id = EXCLUDED.target_user_id,
    occurred_date = EXCLUDED.occurred_date,
    achievement_name = EXCLUDED.achievement_name,
    certification_status = EXCLUDED.certification_status,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = EXCLUDED.updated_by;

INSERT INTO employment_rate_bulk_jobs (
    batch_job_id,
    evaluation_year,
    target_condition_json,
    action_type,
    total_count,
    processed_count,
    unprocessed_count,
    job_status,
    requested_by,
    created_by,
    updated_by
)
SELECT
    seed.batch_job_id,
    '2026',
    seed.target_condition_json,
    seed.action_type,
    seed.total_count,
    seed.processed_count,
    seed.unprocessed_count,
    seed.job_status,
    requester.user_id,
    requester.user_id,
    requester.user_id
FROM (
    VALUES
        ('B83-ERB-001', '{"organizationCode":"EDU"}'::jsonb, 'GENERATE', 1, 1, 0, 'COMPLETED'),
        ('B83-ERB-002', '{"organizationCode":"EDU"}'::jsonb, 'DELETE', 1, 0, 1, 'REJECTED'),
        ('B83-ERB-003', '{}'::jsonb, 'GENERATE', 1, 0, 1, 'FAILED')
) AS seed (
    batch_job_id,
    target_condition_json,
    action_type,
    total_count,
    processed_count,
    unprocessed_count,
    job_status
)
JOIN users requester
    ON requester.login_id = 'admin'
ON CONFLICT (batch_job_id) DO UPDATE SET
    target_condition_json = EXCLUDED.target_condition_json,
    action_type = EXCLUDED.action_type,
    total_count = EXCLUDED.total_count,
    processed_count = EXCLUDED.processed_count,
    unprocessed_count = EXCLUDED.unprocessed_count,
    job_status = EXCLUDED.job_status,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = EXCLUDED.updated_by;

INSERT INTO employment_rate_bulk_job_items (
    batch_job_id,
    target_user_id,
    processed_yn,
    achievement_id,
    unprocessed_reason,
    processed_at,
    created_by,
    updated_by
)
SELECT
    seed.batch_job_id,
    target_user.user_id,
    seed.processed_yn,
    achievement.achievement_id,
    seed.unprocessed_reason,
    CASE WHEN seed.processed_yn = 'Y' THEN CURRENT_TIMESTAMP ELSE NULL END,
    requester.user_id,
    requester.user_id
FROM (
    VALUES
        ('B83-ERB-001', 'professor1', 'Y', 'B83-ERA-001', NULL::varchar(1000)),
        ('B83-ERB-002', 'professor2', 'N', NULL::varchar(50), 'OQ-83-01 실행·삭제 허용 상태 미확정'),
        ('B83-ERB-003', 'business-owner', 'N', NULL::varchar(50), '일괄 처리 실행 실패 fixture')
) AS seed (batch_job_id, login_id, processed_yn, management_no, unprocessed_reason)
JOIN users target_user
    ON target_user.login_id = seed.login_id
JOIN users requester
    ON requester.login_id = 'admin'
LEFT JOIN employment_rate_achievements achievement
    ON achievement.management_no = seed.management_no
WHERE NOT EXISTS (
    SELECT 1
    FROM employment_rate_bulk_job_items item
    WHERE item.batch_job_id = seed.batch_job_id
      AND item.target_user_id = target_user.user_id
);

INSERT INTO education_achievement_status_histories (
    achievement_type,
    achievement_id,
    previous_status,
    next_status,
    action_type,
    reason_code,
    opinion,
    processed_by
)
SELECT
    'EMPLOYMENT_RATE_IMPROVEMENT',
    achievement.achievement_id,
    seed.previous_status,
    seed.next_status,
    seed.action_type,
    seed.reason_code,
    seed.opinion,
    processor.user_id
FROM (
    VALUES
        ('B83-ERI-001', NULL::varchar(30), 'DRAFT', 'CREATE', NULL::varchar(100), '정상 등록 fixture', 'professor1'),
        ('B83-ERI-002', 'DRAFT', 'SUBMITTED', 'SUBMIT', NULL::varchar(100), '기간 경계 제출 fixture', 'professor2'),
        (
            'B83-ERI-003',
            'CERTIFIED',
            'EVALUATION_CONFIRMED',
            'CONFIRM',
            NULL::varchar(100),
            '확정 잠금 fixture',
            'business-owner'
        )
) AS seed (
    management_no,
    previous_status,
    next_status,
    action_type,
    reason_code,
    opinion,
    processor_login_id
)
JOIN employment_rate_improvement_achievements achievement
    ON achievement.management_no = seed.management_no
JOIN users processor
    ON processor.login_id = seed.processor_login_id
WHERE NOT EXISTS (
    SELECT 1
    FROM education_achievement_status_histories history
    WHERE history.achievement_type = 'EMPLOYMENT_RATE_IMPROVEMENT'
      AND history.achievement_id = achievement.achievement_id
      AND history.action_type = seed.action_type
);

INSERT INTO menus (
    menu_id,
    parent_menu_id,
    menu_type,
    menu_name,
    display_order,
    screen_id,
    url,
    icon,
    business_category,
    description,
    system_use_yn,
    status,
    updated_by,
    change_reason
)
SELECT
    COALESCE((SELECT MAX(menu_id) FROM menus), 0) + seed.row_number,
    NULL,
    'SCREEN',
    seed.menu_name,
    1100 + seed.row_number,
    seed.screen_id,
    seed.url,
    seed.icon,
    'EDUCATION_ACHIEVEMENT',
    seed.description,
    'Y',
    'ACTIVE',
    admin_user.user_id,
    'BASIC-83 교육영역 후반 화면 권한 연결'
FROM users admin_user
CROSS JOIN (
    VALUES
        (1, '취업률 제고 실적 관리', 'SCR-EMPLOYMENT-RATE-IMPROVEMENT-ACHIEVEMENT',
            '/faculty/education/employment-rate-improvements', 'trending-up', '취업률 제고 실적 조회·저장 화면'),
        (2, '강좌 개설·운영 실적 관리', 'SCR-COURSE-OFFERING-OPERATION-ACHIEVEMENT',
            '/faculty/education/course-operations', 'book-open', '강좌 개설·운영 실적 조회·저장 화면'),
        (3, '강의개선 실적 관리', 'SCR-TEACHING-IMPROVEMENT-ACHIEVEMENT',
            '/faculty/education/lecture-improvements', 'refresh-cw', '강의개선 실적 조회·저장 화면'),
        (4, '취업률 실적 관리', 'SCR-EMPLOYMENT-RATE-ACHIEVEMENT',
            '/faculty/education/employment-rate-achievements', 'file-spreadsheet', '취업률 실적과 Excel·일괄 처리 화면')
) AS seed (row_number, menu_name, screen_id, url, icon, description)
WHERE admin_user.login_id = 'admin'
  AND NOT EXISTS (
      SELECT 1
      FROM menus existing_menu
      WHERE existing_menu.screen_id = seed.screen_id
  );

INSERT INTO menu_permissions (
    target_type,
    target_id,
    menu_id,
    access_allowed,
    status,
    created_by,
    updated_by,
    change_reason
)
SELECT
    'ROLE',
    role_seed.role_code,
    menu.menu_id,
    'ALLOW',
    'ACTIVE',
    admin_user.user_id,
    admin_user.user_id,
    'BASIC-83 교육영역 후반 역할별 화면 접근'
FROM menus menu
CROSS JOIN users admin_user
JOIN (
    VALUES
        ('SCR-EMPLOYMENT-RATE-IMPROVEMENT-ACHIEVEMENT', 'R01'),
        ('SCR-EMPLOYMENT-RATE-IMPROVEMENT-ACHIEVEMENT', 'R02'),
        ('SCR-EMPLOYMENT-RATE-IMPROVEMENT-ACHIEVEMENT', 'R04'),
        ('SCR-COURSE-OFFERING-OPERATION-ACHIEVEMENT', 'R01'),
        ('SCR-COURSE-OFFERING-OPERATION-ACHIEVEMENT', 'R02'),
        ('SCR-COURSE-OFFERING-OPERATION-ACHIEVEMENT', 'R04'),
        ('SCR-TEACHING-IMPROVEMENT-ACHIEVEMENT', 'R01'),
        ('SCR-TEACHING-IMPROVEMENT-ACHIEVEMENT', 'R02'),
        ('SCR-TEACHING-IMPROVEMENT-ACHIEVEMENT', 'R04'),
        ('SCR-EMPLOYMENT-RATE-ACHIEVEMENT', 'R01'),
        ('SCR-EMPLOYMENT-RATE-ACHIEVEMENT', 'R02'),
        ('SCR-EMPLOYMENT-RATE-ACHIEVEMENT', 'R04'),
        ('SCR-EMPLOYMENT-RATE-ACHIEVEMENT', 'R07')
) AS role_seed (screen_id, role_code)
    ON role_seed.screen_id = menu.screen_id
WHERE menu.screen_id IN (
        'SCR-EMPLOYMENT-RATE-IMPROVEMENT-ACHIEVEMENT',
        'SCR-COURSE-OFFERING-OPERATION-ACHIEVEMENT',
        'SCR-TEACHING-IMPROVEMENT-ACHIEVEMENT',
        'SCR-EMPLOYMENT-RATE-ACHIEVEMENT'
    )
  AND admin_user.login_id = 'admin'
ON CONFLICT (target_type, target_id, menu_id) DO UPDATE SET
    access_allowed = EXCLUDED.access_allowed,
    status = EXCLUDED.status,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = EXCLUDED.updated_by,
    change_reason = EXCLUDED.change_reason;
