-- BASIC-83 교육영역 후반 실적의 공통 원장, 상세, 일괄 처리 결과와 권한 메뉴를 추가한다.

ALTER TABLE education_achievement_status_histories
    DROP CONSTRAINT IF EXISTS ck_education_achievement_status_histories_type;

ALTER TABLE education_achievement_status_histories
    ADD CONSTRAINT ck_education_achievement_status_histories_type CHECK (
        achievement_type IN (
            'LECTURE_EVALUATION',
            'LECTURE',
            'STUDENT_GUIDANCE',
            'DEGREE_COMPLETION',
            'EMPLOYMENT_RATE_IMPROVEMENT',
            'COURSE_OPERATION',
            'LECTURE_IMPROVEMENT',
            'EMPLOYMENT_RATE'
        )
    );

COMMENT ON COLUMN education_achievement_status_histories.achievement_type IS
    'LECTURE_EVALUATION:강의평가|LECTURE:강의실적|STUDENT_GUIDANCE:학생지도|DEGREE_COMPLETION:석박사배출|EMPLOYMENT_RATE_IMPROVEMENT:취업률제고|COURSE_OPERATION:강좌개설운영|LECTURE_IMPROVEMENT:강의개선|EMPLOYMENT_RATE:취업률실적';

CREATE TABLE IF NOT EXISTS education_achievements (
    achievement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    achievement_type varchar(40) NOT NULL,
    teacher_user_id bigint NOT NULL,
    organization_code varchar(50) NOT NULL,
    evaluation_year varchar(4) NOT NULL,
    management_item_code varchar(50) NOT NULL,
    achievement_date date NOT NULL,
    achievement_name varchar(500),
    attachment_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
    achievement_status varchar(30) NOT NULL DEFAULT 'DRAFT',
    deleted_yn char(1) NOT NULL DEFAULT 'N',
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint NOT NULL,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint NOT NULL,
    CONSTRAINT ck_education_achievements_type CHECK (
        achievement_type IN (
            'EMPLOYMENT_RATE_IMPROVEMENT',
            'COURSE_OPERATION',
            'LECTURE_IMPROVEMENT',
            'EMPLOYMENT_RATE'
        )
    ),
    CONSTRAINT ck_education_achievements_year CHECK (evaluation_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_education_achievements_attachment_ids CHECK (jsonb_typeof(attachment_ids) = 'array'),
    CONSTRAINT ck_education_achievements_status CHECK (
        achievement_status IN (
            'DRAFT',
            'SUBMITTED',
            'DEPARTMENT_CONFIRMED',
            'DEPARTMENT_REJECTED',
            'CERTIFIED',
            'CERTIFICATION_REJECTED',
            'EVALUATION_CONFIRMED',
            'DELETED'
        )
    ),
    CONSTRAINT ck_education_achievements_deleted CHECK (deleted_yn IN ('Y', 'N')),
    CONSTRAINT fk_education_achievements_teacher
        FOREIGN KEY (teacher_user_id) REFERENCES users(user_id),
    CONSTRAINT fk_education_achievements_organization
        FOREIGN KEY (organization_code) REFERENCES organizations(organization_code),
    CONSTRAINT fk_education_achievements_created_by
        FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_education_achievements_updated_by
        FOREIGN KEY (updated_by) REFERENCES users(user_id)
);

COMMENT ON TABLE education_achievements IS 'BASIC-83 교육영역 후반 실적의 공통 원장. 유형별 상세와 상태·감사·논리삭제 공통 속성을 보존한다.';
COMMENT ON COLUMN education_achievements.achievement_type IS 'EMPLOYMENT_RATE_IMPROVEMENT:취업률제고|COURSE_OPERATION:강좌개설운영|LECTURE_IMPROVEMENT:강의개선|EMPLOYMENT_RATE:취업률실적';
COMMENT ON COLUMN education_achievements.teacher_user_id IS 'users.user_id 참조 의도 (실적 대상 교원)';
COMMENT ON COLUMN education_achievements.organization_code IS 'organizations.organization_code 참조 의도 (실적 대상 소속 조직)';
COMMENT ON COLUMN education_achievements.evaluation_year IS '업적발생일 기준 평가연도';
COMMENT ON COLUMN education_achievements.attachment_ids IS 'FileStoragePort가 발급한 외부 노출용 첨부 식별자 배열';
COMMENT ON COLUMN education_achievements.achievement_status IS 'DRAFT:작성중|SUBMITTED:제출|DEPARTMENT_CONFIRMED:학과장확인|DEPARTMENT_REJECTED:학과장미승인|CERTIFIED:인증|CERTIFICATION_REJECTED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN education_achievements.deleted_yn IS 'Y:삭제|N:정상';
COMMENT ON COLUMN education_achievements.created_by IS 'users.user_id 참조 의도 (최초 입력자)';
COMMENT ON COLUMN education_achievements.updated_by IS 'users.user_id 참조 의도 (최종 수정자)';

CREATE TABLE IF NOT EXISTS employment_rate_improvement_achievement_details (
    achievement_id bigint PRIMARY KEY,
    special_lecture_start_date date,
    special_lecture_end_date date,
    mock_exam_question_period varchar(200),
    CONSTRAINT ck_employment_rate_improvement_achievement_dates CHECK (
        special_lecture_end_date IS NULL
        OR special_lecture_start_date IS NULL
        OR special_lecture_end_date >= special_lecture_start_date
    ),
    CONSTRAINT fk_employment_rate_improvement_achievement_details_achievement
        FOREIGN KEY (achievement_id) REFERENCES education_achievements(achievement_id)
);

COMMENT ON TABLE employment_rate_improvement_achievement_details IS '취업률 제고 실적의 특강 및 모의평가 출제기간 상세를 공통 실적 원장에 연결해 보존한다.';
COMMENT ON COLUMN employment_rate_improvement_achievement_details.achievement_id IS 'education_achievements.achievement_id 참조 (EMPLOYMENT_RATE_IMPROVEMENT 유형)';

CREATE TABLE IF NOT EXISTS course_operation_achievement_details (
    achievement_id bigint PRIMARY KEY,
    performance_detail text NOT NULL,
    CONSTRAINT fk_course_operation_achievement_details_achievement
        FOREIGN KEY (achievement_id) REFERENCES education_achievements(achievement_id)
);

COMMENT ON TABLE course_operation_achievement_details IS '강좌 개설·운영 실적의 실적내역을 공통 실적 원장에 연결해 보존한다.';
COMMENT ON COLUMN course_operation_achievement_details.achievement_id IS 'education_achievements.achievement_id 참조 (COURSE_OPERATION 유형)';

CREATE TABLE IF NOT EXISTS lecture_improvement_achievement_details (
    achievement_id bigint PRIMARY KEY,
    performance_content text NOT NULL,
    academic_year integer NOT NULL,
    semester_code integer NOT NULL,
    CONSTRAINT ck_lecture_improvement_achievement_details_academic_year CHECK (academic_year >= 2000),
    CONSTRAINT ck_lecture_improvement_achievement_details_semester CHECK (semester_code IN (1, 2)),
    CONSTRAINT fk_lecture_improvement_achievement_details_achievement
        FOREIGN KEY (achievement_id) REFERENCES education_achievements(achievement_id)
);

COMMENT ON TABLE lecture_improvement_achievement_details IS '강의개선 실적의 내용, 학년도, 학기 상세를 공통 실적 원장에 연결해 보존한다.';
COMMENT ON COLUMN lecture_improvement_achievement_details.achievement_id IS 'education_achievements.achievement_id 참조 (LECTURE_IMPROVEMENT 유형)';
COMMENT ON COLUMN lecture_improvement_achievement_details.semester_code IS '1:1학기|2:2학기';

CREATE TABLE IF NOT EXISTS employment_rate_batch_jobs (
    batch_job_id varchar(100) PRIMARY KEY,
    evaluation_year varchar(4) NOT NULL,
    target_condition_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    action_type varchar(20) NOT NULL,
    job_status varchar(30) NOT NULL DEFAULT 'REQUESTED',
    total_count integer NOT NULL DEFAULT 0,
    success_count integer NOT NULL DEFAULT 0,
    failure_count integer NOT NULL DEFAULT 0,
    unprocessed_count integer NOT NULL DEFAULT 0,
    requested_by bigint NOT NULL,
    requested_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at timestamp,
    request_id varchar(100) NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint NOT NULL,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint NOT NULL,
    CONSTRAINT ck_employment_rate_batch_jobs_year CHECK (evaluation_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_employment_rate_batch_jobs_target_condition CHECK (
        jsonb_typeof(target_condition_json) = 'object'
    ),
    CONSTRAINT ck_employment_rate_batch_jobs_action_type CHECK (action_type IN ('GENERATE', 'DELETE')),
    CONSTRAINT ck_employment_rate_batch_jobs_status CHECK (
        job_status IN ('REQUESTED', 'RUNNING', 'COMPLETED', 'FAILED', 'REJECTED')
    ),
    CONSTRAINT ck_employment_rate_batch_jobs_counts CHECK (
        total_count >= 0
        AND success_count >= 0
        AND failure_count >= 0
        AND unprocessed_count >= 0
    ),
    CONSTRAINT fk_employment_rate_batch_jobs_requested_by
        FOREIGN KEY (requested_by) REFERENCES users(user_id),
    CONSTRAINT fk_employment_rate_batch_jobs_created_by
        FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_employment_rate_batch_jobs_updated_by
        FOREIGN KEY (updated_by) REFERENCES users(user_id)
);

COMMENT ON TABLE employment_rate_batch_jobs IS '취업률 실적 일괄 생성·삭제 요청의 조건, 처리 건수, 요청자와 요청 식별자를 보존한다.';
COMMENT ON COLUMN employment_rate_batch_jobs.target_condition_json IS '대상 미리보기와 사용자 확인 후 서비스가 저장한 실행조건 snapshot';
COMMENT ON COLUMN employment_rate_batch_jobs.action_type IS 'GENERATE:일괄생성|DELETE:일괄삭제';
COMMENT ON COLUMN employment_rate_batch_jobs.job_status IS 'REQUESTED:요청됨|RUNNING:실행중|COMPLETED:완료|FAILED:실패|REJECTED:정책거부';
COMMENT ON COLUMN employment_rate_batch_jobs.requested_by IS 'users.user_id 참조 의도 (R07 일괄처리 요청자)';
COMMENT ON COLUMN employment_rate_batch_jobs.request_id IS '요청 식별자 전 구간 추적을 위해 업무 서비스에서 기록';
COMMENT ON COLUMN employment_rate_batch_jobs.created_by IS 'users.user_id 참조 의도 (최초 입력자)';
COMMENT ON COLUMN employment_rate_batch_jobs.updated_by IS 'users.user_id 참조 의도 (최종 수정자)';

CREATE TABLE IF NOT EXISTS employment_rate_batch_job_items (
    batch_job_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_job_id varchar(100) NOT NULL,
    target_user_id bigint,
    processed_yn char(1) NOT NULL DEFAULT 'N',
    unprocessed_reason varchar(500),
    processed_at timestamp,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint NOT NULL,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint NOT NULL,
    CONSTRAINT ck_employment_rate_batch_job_items_processed CHECK (processed_yn IN ('Y', 'N')),
    CONSTRAINT fk_employment_rate_batch_job_items_job
        FOREIGN KEY (batch_job_id) REFERENCES employment_rate_batch_jobs(batch_job_id),
    CONSTRAINT fk_employment_rate_batch_job_items_target_user
        FOREIGN KEY (target_user_id) REFERENCES users(user_id),
    CONSTRAINT fk_employment_rate_batch_job_items_created_by
        FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_employment_rate_batch_job_items_updated_by
        FOREIGN KEY (updated_by) REFERENCES users(user_id)
);

COMMENT ON TABLE employment_rate_batch_job_items IS '취업률 일괄 작업의 대상별 처리 여부와 미처리 사유를 보존해 결과 화면을 지원한다.';
COMMENT ON COLUMN employment_rate_batch_job_items.batch_job_id IS 'employment_rate_batch_jobs.batch_job_id 참조 의도 (일괄 작업)';
COMMENT ON COLUMN employment_rate_batch_job_items.target_user_id IS 'users.user_id 참조 의도 (일괄 처리 대상 교원)';
COMMENT ON COLUMN employment_rate_batch_job_items.processed_yn IS 'Y:처리|N:미처리';
COMMENT ON COLUMN employment_rate_batch_job_items.unprocessed_reason IS '정책 미확정, 권한, 대상 제외 등 미처리 사유';
COMMENT ON COLUMN employment_rate_batch_job_items.created_by IS 'users.user_id 참조 의도 (최초 입력자)';
COMMENT ON COLUMN employment_rate_batch_job_items.updated_by IS 'users.user_id 참조 의도 (최종 수정자)';

CREATE INDEX IF NOT EXISTS idx_education_achievements_search
    ON education_achievements (
        achievement_type,
        teacher_user_id,
        evaluation_year,
        management_item_code,
        achievement_date DESC,
        achievement_status
    )
    WHERE deleted_yn = 'N';

CREATE INDEX IF NOT EXISTS idx_education_achievements_organization
    ON education_achievements (organization_code, achievement_type, achievement_date DESC)
    WHERE deleted_yn = 'N';

CREATE INDEX IF NOT EXISTS idx_employment_rate_batch_jobs_search
    ON employment_rate_batch_jobs (evaluation_year, action_type, job_status, requested_at DESC);

CREATE INDEX IF NOT EXISTS idx_employment_rate_batch_jobs_request
    ON employment_rate_batch_jobs (request_id);

CREATE INDEX IF NOT EXISTS idx_employment_rate_batch_job_items_job
    ON employment_rate_batch_job_items (batch_job_id, processed_yn, processed_at DESC);

INSERT INTO education_achievements (
    achievement_type,
    teacher_user_id,
    organization_code,
    evaluation_year,
    management_item_code,
    achievement_date,
    achievement_name,
    attachment_ids,
    achievement_status,
    deleted_yn,
    created_by,
    updated_by
)
SELECT
    seed.achievement_type,
    teacher.user_id,
    'KNUE-DEPT-COMP',
    seed.evaluation_year,
    seed.management_item_code,
    seed.achievement_date,
    seed.achievement_name,
    seed.attachment_ids::jsonb,
    seed.achievement_status,
    'N',
    admin_user.user_id,
    admin_user.user_id
FROM (
    VALUES
        ('EMPLOYMENT_RATE_IMPROVEMENT', 'professor1', '2026', 'EMPLOYMENT_RATE_IMPROVEMENT',
            DATE '2026-04-10', '취업률 제고 특강', '["B83-ATTACHMENT-001"]', 'DRAFT'),
        ('EMPLOYMENT_RATE_IMPROVEMENT', 'professor1', '2026', 'EMPLOYMENT_RATE_IMPROVEMENT',
            DATE '2025-12-31', '취업률 제고 경계기간 특강', '[]', 'SUBMITTED'),
        ('EMPLOYMENT_RATE_IMPROVEMENT', 'admin', '2026', 'EMPLOYMENT_RATE_IMPROVEMENT',
            DATE '2026-05-01', '취업률 제고 확정 실적', '[]', 'EVALUATION_CONFIRMED'),
        ('COURSE_OPERATION', 'professor1', '2026', 'COURSE_OPERATION',
            DATE '2026-04-11', '현장실습 강좌 운영', '[]', 'DRAFT'),
        ('COURSE_OPERATION', 'professor1', '2026', 'COURSE_OPERATION',
            DATE '2025-12-30', '경계기간 강좌 운영', '[]', 'SUBMITTED'),
        ('COURSE_OPERATION', 'admin', '2026', 'COURSE_OPERATION',
            DATE '2026-05-02', '확정 강좌 운영', '[]', 'EVALUATION_CONFIRMED'),
        ('LECTURE_IMPROVEMENT', 'professor1', '2025', 'LECTURE_IMPROVEMENT',
            DATE '2025-09-01', '2025학년도 2학기 강의개선', '[]', 'DRAFT'),
        ('LECTURE_IMPROVEMENT', 'professor1', '2025', 'LECTURE_IMPROVEMENT',
            DATE '2025-12-31', '경계기간 강의개선', '[]', 'SUBMITTED'),
        ('LECTURE_IMPROVEMENT', 'admin', '2025', 'LECTURE_IMPROVEMENT',
            DATE '2025-11-01', '확정 강의개선', '[]', 'EVALUATION_CONFIRMED'),
        ('EMPLOYMENT_RATE', 'professor1', '2026', 'EMPLOYMENT_RATE',
            DATE '2026-04-15', '취업률 실적 정상 사례', '["B83-ATTACHMENT-002"]', 'DRAFT'),
        ('EMPLOYMENT_RATE', 'professor1', '2026', 'EMPLOYMENT_RATE',
            DATE '2025-12-31', '취업률 실적 경계 사례', '[]', 'SUBMITTED'),
        ('EMPLOYMENT_RATE', 'admin', '2026', 'EMPLOYMENT_RATE',
            DATE '2026-05-03', '취업률 실적 확정 사례', '[]', 'EVALUATION_CONFIRMED')
) AS seed(
    achievement_type,
    login_id,
    evaluation_year,
    management_item_code,
    achievement_date,
    achievement_name,
    attachment_ids,
    achievement_status
)
JOIN users teacher
    ON teacher.login_id = seed.login_id
JOIN users admin_user
    ON admin_user.login_id = 'admin'
WHERE NOT EXISTS (
    SELECT 1
    FROM education_achievements existing
    WHERE existing.achievement_type = seed.achievement_type
      AND existing.teacher_user_id = teacher.user_id
      AND existing.management_item_code = seed.management_item_code
      AND existing.achievement_date = seed.achievement_date
      AND existing.achievement_name = seed.achievement_name
);

INSERT INTO employment_rate_improvement_achievement_details (
    achievement_id,
    special_lecture_start_date,
    special_lecture_end_date,
    mock_exam_question_period
)
SELECT
    achievement.achievement_id,
    seed.special_lecture_start_date,
    seed.special_lecture_end_date,
    seed.mock_exam_question_period
FROM (
    VALUES
        ('취업률 제고 특강', DATE '2026-04-01', DATE '2026-04-10', '2026-03-15~2026-03-20'),
        ('취업률 제고 경계기간 특강', DATE '2025-12-20', DATE '2025-12-31', '2025-12-10~2025-12-12'),
        ('취업률 제고 확정 실적', DATE '2026-04-25', DATE '2026-05-01', '2026-04-05~2026-04-08')
) AS seed(
    achievement_name,
    special_lecture_start_date,
    special_lecture_end_date,
    mock_exam_question_period
)
JOIN education_achievements achievement
    ON achievement.achievement_type = 'EMPLOYMENT_RATE_IMPROVEMENT'
   AND achievement.achievement_name = seed.achievement_name
ON CONFLICT (achievement_id) DO UPDATE SET
    special_lecture_start_date = EXCLUDED.special_lecture_start_date,
    special_lecture_end_date = EXCLUDED.special_lecture_end_date,
    mock_exam_question_period = EXCLUDED.mock_exam_question_period;

INSERT INTO course_operation_achievement_details (
    achievement_id,
    performance_detail
)
SELECT
    achievement.achievement_id,
    seed.performance_detail
FROM (
    VALUES
        ('현장실습 강좌 운영', '2026학년도 현장실습 강좌를 개설·운영함'),
        ('경계기간 강좌 운영', '평가대상 기간 경계의 강좌 운영 내역'),
        ('확정 강좌 운영', '평가확정 상태의 강좌 운영 내역')
) AS seed(achievement_name, performance_detail)
JOIN education_achievements achievement
    ON achievement.achievement_type = 'COURSE_OPERATION'
   AND achievement.achievement_name = seed.achievement_name
ON CONFLICT (achievement_id) DO UPDATE SET
    performance_detail = EXCLUDED.performance_detail;

INSERT INTO lecture_improvement_achievement_details (
    achievement_id,
    performance_content,
    academic_year,
    semester_code
)
SELECT
    achievement.achievement_id,
    seed.performance_content,
    seed.academic_year,
    seed.semester_code
FROM (
    VALUES
        ('2025학년도 2학기 강의개선', '학습자 피드백을 반영하여 토론형 수업을 개선함', 2025, 2),
        ('경계기간 강의개선', '학기 말 학습성과 분석을 반영한 강의개선', 2025, 2),
        ('확정 강의개선', '평가확정 상태의 강의개선 내역', 2025, 1)
) AS seed(achievement_name, performance_content, academic_year, semester_code)
JOIN education_achievements achievement
    ON achievement.achievement_type = 'LECTURE_IMPROVEMENT'
   AND achievement.achievement_name = seed.achievement_name
ON CONFLICT (achievement_id) DO UPDATE SET
    performance_content = EXCLUDED.performance_content,
    academic_year = EXCLUDED.academic_year,
    semester_code = EXCLUDED.semester_code;

INSERT INTO employment_rate_batch_jobs (
    batch_job_id,
    evaluation_year,
    target_condition_json,
    action_type,
    job_status,
    total_count,
    success_count,
    failure_count,
    unprocessed_count,
    requested_by,
    requested_at,
    completed_at,
    request_id,
    created_by,
    updated_by
)
SELECT
    seed.batch_job_id,
    seed.evaluation_year,
    seed.target_condition_json::jsonb,
    seed.action_type,
    seed.job_status,
    seed.total_count,
    seed.success_count,
    seed.failure_count,
    seed.unprocessed_count,
    admin_user.user_id,
    seed.requested_at,
    seed.completed_at,
    seed.request_id,
    admin_user.user_id,
    admin_user.user_id
FROM (
    VALUES
        ('B83-BATCH-001', '2026', '{"organizationCode":"KNUE-DEPT-COMP"}', 'GENERATE',
            'COMPLETED', 3, 3, 0, 0, TIMESTAMP '2026-04-20 09:00:00', TIMESTAMP '2026-04-20 09:01:00',
            'REQ-B83-BATCH-001'),
        ('B83-BATCH-002', '2026', '{"organizationCode":"KNUE-DEPT-COMP"}', 'DELETE',
            'FAILED', 1, 0, 0, 1, TIMESTAMP '2026-04-21 09:00:00', TIMESTAMP '2026-04-21 09:01:00',
            'REQ-B83-BATCH-002'),
        ('B83-BATCH-003', '2026', '{"organizationCode":"KNUE-DEPT-COMP"}', 'GENERATE',
            'REJECTED', 0, 0, 0, 0, TIMESTAMP '2026-04-22 09:00:00', NULL, 'REQ-B83-BATCH-003')
) AS seed(
    batch_job_id,
    evaluation_year,
    target_condition_json,
    action_type,
    job_status,
    total_count,
    success_count,
    failure_count,
    unprocessed_count,
    requested_at,
    completed_at,
    request_id
)
JOIN users admin_user
    ON admin_user.login_id = 'admin'
ON CONFLICT (batch_job_id) DO UPDATE SET
    target_condition_json = EXCLUDED.target_condition_json,
    action_type = EXCLUDED.action_type,
    job_status = EXCLUDED.job_status,
    total_count = EXCLUDED.total_count,
    success_count = EXCLUDED.success_count,
    failure_count = EXCLUDED.failure_count,
    unprocessed_count = EXCLUDED.unprocessed_count,
    completed_at = EXCLUDED.completed_at,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = EXCLUDED.updated_by;

INSERT INTO employment_rate_batch_job_items (
    batch_job_id,
    target_user_id,
    processed_yn,
    unprocessed_reason,
    processed_at,
    created_by,
    updated_by
)
SELECT
    seed.batch_job_id,
    target_user.user_id,
    seed.processed_yn,
    seed.unprocessed_reason,
    seed.processed_at,
    admin_user.user_id,
    admin_user.user_id
FROM (
    VALUES
        ('B83-BATCH-001', 'professor1', 'Y', NULL, TIMESTAMP '2026-04-20 09:01:00'),
        ('B83-BATCH-002', 'professor1', 'N', '삭제 허용 상태 정책이 확정되지 않았습니다.', NULL),
        ('B83-BATCH-003', 'admin', 'N', 'OQ-83-01 실행조건이 확정되지 않았습니다.', NULL)
) AS seed(batch_job_id, login_id, processed_yn, unprocessed_reason, processed_at)
JOIN users target_user
    ON target_user.login_id = seed.login_id
JOIN users admin_user
    ON admin_user.login_id = 'admin'
WHERE NOT EXISTS (
    SELECT 1
    FROM employment_rate_batch_job_items existing
    WHERE existing.batch_job_id = seed.batch_job_id
      AND existing.target_user_id = target_user.user_id
);

INSERT INTO education_achievement_status_histories (
    achievement_type,
    achievement_id,
    previous_status,
    next_status,
    action_type,
    opinion,
    processed_by
)
SELECT
    achievement.achievement_type,
    achievement.achievement_id,
    NULL,
    achievement.achievement_status,
    'CREATE',
    'BASIC-83 증분 migration fixture 최초 입력',
    admin_user.user_id
FROM education_achievements achievement
JOIN users admin_user
    ON admin_user.login_id = 'admin'
WHERE achievement.achievement_type IN (
    'EMPLOYMENT_RATE_IMPROVEMENT',
    'COURSE_OPERATION',
    'LECTURE_IMPROVEMENT',
    'EMPLOYMENT_RATE'
)
  AND NOT EXISTS (
      SELECT 1
      FROM education_achievement_status_histories history
      WHERE history.achievement_type = achievement.achievement_type
        AND history.achievement_id = achievement.achievement_id
        AND history.action_type = 'CREATE'
  );

INSERT INTO menus (
    menu_id,
    parent_menu_id,
    menu_type,
    menu_name,
    display_order,
    screen_id,
    url,
    icon,
    business_category,
    description,
    system_use_yn,
    status,
    updated_by,
    change_reason
)
SELECT
    COALESCE((SELECT MAX(existing_menu.menu_id) FROM menus existing_menu), 0) + seed.row_number,
    NULL,
    'SCREEN',
    seed.menu_name,
    1100 + seed.row_number,
    seed.screen_id,
    seed.url,
    seed.icon,
    'EDUCATION_ACHIEVEMENT',
    seed.description,
    'Y',
    'ACTIVE',
    admin_user.user_id,
    'BASIC-83 교육영역 후반 실적 메뉴 연결'
FROM (
    VALUES
        (1, '취업률 제고 실적 관리', 'SCR-EMPLOYMENT-RATE-IMPROVEMENTS',
            '/faculty/education/employment-rate-improvements', 'briefcase-business', '취업률 제고 실적 조회·저장·상세 화면'),
        (2, '강좌 개설·운영 실적 관리', 'SCR-COURSE-OPERATIONS',
            '/faculty/education/course-operations', 'book-open-check', '강좌 개설·운영 실적 조회·저장·상세 화면'),
        (3, '강의개선 실적 관리', 'SCR-LECTURE-IMPROVEMENTS',
            '/faculty/education/lecture-improvements', 'presentation', '강의개선 실적 조회·저장·상세 화면'),
        (4, '취업률 실적 관리', 'SCR-EMPLOYMENT-RATE-ACHIEVEMENTS',
            '/faculty/education/employment-rate-achievements', 'file-spreadsheet', '취업률 실적 개별·Excel·일괄 처리 화면')
) AS seed(row_number, menu_name, screen_id, url, icon, description)
JOIN users admin_user
    ON admin_user.login_id = 'admin'
WHERE NOT EXISTS (
    SELECT 1
    FROM menus existing_menu
    WHERE existing_menu.screen_id = seed.screen_id
);

INSERT INTO menu_permissions (
    target_type,
    target_id,
    menu_id,
    access_allowed,
    status,
    created_by,
    updated_by,
    change_reason
)
SELECT
    'ROLE',
    role_seed.role_code,
    menu.menu_id,
    'ALLOW',
    'ACTIVE',
    admin_user.user_id,
    admin_user.user_id,
    'BASIC-83 교육영역 후반 실적 접근'
FROM menus menu
JOIN users admin_user
    ON admin_user.login_id = 'admin'
JOIN (
    VALUES
        ('SCR-EMPLOYMENT-RATE-IMPROVEMENTS', 'R01'),
        ('SCR-EMPLOYMENT-RATE-IMPROVEMENTS', 'R02'),
        ('SCR-EMPLOYMENT-RATE-IMPROVEMENTS', 'R04'),
        ('SCR-COURSE-OPERATIONS', 'R01'),
        ('SCR-COURSE-OPERATIONS', 'R02'),
        ('SCR-COURSE-OPERATIONS', 'R04'),
        ('SCR-LECTURE-IMPROVEMENTS', 'R01'),
        ('SCR-LECTURE-IMPROVEMENTS', 'R02'),
        ('SCR-LECTURE-IMPROVEMENTS', 'R04'),
        ('SCR-EMPLOYMENT-RATE-ACHIEVEMENTS', 'R01'),
        ('SCR-EMPLOYMENT-RATE-ACHIEVEMENTS', 'R02'),
        ('SCR-EMPLOYMENT-RATE-ACHIEVEMENTS', 'R04'),
        ('SCR-EMPLOYMENT-RATE-ACHIEVEMENTS', 'R07')
) AS role_seed(screen_id, role_code)
    ON role_seed.screen_id = menu.screen_id
WHERE menu.screen_id IN (
        'SCR-EMPLOYMENT-RATE-IMPROVEMENTS',
        'SCR-COURSE-OPERATIONS',
        'SCR-LECTURE-IMPROVEMENTS',
        'SCR-EMPLOYMENT-RATE-ACHIEVEMENTS'
    )
ON CONFLICT (target_type, target_id, menu_id) DO UPDATE SET
    access_allowed = EXCLUDED.access_allowed,
    status = EXCLUDED.status,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = EXCLUDED.updated_by,
    change_reason = EXCLUDED.change_reason;
