-- BASIC-83 강좌 개설·운영 실적 원천과 상태 이력 유형을 추가한다.
CREATE TABLE IF NOT EXISTS course_offering_operation_achievements (
    achievement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    management_no varchar(50) NOT NULL UNIQUE,
    target_user_id bigint NOT NULL REFERENCES users(user_id),
    evaluation_year varchar(4) NOT NULL,
    management_item_code varchar(50) NOT NULL,
    occurred_date date NOT NULL,
    performance_details text NOT NULL,
    attachment_ref varchar(300),
    certification_status varchar(30) NOT NULL DEFAULT 'DRAFT',
    deleted_yn char(1) NOT NULL DEFAULT 'N',
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint REFERENCES users(user_id),
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint REFERENCES users(user_id),
    CHECK (evaluation_year ~ '^[0-9]{4}$'),
    CHECK (
        certification_status IN (
            'DRAFT',
            'SUBMITTED',
            'DEPARTMENT_CONFIRMED',
            'DEPARTMENT_REJECTED',
            'CERTIFIED',
            'CERTIFICATION_REJECTED',
            'EVALUATION_CONFIRMED',
            'DELETED'
        )
    ),
    CHECK (deleted_yn IN ('Y', 'N'))
);
COMMENT ON TABLE course_offering_operation_achievements IS '교육영역 강좌 개설·운영 실적 원천. 교원별 관리항목, 실적내역, 인증상태와 논리삭제 정보를 보존한다.';
COMMENT ON COLUMN course_offering_operation_achievements.certification_status IS 'DRAFT:작성중|SUBMITTED:제출|DEPARTMENT_CONFIRMED:학과장확인|DEPARTMENT_REJECTED:학과장미승인|CERTIFIED:인증|CERTIFICATION_REJECTED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN course_offering_operation_achievements.deleted_yn IS 'Y:삭제|N:정상';
COMMENT ON COLUMN course_offering_operation_achievements.target_user_id IS 'users.user_id 참조 의도 (실적 대상 교원)';
COMMENT ON COLUMN course_offering_operation_achievements.attachment_ref IS 'FileStoragePort의 외부 비노출 첨부 참조값';
CREATE INDEX IF NOT EXISTS idx_course_offering_operation_achievements_search
    ON course_offering_operation_achievements (
        target_user_id,
        evaluation_year,
        occurred_date DESC
    )
    WHERE deleted_yn = 'N';
ALTER TABLE education_achievement_status_histories
    DROP CONSTRAINT IF EXISTS ck_education_achievement_status_histories_type;
ALTER TABLE education_achievement_status_histories
    ADD CONSTRAINT ck_education_achievement_status_histories_type
    CHECK (
        achievement_type IN (
            'LECTURE_EVALUATION',
            'LECTURE',
            'STUDENT_GUIDANCE',
            'DEGREE_COMPLETION',
            'EMPLOYMENT_RATE_IMPROVEMENT',
            'COURSE_OPERATION'
        )
    );
INSERT INTO course_offering_operation_achievements (
    management_no,
    target_user_id,
    evaluation_year,
    management_item_code,
    occurred_date,
    performance_details,
    certification_status,
    created_by,
    updated_by
)
SELECT
    seed.management_no,
    owner.user_id,
    '2026',
    'COURSE_OPERATION',
    seed.occurred_date,
    seed.performance_details,
    seed.certification_status,
    owner.user_id,
    owner.user_id
FROM (
    VALUES
        ('B83-COA-001', 'professor1', DATE '2026-04-10', '정상 강좌 운영 실적', 'DRAFT'),
        ('B83-COA-002', 'professor2', DATE '2025-12-31', '평가기간 경계 강좌 운영 실적', 'SUBMITTED'),
        ('B83-COA-003', 'business-owner', DATE '2026-04-12', '인증 상태 강좌 개설 실적', 'CERTIFIED')
) AS seed (
    management_no,
    login_id,
    occurred_date,
    performance_details,
    certification_status
)
JOIN users owner
    ON owner.login_id = seed.login_id
ON CONFLICT (management_no) DO NOTHING;
