-- BASIC-83 강의개선 실적 원천과 상태 이력 유형을 추가한다.

CREATE TABLE IF NOT EXISTS teaching_improvement_achievements (
    achievement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    management_no varchar(50) NOT NULL UNIQUE,
    target_user_id bigint NOT NULL REFERENCES users(user_id),
    evaluation_year varchar(4) NOT NULL,
    management_item_code varchar(50) NOT NULL,
    occurred_date date NOT NULL,
    achievement_content text NOT NULL,
    academic_year integer NOT NULL,
    semester integer NOT NULL,
    attachment_ref varchar(300),
    certification_status varchar(30) NOT NULL DEFAULT 'DRAFT',
    deleted_yn char(1) NOT NULL DEFAULT 'N',
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint REFERENCES users(user_id),
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint REFERENCES users(user_id),
    CONSTRAINT ck_teaching_improvement_achievements_evaluation_year
        CHECK (evaluation_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_teaching_improvement_achievements_academic_year
        CHECK (academic_year >= 2000),
    CONSTRAINT ck_teaching_improvement_achievements_semester
        CHECK (semester IN (1, 2)),
    CONSTRAINT ck_teaching_improvement_achievements_status
        CHECK (
            certification_status IN (
                'DRAFT',
                'SUBMITTED',
                'DEPARTMENT_CONFIRMED',
                'DEPARTMENT_REJECTED',
                'CERTIFIED',
                'CERTIFICATION_REJECTED',
                'EVALUATION_CONFIRMED',
                'DELETED'
            )
        ),
    CONSTRAINT ck_teaching_improvement_achievements_deleted
        CHECK (deleted_yn IN ('Y', 'N'))
);

COMMENT ON TABLE teaching_improvement_achievements IS '교육영역 강의개선 실적 원천. 교원별 학년도와 학기, 실적내용, 인증상태 및 논리삭제 정보를 보존한다.';
COMMENT ON COLUMN teaching_improvement_achievements.certification_status IS
    'DRAFT:작성중|SUBMITTED:제출|DEPARTMENT_CONFIRMED:학과장확인|'
    'DEPARTMENT_REJECTED:학과장미승인|CERTIFIED:인증|CERTIFICATION_REJECTED:인증반려|'
    'EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN teaching_improvement_achievements.deleted_yn IS 'Y:삭제|N:정상';
COMMENT ON COLUMN teaching_improvement_achievements.target_user_id IS 'users.user_id 참조 의도 (실적 대상 교원)';
COMMENT ON COLUMN teaching_improvement_achievements.attachment_ref IS 'FileStoragePort의 외부 비노출 첨부 참조값';

CREATE INDEX IF NOT EXISTS idx_teaching_improvement_achievements_search
    ON teaching_improvement_achievements (
        target_user_id,
        evaluation_year,
        occurred_date DESC
    )
    WHERE deleted_yn = 'N';

ALTER TABLE education_achievement_status_histories
    DROP CONSTRAINT IF EXISTS ck_education_achievement_status_histories_type;

ALTER TABLE education_achievement_status_histories
    ADD CONSTRAINT ck_education_achievement_status_histories_type
        CHECK (
            achievement_type IN (
                'LECTURE_EVALUATION',
                'LECTURE',
                'STUDENT_GUIDANCE',
                'DEGREE_COMPLETION',
                'EMPLOYMENT_RATE_IMPROVEMENT',
                'COURSE_OPERATION',
                'LECTURE_IMPROVEMENT'
            )
        );

INSERT INTO teaching_improvement_achievements (
    management_no,
    target_user_id,
    evaluation_year,
    management_item_code,
    occurred_date,
    achievement_content,
    academic_year,
    semester,
    certification_status,
    created_by,
    updated_by
)
SELECT
    seed.management_no,
    owner.user_id,
    '2026',
    'LECTURE_IMPROVEMENT',
    seed.occurred_date,
    seed.achievement_content,
    2025,
    seed.semester,
    seed.certification_status,
    owner.user_id,
    owner.user_id
FROM (
    VALUES
        ('B83-LIA-001', 'professor1', DATE '2026-04-10', '수업 개선안 반영', 1, 'DRAFT'),
        ('B83-LIA-002', 'professor2', DATE '2025-12-31', '강의 피드백 개선', 2, 'SUBMITTED'),
        ('B83-LIA-003', 'business-owner', DATE '2026-04-12', '학습성과 기반 개선', 1, 'CERTIFIED')
) AS seed (
    management_no,
    login_id,
    occurred_date,
    achievement_content,
    semester,
    certification_status
)
JOIN users owner
    ON owner.login_id = seed.login_id
ON CONFLICT (management_no) DO NOTHING;
