-- BASIC-83 취업률 제고 실적 원천과 정상·경계·상태 차이 fixture를 추가한다.

ALTER TABLE education_achievement_status_histories
    DROP CONSTRAINT IF EXISTS ck_education_achievement_status_histories_type;

ALTER TABLE education_achievement_status_histories
    ADD CONSTRAINT ck_education_achievement_status_histories_type CHECK (
        achievement_type IN (
            'LECTURE_EVALUATION',
            'LECTURE',
            'STUDENT_GUIDANCE',
            'DEGREE_COMPLETION',
            'EMPLOYMENT_RATE_IMPROVEMENT'
        )
    );

COMMENT ON COLUMN education_achievement_status_histories.achievement_type IS
    'LECTURE_EVALUATION:강의평가|LECTURE:강의실적|STUDENT_GUIDANCE:학생지도|'
    'DEGREE_COMPLETION:석박사배출|EMPLOYMENT_RATE_IMPROVEMENT:취업률제고';

CREATE TABLE IF NOT EXISTS employment_rate_improvement_achievements (
    achievement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    management_no varchar(50) NOT NULL,
    target_user_id bigint NOT NULL,
    evaluation_year varchar(4) NOT NULL,
    management_item_code varchar(50) NOT NULL,
    achievement_date date NOT NULL,
    special_lecture_start_date date,
    special_lecture_end_date date,
    mock_exam_question_period varchar(200),
    certification_status varchar(30) NOT NULL DEFAULT 'DRAFT',
    attachment_refs text NOT NULL DEFAULT '[]',
    deleted_yn char(1) NOT NULL DEFAULT 'N',
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    CONSTRAINT uq_employment_rate_improvement_management_no UNIQUE (management_no),
    CONSTRAINT ck_employment_rate_improvement_year CHECK (evaluation_year ~ '^[0-9]{4}$'),
    CONSTRAINT ck_employment_rate_improvement_dates CHECK (
        special_lecture_end_date IS NULL
        OR special_lecture_start_date IS NULL
        OR special_lecture_end_date >= special_lecture_start_date
    ),
    CONSTRAINT ck_employment_rate_improvement_status CHECK (
        certification_status IN (
            'DRAFT',
            'SUBMITTED',
            'DEPARTMENT_CONFIRMED',
            'DEPARTMENT_REJECTED',
            'CERTIFIED',
            'CERTIFICATION_REJECTED',
            'EVALUATION_CONFIRMED',
            'DELETED'
        )
    ),
    CONSTRAINT ck_employment_rate_improvement_deleted CHECK (deleted_yn IN ('Y', 'N')),
    CONSTRAINT fk_employment_rate_improvement_target
        FOREIGN KEY (target_user_id) REFERENCES users(user_id),
    CONSTRAINT fk_employment_rate_improvement_created_by
        FOREIGN KEY (created_by) REFERENCES users(user_id),
    CONSTRAINT fk_employment_rate_improvement_updated_by
        FOREIGN KEY (updated_by) REFERENCES users(user_id)
);

COMMENT ON TABLE employment_rate_improvement_achievements IS
    '교육영역 취업률 제고 실적 원천. 특강 및 모의평가 기간, 첨부 참조, 인증상태와 논리삭제 정보를 보존한다.';
COMMENT ON COLUMN employment_rate_improvement_achievements.certification_status IS
    'DRAFT:작성중|SUBMITTED:제출|DEPARTMENT_CONFIRMED:학과장확인|DEPARTMENT_REJECTED:학과장미승인|'
    'CERTIFIED:인증|CERTIFICATION_REJECTED:인증반려|EVALUATION_CONFIRMED:평가확정|DELETED:삭제';
COMMENT ON COLUMN employment_rate_improvement_achievements.attachment_refs IS
    'FileStoragePort의 외부 비노출 첨부 참조 배열을 애플리케이션에서 JSON으로 저장';
COMMENT ON COLUMN employment_rate_improvement_achievements.deleted_yn IS 'Y:삭제|N:정상';
COMMENT ON COLUMN employment_rate_improvement_achievements.target_user_id IS 'users.user_id 참조 의도 (실적 대상 교원)';
COMMENT ON COLUMN employment_rate_improvement_achievements.created_by IS 'users.user_id 참조 의도 (최초 입력자)';
COMMENT ON COLUMN employment_rate_improvement_achievements.updated_by IS 'users.user_id 참조 의도 (최종 수정자)';

CREATE INDEX IF NOT EXISTS idx_employment_rate_improvement_search
    ON employment_rate_improvement_achievements (
        target_user_id,
        evaluation_year,
        management_item_code,
        achievement_date DESC,
        certification_status
    )
    WHERE deleted_yn = 'N';

INSERT INTO employment_rate_improvement_achievements (
    management_no,
    target_user_id,
    evaluation_year,
    management_item_code,
    achievement_date,
    special_lecture_start_date,
    special_lecture_end_date,
    mock_exam_question_period,
    certification_status,
    attachment_refs,
    deleted_yn,
    created_by,
    updated_by
)
SELECT
    seed.management_no,
    owner.user_id,
    seed.evaluation_year,
    seed.management_item_code,
    seed.achievement_date,
    seed.special_lecture_start_date,
    seed.special_lecture_end_date,
    seed.mock_exam_question_period,
    seed.certification_status,
    seed.attachment_refs,
    'N',
    owner.user_id,
    owner.user_id
FROM (
    VALUES
        (
            'B83-ERI-001',
            'professor1',
            '2026',
            'EMPLOYMENT_IMPROVEMENT',
            DATE '2026-04-10',
            DATE '2026-04-01',
            DATE '2026-04-10',
            '2026-1 모의평가 출제',
            'DRAFT',
            '[]'
        ),
        (
            'B83-ERI-002',
            'professor2',
            '2026',
            'EMPLOYMENT_IMPROVEMENT',
            DATE '2025-12-31',
            DATE '2025-12-20',
            DATE '2025-12-31',
            '평가대상 기간 밖 경고',
            'SUBMITTED',
            '["files/opaque/b83-eri-002"]'
        ),
        (
            'B83-ERI-003',
            'business-owner',
            '2026',
            'EMPLOYMENT_IMPROVEMENT',
            DATE '2026-04-15',
            DATE '2026-04-11',
            DATE '2026-04-15',
            '확정 잠금 검증',
            'EVALUATION_CONFIRMED',
            '[]'
        )
) AS seed (
    management_no,
    login_id,
    evaluation_year,
    management_item_code,
    achievement_date,
    special_lecture_start_date,
    special_lecture_end_date,
    mock_exam_question_period,
    certification_status,
    attachment_refs
)
JOIN users owner
    ON owner.login_id = seed.login_id
ON CONFLICT (management_no) DO UPDATE SET
    target_user_id = EXCLUDED.target_user_id,
    evaluation_year = EXCLUDED.evaluation_year,
    management_item_code = EXCLUDED.management_item_code,
    achievement_date = EXCLUDED.achievement_date,
    special_lecture_start_date = EXCLUDED.special_lecture_start_date,
    special_lecture_end_date = EXCLUDED.special_lecture_end_date,
    mock_exam_question_period = EXCLUDED.mock_exam_question_period,
    certification_status = EXCLUDED.certification_status,
    attachment_refs = EXCLUDED.attachment_refs,
    deleted_yn = EXCLUDED.deleted_yn,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = EXCLUDED.updated_by;
