package kr.ac.knue.commonfoundation.educationachievement;

/**
 * Exposes the immutable audit entry generated by an education-achievement change.
 * The response omits database internals while retaining the actor, before value, and request correlation.
 */
public record EducationAchievementChangeHistory(
        String changeType,
        String beforeValue,
        Long changedBy,
        String requestId) {
}
