package kr.ac.knue.commonfoundation.basic29;

import static org.assertj.core.api.Assertions.assertThat;

import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.Comparator;
import java.util.stream.Collectors;
import org.junit.jupiter.api.Test;
import org.springframework.core.io.Resource;
import org.springframework.core.io.support.PathMatchingResourcePatternResolver;

class Basic29SchemaMigrationRedTest {
    private final String migrationSql;
    private final String basic29MigrationSql;

    Basic29SchemaMigrationRedTest() throws Exception {
        Resource[] resources = new PathMatchingResourcePatternResolver().getResources("classpath*:db/migration/*.sql");
        migrationSql = Arrays.stream(resources)
                .sorted(Comparator.comparing(resource -> resource.getFilename() == null ? "" : resource.getFilename()))
                .map(this::readResource)
                .collect(Collectors.joining("\n"))
                .toLowerCase();
        basic29MigrationSql = Arrays.stream(resources)
                .filter(resource -> resource.getFilename() != null && resource.getFilename().contains("__basic29_"))
                .sorted(Comparator.comparing(resource -> resource.getFilename() == null ? "" : resource.getFilename()))
                .map(this::readResource)
                .collect(Collectors.joining("\n"))
                .toLowerCase();
    }

    @Test
    void sessionsTableIsExtendedForActiveSessionStatusAndAdministratorTermination() {
        assertThat(migrationSql)
                .contains("alter table sessions")
                .contains("add column if not exists login_at timestamp")
                .contains("add column if not exists ip_address varchar(100)")
                .contains("add column if not exists terminated_by bigint")
                .contains("add column if not exists terminated_at timestamp")
                .contains("add column if not exists termination_reason varchar(500)")
                .contains("terminated")
                .contains("foreign key (terminated_by) references users(user_id)")
                .contains("comment on column sessions.status is 'active:활성|expired:만료|logged_out:로그아웃|terminated:강제종료'")
                .contains("create index if not exists idx_sessions_active_status")
                .contains("create index if not exists idx_sessions_last_accessed_at");
    }

    @Test
    void sessionTerminationHistoryKeepsImmutableLogoutTimeoutAndForcedTerminationRows() {
        assertTableCreatedWithComment("session_termination_history");
        assertThat(migrationSql)
                .contains("history_id bigint generated by default as identity primary key")
                .contains("session_id varchar(128) not null")
                .contains("termination_type varchar(30) not null")
                .contains("termination_reason varchar(500)")
                .contains("terminated_at timestamp not null")
                .contains("check (termination_type in ('logout','idle_timeout','absolute_timeout','admin_terminated'))")
                .contains("foreign key (session_id) references sessions(session_id)")
                .contains("comment on column session_termination_history.termination_type is 'logout:로그아웃|idle_timeout:유휴만료|absolute_timeout:절대만료|admin_terminated:관리자강제종료'")
                .contains("create index if not exists idx_session_termination_history_filter");
    }

    @Test
    void businessProcessAuditLogsPreserveRequestIdActionActorResultAndMaskedStates() {
        assertTableCreatedWithComment("business_process_audit_logs");
        assertThat(migrationSql)
                .contains("audit_log_id bigint generated by default as identity primary key")
                .contains("action_type varchar(50) not null")
                .contains("target_key varchar(200) not null")
                .contains("before_state jsonb")
                .contains("after_state jsonb")
                .contains("actor_user_id bigint not null")
                .contains("result_status varchar(20) not null")
                .contains("request_id varchar(100) not null")
                .contains("check (action_type in ('create','update','delete','confirm','auth','approve','cancel','batch','session_terminate'))")
                .contains("check (result_status in ('success','failure'))")
                .contains("foreign key (actor_user_id) references users(user_id)")
                .contains("create index if not exists idx_business_process_audit_logs_request_id")
                .contains("create index if not exists idx_business_process_audit_logs_filter");
    }

    @Test
    void sensitiveInformationAccessLogsStoreScopeAndPurposeWithoutProtectedRawValues() {
        assertTableCreatedWithComment("sensitive_information_access_logs");
        assertThat(basic29MigrationSql)
                .contains("access_log_id bigint generated by default as identity primary key")
                .contains("information_type varchar(50) not null")
                .contains("viewer_user_id bigint not null")
                .contains("target_scope varchar(1000) not null")
                .contains("access_purpose varchar(500) not null")
                .contains("access_result varchar(20) not null")
                .contains("request_id varchar(100) not null")
                .contains("check (information_type in ('personal_evaluation_result','score_calculation','personal_information','account_information'))")
                .contains("foreign key (viewer_user_id) references users(user_id)")
                .contains("comment on column sensitive_information_access_logs.target_scope is")
                .contains("create index if not exists idx_sensitive_information_access_logs_filter")
                .doesNotContain("resident_registration_number", "account_number_plain", "password_hash");
    }

    @Test
    void permissionChangeHistoryIsExtendedWithApproverForReadOnlyAuditQueries() {
        assertThat(migrationSql)
                .contains("alter table permission_change_history")
                .contains("add column if not exists approver_user_id bigint")
                .contains("foreign key (approver_user_id) references users(user_id)")
                .contains("create index if not exists idx_permission_change_history_approver");
    }

    private void assertTableCreatedWithComment(String table) {
        assertThat(migrationSql)
                .contains("create table if not exists " + table)
                .contains("comment on table " + table);
    }

    private String readResource(Resource resource) {
        try {
            return resource.getContentAsString(StandardCharsets.UTF_8);
        } catch (Exception exception) {
            throw new IllegalStateException("Cannot read migration resource: " + resource, exception);
        }
    }
}
